// subject.globals.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

word16 g_w00C8;
<anonymous> g_t06B0 = <code>;
word16 g_w08B8 = 0x22;
int16 g_w0958 = 0x0022;
Eq_132 g_t0C98 = 
	{
		
		{
		},
	};
Eq_224 g_t0C9C = 
	{
		
		{
		},
	};
Eq_491 g_t0CA4 = 
	{
		
		{
		},
	};
<anonymous> * g_a10DA8[] = 
	{
	};
word64 g_qw10DB8 = 0x00;
<anonymous> * g_ptr10FB0 = null;
word64 g_qw10FB8 = 0x00;
word64 g_qw10FC0 = 0x00;
<anonymous> * g_ptr10FD8 = null;
<anonymous> * g_ptr10FE0 = null;
<anonymous> * g_ptr11000 = &g_t06B0;
<anonymous> * g_ptr11008 = &g_t06B0;
<anonymous> * g_ptr11010 = &g_t06B0;
<anonymous> * g_ptr11018 = &g_t06B0;
<anonymous> * g_ptr11020 = &g_t06B0;
<anonymous> * g_ptr11028 = &g_t06B0;
byte g_b11040 = 0x00;

