// subject_fini.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject_fini.h"

// 0804846C: void _fini()
// Called from:
//      __libc_csu_fini
void _fini()
{
	__do_global_dtors_aux();
}

// subject_init.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject_init.h"

// 08048254: Register word32 _init(Register word32 edx)
// Called from:
//      __libc_csu_init
word32 _init(word32 edx)
{
	call_gmon_start();
	frame_dummy();
	return __do_global_ctors_aux(edx);
}

// subject_plt.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject_plt.h"

// 0804827C: void scanf()
void scanf()
{
}

// 0804828C: void __libc_start_main()
void __libc_start_main()
{
}

// 0804829C: void printf()
void printf()
{
}

// subject_text.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject_text.h"

// 080482AC: void _start(Register (ptr32 Eq_13) edx, Stack int32 dwArg00)
void _start(void (* edx)(), int32 dwArg00)
{
	__align((char *) fp + 4);
	__libc_start_main(&g_t80483A0, dwArg00, (char *) fp + 4, &g_t80483E4, &g_t8048414, edx, fp);
	__hlt();
}

// 080482D0: void call_gmon_start()
// Called from:
//      _init
void call_gmon_start()
{
	<anonymous> * eax_16 = g_ptr80495BC;
	if (eax_16 != null)
		eax_16();
}

// 080482F4: void __do_global_dtors_aux()
// Called from:
//      _fini
void __do_global_dtors_aux()
{
	if (g_b80495C0 == 0x00)
	{
		<anonymous> ** eax_11 = g_ptr80494C4;
		<anonymous> * edx_12 = *eax_11;
		while (edx_12 != null)
		{
			<anonymous> ** eax_19 = (char *) eax_11 + 4;
			g_ptr80494C4 = eax_19;
			edx_12();
			eax_11 = g_ptr80494C4;
			edx_12 = (<anonymous> *) *eax_11;
		}
		g_b80495C0 = 0x01;
	}
}

// 08048330: void frame_dummy()
// Called from:
//      _init
void frame_dummy()
{
	if (g_dw80495A0 != 0x00 && 0x00 != 0x00)
		fn00000000();
}

// 0804835C: Register int32 fib1(Register int32 eax, Stack int32 dwArg04)
// Called from:
//      fib1
//      main
int32 fib1(int32 eax, int32 dwArg04)
{
	return fib2(eax, dwArg04);
}

// 08048368: Register int32 fib2(Register int32 eax, Stack int32 dwArg04)
// Called from:
//      fib1
int32 fib2(int32 eax, int32 dwArg04)
{
	int32 eax_26;
	if (dwArg04 <= 0x01)
		eax_26 = dwArg04;
	else
	{
		// Failed to bind call argument.
		// Please report this issue at https://github.com/uxmal/reko
		int32 stackArg4 = <invalid>;
		fib1(eax, stackArg4);
		// Failed to bind call argument.
		// Please report this issue at https://github.com/uxmal/reko
		int32 stackArg4 = <invalid>;
		fib1(eax, stackArg4);
		eax_26 = eax * 0x02;
	}
	return eax_26;
}

// 080483A0: void main()
void main()
{
	__align(fp - 0x0C);
	printf("Input number: ");
	scanf("%d", fp - 0x08);
	printf("fibonacci(%d) = %d\n", dwLoc08, fib1(0x0804849F, dwLoc08));
}

// 080483E4: void __libc_csu_init(Register word32 edx)
void __libc_csu_init(word32 edx)
{
	word32 edx_16 = _init(edx);
	uint32 ebx_24 = 0x00;
	if (false)
	{
		do
		{
			(*((char *) g_a80494BC + ebx_24 * 0x04))();
			++ebx_24;
		} while (ebx_24 < 0x00);
	}
}

// 08048414: void __libc_csu_fini()
void __libc_csu_fini()
{
	int32 eax_16 = 0;
	ui32 ebx_19 = ~0x00;
	if (false)
	{
		do
		{
			(*((char *) g_a80494BC + ebx_55 * 0x04))();
			ebx_19 = ebx_55 - 0x01;
			ebx_55 = ebx_19;
		} while (ebx_55 != 0x00);
	}
	_fini();
}

// 08048448: Register word32 __do_global_ctors_aux(Register word32 edx)
// Called from:
//      _init
word32 __do_global_ctors_aux(word32 edx)
{
	<anonymous> * eax_14 = g_ptr8049590;
	word32 * ebx_16 = &g_ptr8049590;
	while (eax_14 != (<anonymous> *) ~0x00)
	{
		eax_14();
		ebx_16 -= 0x04;
		eax_14 = *ebx_16;
	}
	return edx;
}

