
extern void full_write_with_str(void *dest);
    
extern void full_store_with_byte_wise_st1(void *dest);
    
extern void full_store_with_8byte_wise_st1(void *dest);
    
extern void half_store_with_8byte_wise_st1(void *dest);
    
extern void full_store_2_regs_with_byte_wise_st1(void *dest);
    
extern void full_store_4_regs_with_byte_wise_st1(void *dest);
    
extern void indexed_st1__one_byte_from_index_0(void *dest);
    
extern void indexed_st1__one_byte_from_index_3(void *dest);
    
extern void indexed_st1__8_bytes_from_low(void *dest);
    
extern void indexed_st1__8_bytes_from_high(void *dest);
    
extern void write_interleaved_bytes_from_2_regs(void *dest);
    
extern void write_interleaved_bytes_from_2_regs__half_(void *dest);
    
extern void write_interleaved_8_bytes_from_2_regs(void *dest);
    
extern void indexed_st2__write_2_bytes_from_2_regs(void *dest);
    
extern void indexed_st2__8_bytes_from_lows(void *dest);
    
extern void indexed_st2__8_bytes_from_highs(void *dest);
    
extern void write_interleaved_bytes_from_3_regs(void *dest);
    
extern void write_interleaved_bytes_from_3_regs__half_(void *dest);
    
extern void write_interleaved_8_bytes_from_3_regs(void *dest);
    
extern void indexed_st3__write_3_bytes_from_3_regs(void *dest);
    
extern void indexed_st3__8_bytes_from_lows(void *dest);
    
extern void indexed_st3__8_bytes_from_highs(void *dest);
    
extern void write_interleaved_bytes_from_4_regs(void *dest);
    
extern void write_interleaved_bytes_from_4_regs__half_(void *dest);
    
extern void write_interleaved_8_bytes_from_4_regs(void *dest);
    
extern void indexed_st4__write_4_bytes_from_4_regs(void *dest);
    
extern void indexed_st4__8_bytes_from_lows(void *dest);
    
extern void indexed_st4__8_bytes_from_highs(void *dest);
    