// subject_bss.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

byte g_b409024 = 0x00; // 0000000000409024
// subject_fini.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0000000000406978: void _fini()
void _fini()
{
}

// subject_got.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

<anonymous> * __libc_start_main_GOT = null; // 0000000000408FF0
<anonymous> * __gmon_start___GOT = null; // 0000000000408FF8
// subject_got_plt.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

<anonymous> * __assert_fail_GOT = &g_t401036; // 0000000000409018
// subject_init.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0000000000401000: void _init()
// Called from:
//      __libc_csu_init
void _init()
{
	if (__gmon_start__ != 0x00)
		__gmon_start__();
}

// subject_init_array.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

<anonymous> * g_a408E10[] = // 0000000000408E10
	{
	};
// subject_plt.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

<anonymous> g_t401036 = <code>; // 0000000000401036
// subject_text.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0000000000401040: void main()
void main()
{
	inst_0_values_var_0();
	inst_0_flags_var_0();
	inst_1_values_var_0();
	inst_1_flags_var_0();
	inst_2_values_var_0();
	inst_2_flags_var_0();
	inst_3_values_var_0();
	inst_3_flags_var_0();
	inst_4_values_var_0();
	inst_4_flags_var_0();
	inst_5_values_var_0();
	inst_5_flags_var_0();
	inst_6_values_var_0();
	inst_6_flags_var_0();
	inst_7_values_var_0();
	inst_7_flags_var_0();
	inst_8_values_var_0();
	inst_8_flags_var_0();
	inst_9_values_var_0();
	inst_9_flags_var_0();
	inst_10_values_var_0();
	inst_10_flags_var_0();
	inst_11_values_var_0();
	inst_11_flags_var_0();
	inst_12_values_var_0();
	inst_12_flags_var_0();
	inst_13_values_var_0();
	inst_13_flags_var_0();
	inst_14_values_var_0();
	inst_14_flags_var_0();
	inst_15_values_var_0();
	inst_15_flags_var_0();
	inst_16_values_var_0();
	inst_16_flags_var_0();
	inst_17_values_var_0();
	inst_17_flags_var_0();
	inst_18_values_var_0();
	inst_18_flags_var_0();
	inst_19_values_var_0();
	inst_19_flags_var_0();
	inst_20_values_var_0();
	inst_20_flags_var_0();
	inst_21_values_var_0();
	inst_21_flags_var_0();
	inst_22_values_var_0();
	inst_22_flags_var_0();
	inst_23_values_var_0();
	inst_23_flags_var_0();
	inst_24_values_var_0();
	inst_24_flags_var_0();
	inst_25_values_var_0();
	inst_25_flags_var_0();
	inst_26_values_var_0();
	inst_26_flags_var_0();
	inst_27_values_var_0();
	inst_27_flags_var_0();
	inst_28_values_var_0();
	inst_28_flags_var_0();
	inst_29_values_var_0();
	inst_29_flags_var_0();
	inst_30_values_var_0();
	inst_30_flags_var_0();
	inst_31_values_var_0();
	inst_31_flags_var_0();
	inst_32_values_var_0();
	inst_32_flags_var_0();
	inst_33_values_var_0();
}

// 0000000000401300: void _start(Register (ptr64 Eq_209) rdx, Stack word32 dwArg00, Stack (ptr64 char) ptrArg08)
void _start(void (* rdx)(), word32 dwArg00, char * ptrArg08)
{
	void * fp;
	word64 qwArg00;
	__align_stack<word64>(&ptrArg08);
	__libc_start_main(&g_t401040, (int32) qwArg00, &ptrArg08, &g_t406900, &g_t406970, rdx, fp);
	__halt();
}

// 0000000000401330: void _dl_relocate_static_pie()
void _dl_relocate_static_pie()
{
}

// 0000000000401340: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
}

// 0000000000401370: void register_tm_clones()
// Called from:
//      frame_dummy
void register_tm_clones()
{
}

// 00000000004013B0: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	if (g_b409024 != 0x00)
		return;
	deregister_tm_clones();
	g_b409024 = 0x01;
}

// 00000000004013E0: void frame_dummy()
// Called from:
//      __libc_csu_init
void frame_dummy()
{
	register_tm_clones();
}

// 00000000004013E6: void inst_0_values_var_0()
// Called from:
//      main
void inst_0_values_var_0()
{
}

// 00000000004014E6: void inst_0_flags_var_0()
// Called from:
//      main
void inst_0_flags_var_0()
{
}

// 00000000004015ED: void inst_1_values_var_0()
// Called from:
//      main
void inst_1_values_var_0()
{
}

// 00000000004016ED: void inst_1_flags_var_0()
// Called from:
//      main
void inst_1_flags_var_0()
{
}

// 00000000004017F3: void inst_2_values_var_0()
// Called from:
//      main
void inst_2_values_var_0()
{
}

// 00000000004018F3: void inst_2_flags_var_0()
// Called from:
//      main
void inst_2_flags_var_0()
{
}

// 00000000004019F9: void inst_3_values_var_0()
// Called from:
//      main
void inst_3_values_var_0()
{
}

// 0000000000401AF9: void inst_3_flags_var_0()
// Called from:
//      main
void inst_3_flags_var_0()
{
}

// 0000000000401C0F: void inst_4_values_var_0()
// Called from:
//      main
void inst_4_values_var_0()
{
}

// 0000000000401D0F: void inst_4_flags_var_0()
// Called from:
//      main
void inst_4_flags_var_0()
{
}

// 0000000000401E25: void inst_5_values_var_0()
// Called from:
//      main
void inst_5_values_var_0()
{
}

// 0000000000401F25: void inst_5_flags_var_0()
// Called from:
//      main
void inst_5_flags_var_0()
{
	int32 r10d_61 = __blsi<word32>(3411348999);
}

// 000000000040203B: void inst_6_values_var_0()
// Called from:
//      main
void inst_6_values_var_0()
{
}

// 000000000040213B: void inst_6_flags_var_0()
// Called from:
//      main
void inst_6_flags_var_0()
{
	int64 rdi_59 = __blsi<word64>(4680032883993358041);
}

// 0000000000402251: void inst_7_values_var_0()
// Called from:
//      main
void inst_7_values_var_0()
{
}

// 0000000000402351: void inst_7_flags_var_0()
// Called from:
//      main
void inst_7_flags_var_0()
{
	int32 r15d_61 = __blsmsk<word32>(440292650);
}

// 0000000000402467: void inst_8_values_var_0()
// Called from:
//      main
void inst_8_values_var_0()
{
}

// 0000000000402567: void inst_8_flags_var_0()
// Called from:
//      main
void inst_8_flags_var_0()
{
	int64 rdi_59 = __blsmsk<word64>(6444168133486643694);
}

// 000000000040267D: void inst_9_values_var_0()
// Called from:
//      main
void inst_9_values_var_0()
{
}

// 000000000040277D: void inst_9_flags_var_0()
// Called from:
//      main
void inst_9_flags_var_0()
{
	int32 ebp_61 = __blsr<word32>(2126829873);
}

// 0000000000402893: void inst_10_values_var_0()
// Called from:
//      main
void inst_10_values_var_0()
{
}

// 0000000000402993: void inst_10_flags_var_0()
// Called from:
//      main
void inst_10_flags_var_0()
{
	int64 rsi_59 = __blsr<word64>(11980623543633343204);
}

// 0000000000402AA9: void inst_11_values_var_0()
// Called from:
//      main
void inst_11_values_var_0()
{
}

// 0000000000402BA9: void inst_11_flags_var_0()
// Called from:
//      main
void inst_11_flags_var_0()
{
}

// 0000000000402CB7: void inst_12_values_var_0()
// Called from:
//      main
void inst_12_values_var_0()
{
}

// 0000000000402DB7: void inst_12_flags_var_0()
// Called from:
//      main
void inst_12_flags_var_0()
{
}

// 0000000000402EC5: void inst_13_values_var_0()
// Called from:
//      main
void inst_13_values_var_0()
{
}

// 0000000000402FC5: void inst_13_flags_var_0()
// Called from:
//      main
void inst_13_flags_var_0()
{
}

// 00000000004030DB: void inst_14_values_var_0()
// Called from:
//      main
void inst_14_values_var_0()
{
}

// 00000000004031DB: void inst_14_flags_var_0()
// Called from:
//      main
void inst_14_flags_var_0()
{
}

// 00000000004032F1: void inst_15_values_var_0()
// Called from:
//      main
void inst_15_values_var_0()
{
}

// 00000000004033F1: void inst_15_flags_var_0()
// Called from:
//      main
void inst_15_flags_var_0()
{
}

// 00000000004034EF: void inst_16_values_var_0()
// Called from:
//      main
void inst_16_values_var_0()
{
}

// 00000000004035EF: void inst_16_flags_var_0()
// Called from:
//      main
void inst_16_flags_var_0()
{
}

// 00000000004036ED: void inst_17_values_var_0()
// Called from:
//      main
void inst_17_values_var_0()
{
}

// 00000000004037ED: void inst_17_flags_var_0()
// Called from:
//      main
void inst_17_flags_var_0()
{
}

// 00000000004038EB: void inst_18_values_var_0()
// Called from:
//      main
void inst_18_values_var_0()
{
}

// 00000000004039EB: void inst_18_flags_var_0()
// Called from:
//      main
void inst_18_flags_var_0()
{
}

// 0000000000403AE9: void inst_19_values_var_0()
// Called from:
//      main
void inst_19_values_var_0()
{
}

// 0000000000403BE9: void inst_19_flags_var_0()
// Called from:
//      main
void inst_19_flags_var_0()
{
}

// 0000000000403CE7: void inst_20_values_var_0()
// Called from:
//      main
void inst_20_values_var_0()
{
}

// 0000000000403DE7: void inst_20_flags_var_0()
// Called from:
//      main
void inst_20_flags_var_0()
{
}

// 0000000000403EE5: void inst_21_values_var_0()
// Called from:
//      main
void inst_21_values_var_0()
{
}

// 0000000000403FE6: void inst_21_flags_var_0()
// Called from:
//      main
void inst_21_flags_var_0()
{
}

// 00000000004040E5: void inst_22_values_var_0()
// Called from:
//      main
void inst_22_values_var_0()
{
}

// 00000000004041E6: void inst_22_flags_var_0()
// Called from:
//      main
void inst_22_flags_var_0()
{
}

// 00000000004042E5: void inst_23_values_var_0()
// Called from:
//      main
void inst_23_values_var_0()
{
}

// 00000000004043E5: void inst_23_flags_var_0()
// Called from:
//      main
void inst_23_flags_var_0()
{
}

// 00000000004044E3: void inst_24_values_var_0()
// Called from:
//      main
void inst_24_values_var_0()
{
}

// 00000000004045E3: void inst_24_flags_var_0()
// Called from:
//      main
void inst_24_flags_var_0()
{
}

// 00000000004046E1: void inst_25_values_var_0()
// Called from:
//      main
void inst_25_values_var_0()
{
}

// 00000000004047E1: void inst_25_flags_var_0()
// Called from:
//      main
void inst_25_flags_var_0()
{
}

// 00000000004048DF: void inst_26_values_var_0()
// Called from:
//      main
void inst_26_values_var_0()
{
}

// 00000000004049DF: void inst_26_flags_var_0()
// Called from:
//      main
void inst_26_flags_var_0()
{
}

// 0000000000404ADD: void inst_27_values_var_0()
// Called from:
//      main
void inst_27_values_var_0()
{
}

// 0000000000404BDD: void inst_27_flags_var_0()
// Called from:
//      main
void inst_27_flags_var_0()
{
}

// 0000000000404CDB: void inst_28_values_var_0()
// Called from:
//      main
void inst_28_values_var_0()
{
}

// 0000000000404DDB: void inst_28_flags_var_0()
// Called from:
//      main
void inst_28_flags_var_0()
{
}

// 0000000000404ED9: void inst_29_values_var_0()
// Called from:
//      main
void inst_29_values_var_0()
{
}

// 0000000000404FDA: void inst_29_flags_var_0()
// Called from:
//      main
void inst_29_flags_var_0()
{
}

// 00000000004050E1: void inst_30_values_var_0()
// Called from:
//      main
void inst_30_values_var_0()
{
}

// 00000000004051E2: void inst_30_flags_var_0()
// Called from:
//      main
void inst_30_flags_var_0()
{
}

// 00000000004052E9: void inst_31_values_var_0()
// Called from:
//      main
void inst_31_values_var_0()
{
}

// 00000000004053EA: void inst_31_flags_var_0()
// Called from:
//      main
void inst_31_flags_var_0()
{
}

// 00000000004054F1: void inst_32_values_var_0()
// Called from:
//      main
void inst_32_values_var_0()
{
}

// 00000000004055F2: void inst_32_flags_var_0()
// Called from:
//      main
void inst_32_flags_var_0()
{
}

// 00000000004056F9: void inst_33_values_var_0()
// Called from:
//      main
void inst_33_values_var_0()
{
}

// 00000000004057F9: void inst_33_flags_var_0()
// Called from:
//      main
void inst_33_flags_var_0()
{
}

// 00000000004058F7: void inst_34_values_var_0()
// Called from:
//      main
void inst_34_values_var_0()
{
}

// 00000000004059F8: void inst_34_flags_var_0()
// Called from:
//      main
void inst_34_flags_var_0()
{
}

// 0000000000405AF7: void inst_35_values_var_0()
// Called from:
//      main
void inst_35_values_var_0()
{
}

// 0000000000405BF9: void inst_35_flags_var_0()
// Called from:
//      main
void inst_35_flags_var_0()
{
}

// 0000000000405CF9: void inst_36_values_var_0()
// Called from:
//      main
void inst_36_values_var_0()
{
}

// 0000000000405DF9: void inst_36_flags_var_0()
// Called from:
//      main
void inst_36_flags_var_0()
{
}

// 0000000000405EF8: void inst_37_values_var_0()
// Called from:
//      main
void inst_37_values_var_0()
{
}

// 0000000000405FF9: void inst_37_flags_var_0()
// Called from:
//      main
void inst_37_flags_var_0()
{
}

// 00000000004060F8: void inst_38_values_var_0()
// Called from:
//      main
void inst_38_values_var_0()
{
}

// 00000000004061F9: void inst_38_flags_var_0()
// Called from:
//      main
void inst_38_flags_var_0()
{
}

// 00000000004062F8: void inst_39_values_var_0()
// Called from:
//      main
void inst_39_values_var_0()
{
}

// 00000000004063F8: void inst_39_flags_var_0()
// Called from:
//      main
void inst_39_flags_var_0()
{
}

// 00000000004064F7: void inst_40_values_var_0()
// Called from:
//      main
void inst_40_values_var_0()
{
}

// 00000000004065F6: void inst_40_flags_var_0()
// Called from:
//      main
void inst_40_flags_var_0()
{
}

// 00000000004066F4: void inst_41_values_var_0()
// Called from:
//      main
void inst_41_values_var_0()
{
}

// 00000000004067F4: void inst_41_flags_var_0()
// Called from:
//      main
void inst_41_flags_var_0()
{
}

// 0000000000406900: void __libc_csu_init(Register word64 rdx, Register word64 rsi, Register word32 edi)
void __libc_csu_init(word64 rdx, word64 rsi, word32 edi)
{
	word64 rdi;
	word32 edi = (word32) rdi;
	_init();
	int64 rbp_31 = 0x00408E18 - g_a408E10;
	if (rbp_31 >> 0x03 != 0x00)
	{
		Eq_413 rbx_45 = 0x00;
		do
		{
			(*((char *) g_a408E10 + rbx_45 * 0x08))();
			rbx_45 = (word64) rbx_45.u1 + 1;
		} while (rbp_31 >> 0x03 != rbx_45);
	}
}

// 0000000000406970: void __libc_csu_fini()
void __libc_csu_fini()
{
}

