// subject.globals.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

struct Eq_240 * g_ptrFFF80000;
struct Eq_166 * g_ptrFFF90000;
struct Eq_511 * g_ptrFFFA0000;
struct Eq_240 * g_ptr60000;
struct Eq_240 * g_ptr70000;

