/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// void *init_proc();
int sub_8049030();
// int printf(const char *format, ...);
// int __cdecl __libc_start_main(int (__cdecl *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
int __cdecl main(int argc, const char **argv, const char **envp);
// void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>);
void sub_8049207();
// void dl_relocate_static_pie();
// void _x86_get_pc_thunk_bx();
// char *deregister_tm_clones();
// int register_tm_clones();
// char *_do_global_dtors_aux();
// int frame_dummy();
_BOOL4 __cdecl do_cmp(char a1, char a2);
_BOOL4 __cdecl do_signed(char a1, char a2);
_BOOL4 __cdecl do_cmp_const(char a1);
_BOOL4 __cdecl do_signed_const(char a1);
// int (**_libc_csu_init())();
// void _libc_csu_fini();
// void term_proc();

//-------------------------------------------------------------------------
// Data declarations

int (*dword_804C008)(void) = NULL; // weak


//----- (08049030) --------------------------------------------------------
int sub_8049030()
{
  return dword_804C008();
}
// 804C008: using guessed type int (*dword_804C008)(void);

//----- (08049060) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  int i; // esi
  int v4; // ebx
  int v5; // edx
  int v6; // edi
  int j; // ebx
  int v8; // edi
  _BOOL4 v9; // eax
  int v10; // edx
  _BOOL4 v12; // [esp+0h] [ebp-24h]
  int v13; // [esp+8h] [ebp-1Ch]
  int v14; // [esp+8h] [ebp-1Ch]
  int v15; // [esp+8h] [ebp-1Ch]

  for ( i = 0; i != 256; ++i )
  {
    v4 = do_cmp_const(i);
    v5 = do_signed_const(i);
    v6 = (char)i <= 9;
    if ( v4 != v6 )
    {
      v13 = v5;
      printf("CONST C and setl differ: %3d = 0x%02x  ->  ", i, i);
      printf("x<10 = %d %d\n", v4, v6);
      v5 = v13;
    }
    v14 = v5;
    if ( v4 != v5 )
    {
      printf("CONST %3d = 0x%02x  ->  ", i, i);
      printf("x<10 = %d %d ", v4, v6);
      printf("x-10<0 =%d\n", v14);
    }
    for ( j = 0; j != 256; ++j )
    {
      v8 = do_cmp(i, j);
      v9 = do_signed(i, j);
      v10 = v9;
      if ( v8 != (char)i < (char)j )
      {
        v12 = v9;
        printf("C and setl differ: %3d = 0x%02x %3d = 0x%02x  ->  ", i, i, j, j);
        printf("x<y = %d %d\n", v8, (char)i < (char)j);
        v10 = v12;
      }
      v15 = v10;
      if ( v8 != v10 )
      {
        printf("%3d = 0x%02x %3d = 0x%02x  ->  ", i, i, j, j);
        printf("x<y = %d ", v8);
        printf("x-y<0 =%d\n", v15);
      }
    }
  }
  return 0;
}

//----- (08049207) --------------------------------------------------------
void sub_8049207()
{
  ;
}

//----- (080492E6) --------------------------------------------------------
_BOOL4 __cdecl do_cmp(char a1, char a2)
{
  return a1 < a2;
}

//----- (080492FB) --------------------------------------------------------
_BOOL4 __cdecl do_signed(char a1, char a2)
{
  return (char)(a1 - a2) < 0;
}

//----- (08049310) --------------------------------------------------------
_BOOL4 __cdecl do_cmp_const(char a1)
{
  return a1 < 10;
}

//----- (08049320) --------------------------------------------------------
_BOOL4 __cdecl do_signed_const(char a1)
{
  return (char)(a1 - 10) < 0;
}

// nfuncs=22 queued=7 decompiled=7 lumina nreq=0 worse=0 better=0
// ALL OK, 7 function(s) have been successfully decompiled
