// subject.globals.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

Eq_7 g_t000E;
Eq_347 g_a006F[];
byte g_b01CB; // 000001CB
ui32 g_dw01F9; // 000001F9
Eq_2 g_t118A;
