// subject.globals.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

word32 g_dw10000588 = 99252;
struct Eq_3 g_t10000628 = 
	{
		0x93E1001C,
	};
Eq_39 g_t10000914 = Unexpected function type (fn void ())
;
char g_str10000928[] = "%d, %d";
char g_str1000092C[] = "%d";
char g_str10000930[] = "%d\n";
word32 g_dw10010938 = ~0x00;
word32 g_dw10010944 = 0x00;
word32 g_dw10010948 = 0x00;
word32 * g_ptr10010A28 = &g_dw10010944;
byte g_b10010AAC = 0x00;

