// subject.globals.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

Eq_24 g_t8049060 = Unexpected function type (fn int32 (int32, (ptr32 (ptr32 char)), (ptr32 (ptr32 char))))
;
void g_t8053740() = Unexpected function type (fn void ())
;
void g_t80537A0() = Unexpected function type (fn void ())
;
<anonymous> * g_ptr8056004 = null;
byte g_b8056018 = 0x00;

