/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall sub_4010FB(__int64 *, __int64);
__int64 __fastcall sub_4011A5(__int64, __int64 *, __int64, __int64);
__int64 sub_401214();
char *__fastcall sub_401297();
__int64 sub_40134D();
void __fastcall __noreturn sub_40139B(__int64, __int64);
__int64 sub_4013B4();
void __noreturn start();
__int64 __fastcall sub_401601();
unsigned __int64 __fastcall sub_40162C();
__int64 __fastcall sub_40165C(__int64, __int64);
__int64 __fastcall sub_401872(__int64, __int64);
__int64 __fastcall sub_401907(__int64, __int64);
__int64 __fastcall sub_40199D(); // weak
__int64 sub_4019FA();
__int64 __fastcall sub_401A09();
__int64 __fastcall sub_401A3C();
void __fastcall __noreturn sub_401AA1();

//-------------------------------------------------------------------------
// Data declarations

char byte_401AD2[6] = { '\0', '\0', '\0', '\0', '\0', '\0' }; // weak
char byte_401AF7[2] = { '\x01', 'À' }; // weak
char byte_401EE9[4] = { '\f', 'Î', '\0', '\x01' }; // weak
char byte_401EED[3] = { '\f', '&', 'ç' }; // weak
char byte_401EF1[4] = { '\f', 'Î', '\0', '\x01' }; // weak
char byte_401EF5[3] = { '\x0E', '\x01', '\x7F' }; // weak
__int64 qword_401EF8[33] =
{
  7354519480904502796i64,
  2216628014i64,
  145268933551616i64,
  -8926399244470845440i64,
  1093923909683642368i64,
  7349874591868683295i64,
  2216628014i64,
  145268933551616i64,
  -8926399244470845440i64,
  1093923909683642368i64,
  7349874591868683295i64,
  2216628014i64,
  145268933551616i64,
  -8926399244470845440i64,
  1093923909683642368i64,
  7349874591868683295i64,
  2216628014i64,
  145268933551616i64,
  -8926399244470845440i64,
  1093923909683642368i64,
  7349874591868683295i64,
  2216628014i64,
  145268933551616i64,
  -8926399244470845440i64,
  1093923909683642368i64,
  7349874591868683295i64,
  2216628014i64,
  145268933551616i64,
  -8926399244470845440i64,
  1093923909683642368i64,
  7349874591868683295i64,
  2216628014i64,
  2149519104i64
}; // weak
_UNKNOWN unk_402008; // weak
// extern void (__stdcall __noreturn *ExitProcess)(UINT uExitCode);
// extern BOOL (__stdcall *FreeEnvironmentStringsW)(LPWCH penv);
// extern LPWSTR (__stdcall *GetCommandLineW)();
// extern LPWCH (__stdcall *GetEnvironmentStringsW)();
// extern HANDLE (__stdcall *GetStdHandle)(DWORD nStdHandle);
// extern BOOL (__stdcall *SetDefaultDllDirectories)(DWORD DirectoryFlags);
// extern BOOL (__stdcall *WriteFile)(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);
int dword_403000; // weak
int dword_403018; // weak
int dword_403020; // weak
int dword_403030[4]; // weak
__int64 qword_403040; // weak
_UNKNOWN unk_403048; // weak
int dword_403358; // weak
int dword_40335C; // weak


//----- (00000000004010FB) ----------------------------------------------------
__int64 __fastcall sub_4010FB(__int64 *a1, __int64 a2)
{
  unsigned __int64 v2; // rdi
  int v3; // esi
  char i; // cl
  __int64 v6; // rax
  __int64 *v8; // rdx
  __int64 v9; // rax

  for ( i = 39; ; i -= 9 )
  {
    --v3;
    v6 = (v2 >> i) & 0x1FF;
    if ( v3 == -1 )
      break;
    v8 = (__int64 *)(a2 + 8 * v6);
    if ( !*v8 )
    {
      v9 = *a1 - 4096;
      *a1 = v9;
      *v8 = v9 | 3;
    }
    a2 = *v8 & 0x3FFFFFFFFF000i64;
  }
  return a2 + 8 * v6;
}
// 401110: variable 'v3' is possibly undefined
// 401112: variable 'v2' is possibly undefined

//----- (00000000004011A5) ----------------------------------------------------
__int64 __fastcall sub_4011A5(__int64 a1, __int64 *a2, __int64 a3, __int64 a4)
{
  unsigned int v4; // er10
  unsigned int v5; // er11
  __int64 v6; // rbx
  __int64 v7; // r13
  __int64 *v8; // r8
  int v9; // er12
  int v10; // er14
  __int64 v11; // rax
  unsigned int v12; // ecx
  __int64 *v13; // rsi
  __int64 *v14; // rdi
  __int64 i; // rcx
  __int64 result; // rax

  do
  {
    v6 = *a2;
    v7 = a2[1];
    v8 = a2;
    v9 = *((_DWORD *)a2 + 4);
    v10 = *((_DWORD *)a2 + 5);
    LODWORD(v11) = v5;
    while ( 1 )
    {
      v12 = v11;
      v11 = (unsigned int)(v11 - 1);
      if ( v6 == *(v8 - 3) )
        break;
      v13 = v8 - 3;
      v14 = v8;
      v8 -= 3;
      for ( i = 6i64; i; --i )
      {
        *(_DWORD *)v14 = *(_DWORD *)v13;
        v13 = (__int64 *)((char *)v13 + 4);
        v14 = (__int64 *)((char *)v14 + 4);
      }
      if ( !(_DWORD)v11 )
        goto LABEL_9;
    }
    v11 = v12;
LABEL_9:
    ++v5;
    a2 += 3;
    result = a4 + 24 * v11;
    *(_QWORD *)result = v6;
    *(_QWORD *)(result + 8) = v7;
    *(_DWORD *)(result + 16) = v9;
    *(_DWORD *)(result + 20) = v10;
  }
  while ( v5 < v4 );
  return result;
}
// 4011C2: variable 'v5' is possibly undefined
// 401209: variable 'v4' is possibly undefined

//----- (0000000000401214) ----------------------------------------------------
__int64 sub_401214()
{
  return 0i64;
}

//----- (0000000000401297) ----------------------------------------------------
char *__fastcall sub_401297()
{
  _QWORD *v0; // r15
  char *v1; // rsi
  char *result; // rax
  char **i; // rdi
  char v4; // cl
  unsigned __int64 v5; // rdx
  char v6; // al
  unsigned __int64 v7; // r8
  __int64 v8; // [rsp-18h] [rbp-20h]
  __int64 v9; // [rsp-10h] [rbp-18h]

  if ( (dword_403000 & 8) != 0 )
  {
    v9 = 69i64;
    v8 = 8i64;
    v1 = (char *)qword_401EF8;
  }
  else if ( (dword_403000 & 0x20) != 0 )
  {
    v9 = 48i64;
    v8 = 32i64;
    v1 = byte_401EE9;
  }
  else if ( (dword_403000 & 4) != 0 )
  {
    v9 = 34i64;
    v8 = 4i64;
    v1 = byte_401EF5;
  }
  else if ( *v0 )
  {
    v9 = 0i64;
    v8 = 1i64;
    v1 = byte_401EED;
  }
  else
  {
    v9 = 42i64;
    v8 = 16i64;
    v1 = byte_401EF1;
  }
  *(_QWORD *)&dword_403000 = v8;
  result = (char *)sub_40199D + v9;
  *((_QWORD *)&dword_403000 + 1) = (char *)sub_40199D + v9;
  for ( i = (char **)&dword_403018; i < (char **)dword_403030; ++i )
  {
    v4 = 0;
    v5 = 0i64;
    do
    {
      v6 = *v1++;
      v7 = (unsigned __int64)(v6 & 0x7F) << v4;
      v4 += 7;
      v5 |= v7;
    }
    while ( v6 < 0 );
    if ( (v6 & 0x40) != 0 )
      v5 |= -1i64 << v4;
    result = (char *)v5;
    if ( *i )
      result = *i;
    *i = result;
  }
  return result;
}
// 401297: could not find valid save-restore pair for rdi
// 401297: could not find valid save-restore pair for rsi
// 4012B6: variable 'v0' is possibly undefined
// 40199D: using guessed type __int64 __fastcall sub_40199D();
// 401EF8: using guessed type __int64 qword_401EF8[33];
// 403000: using guessed type int dword_403000;
// 403018: using guessed type int dword_403018;
// 403030: using guessed type int dword_403030[4];

//----- (000000000040134D) ----------------------------------------------------
__int64 sub_40134D()
{
  return 42i64;
}

//----- (000000000040139B) ----------------------------------------------------
void __fastcall __noreturn sub_40139B(__int64 a1, __int64 a2)
{
  sub_401907(a1, a2);
  sub_401AA1();
}
// 4013A6: ignored the value written to the shadow area of the succeeding call

//----- (00000000004013B4) ----------------------------------------------------
__int64 sub_4013B4()
{
  dword_403358 = dword_403018;
  return -1i64;
}
// 403018: using guessed type int dword_403018;
// 403358: using guessed type int dword_403358;

//----- (00000000004013C5) ----------------------------------------------------
void __noreturn start()
{
  void (**v0)(void); // rax
  void (**v1)(void); // rcx
  __int64 v2; // rdx
  __int64 v3; // rcx
  HANDLE StdHandle; // rax
  LPWCH EnvironmentStringsW; // r13
  __int64 i; // rax
  unsigned int v7; // eax
  DWORD *v8; // rcx
  char *v9; // r10
  unsigned __int64 v10; // r8
  WCHAR *v11; // rdx
  DWORD *v12; // r11
  __int64 v13; // rax
  unsigned int v14; // er9
  unsigned __int64 v15; // rax
  unsigned int v16; // eax
  __int64 v17; // rax
  unsigned __int64 v18; // rcx
  void (**v19)(void); // [rsp-10h] [rbp-E080h]
  __int64 v20; // [rsp-8h] [rbp-E078h]
  unsigned int v21; // [rsp+2Ch] [rbp-E044h]
  __int64 v22[513]; // [rsp+38h] [rbp-E038h]
  __int64 v23[512]; // [rsp+1040h] [rbp-D030h] BYREF
  DWORD NumberOfBytesWritten[8191]; // [rsp+6040h] [rbp-8030h] BYREF
  char v25; // [rsp+E03Eh] [rbp-32h] BYREF

  v22[0] = 0i64;
  if ( !SetDefaultDllDirectories(0x800u) )
  {
    StdHandle = GetStdHandle(0xFFFFFFF4);
    WriteFile(StdHandle, "nodll\n", 6u, NumberOfBytesWritten, 0i64);
    ExitProcess(1u);
  }
  dword_403000 = 4;
  GetCommandLineW();
  EnvironmentStringsW = GetEnvironmentStringsW();
  sub_40165C((__int64)v23, 0x3FFFi64);
  for ( i = 0i64; *(_BYTE *)(i + v23[0]); ++i )
  {
    if ( *(_BYTE *)(i + v23[0]) == 92 )
      *(_BYTE *)(i + v23[0]) = 47;
  }
  if ( *EnvironmentStringsW > 0xD7FFu )
  {
    v7 = sub_4019FA();
  }
  else
  {
    v21 = *EnvironmentStringsW;
    v7 = 1;
  }
  v8 = NumberOfBytesWritten;
  v9 = &v25;
  v10 = 0i64;
  v11 = &EnvironmentStringsW[v7];
  v12 = NumberOfBytesWritten;
  while ( v21 )
  {
    if ( ++v10 <= 0x1FF )
    {
      v13 = 0i64;
      if ( v8 < (DWORD *)v9 )
        v13 = (__int64)v8;
      v22[v10] = v13;
    }
    do
    {
      v14 = v21;
      v15 = (int)v21;
      if ( v21 > 0x7F )
        v15 = sub_401A09();
      do
      {
        if ( v8 >= (DWORD *)v9 )
          break;
        v8 = (DWORD *)((char *)v8 + 1);
        *((_BYTE *)v8 - 1) = v15;
        v15 >>= 8;
      }
      while ( v15 );
      if ( *v11 > 0xD7FFu )
      {
        v16 = sub_4019FA();
      }
      else
      {
        v21 = *v11;
        v16 = 1;
      }
      v11 += v16;
    }
    while ( v14 );
    v17 = (char *)v8 - (char *)v12;
    if ( (unsigned __int64)((char *)v8 - (char *)v12) > 0x7FFD )
      v17 = 32765i64;
    *((_BYTE *)NumberOfBytesWritten + v17) = 0;
  }
  if ( v8 < (DWORD *)v9 )
  {
    *(_BYTE *)v8 = 0;
    v8 = (DWORD *)((char *)v8 + 1);
  }
  v18 = (char *)v8 - (char *)v12;
  if ( v18 > 0x7FFE )
    v18 = 32766i64;
  if ( v10 > 0x1FF )
    v10 = 511i64;
  *((_BYTE *)NumberOfBytesWritten + v18) = 0;
  v22[v10 + 1] = 0i64;
  FreeEnvironmentStringsW(EnvironmentStringsW);
  sub_401297();
  dword_40335C |= 1u;
  v0 = (void (**)(void))&unk_402008;
  v1 = (void (**)(void))&unk_402008;
  while ( v1 != v0 )
  {
    (*v0)();
    v1 = v19;
    v0 = (void (**)(void))(v20 + 8);
  }
  sub_40134D();
  sub_40139B(v3, v2);
}
// 40137A: ignored the value written to the shadow area of the succeeding call
// 401379: ignored the value written to the shadow area of the succeeding call
// 401503: variable 'v21' is possibly undefined
// 401509: variable 'v10' is possibly undefined
// 40151B: variable 'v8' is possibly undefined
// 40151B: variable 'v9' is possibly undefined
// 401550: variable 'v11' is possibly undefined
// 401579: variable 'v14' is possibly undefined
// 40157E: variable 'v12' is possibly undefined
// 40137D: variable 'v19' is possibly undefined
// 40137F: variable 'v20' is possibly undefined
// 401396: variable 'v3' is possibly undefined
// 401396: variable 'v2' is possibly undefined
// 403000: using guessed type int dword_403000;
// 40335C: using guessed type int dword_40335C;
// 4013C5: using guessed type __int64 var_D030[512];

//----- (0000000000401601) ----------------------------------------------------
__int64 __fastcall sub_401601()
{
  unsigned __int16 **v0; // rdi
  _QWORD *v1; // rdx
  int v2; // eax
  unsigned int v3; // eax
  __int64 result; // rax

  v1 = v0;
  v2 = **v0;
  if ( (unsigned __int16)v2 > 0xD7FFu )
  {
    v3 = sub_4019FA();
  }
  else
  {
    *((_DWORD *)v0 + 6) = v2;
    v3 = 1;
  }
  result = 2i64 * v3;
  *v1 += result;
  return result;
}
// 401601: variable 'v0' is possibly undefined
// 401628: variable 'v1' is possibly undefined

//----- (000000000040162C) ----------------------------------------------------
unsigned __int64 __fastcall sub_40162C()
{
  __int64 v0; // rdi
  unsigned int v1; // esi
  __int64 v2; // rdx
  unsigned __int64 v3; // r8
  unsigned __int64 result; // rax
  _BYTE *v5; // rcx

  v2 = v0;
  v3 = *(_QWORD *)(v0 + 16);
  result = (int)v1;
  if ( v1 > 0x7F )
    result = sub_401A09();
  do
  {
    v5 = *(_BYTE **)(v2 + 8);
    if ( v3 <= (unsigned __int64)v5 )
      break;
    *(_QWORD *)(v2 + 8) = v5 + 1;
    *v5 = result;
    result >>= 8;
  }
  while ( result );
  return result;
}
// 40162C: variable 'v0' is possibly undefined
// 401638: variable 'v1' is possibly undefined
// 401642: variable 'v2' is possibly undefined
// 401649: variable 'v3' is possibly undefined

//----- (000000000040165C) ----------------------------------------------------
__int64 __fastcall sub_40165C(__int64 a1, __int64 a2)
{
  _BYTE *v2; // rsi
  __int64 v3; // r15
  unsigned __int64 v4; // rbx
  __int64 v5; // r11
  unsigned __int64 v6; // r8
  _BYTE *v7; // rax
  __int64 v8; // r12
  __int64 v10; // [rsp+10h] [rbp-60h]
  __int64 v11; // [rsp+10h] [rbp-60h]
  unsigned __int64 v12; // [rsp+18h] [rbp-58h]
  __int64 v13; // [rsp+18h] [rbp-58h]
  _BYTE *v14; // [rsp+30h] [rbp-40h]
  unsigned int v15; // [rsp+38h] [rbp-38h]

  v3 = 0x100002600i64;
  v4 = 0i64;
  v14 = &v2[a2];
  sub_401601();
LABEL_2:
  if ( v15 )
  {
    while ( v15 <= 0x20 && _bittest64(&v3, v15) )
      sub_401601();
    if ( ++v4 < v12 )
    {
      v7 = v2;
      if ( v2 >= v14 )
        v7 = 0i64;
      *(_QWORD *)(v10 + 8 * v4 - 8) = v7;
    }
    while ( 1 )
    {
      if ( v15 > 0x20 )
      {
        if ( v15 == 34 || v15 == 92 )
        {
          v8 = 0i64;
          while ( v15 == 92 )
          {
            ++v8;
            sub_401601();
          }
          while ( 1 )
            sub_401601();
        }
      }
      else if ( _bittest64(&v3, v15) )
      {
        sub_40162C();
        goto LABEL_2;
      }
      sub_40162C();
      sub_401601();
    }
  }
  sub_40162C();
  if ( v5 )
    *v2 = 0;
  if ( v13 )
  {
    v6 = v13 - 1;
    if ( v13 - 1 > v4 )
      v6 = v4;
    *(_QWORD *)(v11 + 8 * v6) = 0i64;
  }
  return (unsigned int)v4;
}
// 401692: ignored the value written to the shadow area of the succeeding call
// 40168E: ignored the value written to the shadow area of the succeeding call
// 4017C2: ignored the value written to the shadow area of the succeeding call
// 4016AE: conditional instruction was optimized away because %var_38.4!=0
// 40173B: conditional instruction was optimized away because %var_38.4!=0
// 401744: conditional instruction was optimized away because r14.1==0
// 401785: conditional instruction was optimized away because %var_38.4==22
// 40169A: variable 'v2' is possibly undefined
// 4016A7: variable 'v15' is possibly undefined
// 4016D2: variable 'v5' is possibly undefined
// 4016F0: variable 'v13' is possibly undefined
// 401708: variable 'v11' is possibly undefined
// 40171C: variable 'v12' is possibly undefined
// 40172E: variable 'v10' is possibly undefined

//----- (0000000000401872) ----------------------------------------------------
__int64 __fastcall sub_401872(__int64 a1, __int64 a2)
{
  __int64 v2; // rdi
  __int64 v3; // rsi
  _DWORD *v4; // rbx
  __int64 result; // rax
  unsigned int v6; // eax
  _QWORD *v7; // rbx

  v4 = (_DWORD *)qword_403040;
  if ( !qword_403040 )
  {
    v4 = &unk_403048;
    qword_403040 = (__int64)&unk_403048;
  }
  if ( *v4 == -1 )
    return sub_4013B4();
  _BitScanReverse(&v6, ~*v4);
  *v4 |= 1 << v6;
  v7 = &v4[6 * v6];
  result = 0i64;
  v7[2] = v2;
  v7[3] = v3;
  v7[4] = a2;
  return result;
}
// 4018F2: variable 'v2' is possibly undefined
// 4018F6: variable 'v3' is possibly undefined
// 403040: using guessed type __int64 qword_403040;

//----- (0000000000401907) ----------------------------------------------------
__int64 __fastcall sub_401907(__int64 a1, __int64 a2)
{
  __int64 v2; // rdi
  __int64 v3; // r12
  unsigned int *v4; // rdi
  __int64 v5; // rax
  int v6; // ecx
  __int64 v7; // rdx
  void (*v8)(void); // rdx
  __int64 v10; // [rsp-8h] [rbp-20h]

  v3 = v2;
  v10 = a2;
LABEL_2:
  while ( 1 )
  {
    v4 = (unsigned int *)qword_403040;
    if ( !qword_403040 )
      return v10;
    while ( 1 )
    {
      v5 = *v4;
      while ( v5 )
      {
        _BitScanForward((unsigned int *)&v6, v5);
        v7 = (unsigned int)~(1 << v6);
        v5 &= v7;
        if ( !v3 || *(_QWORD *)&v4[6 * v6 + 8] == v3 )
        {
          *v4 &= v7;
          v8 = *(void (**)(void))&v4[6 * v6 + 4];
          if ( v8 )
          {
            v8();
            goto LABEL_2;
          }
        }
      }
      if ( !v3 )
        break;
      if ( !*((_QWORD *)v4 + 1) )
        return v10;
      v4 = (unsigned int *)*((_QWORD *)v4 + 1);
    }
    qword_403040 = *((_QWORD *)v4 + 1);
  }
}
// 40190F: variable 'v2' is possibly undefined
// 401995: variable 'v10' is possibly undefined
// 403040: using guessed type __int64 qword_403040;

//----- (000000000040199D) ----------------------------------------------------
__int64 __fastcall sub_40199D()
{
  __int16 v0; // ax
  __int64 result; // rax

  result = (unsigned int)v0;
  if ( (int)result < 0 )
  {
    dword_403358 = dword_403020;
    return -1i64;
  }
  else
  {
    __asm { syscall; Low latency system call }
  }
  return result;
}
// 4019AF: conditional instruction was optimized away because rax.8<80000000u
// 40199D: variable 'v0' is possibly undefined
// 40199D: using guessed type __int64 __fastcall sub_40199D();
// 403020: using guessed type int dword_403020;
// 403358: using guessed type int dword_403358;

//----- (00000000004019FA) ----------------------------------------------------
__int64 sub_4019FA()
{
  return sub_401A3C();
}

//----- (0000000000401A09) ----------------------------------------------------
__int64 __fastcall sub_401A09()
{
  __int64 v0; // rdi
  __int64 v1; // rax
  __int64 v2; // rcx
  int v3; // ecx
  char v4; // dl

  v0 = (unsigned int)v0;
  v1 = 0i64;
  if ( (unsigned int)v0 > 0x7F )
  {
    _BitScanReverse((unsigned int *)&v2, v0);
    v3 = *(_DWORD *)&byte_401AF7[2 * v2 - 14];
    do
    {
      v4 = v0;
      v0 = (unsigned int)v0 >> 6;
      LOBYTE(v1) = v4 & 0x3F | v1 | 0x80;
      v1 <<= 8;
      LOBYTE(v3) = v3 - 1;
    }
    while ( (_BYTE)v3 );
    LOBYTE(v1) = BYTE1(v3) | v1;
  }
  return v0 | v1;
}
// 401A0B: variable 'v0' is possibly undefined
// 401A1C: variable 'v2' is possibly undefined

//----- (0000000000401A3C) ----------------------------------------------------
__int64 __fastcall sub_401A3C()
{
  __int64 v0; // rdi
  _DWORD *v1; // rsi
  __int64 result; // rax
  __int64 v3; // rdx
  int v4; // ebx
  int v5; // edx
  int v6; // eax

  LODWORD(result) = 0;
  do
  {
    v3 = (unsigned int)result;
    v4 = result;
    result = (unsigned int)(result + 1);
    v5 = *(unsigned __int16 *)(v0 + 2 * v3);
  }
  while ( (v5 & 0xFC00) == 0xDC00 );
  if ( (v5 & 0xFC00) == 0xD800 )
  {
    v6 = *(unsigned __int16 *)(v0 + 2 * result);
    if ( (v6 & 0xFC00) == 0xDC00 )
    {
      *v1 = (v5 << 10) + v6 - 56613888;
      return (unsigned int)(v4 + 2);
    }
    else
    {
      *v1 = 65533;
      return 0xFFFFFFFFi64;
    }
  }
  else
  {
    *v1 = v5;
  }
  return result;
}
// 401A4D: variable 'v0' is possibly undefined
// 401A66: variable 'v1' is possibly undefined

//----- (0000000000401AA1) ----------------------------------------------------
void __fastcall __noreturn sub_401AA1()
{
  unsigned __int8 v0; // di

  dword_40335C |= 4u;
  if ( (dword_403000 & 4) != 0 )
    ExitProcess(v0);
  __asm { syscall; Low latency system call }
  _disable();
  __lidt(byte_401AD2);
  __halt();
}
// 401AB1: variable 'v0' is possibly undefined
// 403000: using guessed type int dword_403000;
// 40335C: using guessed type int dword_40335C;

// nfuncs=18 queued=18 decompiled=18 lumina nreq=0 worse=0 better=0
// ALL OK, 18 function(s) have been successfully decompiled
