// subject_code.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0C00:0100: void fn0C00_0100(Register byte bh, Register (ptr16 Eq_4) ds)
void fn0C00_0100(byte bh, struct Eq_4 * ds)
{
	bios_video_set_mode(0x13);
	union Eq_10 Eq_4::* si_11 = &Eq_4::t01BC;
	do
	{
		word16 ax_10 = (ds->*si_11).u1;
		byte dh_18 = SLICE(ax_10, byte, 8);
		bios_video_set_cursor_position(bh, dh_18, (byte) ax_10);
		si_11 = (union Eq_10 Eq_4::*) ((char *) si_11 + 2);
		byte ah_16 = 0x02;
		do
		{
			byte al_183 = (ds->*si_11).u0;
			__syscall<byte>(33);
			si_11 = (union Eq_10 Eq_4::*) ((char *) si_11 + 1);
		} while (al_183 != 0x00);
	} while (dh_18 != 0x00);
	do
	{
		__out<byte>(969, al_183);
		word16 ax_44 = __rol<word16,byte>(SEQ(ah_16, ~al_183), 0x01);
		__out<byte>(969, (byte) ax_44);
		word16 ax_47 = __ror<word16,byte>(ax_44, 0x01);
		byte al_49 = (byte) ax_47;
		__out<byte>(969, al_49);
		byte al_50 = ~al_49;
		word16 ax_52 = SEQ(SLICE(ax_47, byte, 8), al_50);
		al_183 = al_50 + 0x01;
		ah_16 = SLICE(ax_52 + 0x01, byte, 8);
	} while (ax_52 != ~0x00);
	byte Eq_120::* di_108 = Eq_120::a0000;
	uint8 bl_193 = 0xCC;
	do
	{
		byte ch_110 = 0x01;
		ui16 cl_bl_232 = SEQ(0x40, bl_193);
		do
		{
			word16 bx_114;
			byte al_103;
			uint8 cl_85 = SLICE(cl_bl_232, byte, 8);
			byte bl_88 = (byte) cl_bl_232;
			word16 cx_109 = SEQ(ch_110, cl_85);
			if (0xA000->*di_108 == 0x00)
			{
				word16 ax_95 = __aam(cl_85 | bl_88);
				al_103 = ((byte) ax_95 | SLICE(ax_95, byte, 8)) & 0x3F;
				bx_114 = SEQ(bh, bl_88);
			}
			else
			{
				ui16 al_al_204 = SEQ(al_89, cl_85) - cl_bl_232;
				ui8 al_89 = (byte) al_al_204;
				al_103 = SLICE(al_al_204, byte, 8);
				cx_109 = SEQ(ch_110, cl_85);
				bx_114 = SEQ(bh, bl_88);
			}
			0xA000->*di_108 = al_103;
			word16 cx_113 = cx_109 - 0x01;
			bh = SLICE(bx_114, byte, 8);
			++di_108;
			ch_110 = SLICE(cx_113, byte, 8);
			cl_bl_232 = SEQ((byte) cx_113, (byte) bx_114);
		} while (cx_113 != 0x00);
		word16 bx_120 = bx_114 - 0x01;
		bl_193 = (byte) bx_120;
		bh = SLICE(bx_120, byte, 8);
	} while (bx_120 != 0x00);
	__out<byte>(0x0331, 0x3F);
	byte Eq_120::* si_130 = Eq_120::a0000;
	byte Eq_120::* di_134 = &Eq_120::bFA00;
	word16 cx_135;
	for (cx_135 = 0x0140; cx_135 != 0x00; --cx_135)
	{
		0xA000->*di_134 = 0xA000->*si_130;
		++si_130;
		++di_134;
	}
	do
		;
	while (((byte) __in<word16>(0x03DA) & 0x08) == 0x00);
}

