//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// --------------------- Global Variables ---------------------

struct _IO_FILE * g1 = NULL; // 0x8049854

// ------------------------ Functions -------------------------

// Address range: 0x8048410 - 0x804865f
int main(int argc, char ** argv) {
    int32_t result;
    scanf("%d", &result);
    int32_t v1;
    scanf("%d", &v1);
    if (result == 5) {
        // 0x8048627
        fwrite("Equal\n", 1, 6, g1);
        if (result == 5) {
            // 0x80484a4
            fwrite("Less or Equal\n", 1, 14, g1);
            if (result <= 5) {
                // 0x80484ce
                fwrite("Greater or Equal\n", 1, 17, g1);
                if (result <= 5) {
                    // 0x804851d
                    if (v1 < 5) {
                        // 0x8048522
                        fwrite("Greater Unsigned\n", 1, 17, g1);
                        if (v1 < 5) {
                            // 0x8048576
                            fwrite("Carry Clear\n", 1, 12, g1);
                            if (v1 > 5) {
                                // 0x80485a0
                                fwrite("Carry Set\n", 1, 10, g1);
                                // branch -> 0x80485f8
                            }
                            // 0x80485f8
                            fwrite("Minus\n", 1, 6, g1);
                            return result;
                        }
                    }
                    // 0x804854c
                    fwrite("Less or Equal Unsigned\n", 1, 23, g1);
                    if (v1 <= 5) {
                        // 0x8048576
                        fwrite("Carry Clear\n", 1, 12, g1);
                        if (v1 <= 5) {
                            // 0x80485f8
                            fwrite("Minus\n", 1, 6, g1);
                            return result;
                        }
                    }
                    // 0x80485a0
                    fwrite("Carry Set\n", 1, 10, g1);
                    // branch -> 0x80485f8
                    // 0x80485f8
                    fwrite("Minus\n", 1, 6, g1);
                    return result;
                }
            }
            // 0x80484f8
            fwrite("Less\n", 1, 5, g1);
            // branch -> 0x804851d
            // 0x804851d
            if (v1 < 5) {
                // 0x8048522
                fwrite("Greater Unsigned\n", 1, 17, g1);
                if (v1 < 5) {
                    // 0x8048576
                    fwrite("Carry Clear\n", 1, 12, g1);
                    if (v1 > 5) {
                        // 0x80485a0
                        fwrite("Carry Set\n", 1, 10, g1);
                        // branch -> 0x80485f8
                    }
                    // 0x80485f8
                    fwrite("Minus\n", 1, 6, g1);
                    return result;
                }
            }
            // 0x804854c
            fwrite("Less or Equal Unsigned\n", 1, 23, g1);
            if (v1 <= 5) {
                // 0x8048576
                fwrite("Carry Clear\n", 1, 12, g1);
                if (v1 <= 5) {
                    // 0x80485f8
                    fwrite("Minus\n", 1, 6, g1);
                    return result;
                }
            }
            // 0x80485a0
            fwrite("Carry Set\n", 1, 10, g1);
            // branch -> 0x80485f8
            // 0x80485f8
            fwrite("Minus\n", 1, 6, g1);
            return result;
        }
    }
    // 0x8048476
    fwrite("Not Equal\n", 1, 10, g1);
    if (result < 5) {
        // 0x804847a
        fwrite("Greater\n", 1, 8, g1);
        if (result < 5) {
            // 0x80484ce
            fwrite("Greater or Equal\n", 1, 17, g1);
            if (result > 5) {
                // 0x80484f8
                fwrite("Less\n", 1, 5, g1);
                // branch -> 0x804851d
            }
            // 0x804851d
            if (v1 < 5) {
                // 0x8048522
                fwrite("Greater Unsigned\n", 1, 17, g1);
                if (v1 < 5) {
                    // 0x8048576
                    fwrite("Carry Clear\n", 1, 12, g1);
                    if (v1 > 5) {
                        // 0x80485a0
                        fwrite("Carry Set\n", 1, 10, g1);
                        // branch -> 0x80485f8
                    }
                    // 0x80485f8
                    fwrite("Minus\n", 1, 6, g1);
                    return result;
                }
            }
            // 0x804854c
            fwrite("Less or Equal Unsigned\n", 1, 23, g1);
            if (v1 <= 5) {
                // 0x8048576
                fwrite("Carry Clear\n", 1, 12, g1);
                if (v1 <= 5) {
                    // 0x80485f8
                    fwrite("Minus\n", 1, 6, g1);
                    return result;
                }
            }
            // 0x80485a0
            fwrite("Carry Set\n", 1, 10, g1);
            // branch -> 0x80485f8
            // 0x80485f8
            fwrite("Minus\n", 1, 6, g1);
            return result;
        }
    }
    // 0x80484a4
    fwrite("Less or Equal\n", 1, 14, g1);
    if (result > 5) {
        // 0x80484f8
        fwrite("Less\n", 1, 5, g1);
        // branch -> 0x804851d
        // 0x804851d
        if (v1 < 5) {
            // 0x8048522
            fwrite("Greater Unsigned\n", 1, 17, g1);
            if (v1 < 5) {
                // 0x8048576
                fwrite("Carry Clear\n", 1, 12, g1);
                if (v1 > 5) {
                    // 0x80485a0
                    fwrite("Carry Set\n", 1, 10, g1);
                    // branch -> 0x80485f8
                }
                // 0x80485f8
                fwrite("Minus\n", 1, 6, g1);
                return result;
            }
        }
        // 0x804854c
        fwrite("Less or Equal Unsigned\n", 1, 23, g1);
        if (v1 > 5) {
            // 0x80485a0
            fwrite("Carry Set\n", 1, 10, g1);
            // branch -> 0x80485f8
            // 0x80485f8
            fwrite("Minus\n", 1, 6, g1);
            return result;
        }
        // 0x8048576
        fwrite("Carry Clear\n", 1, 12, g1);
        if (v1 <= 5) {
            // 0x80485f8
            fwrite("Minus\n", 1, 6, g1);
            return result;
        }
        // 0x80485a0
        fwrite("Carry Set\n", 1, 10, g1);
        // branch -> 0x80485f8
        // 0x80485f8
        fwrite("Minus\n", 1, 6, g1);
        return result;
    }
    // 0x80484ce
    fwrite("Greater or Equal\n", 1, 17, g1);
    if (result <= 5) {
        // 0x804851d
        if (v1 < 5) {
            // 0x8048522
            fwrite("Greater Unsigned\n", 1, 17, g1);
            if (v1 < 5) {
                // 0x8048576
                fwrite("Carry Clear\n", 1, 12, g1);
                if (v1 > 5) {
                    // 0x80485a0
                    fwrite("Carry Set\n", 1, 10, g1);
                    // branch -> 0x80485f8
                }
                // 0x80485f8
                fwrite("Minus\n", 1, 6, g1);
                return result;
            }
        }
        // 0x804854c
        fwrite("Less or Equal Unsigned\n", 1, 23, g1);
        if (v1 <= 5) {
            // 0x8048576
            fwrite("Carry Clear\n", 1, 12, g1);
            if (v1 <= 5) {
                // 0x80485f8
                fwrite("Minus\n", 1, 6, g1);
                return result;
            }
        }
        // 0x80485a0
        fwrite("Carry Set\n", 1, 10, g1);
        // branch -> 0x80485f8
        // 0x80485f8
        fwrite("Minus\n", 1, 6, g1);
        return result;
    }
    // 0x80484f8
    fwrite("Less\n", 1, 5, g1);
    // branch -> 0x804851d
    // 0x804851d
    if (v1 < 5) {
        // 0x8048522
        fwrite("Greater Unsigned\n", 1, 17, g1);
        if (v1 < 5) {
            // 0x8048576
            fwrite("Carry Clear\n", 1, 12, g1);
            if (v1 > 5) {
                // 0x80485a0
                fwrite("Carry Set\n", 1, 10, g1);
                // branch -> 0x80485f8
            }
            // 0x80485f8
            fwrite("Minus\n", 1, 6, g1);
            return result;
        }
    }
    // 0x804854c
    fwrite("Less or Equal Unsigned\n", 1, 23, g1);
    if (v1 <= 5) {
        // 0x8048576
        fwrite("Carry Clear\n", 1, 12, g1);
        if (v1 <= 5) {
            // 0x80485f8
            fwrite("Minus\n", 1, 6, g1);
            return result;
        }
    }
    // 0x80485a0
    fwrite("Carry Set\n", 1, 10, g1);
    // branch -> 0x80485f8
    // 0x80485f8
    fwrite("Minus\n", 1, 6, g1);
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// size_t fwrite(const void * restrict ptr, size_t size, size_t n, FILE * restrict s);
// int scanf(const char * restrict format, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (x86_64-unknown-linux-gnu) (4.7.2)
// Detected functions: 1
// Decompiler release: VERSION
// Decompilation date: DATE
