// subject.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

ui32 g_dwFFFFFFFF;
Eq_2 g_t80487A0 = Unexpected function type (fn void ())
;
ui32 g_a8048F6C[] = 
	{
	};
Eq_2 g_t8049510 = Unexpected function type (fn void ())
;
char g_str8049528[] = "%d";
char g_str804952B[] = "Equal\n";
char g_str8049532[] = "Not Equal\n";
char g_str804953D[] = "Greater\n";
char g_str8049546[] = "Less or Equal\n";
char g_str8049555[] = "Greater or Equal\n";
char g_str8049567[] = "Less\n";
char g_str804956D[] = "Greater Unsigned\n";
char g_str804957F[] = "Less or Equal Unsigned\n";
char g_str8049597[] = "Carry Clear\n";
char g_str80495A4[] = "Carry Set\n";
char g_str80495AF[] = "Minus\n";
char g_str80495B6[] = "Plus\n";
byte g_b80495BC = 0x00;
byte g_b80495BD = 0x65;
struct Eq_47 g_t804A5C0 = 
	{
		&g_ptr804A69C,
	};
word32 g_dw804A698 = 0xFFFFFFFF;
<anonymous> * g_ptr804A69C = null;
struct Eq_82 g_t804ACB0 = 
	{
		0x00000000,
		0x00000000,
		0x00000000,
		0x00000000,
		0x00000000,
		0x00000000,
	};
struct Eq_395 * g_ptr804ACC8 = null;
ptr32 g_ptr804ACCC = 0x00000000;

