// subject_fini.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject_fini.h"

// 0000000000000A7C: void _fini()
void _fini()
{
}

// subject_init.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject_init.h"

// 0000000000000690: Register word64 _init(Register out ptr64 x30Out)
// Called from:
//      __libc_csu_init
word64 _init(ptr64 & x30Out)
{
	call_weak_fn();
	x30Out = qwArg00;
	return x30;
}

// subject_plt.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject_plt.h"

// 00000000000006D0: void fn00000000000006D0()
// Called from:
//      __do_global_dtors_aux
void fn00000000000006D0()
{
	g_ptr11000();
}

// 00000000000006E0: void fn00000000000006E0()
// Called from:
//      _start
void fn00000000000006E0()
{
	g_ptr11008();
}

// 0000000000000700: void fn0000000000000700()
// Called from:
//      _start
void fn0000000000000700()
{
	g_ptr11018();
}

// 0000000000000710: void fn0000000000000710()
// Called from:
//      main
void fn0000000000000710()
{
	g_ptr11020();
}

// subject_text.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject_text.h"

// 0000000000000720: void main()
void main()
{
	real32 s9_24 = g_r0804;
	real32 s11_32 = g_r0818;
	word32 w19_39;
	real32 s13_40 = g_r0810;
	real32 s12_47 = g_r0814;
	real32 s15_48 = g_r0808;
	real32 s14_49 = g_r080C;
	real32 s10_50 = g_r081C;
	for (w19_39 = 33; w19_39 != 0x00; --w19_39)
	{
		real32 s1_52 = s9_24 * s9_24;
		real32 s6_59 = s1_52 * s1_52;
		real32 s16_65 = s6_59 * s9_24;
		real32 s17_66 = s6_59 * s16_65;
		__fmaddf(1.0F - s1_52 / 6.0F, s9_24, (1.0F - s1_52 / s11_32) * s16_65 / s10_50 + (((1.0F - s1_52 / s15_48) * (s6_59 * s17_66)) / s14_49 + ((1.0F - s1_52 / s13_40) * s17_66) / s12_47));
		fn0000000000000710();
		s9_24 += g_r0820;
	}
}

// 0000000000000824: void _start()
void _start()
{
	fn00000000000006E0();
	fn0000000000000700();
	call_weak_fn();
}

// 000000000000085C: void call_weak_fn()
// Called from:
//      _init
//      _start
void call_weak_fn()
{
	if (g_qw10FC0 == 0x00)
		return;
	word64 x17_12;
	g_ptr11010();
}

// 0000000000000870: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
	if (69695 - 69688 <= 0x0E)
		return;
	<anonymous> * x1_13 = g_ptr10FB0;
	if (x1_13 == null)
		return;
	x1_13();
}

// 00000000000008A8: void register_tm_clones()
// Called from:
//      frame_dummy
void register_tm_clones()
{
	int64 x1_7 = 69688 - 69688;
	if ((x1_7 >> 3) + ((x1_7 >> 3) >>u 63) >> 1 == 0x00)
		return;
	<anonymous> * x2_13 = g_ptr10FE0;
	if (x2_13 == null)
		return;
	word64 x2_17;
	x2_13();
}

// 00000000000008E8: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	if ((word32) g_b11038 == 0x00)
	{
		if (g_qw10FB8 != 0x00)
			fn00000000000006D0();
		deregister_tm_clones();
		g_b11038 = 0x01;
	}
}

// 0000000000000930: void frame_dummy(Register word64 x29, Register word64 x30)
void frame_dummy(word64 x29, word64 x30)
{
	if (g_qw10DA8 != 0x00)
	{
		<anonymous> * x1_8 = g_ptr10FD8;
		if (x1_8 != null)
		{
			x1_8();
			register_tm_clones();
			return;
		}
	}
	register_tm_clones();
}

// 0000000000000968: void sin(Register real32 s0)
void sin(real32 s0)
{
	real32 s1_4 = s0 * s0;
	real32 s1_18 = s1_4 * s1_4;
	real32 s6_19 = s0 * s1_18;
	real32 s6_24 = s1_18 * s6_19;
	__fmaddf(s0, 1.0F - s1_4 / 6.0F, (1.0F - s1_4 / g_r09F4) * s6_19 / g_r09F8 + (((1.0F - s1_4 / g_r09E4) * (s1_18 * s6_24)) / g_r09E8 + ((1.0F - s1_4 / g_r09EC) * s6_24) / g_r09F0));
}

// 0000000000000A00: void __libc_csu_init(Register word32 w0, Register word64 x1, Register word64 x2, Register word64 x24)
void __libc_csu_init(word32 w0, word64 x1, word64 x2, word64 x24)
{
	word32 x24_32_32_104 = SLICE(x24, word32, 32);
	int64 x20_26 = 0x00010DA0 - 69016;
	<anonymous> * x21_24[] = g_a10D98;
	word64 x22_34 = x2;
	word64 x23_38 = x1;
	word64 x30_44;
	word64 x29_43 = _init(out x30_44);
	int64 x20_45 = x20_26 >> 3;
	if (x20_26 >> 3 != 0x00)
	{
		int64 x19_46 = 0x00;
		word64 x24_151 = SEQ(x24_32_32_104, w0);
		do
		{
			word64 x3_76;
			x21_24[x19_46]();
			int64 x31_81 = x20_45 - x19_46;
		} while (x31_81 != 0x00);
	}
}

// 0000000000000A78: void __libc_csu_fini()
void __libc_csu_fini()
{
}

