// subject_code.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0C00:0100: void fn0C00_0100(Register (ptr16 Eq_3) ds)
void fn0C00_0100(struct Eq_3 * ds)
{
	bios_video_set_mode(0x13);
	byte Eq_18::* di_11 = &Eq_18::b0000;
	word16 cx_15;
	for (cx_15 = 0x0140; cx_15 != 0x00; --cx_15)
	{
		0xA000->*di_11 = 0x00;
		++di_11;
	}
	word16 cx_18;
	byte al_19 = 0x12;
	for (cx_18 = 63800; cx_18 != 0x00; --cx_18)
	{
		0xA000->*di_11 = 0x12;
		++di_11;
	}
	do
	{
		ds->w023A = 0x00;
		__syscall<byte>(22);
		if ((al_19 & 0x04) != 0x00)
			++ds->w023A;
		if ((al_19 & 0x08) != 0x00)
			--ds->w023A;
		Eq_64 bx_45 = ds->t0238;
		if (ds->t023C >= 0xE6)
		{
			Eq_64 ax_47 = ds->t023E;
			if (ax_47 - 0x05 >= bx_45)
			{
				if (ax_47 - 0x05 > bx_45)
					bx_45 = (word16) bx_45.u0 + 1;
			}
			else
				--bx_45;
		}
		ds->t0238 = fn0C00_029C(bx_45);
		Eq_64 bx_67 = fn0C00_029C((word16) ds->t0236 + ds->w023A);
		ds->t0236 = bx_67;
		if (ds->w0248 != 0x00)
			--ds->w0248;
		else
		{
			Eq_64 ax_76 = (word16) ds->t023E + ds->w0242;
			ds->t023E = ax_76;
			if (ax_76 == 0x02)
				ds->w0242 = 0x01;
			if (ax_76 == 0xC6)
				ds->w0242 = ~0x00;
			Eq_70 cx_90 = (word16) ds->t023C + ds->w0240;
			ds->t023C = cx_90;
			fn0C00_02AE(ax_76, cx_90, 0x01, bx_67, ds);
			fn0C00_02AE(ax_76, cx_90, 0x013E, ds->t0238, ds);
			if (cx_90 == 0x00)
				fn0C00_0275(ax_76, &Eq_3::w024C, ds);
			else if (cx_90 == 0x013F)
				fn0C00_0275(ax_76, &Eq_3::w024A, ds);
		}
		do
			;
		while ((__in<byte>(0x03DA) & 0x08) != 0x00);
		do
			;
		while ((__in<byte>(0x03DA) & 0x08) == 0x00);
		fn0C00_0250(ds->t0246, 0x12, ds->t0244, 0xA000, ds);
		Eq_64 ax_165 = ds->t023E;
		ds->t0246 = ax_165;
		Eq_70 bx_167 = ds->t023C;
		ds->t0244 = bx_167;
		fn0C00_0250(ax_165, 0x0E, bx_167, 0xA000, ds);
		fn0C00_0260(ds->t0238, SEQ(SLICE((uint16) fn0C00_0260(ds->t0236, 778, 0x01, 0xA000, ds), byte, 8), 0x0C), 0x013E, 0xA000, ds);
		Eq_70 bx_200 = 0x00;
		word16 cx_204 = ds->w024A;
		do
		{
			fn0C00_0250(0x00, 0x0F, bx_200, 0xA000, ds);
			bx_200 = (word16) bx_200 + 2;
			--cx_204;
		} while (cx_204 != 0x00);
		Eq_70 bx_219 = 0x013F;
		word16 cx_221 = ds->w024C;
		do
		{
			fn0C00_0250(0x00, 0x0F, bx_219, 0xA000, ds);
			bx_219 -= 0x02;
			--cx_221;
		} while (cx_221 != 0x00);
		byte ah_238;
	} while (bios_kbd_check_keystroke(out al_19, out ah_238));
	msdos_terminate_program20();
}

// 0C00:0250: void fn0C00_0250(Register Eq_64 ax, Register byte dl, Register Eq_70 bx, Register (ptr16 Eq_18) es, Register (ptr16 Eq_3) ds)
// Called from:
//      fn0C00_0100
//      fn0C00_0260
void fn0C00_0250(Eq_64 ax, byte dl, Eq_70 bx, struct Eq_18 * es, struct Eq_3 * ds)
{
	word16 dx;
	Mem23[es:bx + Mem13[ds:0x024E:word16] *u ax:byte] = SLICE(dx, byte, 0);
}

// 0C00:0260: Register byte fn0C00_0260(Register Eq_64 ax, Register cui16 dx, Register Eq_70 bx, Register (ptr16 Eq_18) es, Register (ptr16 Eq_3) ds)
// Called from:
//      fn0C00_0100
byte fn0C00_0260(Eq_64 ax, cui16 dx, Eq_70 bx, struct Eq_18 * es, struct Eq_3 * ds)
{
	word16 cx_16;
	for (cx_16 = 0x0A; cx_16 != 0x00; --cx_16)
	{
		fn0C00_0250(ax, (byte) dx, bx, es, ds);
		byte dh_19 = SLICE(dx, byte, 8);
		ax = (word16) ax + 1;
	}
	fn0C00_0250(ax, 0x12, bx, es, ds);
	fn0C00_0250(ax - 11, 0x12, bx, es, ds);
	return dh_19;
}

// 0C00:0275: void fn0C00_0275(Register Eq_64 ax, Register (memptr (ptr16 Eq_3) ci16) bx, Register (ptr16 Eq_3) ds)
// Called from:
//      fn0C00_0100
void fn0C00_0275(Eq_64 ax, ci16 Eq_3::* bx, struct Eq_3 * ds)
{
	if (ds->*bx < 0x50)
		++ds->*bx;
	Mem23[ds:0x023E:word16] = (Mem16[ds:14033:word16] *u (ax + Mem16[ds:566:word16]) & 0x7F) + 0x24;
	ds->t023C.u0 = 0xA0;
	ds->w0248 = 0x1E;
}

// 0C00:029C: Register Eq_64 fn0C00_029C(Register Eq_64 bx)
// Called from:
//      fn0C00_0100
Eq_64 fn0C00_029C(Eq_64 bx)
{
	if (bx <= 0x02)
		bx.u0 = 0x02;
	if (bx >= 0xBD)
		bx.u0 = 0xBD;
	return bx;
}

// 0C00:02AE: void fn0C00_02AE(Register Eq_64 ax, Register Eq_70 cx, Register Eq_70 dx, Register Eq_64 bx, Register (ptr16 Eq_3) ds)
// Called from:
//      fn0C00_0100
void fn0C00_02AE(Eq_64 ax, Eq_70 cx, Eq_70 dx, Eq_64 bx, struct Eq_3 * ds)
{
	if (cx == dx && (ax >= bx && ax < (word16) bx.u0 + 0x0A))
		ds->w0240 = -ds->w0240;
}

