// subject_seg08048000.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0804804C: FlagGroup byte fn0804804C(Register (ptr32 Eq_3) esi, Register out Eq_4 alOut, Register out ptr32 esiOut)
// Called from:
//      fn0804806C
byte fn0804804C(struct Eq_3 * esi, union Eq_4 & alOut, ptr32 & esiOut)
{
	char al_6 = esi->b0000;
	ptr32 esi_15 = &esi->b0001;
	if (al_6 != 0x00)
	{
		char al_14 = esi->b0001;
		esi_15 = &esi->b0001 + 1;
		if (al_6 < 0x30 || al_14 < 0x30)
		{
l0804806B:
			alOut.u1 = <invalid>;
			esiOut = esi_15;
			return <invalid>;
		}
		if (al_6 <= 0x39 && al_14 <= 0x39)
		{
			alOut.u1 = <invalid>;
			esiOut = &esi->b0001 + 1;
			return <invalid>;
		}
	}
	goto l0804806B;
}

// 0804806C: void fn0804806C(Register Eq_31 edx)
void fn0804806C(Eq_31 edx)
{
	ptr32 fp;
	struct Eq_33 * esp_10 = fp + 8;
	struct Eq_36 * ebp_21 = &g_t80482BA;
	while (true)
	{
		word16 edx_16_16_385 = SLICE(edx, word16, 16);
		struct Eq_36 * esi_12 = esp_10->dw0000;
		++esp_10;
		if (esi_12 == null)
			break;
		byte al_300 = esi_12->b0000;
		if (al_300 == 0x2D)
		{
			byte al_304 = esi_12->b0001;
			if (al_304 != 115)
			{
				if (al_304 == 116)
				{
					++g_b8048C2C;
					byte * esi_324;
					byte al_405;
					fn0804804C(&esi_12->b0002, out al_405, out esi_324);
					word16 ax_323 = <invalid>;
					bool Z_327 = <invalid>;
					bool C_326 = <invalid>;
					ci8 al_330 = (byte) ax_323;
					if (!(Z_327 | C_326) && *esi_324 == 0x2D)
					{
						byte * esi_337;
						byte al_406;
						fn0804804C(esi_324 + 1, out al_406, out esi_337);
						word16 ax_336 = <invalid>;
						bool Z_340 = <invalid>;
						bool C_339 = <invalid>;
						ci8 al_343 = (byte) ax_336;
						if (!(Z_340 | C_339))
						{
							if (al_330 > al_343)
								goto l080482AB;
							g_t8048C2A.u1 = (word16) SEQ(al_343, al_330);
							edx = SEQ(edx_16_16_385, al_343, al_330);
							if (*esi_337 == 0x00)
								continue;
						}
					}
				}
			}
			else if (esi_12->b0002 == 0x00)
			{
				++g_b8048C2D;
				continue;
			}
l0804829B:
			esp_10->dwFFFFFFFC = 0x28;
			Eq_71 edx_362 = esp_10->dwFFFFFFFC;
			esp_10->dwFFFFFFFC = 0x02;
			uint32 ebx_367 = esp_10->dwFFFFFFFC;
			esp_10->dwFFFFFFFC = 0x04;
			sys_write(ebx_367, &g_b80482C5, edx_362);
			goto l080482AB;
		}
		if (al_300 != 0x2F)
			goto l0804829B;
		ebp_21 = esi_12;
	}
	esp_10->dwFFFFFFFC = 0x05;
	Eq_42 eax_31 = sys_open(ebp_21, 0x0800, edx);
	if (eax_31 >= 0x00)
	{
		do
		{
			esp_10->dwFFFFFFFC = 0x36;
			int32 eax_49 = sys_ioctl(eax_31, 21286, edx);
			if (eax_49 == 0x01)
				break;
			if (eax_49 != 0x02)
			{
				if (eax_49 == 0x03)
					break;
				esp_10->dwFFFFFFFC = 0x00;
				esp_10->dwFFFFFFF8 = 0x36;
				esp_10 -= 4;
				if (sys_ioctl(eax_31, 0x5305, esp_10 - 4) < 0x00)
					break;
				word32 eax_84 = esp_10->dwFFFFFFFC;
				Eq_155 al_88 = (byte) eax_84;
				Eq_155 ah_92 = SLICE(eax_84, byte, 8);
				if (g_b8048C2C != 0x00)
				{
					if (g_t8048C2A.u0 < al_88)
						break;
					if (g_t8048C2B.u0 <= ah_92)
						goto l08048174;
				}
				else
					g_t8048C2A.u0 = (ci8) al_88;
				g_t8048C2B.u0 = (ci8) ah_92;
l08048174:
				g_t8048C29.u0 = (ci8) ah_92;
				if (g_b8048C2D == 0x00)
				{
l08048194:
					word32 * esp_127 = esp_10 - 4;
					*esp_127 = 0x05;
					esp_10 = (struct Eq_33 *) (esp_127 + 1);
					Eq_201 eax_131 = sys_open(&g_b80482ED, 577, 0x01A4);
					if (eax_131 < 0x00)
						break;
					do
					{
						Eq_155 al_147 = g_t8048C2A.u0;
						struct Eq_230 * esp_149 = esp_10 - 4;
						esp_149->dw0000 = 0x00;
						esp_149->dwFFFFFFFC = 0x00;
						esp_149->dwFFFFFFF8 = SEQ(0x0200, al_147);
						esp_149->dwFFFFFFF4 = 0x36;
						esp_10 = esp_149 - 8;
						if (sys_ioctl(eax_31, 0x5306, esp_149 - 8) < 0x00)
							goto l080482AB;
						word32 eax_171 = esp_149->dwFFFFFFF8;
						esp_149->dwFFFFFFF8 = eax_171;
						if ((SLICE(eax_171, byte, 8) & 0x40) == 0x00)
						{
							Eq_155 al_181 = g_t8048C2A.u0;
							uip32 eax_192 = SEQ(0x0200, (byte) al_181.u0 + 1);
							if (g_t8048C29.u0 < (byte) al_181.u0 + 1)
								eax_192 = 0x000200AA;
							esp_149->dwFFFFFFF4 = 0x00;
							esp_149->dwFFFFFFF0 = 0x00;
							esp_149->dwFFFFFFEC = eax_192;
							esp_149->dwFFFFFFE8 = 0x36;
							esp_10 = esp_149 - 20;
							if (sys_ioctl(eax_31, 0x5306, esp_149 - 20) < 0x00)
								goto l080482AB;
							do
							{
								struct Eq_299 * esp_211 = esp_10 - 24;
								esp_211->ptrFFFFFFFC = &g_b80482F9;
								esp_211->dwFFFFFFF8 = 0x01;
								esp_211->dwFFFFFFF4 = 0x02;
								esp_211->dwFFFFFFF0 = esp_211->dw0010;
								esp_211->dwFFFFFFEC = 0x36;
								esp_10 = esp_211 - 16;
								if (sys_ioctl(eax_31, 21262, esp_211 - 16) < 0x00)
									goto l080482AB;
								char * ecx_236 = esp_211->ptrFFFFFFFC;
								esp_211->dwFFFFFFEC = 0x04;
								esp_10 = esp_211 - 16;
								if (sys_write(eax_131, ecx_236, 0x0930) < 0x00)
									goto l080482AB;
								uint32 eax_252 = __bswap<word32>(esp_211->dwFFFFFFF0);
								ci8 al_254 = (byte) (eax_252 >> 0x08);
								ci8 ah_259 = SLICE(eax_252 >> 0x08, byte, 8);
								word16 eax_16_16_264 = SLICE(eax_252 >> 0x08, word16, 16);
								ui32 eax_266 = SEQ(SLICE(eax_252 >> 0x08, word24, 8), al_254 + 0x01);
								if (al_254 >= 0x4A)
								{
									eax_266 = SEQ(eax_16_16_264, ah_259 + 0x01, 0x00);
									if (ah_259 >= 0x3B)
										eax_266 = SEQ(eax_16_16_264, 0x00, 0x00) + 0x00010000;
								}
								uint32 eax_273 = __bswap<word32>(eax_266 << 0x08);
								esp_211->dw0010 = eax_273;
							} while (esp_211->dw0004 != eax_273);
						}
						Eq_155 al_284 = g_t8048C2B.u0;
						g_t8048C2A.u0 = (ci8) (g_t8048C2A.u0 + 0x01);
						struct Eq_251 * esp_280 = esp_10 - 0x0C;
						esp_10 = (struct Eq_33 *) (&esp_280->dw0008 + 1);
						if (al_284 < g_t8048C2A.u0)
						{
							esp_280->dw0008 = 0x01;
							sys_exit(0x00);
						}
					} while (g_b8048C2D == 0x00);
				}
				word16 ax_108 = __aam(g_t8048C2A.u0);
				g_w80482F2 = SEQ((byte) ax_108 + 0x30, SLICE(ax_108 + 0x3030, byte, 8));
				goto l08048194;
			}
			esp_10->dwFFFFFFFC = 0x36;
		} while (sys_ioctl(eax_31, 21273, edx) >= 0x00);
	}
l080482AB:
	int32 * esp_375 = esp_10 - 4;
	*esp_375 = 0x01;
	int32 ebx_377 = *esp_375;
	*esp_375 = 0x01;
	sys_exit(ebx_377);
}

Eq_36 g_t80482BA = // 080482BA
	{
		'/',
		100,
		101,
	};
char g_b80482C5 = '$'; // 080482C5
char g_b80482ED = 't'; // 080482ED
word16 g_w80482F2 = 0x3030; // 080482F2
char g_b80482F9 = '\0'; // 080482F9
Eq_155 g_t8048C29 = // 08048C29
	{
		0x00
	};
Eq_155 g_t8048C2A = // 08048C2A
	{
		0x00
	};
Eq_155 g_t8048C2B = // 08048C2B
	{
		0x00
	};
byte g_b8048C2C = 0x00; // 08048C2C
byte g_b8048C2D = 0x00; // 08048C2D
