/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall sub_400450(); // weak
__int64 f(void); // idb
__int64 __fastcall g(unsigned int);
int __cdecl main(int argc, const char **argv, const char **envp);

//-------------------------------------------------------------------------
// Data declarations

__int64 (*qword_6009E0)(void) = NULL; // weak


//----- (0000000000400450) ----------------------------------------------------
__int64 sub_400450()
{
  return qword_6009E0();
}
// 400450: using guessed type __int64 __fastcall sub_400450();
// 6009E0: using guessed type __int64 (*qword_6009E0)(void);

//----- (000000000040056D) ----------------------------------------------------
__int64 f(void)
{
  return 10LL;
}

//----- (0000000000400578) ----------------------------------------------------
__int64 __fastcall g(unsigned int a1)
{
  return a1;
}

//----- (0000000000400583) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  int v3; // eax

  v3 = f();
  g(v3 != 0);
  return 0;
}

// nfuncs=17 queued=4 decompiled=4 lumina nreq=0 worse=0 better=0
// ALL OK, 4 function(s) have been successfully decompiled
