// subject.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 00008258: void _init()
void _init()
{
}

// 0000829C: void _start()
void _start()
{
}

// 000082D8: void call_weak_fn()
void call_weak_fn()
{
}

// 000082FC: void deregister_tm_clones()
void deregister_tm_clones()
{
}

// 0000832C: void register_tm_clones()
void register_tm_clones()
{
}

// 00008364: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
}

// 0000838C: void frame_dummy()
void frame_dummy()
{
}

// 000083C4: void f()
void f()
{
}

// 000083FC: void main()
void main()
{
}

// 00008454: void __libc_csu_init()
void __libc_csu_init()
{
}

// 000084B4: void __libc_csu_fini()
void __libc_csu_fini()
{
}

// 000084B8: void _fini()
void _fini()
{
}

