//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>

// ------------------- Function Prototypes --------------------

int32_t function_8048396(void);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // ebx

// ------------------------ Functions -------------------------

// Address range: 0x804837c - 0x8048395
int main(int argc, char ** argv) {
    // 0x804837c
    g1 = argc;
    printf("Result is %d\n", function_8048396());
    return 0;
}

// Address range: 0x8048396 - 0x80483a3
int32_t function_8048396(void) {
    // 0x8048396
    return 2 * g1;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (i686-redhat-linux-gcc) (4.6.3)
// Detected functions: 2
// Decompiler release: VERSION
// Decompilation date: DATE
