// subject.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 00000000000006A0: Register ptr64 _init(Stack word64 qwArg00)
ptr64 _init(word64 qwArg00)
{
	call_weak_fn();
	return fp + 0x08;
}

// 00000000000006E0: void fn00000000000006E0()
void fn00000000000006E0()
{
	<anonymous> * x17_4 = globals->ptr11000;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 00000000000006F0: void fn00000000000006F0()
void fn00000000000006F0()
{
	<anonymous> * x17_4 = globals->ptr11008;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000000710: void fn0000000000000710()
void fn0000000000000710()
{
	<anonymous> * x17_4 = globals->ptr11018;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000000720: void fn0000000000000720()
void fn0000000000000720()
{
	<anonymous> * x17_4 = globals->ptr11020;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000000730: void fn0000000000000730()
void fn0000000000000730()
{
	<anonymous> * x17_4 = globals->ptr11028;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000000740: void main(Stack int32 dwArg04)
void main(int32 dwArg04)
{
	fn0000000000000730();
	fn0000000000000720();
	int32 w3_20 = dwArg04;
	if (dwArg04 > 0x01)
	{
		do
		{
			word32 w20_47;
			word32 w21_48;
			word64 sp_49;
			fib(w3_20 - 0x01, out w20_47, out w21_48, out sp_49);
			w3_20 = w3_20 - 0x02;
		} while (w3_20 > 0x01);
	}
	fn0000000000000730();
}

// 00000000000007B0: void _start(Stack word64 qwArg00)
void _start(word64 qwArg00)
{
	fn00000000000006F0();
	fn0000000000000710();
	call_weak_fn();
}

// 00000000000007E8: void call_weak_fn()
void call_weak_fn()
{
	word64 x0_4 = globals->qw10FC0;
	if (x0_4 == 0x00)
		return;
	<anonymous> * x17_10 = globals->ptr11010;
	word64 sp_12;
	word64 x0_13;
	word64 x16_14;
	word64 x17_15;
	x17_10();
}

// 0000000000000800: void deregister_tm_clones()
void deregister_tm_clones()
{
	if (0x00011047 - 69696 <= 0x0E)
		return;
	<anonymous> * x1_18 = globals->ptr10FB0;
	if (x1_18 == null)
		return;
	word64 sp_19;
	word64 x1_20;
	word64 x0_21;
	byte NZCV_22;
	byte ZC_23;
	x1_18();
}

// 0000000000000838: void register_tm_clones()
void register_tm_clones()
{
	int64 x1_6 = 69696 - 69696;
	if ((x1_6 >> 0x03) + ((x1_6 >> 0x03) >>u 0x003F) >> 0x01 == 0x00)
		return;
	<anonymous> * x2_18 = globals->ptr10FE0;
	if (x2_18 == null)
		return;
	word64 sp_19;
	word64 x1_20;
	word64 x0_21;
	word64 x2_22;
	x2_18();
}

// 0000000000000878: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	if ((word32) globals->b11040 == 0x00)
	{
		if (globals->qw10FB8 != 0x00)
			fn00000000000006E0();
		deregister_tm_clones();
		globals->b11040 = 0x01;
	}
}

// 00000000000008C0: void frame_dummy(Stack word64 qwArg00)
void frame_dummy(word64 qwArg00)
{
	if (globals->qw10DB8 != 0x00)
	{
		<anonymous> * x1_21 = globals->ptr10FD8;
		if (x1_21 != null)
		{
			word64 sp_27;
			word64 x0_28;
			word64 x1_29;
			word64 x29_30;
			word64 x30_31;
			word64 x2_32;
			x1_21();
			register_tm_clones();
			return;
		}
	}
	register_tm_clones();
}

// 00000000000008F8: Register word32 fib(Register int32 w0, Register out Eq_68 w20Out, Register out Eq_69 w21Out, Register out ptr64 spOut)
word32 fib(int32 w0, Eq_68 & w20Out, Eq_69 & w21Out, ptr64 & spOut)
{
	struct Eq_198 * sp_26 = fp + -0x0028;
	if (w0 > 0x01)
	{
		int32 w19_45 = w0;
		do
		{
			word32 w20_53;
			word32 w21_54;
			w19_45 = fib(w19_45 - 0x01, out w20_53, out w21_54, out sp_26);
		} while (w19_45 > 0x01);
	}
	struct Eq_216 * v16_31 = (char *) sp_26 + 0x0010;
	word32 w21_30;
	*w21Out = (word32) sp_26->qw0020;
	word32 w20_36;
	*w20Out = (word32) v16_31->qw0008;
	word64 sp_41;
	*spOut = &sp_26->qw0020 + 0x02;
	return (word32) v16_31->qw0000;
}

// 0000000000000958: void __libc_csu_init(Register word64 x30, Stack word64 qwArg00)
void __libc_csu_init(word64 x30, word64 qwArg00)
{
	<anonymous> * x21_23[] = globals->a10DA8;
	word64 sp_38 = _init(x30);
	if (0x00010DB0 - 0x00010DA8 >> 0x03 != 0x00)
	{
		ui64 x19_71 = 0x00;
		do
		{
			<anonymous> * x3_77 = x21_23[x19_71];
			word64 sp_82;
			word64 x29_83;
			word64 x30_84;
			word64 x22_86;
			word64 x20_88;
			word64 x23_89;
			word64 x24_90;
			word64 x2_91;
			word32 w0_92;
			word32 w24_93;
			word64 x1_94;
			word64 x3_95;
			word64 x31_96;
			byte NZCV_97;
			bool Z_98;
			x3_77();
		} while (x20_88 - x19_71 != 0x00);
	}
}

// 00000000000009D0: void __libc_csu_fini()
void __libc_csu_fini()
{
}

// 00000000000009D4: void _fini(Stack word64 qwArg00)
void _fini(word64 qwArg00)
{
}

