//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);

// ------------------------ Functions -------------------------

// Address range: 0x4000d4 - 0x4000e0
int64_t entry_point(void) {
    // 0x4000d4
    int64_t v1; // 0x4000d4
    int64_t result = (uint64_t)v1 % 256 | v1 & -0x10000 | 512; // 0x4000d6
    *(int64_t *)100 = result;
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (3.4.3)
// Detected functions: 1

