// subject.globals.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

Eq_2 g_t10764 = Unexpected function type (fn void ())
;
char g_str10780[] = "test/source/stattest.c";
char g_str10798[] = "Stat returns %d; size of file is %d\n";
ptr32 g_ptr20978 = 0x00;

