typedef unsigned char   undefined;

typedef unsigned char    byte;
typedef unsigned int    dword;
typedef unsigned int    undefined4;
typedef unsigned short    word;
typedef struct Elf32_Ehdr Elf32_Ehdr, *PElf32_Ehdr;

struct Elf32_Ehdr {
    byte e_ident_magic_num;
    char e_ident_magic_str[3];
    byte e_ident_class;
    byte e_ident_data;
    byte e_ident_version;
    byte e_ident_osabi;
    byte e_ident_abiversion;
    byte e_ident_pad[7];
    word e_type;
    word e_machine;
    dword e_version;
    dword e_entry;
    dword e_phoff;
    dword e_shoff;
    dword e_flags;
    word e_ehsize;
    word e_phentsize;
    word e_phnum;
    word e_shentsize;
    word e_shnum;
    word e_shstrndx;
};




// WARNING: Control flow encountered bad instruction data
// WARNING: Instruction at (ram,0x0804814f) overlaps instruction at (ram,0x0804814e)
// 

void entry(void)

{
  undefined4 uVar1;
  bool bVar2;
  code *pcVar3;
  byte bVar4;
  char cVar5;
  int iVar6;
  byte extraout_CL;
  undefined2 uVar8;
  byte *pbVar9;
  int *piVar10;
  undefined *unaff_ESI;
  undefined4 *unaff_EDI;
  byte bVar11;
  byte in_AF;
  bool bVar12;
  undefined8 uVar13;
  char unaff_retaddr;
  char *pcVar7;
  
  piVar10 = (int *)&stack0x00000004;
  if (unaff_retaddr == '\x02') {
    piVar10 = (int *)&stack0x0000000c;
  }
  piVar10[-1] = 5;
  pcVar3 = (code *)swi(0x80);
  iVar6 = (*pcVar3)();
  *piVar10 = iVar6;
  if (iVar6 != -2) {
    while( true ) {
      piVar10[-1] = 3;
      pcVar3 = (code *)swi(0x80);
      iVar6 = (*pcVar3)();
      if (iVar6 == 0) break;
                    // WARNING: Read-only address (ram,0x080480e0) is written
      uRam080480e0 = 7;
      *piVar10 = 0x20;
      *piVar10 = 1;
      *piVar10 = 4;
      pcVar3 = (code *)swi(0x80);
      (*pcVar3)();
      piVar10[1] = 1;
      piVar10[1] = 1;
      piVar10[1] = 4;
      pcVar3 = (code *)swi(0x80);
      (*pcVar3)();
      piVar10 = piVar10 + 3;
    }
    *piVar10 = 1;
    *piVar10 = 1;
    *piVar10 = 4;
    pcVar3 = (code *)swi(0x80);
    (*pcVar3)();
    piVar10 = piVar10 + 2;
  }
  piVar10[-1] = 6;
  pcVar3 = (code *)swi(0x80);
  (*pcVar3)();
  bVar11 = 0;
  bVar12 = true;
  *piVar10 = 1;
  pcVar3 = (code *)swi(0x80);
  uVar13 = (*pcVar3)();
  pbVar9 = (byte *)((ulonglong)uVar13 >> 0x20);
  in_AF = 9 < ((byte)uVar13 & 0xf) | in_AF;
  bVar4 = (byte)uVar13 + in_AF * -6;
  bVar2 = (bool)(0x9f < bVar4 | bVar11 | in_AF * (bVar4 < 6));
  bVar4 = bVar4 + bVar2 * -0x60;
  pcVar7 = (char *)((uint)uVar13 & 0xffffff00 | (uint)bVar4);
  if (!bVar2 && !bVar12) {
    if (!bVar2) {
      if (bVar2) goto LAB_0804814c;
      uVar8 = (undefined2)((ulonglong)uVar13 >> 0x20);
      out(*unaff_ESI,uVar8);
      in_AF = 9 < (bVar4 & 0xf) | in_AF;
      bVar4 = bVar4 + in_AF * -6;
      bVar4 = bVar4 + (0x9f < bVar4 | bVar2 | in_AF * (bVar4 < 6)) * -0x60;
      pcVar7 = (char *)((uint)uVar13 & 0xffffff00 | (uint)bVar4);
      if (!bVar12) {
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
        *pcVar7 = *pcVar7 + bVar4;
                    // WARNING: Bad instruction - Truncating control flow here
        halt_baddata();
      }
      uVar1 = in(uVar8);
      *unaff_EDI = uVar1;
      *pbVar9 = *pbVar9 & extraout_CL;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
      *pcVar7 = *pcVar7 + bVar4;
    }
    cVar5 = (char)pcVar7;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
    *pcVar7 = *pcVar7 + cVar5;
  }
  cVar5 = (char)pcVar7;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
LAB_0804814c:
  cVar5 = (char)pcVar7;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
  *pcVar7 = *pcVar7 + cVar5;
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}


