// subject_data.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

ui32 g_dw405058 = 0xBB40E64E; // 00405058
ui32 g_dw40505C = 1153374641; // 0040505C
word32 g_dw405170 = 0x00; // 00405170
int32 g_dw405174 = 0; // 00405174
word32 g_dw405178 = 0x00; // 00405178
word32 g_dw40517C = 0x00; // 0040517C
int32 g_dw405188 = 0; // 00405188
word32 g_dw40518C = 0x00; // 0040518C
word32 g_dw4054C4 = 0x00; // 004054C4
Eq_871 g_t4054D4 = 0; // 004054D4
word32 g_dw4054EC = 0x00; // 004054EC
<anonymous> * g_ptr4054F0 = null; // 004054F0
// subject_idata.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

word32 g_dw40603C = 0x656A; // 0040603C
word32 g_dw406040 = 0x6556; // 00406040
word32 g_dw406044 = 25922; // 00406044
word32 g_dw406048 = 0x6528; // 00406048
word32 g_dw40604C = 0x6512; // 0040604C
word32 g_dw406050 = 25852; // 00406050
word32 g_dw406054 = 0x64EC; // 00406054
word32 g_dw406058 = 0x64D2; // 00406058
word32 g_dw40605C = 0x64C2; // 0040605C
word32 g_dw406060 = 0x64A4; // 00406060
word32 g_dw406064 = 0x6494; // 00406064
word32 g_dw406068 = 25726; // 00406068
word32 g_dw40606C = 0x6460; // 0040606C
word32 g_dw406070 = 25688; // 00406070
word32 g_dw406074 = 25666; // 00406074
word32 g_dw406078 = 0x6586; // 00406078
word32 g_dw4060B4 = 0x637C; // 004060B4
word32 g_dw4060B8 = 0x6390; // 004060B8
word32 g_dw4060BC = 25542; // 004060BC
word32 g_dw4060C0 = 25552; // 004060C0
word32 g_dw4060C4 = 0x636A; // 004060C4
word32 g_dw4060C8 = 0x63E6; // 004060C8
word32 g_dw4060CC = 0x63F0; // 004060CC
word32 g_dw4060D0 = 0x640A; // 004060D0
word32 g_dw4060D4 = 25628; // 004060D4
word32 g_dw4060D8 = 25644; // 004060D8
word32 g_dw4060DC = 0x6360; // 004060DC
word32 g_dw4060E0 = 25428; // 004060E0
word32 g_dw4060E4 = 0x6340; // 004060E4
word32 g_dw4060E8 = 0x632A; // 004060E8
word32 g_dw4060EC = 25372; // 004060EC
word32 g_dw4060F0 = 0x6310; // 004060F0
word32 g_dw4060F4 = 0x6304; // 004060F4
word32 g_dw4060F8 = 0x62FC; // 004060F8
word32 g_dw4060FC = 0x62EE; // 004060FC
word32 g_dw406100 = 0x62E6; // 00406100
word32 g_dw406104 = 0x62DC; // 00406104
word32 g_dw406108 = 25292; // 00406108
word32 g_dw40610C = 25278; // 0040610C
word32 g_dw406110 = 0x62A0; // 00406110
word32 g_dw406114 = 25232; // 00406114
word32 g_dw406118 = 25566; // 00406118
word32 g_dw40611C = 25220; // 0040611C
<anonymous> * __imp__UnhandledExceptionFilter = &g_t656A; // 00406160
<anonymous> * __imp__GetCurrentProcess = &g_t6556; // 00406164
<anonymous> * __imp__TerminateProcess = &g_t6542; // 00406168
<anonymous> * __imp__GetSystemTimeAsFileTime = &g_t6528; // 0040616C
<anonymous> * __imp__GetCurrentProcessId = &g_t6512; // 00406170
<anonymous> * __imp__GetCurrentThreadId = &g_t64FC; // 00406174
<anonymous> * __imp__GetTickCount = &g_t64EC; // 00406178
<anonymous> * __imp__QueryPerformanceCounter = &g_t64D2; // 0040617C
<anonymous> * __imp__DecodePointer = &g_t64C2; // 00406180
<anonymous> * __imp__SetUnhandledExceptionFilter = &g_t64A4; // 00406184
<anonymous> * __imp__EncodePointer = &g_t6494; // 00406188
<anonymous> * __imp__HeapSetInformation = &g_t647E; // 0040618C
<anonymous> * __imp__InterlockedCompareExchange = &g_t6460; // 00406190
<anonymous> * __imp__Sleep = &g_t6458; // 00406194
<anonymous> * __imp__InterlockedExchange = &g_t6442; // 00406198
<anonymous> * __imp__IsDebuggerPresent = &g_t6586; // 0040619C
<anonymous> * __imp__?terminate@@YAXXZ = &g_t637C; // 004061D8
<anonymous> * __imp__?_type_info_dtor_internal_method@type_info@@QAEXXZ = &g_t6390; // 004061DC
<anonymous> * __imp___unlock = &g_t63C6; // 004061E0
<anonymous> * __imp____dllonexit = &g_t63D0; // 004061E4
<anonymous> * __imp____set_app_type = &g_t636A; // 004061E8
<anonymous> * __imp___onexit = &g_t63E6; // 004061EC
<anonymous> * __imp___except_handler4_common = &g_t63F0; // 004061F0
<anonymous> * __imp___invoke_watson = &g_t640A; // 004061F4
<anonymous> * __imp___controlfp_s = &g_t641C; // 004061F8
<anonymous> * __imp___crt_debugger_hook = &g_t642C; // 004061FC
<anonymous> * __imp___fmode = &g_t6360; // 00406200
<anonymous> * __imp___commode = &g_t6354; // 00406204
<anonymous> * __imp____setusermatherr = &g_t6340; // 00406208
<anonymous> * __imp___configthreadlocale = &g_t632A; // 0040620C
<anonymous> * __imp___initterm_e = &g_t631C; // 00406210
<anonymous> * __imp___initterm = &g_t6310; // 00406214
<anonymous> * __imp____initenv = &g_t6304; // 00406218
<anonymous> * __imp__exit = &g_t62FC; // 0040621C
<anonymous> * __imp___XcptFilter = &g_t62EE; // 00406220
<anonymous> * __imp___exit = &g_t62E6; // 00406224
<anonymous> * __imp___cexit = &g_t62DC; // 00406228
<anonymous> * __imp____getmainargs = &g_t62CC; // 0040622C
<anonymous> * __imp___amsg_exit = &g_t62BE; // 00406230
<anonymous> * __imp__??3@YAXPAX@Z = &g_t62A0; // 00406234
<anonymous> * __imp__??2@YAPAXI@Z = &g_t6290; // 00406238
<anonymous> * __imp___lock = &g_t63DE; // 0040623C
<anonymous> * __imp___purecall = &g_t6284; // 00406240
// subject_rdata.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

Eq_1032 g_t403000 = null; // 00403000
Eq_1025 g_t403208 = null; // 00403208
<anonymous> * g_ptr40374C = &g_t401005; // 0040374C
// subject_text.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

<anonymous> g_t401005 = <code>; // 00401005
// 0040100A: define fn0040100A
// Called from:
//      Win32CrtStartup
define fn0040100A
{
	eax_6 = operator new(0x04);
	if (eax_6 != null)
		*eax_6 = (<anonymous> ***) &g_ptr40374C;
	else
		eax_11 = null;
	Mem16 = ϕ(Mem14, Mem5);
	eax_15 = ϕ(eax_6, eax_11);
	edx_17 = (<anonymous> **) *eax_15;
	eax_19 = (<anonymous> *) *edx_17;
	eax_19();
	C_29 = SLICE(SCZO_27, bool, 1);
	O_30 = SLICE(SCZO_27, bool, 4);
	S_31 = (bool) SCZO_27;
	Z_32 = SLICE(SCZO_27, bool, 2);
	Top_26 = 0;
}

// 004013CC: Register Eq_44 Win32CrtStartup()
Eq_44 Win32CrtStartup()
{
}

// 00401630: define fn00401630
// Called from:
//      fn004016C0
define fn00401630
{
	word32 dwArg04;
	word32 edx;
	Top_3 = 0;
	ecx_10 = dwArg04;
	if (dwArg04->w0000 == 23117)
	{
		eax_15 = dwArg04->dw003C;
		eax_16 = (struct Eq_1286 *) (dwArg04 + eax_15 / 64);
		if (eax_16->dw0000 == 0x4550)
		{
			ecx_20 = (struct Eq_1264 *) 0x010B;
			SCZO_22 = cond(eax_16->w0018 - 0x010B);
			Z_23 = SLICE(SCZO_22, bool, 2);
			C_41 = SLICE(SCZO_22, bool, 1);
			O_54 = SLICE(SCZO_22, bool, 4);
			S_57 = (bool) SCZO_22;
			dl_24 = (int8) (eax_16->w0018 == 0x010B);
			edx_26 = (uint32) dl_24;
			eax_27 = edx_26;
			return;
		}
	}
	eax_30 = 0x00;
	SZO_31 = cond(0x00);
	O_53 = SLICE(SZO_31, bool, 4);
	S_56 = (bool) SZO_31;
	Z_61 = SLICE(SZO_31, bool, 2);
	C_32 = false;
}

// 00401670: define fn00401670
// Called from:
//      fn004016C0
define fn00401670
{
	word32 dwArg04;
	word32 dwArg08;
	Top_3 = 0;
	ecx_11 = dwArg04->dw003C;
	ecx_12 = (struct Eq_1323 *) (dwArg04 + ecx_11 / 64);
	eax_13 = (word32) ecx_12->w0014;
	esi_20 = (word32) ecx_12->w0006;
	edx_21 = 0x00;
	eax_24 = (struct Eq_1322 *) (ecx_12 + (eax_13 + 0x18) / 22);
	if (esi_20 != 0x00)
	{
		do
		{
			edx_40 = ϕ(edx_21, edx_41);
			eax_29 = ϕ(eax_24, eax_43);
			ecx_31 = eax_29->ptr000C;
			if (dwArg08 >= ecx_31)
			{
				ebx_35 = eax_29->dw0008;
				ebx_36 = ecx_31 + ebx_35 / 22;
				SCZO_37 = cond(dwArg08 - ebx_36);
				C_38 = SLICE(SCZO_37, bool, 1);
				O_97 = SLICE(SCZO_37, bool, 4);
				S_100 = (bool) SCZO_37;
				Z_107 = SLICE(SCZO_37, bool, 2);
				if (dwArg08 < ebx_36)
					goto l004016AF;
			}
			edx_41 = edx_40 + 0x01;
			eax_43 = (struct Eq_1322 *) ((char *) &eax_29->ptr000C + 28);
		} while (edx_41 < esi_20);
	}
	edx_95 = ϕ(edx_21, edx_41);
	ecx_92 = ϕ(ecx_12, ecx_31);
	eax_48 = null;
	SZO_49 = cond(0x00);
	O_98 = SLICE(SZO_49, bool, 4);
	S_101 = (bool) SZO_49;
	Z_108 = SLICE(SZO_49, bool, 2);
	C_50 = false;
l004016AF:
	Z_106 = ϕ(Z_107, Z_108);
	S_99 = ϕ(S_100, S_101);
	O_96 = ϕ(O_97, O_98);
	edx_94 = ϕ(edx_40, edx_95);
	ecx_91 = ϕ(ecx_31, ecx_92);
	eax_90 = ϕ(eax_29, eax_48);
	C_89 = ϕ(C_38, C_50);
}

// 004016C0: define fn004016C0
// Called from:
//      Win32CrtStartup
define fn004016C0
{
	ptr32 fp;
	selector fs;
	word32 dwArg04;
	Top_3 = 0;
	eax_17 = fs->ptr0000;
	eax_29 = g_dw405058;
	eax_33 = eax_29 ^ fp - 4;
	fs->ptr0000 = fp - 0x14;
	fn00401630();
	if (eax_44 != 0x00)
	{
		fn00401670();
		if (eax_62 != null)
		{
			eax_92 = eax_62->dw0024;
			eax_94 = ~(eax_92 >> 0x1F);
			eax_95 = eax_94 & 0x01;
			SZO_96 = cond(eax_94 & 0x01);
			O_146 = SLICE(SZO_96, bool, 4);
			S_149 = (bool) SZO_96;
			Z_154 = SLICE(SZO_96, bool, 2);
			fs->ptr0000 = eax_17;
			return;
		}
	}
	edx_142 = ϕ(edx_46, edx_64);
	eax_75 = 0x00;
	SZO_76 = cond(0x00);
	O_147 = SLICE(SZO_76, bool, 4);
	S_150 = (bool) SZO_76;
	Z_155 = SLICE(SZO_76, bool, 2);
	fs->ptr0000 = eax_17;
}

// 00401790: define fn00401790
// Called from:
//      Win32CrtStartup
define fn00401790
{
	ptr32 fp;
	selector fs;
	word32 ebx;
	word32 esi;
	word32 edi;
	word32 dwArg08;
	word32 dwArg00;
	Top_3 = 0;
	ebp_13 = fp + 0x08;
	esp_14 = fp - 8 - dwArg08;
	esp_14->dwFFFFFFFC = ebx;
	esp_14->dwFFFFFFF8 = esi;
	esp_14->dwFFFFFFF4 = edi;
	eax_24 = g_dw405058;
	eax_28 = eax_24 ^ fp + 0x08;
	SZO_29 = cond(eax_28);
	O_52 = SLICE(SZO_29, bool, 4);
	S_53 = (bool) SZO_29;
	Z_54 = SLICE(SZO_29, bool, 2);
	C_30 = false;
	esp_14->dwFFFFFFF0 = eax_28;
	esp_14->dwFFFFFFEC = dwArg00;
	eax_40 = fp - 0x08;
	fs->ptr0000 = fp - 0x08;
}

// 004017D5: define fn004017D5
// Called from:
//      Win32CrtStartup
define fn004017D5
{
	word32 ebp;
	<type-error> Mem0;
	selector fs;
	word32 dwArg00;
	word32 dwArg08;
	word32 dwArg0C;
	word32 dwArg10;
	Top_3 = 0;
	ecx_6 = ebp->dwFFFFFFF0;
	fs->dw0000 = ecx_6;
	ecx_9 = dwArg00;
	edi_13 = dwArg08;
	esi_15 = dwArg0C;
	ebx_17 = dwArg10;
	ebp_19 = ebp->dw0000;
	esp_21 = ebp;
	ebp->dw0000 = dwArg00;
}

// 00401870: define fn00401870
// Called from:
//      Win32CrtStartup
define fn00401870
{
	ptr32 fp;
	word32 dwLoc10;
	word32 dwLoc14;
	Top_3 = 0;
	eax_11 = g_dw405058;
	if (eax_11 != 0xBB40E64E)
	{
		SZO_27 = cond(eax_11 & 0xFFFF0000);
		Z_29 = SLICE(SZO_27, bool, 2);
		O_120 = SLICE(SZO_27, bool, 4);
		S_126 = (bool) SZO_27;
		C_28 = false;
		if ((eax_11 & 0xFFFF0000) != 0x00)
		{
			eax_77 = ~eax_11;
			g_dw40505C = eax_77;
			goto l00401907;
		}
	}
	GetSystemTimeAsFileTime(fp - 0x0C);
	eax_42 = GetCurrentProcessId();
	eax_44 = GetCurrentThreadId();
	esi_45 = eax_42 ^ eax_44;
	eax_46 = GetTickCount();
	esi_47 = esi_45 ^ eax_46;
	QueryPerformanceCounter(fp - 0x14);
	eax_54 = dwLoc10 ^ dwLoc14;
	esi_55 = esi_47 ^ eax_54;
	SCZO_57 = cond(esi_55 - 0xBB40E64E);
	Z_58 = SLICE(SCZO_57, bool, 2);
	C_115 = SLICE(SCZO_57, bool, 1);
	O_122 = SLICE(SCZO_57, bool, 4);
	S_128 = (bool) SCZO_57;
	if (esi_55 == 0xBB40E64E)
		esi_69 = ~0x44BF19B0;
	else
	{
		SZO_60 = cond(esi_55 & 0xFFFF0000);
		Z_62 = SLICE(SZO_60, bool, 2);
		O_123 = SLICE(SZO_60, bool, 4);
		S_129 = (bool) SZO_60;
		C_61 = false;
		if ((esi_55 & 0xFFFF0000) == 0x00)
		{
			eax_65 = (esi_55 | 0x4711) << 0x10;
			esi_66 = esi_55 | eax_65;
			SZO_67 = cond(esi_66);
			O_124 = SLICE(SZO_67, bool, 4);
			S_130 = (bool) SZO_67;
			Z_136 = SLICE(SZO_67, bool, 2);
			C_68 = false;
		}
	}
	Z_135 = ϕ(Z_58, Z_62, Z_136);
	S_127 = ϕ(S_128, S_129, S_130);
	O_121 = ϕ(O_122, O_123, O_124);
	eax_117 = ϕ(eax_54, eax_54, eax_65);
	C_114 = ϕ(C_115, C_61, C_68);
	esi_70 = ϕ(esi_69, esi_55, esi_66);
	g_dw405058 = esi_70;
	esi_72 = ~esi_70;
	g_dw40505C = esi_72;
l00401907:
	Z_134 = ϕ(Z_29, Z_135);
	S_125 = ϕ(S_126, S_127);
	O_119 = ϕ(O_120, O_121);
	eax_116 = ϕ(eax_77, eax_117);
	C_113 = ϕ(C_28, C_114);
}

