// subject_text.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 00000000004000D4: void fn00000000004000D4()
void fn00000000004000D4()
{
	*(uint64 *) 100 = 0x02;
}

