// subject.h
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals" (FFFFFFFF code tFFFFFFFF) (80482CA code t80482CA) (80482DA code t80482DA) (80482EA code t80482EA) (8049574 (ptr code) ptr8049574) (8049580 (ptr code) ptr8049580) (8049584 word32 dw8049584) (8049658 (ptr code) ptr8049658) (8049660 (ptr code) ptr8049660) (8049664 (ptr code) ptr8049664) (8049668 (ptr code) ptr8049668) (8049674 (ptr (ptr code)) ptr8049674) (8049678 byte b8049678))
	globals_t (in globals : (ptr (struct "Globals")))
Eq_3: (fn void ())
	T_3 (in call_gmon_start : ptr32)
	T_4 (in signature of call_gmon_start : void)
Eq_6: (fn void (word32))
	T_6 (in frame_dummy : ptr32)
	T_7 (in signature of frame_dummy : void)
Eq_10: (fn void ())
	T_10 (in __do_global_ctors_aux : ptr32)
	T_11 (in signature of __do_global_ctors_aux : void)
Eq_23: (fn void (ptr32))
	T_23 (in __align : ptr32)
Eq_28: (fn void ())
	T_28 (in fn080482D4 : ptr32)
	T_29 (in signature of fn080482D4 : void)
Eq_31: (fn void ())
	T_31 (in __hlt : ptr32)
Eq_100: (fn void (ptr32, word32))
	T_100 (in twofib : ptr32)
	T_101 (in signature of twofib : void)
	T_131 (in twofib : ptr32)
Eq_113: (struct "Eq_113" (0 word32 dw0000) (4 word32 dw0004))
	T_113 (in dwArg04 : word32)
Eq_120: (fn void (ptr32))
	T_120 (in __align : ptr32)
Eq_125: (fn void ())
	T_125 (in fn080482E4 : ptr32)
	T_126 (in signature of fn080482E4 : void)
	T_136 (in fn080482E4 : ptr32)
Eq_128: (fn void ())
	T_128 (in fn080482C4 : ptr32)
	T_129 (in signature of fn080482C4 : void)
Eq_139: (fn void (word32))
	T_139 (in _init : ptr32)
	T_140 (in signature of _init : void)
Eq_151: (union "Eq_151" (int32 u0) (ptr32 u1))
	T_151 (in edi_49 : Eq_151)
Eq_165: (union "Eq_165" (int32 u0) (uint32 u1))
	T_165 (in esi_50 + 0x00000001 : word32)
	T_169 (in 0x08049734 - edi_49 >> 0x00000002 : word32)
Eq_166: (union "Eq_166" (int32 u0) (ptr32 u1))
	T_166 (in 08049734 : ptr32)
Eq_167: (union "Eq_167" (int32 u0) (ptr32 u1))
	T_167 (in 0x08049734 - edi_49 : word32)
Eq_196: (fn void ())
	T_196 (in _fini : ptr32)
	T_197 (in signature of _fini : void)
Eq_214: (fn void ())
	T_214 (in __do_global_dtors_aux : ptr32)
	T_215 (in signature of __do_global_dtors_aux : void)
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct "Globals"))
T_2: (in esi : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_3: (in call_gmon_start : ptr32)
  Class: Eq_3
  DataType: (ptr Eq_3)
  OrigDataType: (ptr (fn T_5 ()))
T_4: (in signature of call_gmon_start : void)
  Class: Eq_3
  DataType: (ptr Eq_3)
  OrigDataType: 
T_5: (in call_gmon_start() : void)
  Class: Eq_5
  DataType: void
  OrigDataType: void
T_6: (in frame_dummy : ptr32)
  Class: Eq_6
  DataType: (ptr Eq_6)
  OrigDataType: (ptr (fn T_9 (T_2)))
T_7: (in signature of frame_dummy : void)
  Class: Eq_6
  DataType: (ptr Eq_6)
  OrigDataType: 
T_8: (in esi : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_9: (in frame_dummy(esi) : void)
  Class: Eq_9
  DataType: void
  OrigDataType: void
T_10: (in __do_global_ctors_aux : ptr32)
  Class: Eq_10
  DataType: (ptr Eq_10)
  OrigDataType: (ptr (fn T_12 ()))
T_11: (in signature of __do_global_ctors_aux : void)
  Class: Eq_10
  DataType: (ptr Eq_10)
  OrigDataType: 
T_12: (in __do_global_ctors_aux() : void)
  Class: Eq_12
  DataType: void
  OrigDataType: void
T_13: (in esp_3 : word32)
  Class: Eq_13
  DataType: word32
  OrigDataType: word32
T_14: (in 0x08049660 : ptr32)
  Class: Eq_14
  DataType: (ptr (ptr code))
  OrigDataType: (ptr (struct (0 T_15 t0000)))
T_15: (in Mem0[0x08049660:word32] : word32)
  Class: Eq_15
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_16: (in esp_3 : word32)
  Class: Eq_16
  DataType: word32
  OrigDataType: word32
T_17: (in 0x08049664 : ptr32)
  Class: Eq_17
  DataType: (ptr (ptr code))
  OrigDataType: (ptr (struct (0 T_18 t0000)))
T_18: (in Mem0[0x08049664:word32] : word32)
  Class: Eq_18
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_19: (in esp_3 : word32)
  Class: Eq_19
  DataType: word32
  OrigDataType: word32
T_20: (in 0x08049668 : ptr32)
  Class: Eq_20
  DataType: (ptr (ptr code))
  OrigDataType: (ptr (struct (0 T_21 t0000)))
T_21: (in Mem0[0x08049668:word32] : word32)
  Class: Eq_21
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_22: (in dwArg00 : word32)
  Class: Eq_22
  DataType: word32
  OrigDataType: word32
T_23: (in __align : ptr32)
  Class: Eq_23
  DataType: (ptr Eq_23)
  OrigDataType: (ptr (fn T_27 (T_26)))
T_24: (in fp : ptr32)
  Class: Eq_24
  DataType: ptr32
  OrigDataType: ptr32
T_25: (in 0x00000004 : word32)
  Class: Eq_25
  DataType: int32
  OrigDataType: int32
T_26: (in fp + 0x00000004 : word32)
  Class: Eq_26
  DataType: ptr32
  OrigDataType: ptr32
T_27: (in __align(fp + 0x00000004) : void)
  Class: Eq_27
  DataType: void
  OrigDataType: void
T_28: (in fn080482D4 : ptr32)
  Class: Eq_28
  DataType: (ptr Eq_28)
  OrigDataType: (ptr (fn T_30 ()))
T_29: (in signature of fn080482D4 : void)
  Class: Eq_28
  DataType: (ptr Eq_28)
  OrigDataType: 
T_30: (in fn080482D4() : void)
  Class: Eq_30
  DataType: void
  OrigDataType: void
T_31: (in __hlt : ptr32)
  Class: Eq_31
  DataType: (ptr Eq_31)
  OrigDataType: (ptr (fn T_32 ()))
T_32: (in __hlt() : void)
  Class: Eq_32
  DataType: void
  OrigDataType: void
T_33: (in eax_15 : (ptr code))
  Class: Eq_33
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_34: (in 08049658 : ptr32)
  Class: Eq_34
  DataType: (ptr (ptr code))
  OrigDataType: (ptr (struct (0 T_37 t0000)))
T_35: (in 0x00000000 : word32)
  Class: Eq_35
  DataType: word32
  OrigDataType: word32
T_36: (in 0x08049658 + 0x00000000 : word32)
  Class: Eq_36
  DataType: ptr32
  OrigDataType: ptr32
T_37: (in Mem0[0x08049658 + 0x00000000:word32] : word32)
  Class: Eq_33
  DataType: (ptr code)
  OrigDataType: word32
T_38: (in 0x00000000 : word32)
  Class: Eq_33
  DataType: (ptr code)
  OrigDataType: word32
T_39: (in eax_15 == null : bool)
  Class: Eq_39
  DataType: bool
  OrigDataType: bool
T_40: (in esp_31 : word32)
  Class: Eq_40
  DataType: word32
  OrigDataType: word32
T_41: (in ebp_32 : word32)
  Class: Eq_41
  DataType: word32
  OrigDataType: word32
T_42: (in ebx_33 : word32)
  Class: Eq_42
  DataType: word32
  OrigDataType: word32
T_43: (in SCZO_34 : byte)
  Class: Eq_43
  DataType: byte
  OrigDataType: byte
T_44: (in edx_35 : word32)
  Class: Eq_44
  DataType: word32
  OrigDataType: word32
T_45: (in eax_36 : word32)
  Class: Eq_45
  DataType: word32
  OrigDataType: word32
T_46: (in SZO_37 : byte)
  Class: Eq_46
  DataType: byte
  OrigDataType: byte
T_47: (in C_38 : byte)
  Class: Eq_47
  DataType: byte
  OrigDataType: byte
T_48: (in Z_39 : byte)
  Class: Eq_48
  DataType: byte
  OrigDataType: byte
T_49: (in 0x08049678 : ptr32)
  Class: Eq_49
  DataType: (ptr byte)
  OrigDataType: (ptr (struct (0 T_50 t0000)))
T_50: (in Mem0[0x08049678:byte] : byte)
  Class: Eq_50
  DataType: byte
  OrigDataType: byte
T_51: (in 0x00 : byte)
  Class: Eq_50
  DataType: byte
  OrigDataType: byte
T_52: (in globals->b8049678 == 0x00 : bool)
  Class: Eq_52
  DataType: bool
  OrigDataType: bool
T_53: (in eax_26 : (ptr (ptr code)))
  Class: Eq_53
  DataType: (ptr (ptr code))
  OrigDataType: (ptr (struct (0 T_59 t0000)))
T_54: (in 0x08049674 : word32)
  Class: Eq_54
  DataType: (ptr (ptr (ptr code)))
  OrigDataType: (ptr (struct (0 T_55 t0000)))
T_55: (in Mem0[0x08049674:word32] : word32)
  Class: Eq_53
  DataType: (ptr (ptr code))
  OrigDataType: word32
T_56: (in edx_27 : (ptr code))
  Class: Eq_56
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_57: (in 0x00000000 : word32)
  Class: Eq_57
  DataType: word32
  OrigDataType: word32
T_58: (in eax_26 + 0x00000000 : word32)
  Class: Eq_58
  DataType: word32
  OrigDataType: word32
T_59: (in Mem0[eax_26 + 0x00000000:word32] : word32)
  Class: Eq_56
  DataType: (ptr code)
  OrigDataType: word32
T_60: (in 0x00000000 : word32)
  Class: Eq_56
  DataType: (ptr code)
  OrigDataType: word32
T_61: (in edx_27 != null : bool)
  Class: Eq_61
  DataType: bool
  OrigDataType: bool
T_62: (in 0x00000004 : word32)
  Class: Eq_62
  DataType: int32
  OrigDataType: int32
T_63: (in eax_26 + 0x00000004 : word32)
  Class: Eq_53
  DataType: (ptr (ptr code))
  OrigDataType: ptr32
T_64: (in 0x08049674 : word32)
  Class: Eq_64
  DataType: (ptr (ptr (ptr code)))
  OrigDataType: (ptr (struct (0 T_65 t0000)))
T_65: (in Mem34[0x08049674:word32] : word32)
  Class: Eq_53
  DataType: (ptr (ptr code))
  OrigDataType: word32
T_66: (in esp_35 : word32)
  Class: Eq_66
  DataType: word32
  OrigDataType: word32
T_67: (in ebp_36 : word32)
  Class: Eq_67
  DataType: word32
  OrigDataType: word32
T_68: (in SCZO_37 : byte)
  Class: Eq_68
  DataType: byte
  OrigDataType: byte
T_69: (in Z_38 : byte)
  Class: Eq_69
  DataType: byte
  OrigDataType: byte
T_70: (in eax_39 : word32)
  Class: Eq_70
  DataType: word32
  OrigDataType: word32
T_71: (in edx_40 : word32)
  Class: Eq_71
  DataType: word32
  OrigDataType: word32
T_72: (in SZO_41 : byte)
  Class: Eq_72
  DataType: byte
  OrigDataType: byte
T_73: (in C_42 : byte)
  Class: Eq_73
  DataType: byte
  OrigDataType: byte
T_74: (in 0x01 : byte)
  Class: Eq_50
  DataType: byte
  OrigDataType: byte
T_75: (in 0x08049678 : ptr32)
  Class: Eq_75
  DataType: (ptr byte)
  OrigDataType: (ptr (struct (0 T_76 t0000)))
T_76: (in Mem31[0x08049678:byte] : byte)
  Class: Eq_50
  DataType: byte
  OrigDataType: byte
T_77: (in 0x08049584 : word32)
  Class: Eq_77
  DataType: (ptr word32)
  OrigDataType: (ptr (struct (0 T_78 t0000)))
T_78: (in Mem0[0x08049584:word32] : word32)
  Class: Eq_78
  DataType: word32
  OrigDataType: word32
T_79: (in 0x00000000 : word32)
  Class: Eq_78
  DataType: word32
  OrigDataType: word32
T_80: (in globals->dw8049584 == 0x00000000 : bool)
  Class: Eq_80
  DataType: bool
  OrigDataType: bool
T_81: (in 0x00000000 : word32)
  Class: Eq_81
  DataType: word32
  OrigDataType: word32
T_82: (in 0x00000000 : word32)
  Class: Eq_81
  DataType: word32
  OrigDataType: word32
T_83: (in 0x00000000 == 0x00000000 : bool)
  Class: Eq_83
  DataType: bool
  OrigDataType: bool
T_84: (in esp_33 : word32)
  Class: Eq_84
  DataType: word32
  OrigDataType: word32
T_85: (in ebp_34 : word32)
  Class: Eq_85
  DataType: word32
  OrigDataType: word32
T_86: (in SCZO_35 : byte)
  Class: Eq_86
  DataType: byte
  OrigDataType: byte
T_87: (in eax_36 : word32)
  Class: Eq_87
  DataType: word32
  OrigDataType: word32
T_88: (in SZO_37 : byte)
  Class: Eq_88
  DataType: byte
  OrigDataType: byte
T_89: (in C_38 : byte)
  Class: Eq_89
  DataType: byte
  OrigDataType: byte
T_90: (in Z_39 : byte)
  Class: Eq_90
  DataType: byte
  OrigDataType: byte
T_91: (in esi_40 : word32)
  Class: Eq_91
  DataType: word32
  OrigDataType: word32
T_92: (in 0x00000000 : word32)
  Class: Eq_92
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_93: (in dwArg04 : ptr32)
  Class: Eq_93
  DataType: ptr32
  OrigDataType: word32
T_94: (in dwArg08 : word32)
  Class: Eq_94
  DataType: word32
  OrigDataType: word32
T_95: (in dwLoc08_16 : word32)
  Class: Eq_95
  DataType: word32
  OrigDataType: word32
T_96: (in dwLoc0C_15 : word32)
  Class: Eq_96
  DataType: word32
  OrigDataType: word32
T_97: (in dwArg08 : word32)
  Class: Eq_97
  DataType: word32
  OrigDataType: word32
T_98: (in 0x00000000 : word32)
  Class: Eq_97
  DataType: word32
  OrigDataType: word32
T_99: (in dwArg08 != 0x00000000 : bool)
  Class: Eq_99
  DataType: bool
  OrigDataType: bool
T_100: (in twofib : ptr32)
  Class: Eq_100
  DataType: (ptr Eq_100)
  OrigDataType: (ptr (fn T_107 (T_104, T_106)))
T_101: (in signature of twofib : void)
  Class: Eq_100
  DataType: (ptr Eq_100)
  OrigDataType: 
T_102: (in fp : ptr32)
  Class: Eq_102
  DataType: ptr32
  OrigDataType: ptr32
T_103: (in 0x0000000C : word32)
  Class: Eq_103
  DataType: ui32
  OrigDataType: ui32
T_104: (in fp - 0x0000000C : word32)
  Class: Eq_93
  DataType: ptr32
  OrigDataType: ptr32
T_105: (in 0x00000001 : word32)
  Class: Eq_105
  DataType: word32
  OrigDataType: word32
T_106: (in dwArg08 - 0x00000001 : word32)
  Class: Eq_94
  DataType: word32
  OrigDataType: word32
T_107: (in twofib(fp - 0x0000000C, dwArg08 - 0x00000001) : void)
  Class: Eq_107
  DataType: void
  OrigDataType: void
T_108: (in dwLoc08 : word32)
  Class: Eq_96
  DataType: word32
  OrigDataType: word32
T_109: (in dwLoc0C : word32)
  Class: Eq_109
  DataType: word32
  OrigDataType: word32
T_110: (in dwLoc08 + dwLoc0C : word32)
  Class: Eq_95
  DataType: word32
  OrigDataType: word32
T_111: (in 0x00000000 : word32)
  Class: Eq_96
  DataType: word32
  OrigDataType: word32
T_112: (in 0x00000001 : word32)
  Class: Eq_95
  DataType: word32
  OrigDataType: word32
T_113: (in dwArg04 : word32)
  Class: Eq_113
  DataType: (ptr Eq_113)
  OrigDataType: (ptr (struct (0 T_116 t0000) (4 T_119 t0004)))
T_114: (in 0x00000000 : word32)
  Class: Eq_114
  DataType: word32
  OrigDataType: word32
T_115: (in dwArg04 + 0x00000000 : word32)
  Class: Eq_115
  DataType: word32
  OrigDataType: word32
T_116: (in Mem21[dwArg04 + 0x00000000:word32] : word32)
  Class: Eq_96
  DataType: word32
  OrigDataType: word32
T_117: (in 0x00000004 : word32)
  Class: Eq_117
  DataType: word32
  OrigDataType: word32
T_118: (in dwArg04 + 0x00000004 : word32)
  Class: Eq_118
  DataType: ptr32
  OrigDataType: ptr32
T_119: (in Mem22[dwArg04 + 0x00000004:word32] : word32)
  Class: Eq_95
  DataType: word32
  OrigDataType: word32
T_120: (in __align : ptr32)
  Class: Eq_120
  DataType: (ptr Eq_120)
  OrigDataType: (ptr (fn T_124 (T_123)))
T_121: (in fp : ptr32)
  Class: Eq_121
  DataType: ptr32
  OrigDataType: ptr32
T_122: (in 0x0000001C : word32)
  Class: Eq_122
  DataType: ui32
  OrigDataType: ui32
T_123: (in fp - 0x0000001C : word32)
  Class: Eq_123
  DataType: ptr32
  OrigDataType: ptr32
T_124: (in __align(fp - 0x0000001C) : void)
  Class: Eq_124
  DataType: void
  OrigDataType: void
T_125: (in fn080482E4 : ptr32)
  Class: Eq_125
  DataType: (ptr Eq_125)
  OrigDataType: (ptr (fn T_127 ()))
T_126: (in signature of fn080482E4 : void)
  Class: Eq_125
  DataType: (ptr Eq_125)
  OrigDataType: 
T_127: (in fn080482E4() : void)
  Class: Eq_127
  DataType: void
  OrigDataType: void
T_128: (in fn080482C4 : ptr32)
  Class: Eq_128
  DataType: (ptr Eq_128)
  OrigDataType: (ptr (fn T_130 ()))
T_129: (in signature of fn080482C4 : void)
  Class: Eq_128
  DataType: (ptr Eq_128)
  OrigDataType: 
T_130: (in fn080482C4() : void)
  Class: Eq_130
  DataType: void
  OrigDataType: void
T_131: (in twofib : ptr32)
  Class: Eq_100
  DataType: (ptr Eq_100)
  OrigDataType: (ptr (fn T_135 (T_133, T_134)))
T_132: (in 0x00000014 : word32)
  Class: Eq_132
  DataType: ui32
  OrigDataType: ui32
T_133: (in fp - 0x00000014 : word32)
  Class: Eq_93
  DataType: ptr32
  OrigDataType: ptr32
T_134: (in dwLoc08 : word32)
  Class: Eq_94
  DataType: word32
  OrigDataType: word32
T_135: (in twofib(fp - 0x00000014, dwLoc08) : void)
  Class: Eq_107
  DataType: void
  OrigDataType: void
T_136: (in fn080482E4 : ptr32)
  Class: Eq_125
  DataType: (ptr Eq_125)
  OrigDataType: (ptr (fn T_137 ()))
T_137: (in fn080482E4() : void)
  Class: Eq_127
  DataType: void
  OrigDataType: void
T_138: (in esi : word32)
  Class: Eq_2
  DataType: word32
  OrigDataType: word32
T_139: (in _init : ptr32)
  Class: Eq_139
  DataType: (ptr Eq_139)
  OrigDataType: (ptr (fn T_141 (T_138)))
T_140: (in signature of _init : void)
  Class: Eq_139
  DataType: (ptr Eq_139)
  OrigDataType: 
T_141: (in _init(esi) : void)
  Class: Eq_141
  DataType: void
  OrigDataType: void
T_142: (in 0x00000000 : word32)
  Class: Eq_142
  DataType: word32
  OrigDataType: word32
T_143: (in 08049734 : ptr32)
  Class: Eq_143
  DataType: ptr32
  OrigDataType: ptr32
T_144: (in 08049734 : ptr32)
  Class: Eq_144
  DataType: ptr32
  OrigDataType: ptr32
T_145: (in 0x08049734 - 0x08049734 : word32)
  Class: Eq_145
  DataType: Eq_145
  OrigDataType: 
T_146: (in 0x00000002 : word32)
  Class: Eq_146
  DataType: Eq_146
  OrigDataType: 
T_147: (in 0x08049734 - 0x08049734 >> 0x00000002 : word32)
  Class: Eq_142
  DataType: word32
  OrigDataType: 
T_148: (in 0x00000000 >=u 0x08049734 - 0x08049734 >> 0x00000002 : bool)
  Class: Eq_148
  DataType: Eq_148
  OrigDataType: 
T_149: (in esp_47 : word32)
  Class: Eq_149
  DataType: word32
  OrigDataType: word32
T_150: (in ebp_48 : word32)
  Class: Eq_150
  DataType: word32
  OrigDataType: word32
T_151: (in edi_49 : Eq_151)
  Class: Eq_151
  DataType: Eq_151
  OrigDataType: (union (int32 u1) (ptr32 u0))
T_152: (in esi_50 : uint32)
  Class: Eq_152
  DataType: uint32
  OrigDataType: uint32
T_153: (in ebx_51 : word32)
  Class: Eq_153
  DataType: word32
  OrigDataType: word32
T_154: (in SCZO_52 : byte)
  Class: Eq_154
  DataType: byte
  OrigDataType: byte
T_155: (in eax_53 : word32)
  Class: Eq_155
  DataType: word32
  OrigDataType: word32
T_156: (in edx_54 : word32)
  Class: Eq_156
  DataType: word32
  OrigDataType: word32
T_157: (in SZO_55 : byte)
  Class: Eq_157
  DataType: byte
  OrigDataType: byte
T_158: (in C_56 : byte)
  Class: Eq_158
  DataType: byte
  OrigDataType: byte
T_159: (in ecx_57 : word32)
  Class: Eq_159
  DataType: word32
  OrigDataType: word32
T_160: (in 08049734 : ptr32)
  Class: Eq_160
  DataType: (ptr (ptr code))
  OrigDataType: (ptr (struct (0 T_163 t0000)))
T_161: (in 0x00000000 : word32)
  Class: Eq_161
  DataType: word32
  OrigDataType: word32
T_162: (in 0x08049734 + 0x00000000 : word32)
  Class: Eq_162
  DataType: ptr32
  OrigDataType: ptr32
T_163: (in Mem0[0x08049734 + 0x00000000:word32] : word32)
  Class: Eq_163
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_164: (in 0x00000001 : word32)
  Class: Eq_164
  DataType: uint32
  OrigDataType: uint32
T_165: (in esi_50 + 0x00000001 : word32)
  Class: Eq_165
  DataType: Eq_165
  OrigDataType: uint32
T_166: (in 08049734 : ptr32)
  Class: Eq_166
  DataType: Eq_166
  OrigDataType: (union (int32 u1) (ptr32 u0))
T_167: (in 0x08049734 - edi_49 : word32)
  Class: Eq_167
  DataType: Eq_167
  OrigDataType: (union (int32 u1) (ptr32 u0))
T_168: (in 0x00000002 : word32)
  Class: Eq_168
  DataType: word32
  OrigDataType: word32
T_169: (in 0x08049734 - edi_49 >> 0x00000002 : word32)
  Class: Eq_165
  DataType: Eq_165
  OrigDataType: (union (int32 u0) (uint32 u1))
T_170: (in esi_50 + 0x00000001 <u 0x08049734 - edi_49 >> 0x00000002 : bool)
  Class: Eq_170
  DataType: bool
  OrigDataType: bool
T_171: (in edi_18 : (arr (ptr code)))
  Class: Eq_171
  DataType: (ptr (arr (ptr code)))
  OrigDataType: (ptr (struct (0 (arr T_217) a0000)))
T_172: (in 08049734 : ptr32)
  Class: Eq_171
  DataType: (ptr (arr (ptr code)))
  OrigDataType: ptr32
T_173: (in esi_23 : word32)
  Class: Eq_173
  DataType: ui32
  OrigDataType: ui32
T_174: (in 08049734 : ptr32)
  Class: Eq_174
  DataType: ptr32
  OrigDataType: ptr32
T_175: (in 08049734 : ptr32)
  Class: Eq_175
  DataType: ptr32
  OrigDataType: ptr32
T_176: (in 0x08049734 - 0x08049734 : word32)
  Class: Eq_176
  DataType: Eq_176
  OrigDataType: 
T_177: (in 0x00000002 : word32)
  Class: Eq_177
  DataType: Eq_177
  OrigDataType: 
T_178: (in 0x08049734 - 0x08049734 >> 0x00000002 : word32)
  Class: Eq_178
  DataType: Eq_178
  OrigDataType: 
T_179: (in 0x00000001 : word32)
  Class: Eq_179
  DataType: Eq_179
  OrigDataType: 
T_180: (in (0x08049734 - 0x08049734 >> 0x00000002) - 0x00000001 : word32)
  Class: Eq_173
  DataType: ui32
  OrigDataType: 
T_181: (in 0xFFFFFFFF : word32)
  Class: Eq_173
  DataType: ui32
  OrigDataType: word32
T_182: (in esi_23 != 0xFFFFFFFF : bool)
  Class: Eq_182
  DataType: bool
  OrigDataType: bool
T_183: (in esp_45 : word32)
  Class: Eq_183
  DataType: word32
  OrigDataType: word32
T_184: (in ebp_46 : word32)
  Class: Eq_184
  DataType: word32
  OrigDataType: word32
T_185: (in esi_48 : word32)
  Class: Eq_185
  DataType: word32
  OrigDataType: word32
T_186: (in ebx_49 : word32)
  Class: Eq_186
  DataType: word32
  OrigDataType: word32
T_187: (in SCZO_50 : byte)
  Class: Eq_187
  DataType: byte
  OrigDataType: byte
T_188: (in eax_51 : word32)
  Class: Eq_188
  DataType: word32
  OrigDataType: word32
T_189: (in Z_52 : byte)
  Class: Eq_189
  DataType: byte
  OrigDataType: byte
T_190: (in SZO_53 : byte)
  Class: Eq_190
  DataType: byte
  OrigDataType: byte
T_191: (in 0x00000004 : word32)
  Class: Eq_191
  DataType: ui32
  OrigDataType: ui32
T_192: (in esi_23 * 0x00000004 : word32)
  Class: Eq_192
  DataType: ui32
  OrigDataType: ui32
T_193: (in edi_18[esi_23 * 0x00000004] : word32)
  Class: Eq_193
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_194: (in 0x00000001 : word32)
  Class: Eq_194
  DataType: word32
  OrigDataType: word32
T_195: (in esi_48 - 0x00000001 : word32)
  Class: Eq_173
  DataType: ui32
  OrigDataType: word32
T_196: (in _fini : ptr32)
  Class: Eq_196
  DataType: (ptr Eq_196)
  OrigDataType: (ptr (fn T_198 ()))
T_197: (in signature of _fini : void)
  Class: Eq_196
  DataType: (ptr Eq_196)
  OrigDataType: 
T_198: (in _fini() : void)
  Class: Eq_198
  DataType: void
  OrigDataType: void
T_199: (in eax_14 : (ptr code))
  Class: Eq_199
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_200: (in 0x08049574 : word32)
  Class: Eq_200
  DataType: (ptr (ptr code))
  OrigDataType: (ptr (struct (0 T_201 t0000)))
T_201: (in Mem0[0x08049574:word32] : word32)
  Class: Eq_199
  DataType: (ptr code)
  OrigDataType: word32
T_202: (in 0xFFFFFFFF : word32)
  Class: Eq_199
  DataType: (ptr code)
  OrigDataType: word32
T_203: (in eax_14 != (<anonymous> *) 0xFFFFFFFF : bool)
  Class: Eq_203
  DataType: bool
  OrigDataType: bool
T_204: (in esp_30 : word32)
  Class: Eq_204
  DataType: word32
  OrigDataType: word32
T_205: (in ebp_31 : word32)
  Class: Eq_205
  DataType: word32
  OrigDataType: word32
T_206: (in ebx_32 : (ptr (ptr code)))
  Class: Eq_206
  DataType: (ptr (ptr code))
  OrigDataType: (ptr (struct (0 T_213 t0000)))
T_207: (in edx_33 : word32)
  Class: Eq_207
  DataType: word32
  OrigDataType: word32
T_208: (in eax_34 : word32)
  Class: Eq_208
  DataType: word32
  OrigDataType: word32
T_209: (in SCZO_35 : byte)
  Class: Eq_209
  DataType: byte
  OrigDataType: byte
T_210: (in Z_36 : byte)
  Class: Eq_210
  DataType: byte
  OrigDataType: byte
T_211: (in 0x00000000 : word32)
  Class: Eq_211
  DataType: word32
  OrigDataType: word32
T_212: (in ebx_32 + 0x00000000 : word32)
  Class: Eq_212
  DataType: word32
  OrigDataType: word32
T_213: (in Mem0[ebx_32 + 0x00000000:word32] : word32)
  Class: Eq_199
  DataType: (ptr code)
  OrigDataType: word32
T_214: (in __do_global_dtors_aux : ptr32)
  Class: Eq_214
  DataType: (ptr Eq_214)
  OrigDataType: (ptr (fn T_216 ()))
T_215: (in signature of __do_global_dtors_aux : void)
  Class: Eq_214
  DataType: (ptr Eq_214)
  OrigDataType: 
T_216: (in __do_global_dtors_aux() : void)
  Class: Eq_216
  DataType: void
  OrigDataType: void
T_217:
  Class: Eq_217
  DataType: (ptr code)
  OrigDataType: (struct 0004 (0 T_193 t0000))
*/
typedef struct Globals {
	<anonymous> tFFFFFFFF;	// FFFFFFFF
	<anonymous> t80482CA;	// 80482CA
	<anonymous> t80482DA;	// 80482DA
	<anonymous> t80482EA;	// 80482EA
	<anonymous> * ptr8049574;	// 8049574
	<anonymous> * ptr8049580;	// 8049580
	word32 dw8049584;	// 8049584
	<anonymous> * ptr8049658;	// 8049658
	<anonymous> * ptr8049660;	// 8049660
	<anonymous> * ptr8049664;	// 8049664
	<anonymous> * ptr8049668;	// 8049668
	<anonymous> ** ptr8049674;	// 8049674
	byte b8049678;	// 8049678
} Eq_1;

typedef void (Eq_3)();

typedef void (Eq_6)(word32);

typedef void (Eq_10)();

typedef void (Eq_23)(ptr32);

typedef void (Eq_28)();

typedef void (Eq_31)();

typedef void (Eq_100)(ptr32, word32);

typedef struct Eq_113 {
	word32 dw0000;	// 0
	word32 dw0004;	// 4
} Eq_113;

typedef void (Eq_120)(ptr32);

typedef void (Eq_125)();

typedef void (Eq_128)();

typedef void (Eq_139)(word32);

typedef union Eq_151 {
	int32 u0;
	ptr32 u1;
} Eq_151;

typedef union Eq_165 {
	int32 u0;
	uint32 u1;
} Eq_165;

typedef union Eq_166 {
	int32 u0;
	ptr32 u1;
} Eq_166;

typedef union Eq_167 {
	int32 u0;
	ptr32 u1;
} Eq_167;

typedef void (Eq_196)();

typedef void (Eq_214)();

