// subject.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 00010538: void _start(Register (ptr32 Eq_2) g1, Register (ptr32 Eq_3) o7, Register ui32 fsr, Stack int32 dwArg40)
void _start( * g1, Eq_3 * o7, ui32 fsr, int32 dwArg40)
{
	globals->ptr20854 = fp + 0x44;
	globals->ptr20848 = fp + 0x44 + ((dwArg40 << 0x02) + 0x04);
	if (0x00 != 0x00)
	{
		globals->dw2084C = fsr;
		globals->dw2084C = globals->dw2084C & ~0x00;
	}
	if (g1 == null)
	{
		atexit(&globals->t10690);
		_init(o7);
		main(tLoc24);
		exit(dwArg40);
	}
	else
		atexit(g1);
}

// 00010618: Register word32 proc1(Register word32 o0, Register word32 o1)
word32 proc1(word32 o0, word32 o1)
{
	return o0 - o1;
}

// 00010620: void main(Stack Eq_44 tArg00)
void main( tArg00)
{
	proc1(11, 0x04);
	printf(&globals->b20858, tArg00);
}

// 00010640: void _init(Register (ptr32 Eq_3) o7)
void _init(Eq_3 * o7)
{
	fn00010650(o7);
}

// 00010650: void fn00010650(Register (ptr32 Eq_3) o7)
void fn00010650(Eq_3 * o7)
{
	struct Eq_71 * o0_5 = o7 + o7->dw0008 / 0x0C;
	<anonymous> * l0_6 = o0_5->ptrFFFFFFF8;
	<anonymous> * l1_7 = o0_5->ptrFFFFFFF0;
	if (l0_6 == null)
	{
		if (l1_7 == null)
			return;
		word32 sp_50;
		word32 o0_51;
		word32 o7_52;
		word32 l0_53;
		word32 l1_54;
		word32 g0_55;
		byte NZVC_56;
		byte Z_57;
		word32 i7_58;
		word32 i0_59;
		word32 o1_60;
		word32 i1_61;
		word32 o2_62;
		word32 i2_63;
		word32 o3_64;
		word32 i3_65;
		word32 o4_66;
		word32 i4_67;
		word32 o5_68;
		word32 i5_69;
		word32 i6_70;
		l1_7();
	}
	else
	{
		word32 sp_12;
		word32 o0_13;
		word32 o7_14;
		word32 l0_15;
		word32 l1_16;
		word32 g0_17;
		byte NZVC_18;
		byte Z_19;
		word32 i7_20;
		word32 i0_21;
		word32 o1_22;
		word32 i1_23;
		word32 o2_24;
		word32 i2_25;
		word32 o3_26;
		word32 i3_27;
		word32 o4_28;
		word32 i4_29;
		word32 o5_30;
		word32 i5_31;
		word32 i6_32;
		l0_6();
	}
}

// 00010690: void _fini(Register (ptr32 Eq_130) o7)
void _fini(Eq_130 * o7)
{
	fn000106A0(o7);
}

// 000106A0: void fn000106A0(Register (ptr32 Eq_130) o7)
void fn000106A0(Eq_130 * o7)
{
	struct Eq_135 * o0_5 = o7 + o7->dw0008 / 0x0C;
	<anonymous> * l0_6 = o0_5->ptrFFFFFFFC;
	<anonymous> * l1_7 = o0_5->ptrFFFFFFF4;
	if (l0_6 == null)
	{
		if (l1_7 == null)
			return;
		word32 sp_50;
		word32 o0_51;
		word32 o7_52;
		word32 l0_53;
		word32 l1_54;
		word32 g0_55;
		byte NZVC_56;
		byte Z_57;
		word32 i7_58;
		word32 i0_59;
		word32 o1_60;
		word32 i1_61;
		word32 o2_62;
		word32 i2_63;
		word32 o3_64;
		word32 i3_65;
		word32 o4_66;
		word32 i4_67;
		word32 o5_68;
		word32 i5_69;
		word32 i6_70;
		l1_7();
	}
	else
	{
		word32 sp_12;
		word32 o0_13;
		word32 o7_14;
		word32 l0_15;
		word32 l1_16;
		word32 g0_17;
		byte NZVC_18;
		byte Z_19;
		word32 i7_20;
		word32 i0_21;
		word32 o1_22;
		word32 i1_23;
		word32 o2_24;
		word32 i2_25;
		word32 o3_26;
		word32 i3_27;
		word32 o4_28;
		word32 i4_29;
		word32 o5_30;
		word32 i5_31;
		word32 i6_32;
		l0_6();
	}
}

// 0002071C: void atexit()
void atexit()
{
}

// 00020728: void exit()
void exit()
{
}

// 00020734: void _exit()
void _exit()
{
}

// 00020740: void printf()
void printf()
{
}

