// subject_code.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0C00:0100: void fn0C00_0100(Register byte ch, Register (ptr16 Eq_4) ds)
void fn0C00_0100(byte ch, struct Eq_4 * ds)
{
	bios_video_set_mode(0x13);
	__out<byte>(0x03D4, 0x11);
	__out<byte>(0x03D5, __in<byte>(0x03D5) & 0x7F);
	byte Eq_4::* si_158 = Eq_4::a01A0;
	while (true)
	{
		byte al_20 = ds->*si_158;
		byte Eq_4::* si_21 = si_158 + 1;
		if (al_20 == 0x00)
			break;
		__out<byte>(SEQ(0x03, al_20), ds->*si_21);
		si_158 = si_21 + 1;
	}
	byte ah_164 = 0x00;
	word16 cx_194 = SEQ(ch, 0x7F);
	do
	{
		byte cl_33 = (byte) cx_197;
		byte bl_35 = cl_33 & 0x1F;
		byte bh_37 = 0x1F - (cl_33 & 0x1F);
		if ((cl_33 & 0x20) != 0x00)
			bl_35 = bh_37;
		if ((cl_33 & 0x40) != 0x00)
		{
			bl_35 = ah_164;
			ah_164 = bl_35;
		}
		__out<byte>(0x03C8, cl_33);
		__out<byte>(969, bl_35);
		__out<byte>(969, bl_35);
		__out<byte>(969, ah_164);
		byte al_101 = ah_164;
		cx_194 = SEQ(SLICE(cx_197 - 0x01, byte, 8), cl_33 - 0x01);
		cx_197 = cx_194;
	} while (cx_197 != 0x01);
	do
	{
		struct Eq_97 Eq_96::* di_107 = &Eq_96::t0000;
		byte ch_109 = 0x00;
		do
		{
			byte cl_103 = 0x00;
			do
			{
				byte al_94 = al_101 & 0x3F;
				(0xA000->*di_107).b0000 = al_94;
				struct Eq_102 Eq_96::* di_98 = &di_107->b0000 + 1;
				di_107 = (struct Eq_97 Eq_96::*) (&di_98->b0000 + 1);
				al_101 = al_94 + ds->b01C0;
				++cl_103;
			} while (cl_103 != 0x00);
			di_107 = (struct Eq_97 Eq_96::*) (di_98 + 1);
			++ch_109;
		} while (ch_109 != 0x00);
		++ds->b01C0;
		byte Eq_96::* di_116 = &Eq_96::b0001;
		byte ch_117 = 0x00;
		do
		{
			byte cl_118 = 0x00;
			do
			{
				byte al_120 = al_101 & 0x3F;
				0xA000->*di_116 = al_120 | 0x40;
				byte Eq_96::* di_125 = di_116 + 1;
				di_116 = di_125 + 1;
				al_101 = (al_120 | 0x40) - ds->b01C1;
				++cl_118;
			} while (cl_118 != 0x00);
			di_116 = di_125;
			++ch_117;
		} while (ch_117 != 0x00);
		++ds->b01C1;
		do
			;
		while ((__in<byte>(0x03DA) & 0x08) == 0x00);
		byte al_149 = __in<byte>(0x60);
		al_101 = al_149 - 0x01;
	} while (al_149 != 0x01);
	bios_video_set_mode(0x03);
	msdos_terminate(0x03);
}

