// subject.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0000000000000C10: Register ptr64 _init(Stack word64 qwArg00)
ptr64 _init(word64 qwArg00)
{
	call_weak_fn();
	return fp + 0x08;
}

// 0000000000000C50: void fn0000000000000C50()
void fn0000000000000C50()
{
	<anonymous> * x17_4 = globals->ptr13000;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000000C60: void fn0000000000000C60()
void fn0000000000000C60()
{
	<anonymous> * x17_4 = globals->ptr13008;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000000C70: void fn0000000000000C70()
void fn0000000000000C70()
{
	<anonymous> * x17_4 = globals->ptr13010;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000000C80: void fn0000000000000C80()
void fn0000000000000C80()
{
	<anonymous> * x17_4 = globals->ptr13018;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000000C90: void fn0000000000000C90()
void fn0000000000000C90()
{
	<anonymous> * x17_4 = globals->ptr13020;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000000CA0: void fn0000000000000CA0()
void fn0000000000000CA0()
{
	<anonymous> * x17_4 = globals->ptr13028;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000000CB0: void fn0000000000000CB0()
void fn0000000000000CB0()
{
	<anonymous> * x17_4 = globals->ptr13030;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000000CD0: void fn0000000000000CD0()
void fn0000000000000CD0()
{
	<anonymous> * x17_4 = globals->ptr13040;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000000CE0: void fn0000000000000CE0()
void fn0000000000000CE0()
{
	<anonymous> * x17_4 = globals->ptr13048;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000000CF0: void fn0000000000000CF0()
void fn0000000000000CF0()
{
	<anonymous> * x17_4 = globals->ptr13050;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000000D00: void fn0000000000000D00()
void fn0000000000000D00()
{
	<anonymous> * x17_4 = globals->ptr13058;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000000D10: void main(Register int32 w0, Register word32 w1, Register word32 w4, Register word32 w5, Register ui32 w18, Register word32 w20, Register (ptr64 Eq_104) x30)
void main(int32 w0, word32 w1, word32 w4, word32 w5, ui32 w18, word32 w20, Eq_104 * x30)
{
	word32 * x20_23 = globals->ptr12FC0;
	*x20_23 = (word32) *globals->ptr12F78;
	if (w0 > 0x01)
	{
		word32 w0_188 = (word32) (word64) *(int64) (int32) (w1 + 0x04);
		fn0000000000000C60();
		*x20_23 = w0_188;
	}
	fn0000000000000CB0();
	word32 * x6_45 = globals->ptr12F40;
	word64 x9_50 = globals->qw2A10;
	(word64 *) 0x01 = globals->qw2A08;
	globals->qw2A09 = x9_50;
	*x6_45 = 0x01;
	word64 x8_57 = globals->qw2A28;
	word64 x9_59 = globals->qw2A30;
	word64 x6_61 = globals->qw2A18;
	word64 x7_63 = globals->qw2A20;
	globals->qw2A19 = x8_57;
	globals->qw2A21 = x9_59;
	word32 * x4_68 = globals->ptr12F30;
	word32 w0_70 = (word32) globals->b2A38;
	globals->qw2A09 = x6_61;
	globals->qw2A11 = x7_63;
	globals->b2A0A = (byte) w0_70;
	word32 w5_76 = (word32) 0x2A0A;
	*x4_68 = w5_76;
	fn0000000000000CB0();
	*globals->ptr12F60 = 0x01;
	fn0000000000000CB0();
	word32 * x3_94 = globals->ptr12F80;
	word32 * x2_96 = globals->ptr12FC8;
	*x3_94 = 0x01;
	*x2_96 = 0x01;
	fn0000000000000CB0();
	word32 * x20_99 = globals->ptr12F38;
	*x20_99 = 0x01;
	word32 w3_102;
	word64 x29_103;
	word64 x30_104;
	word64 sp_105;
	o(0x01, x30, out w3_102, out x29_103, out x30_104, out sp_105);
	Eq_255 w20_100 = (word32) x20_99;
	word64 x19_109;
	word64 x20_110;
	word64 x21_111;
	word64 x22_112;
	word64 x23_113;
	word64 x24_114;
	word64 x25_115;
	word64 x26_116;
	word64 x27_117;
	word64 x29_118;
	word64 x30_119;
	word64 sp_120;
	ad(w18, w20_100, qwArg00, out x19_109, out x20_110, out x21_111, out x22_112, out x23_113, out x24_114, out x25_115, out x26_116, out x27_117, out x29_118, out x30_119, out sp_120);
	word64 x21_123;
	word32 w22_124;
	word32 w24_125;
	word32 w27_126;
	<anonymous> * x2_144 = (word64) *(int64) (int32) (*ab(0x00, w18, w20_100, out x21_123, out w22_124, out w24_125, out w27_126) + 0x0250);
	word64 sp_145;
	word64 x29_146;
	word64 x30_147;
	word64 x2_148;
	word32 w0_149;
	byte NZCV_150;
	word64 x19_151;
	word64 x20_152;
	word32 w19_153;
	word64 x0_154;
	word64 x21_155;
	word32 w1_156;
	word32 w21_157;
	byte ZCV_158;
	word64 x1_159;
	word64 x3_160;
	word64 x6_161;
	word64 x4_162;
	word64 x5_163;
	word64 x8_164;
	word64 x9_165;
	word64 x7_166;
	word32 w5_167;
	word32 w4_168;
	word32 w2_169;
	word32 w18_170;
	word32 w20_171;
	word32 w3_172;
	word64 x22_173;
	word64 x23_174;
	word64 x24_175;
	word64 x25_176;
	word64 x26_177;
	word64 x27_178;
	word32 w22_179;
	word32 w24_180;
	word32 w27_181;
	x2_144();
}

// 0000000000000E58: void _start(Stack word64 qwArg00)
void _start(word64 qwArg00)
{
	fn0000000000000C90();
	fn0000000000000CD0();
	call_weak_fn();
}

// 0000000000000E90: void call_weak_fn()
void call_weak_fn()
{
	word64 x0_4 = globals->qw12F88;
	if (x0_4 == 0x00)
		return;
	<anonymous> * x17_10 = globals->ptr13038;
	word64 sp_12;
	word64 x0_13;
	word64 x16_14;
	word64 x17_15;
	x17_10();
}

// 0000000000000EA8: void deregister_tm_clones()
void deregister_tm_clones()
{
	if (0x00013077 - 0x00013070 <= 0x0E)
		return;
	<anonymous> * x1_18 = globals->ptr12F28;
	if (x1_18 == null)
		return;
	word64 sp_19;
	word64 x1_20;
	word64 x0_21;
	byte NZCV_22;
	byte ZC_23;
	x1_18();
}

// 0000000000000EE0: void register_tm_clones()
void register_tm_clones()
{
	int64 x1_6 = 0x00013070 - 0x00013070;
	if ((x1_6 >> 0x03) + ((x1_6 >> 0x03) >>u 0x003F) >> 0x01 == 0x00)
		return;
	<anonymous> * x2_18 = globals->ptr12FE0;
	if (x2_18 == null)
		return;
	word64 sp_19;
	word64 x1_20;
	word64 x0_21;
	word64 x2_22;
	x2_18();
}

// 0000000000000F20: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	if ((word32) globals->b13070 == 0x00)
	{
		if (globals->qw12F48 != 0x00)
			fn0000000000000C50();
		deregister_tm_clones();
		globals->b13070 = 0x01;
	}
}

// 0000000000000F68: void frame_dummy(Stack word64 qwArg00)
void frame_dummy(word64 qwArg00)
{
	if (globals->qw12D20 != 0x00)
	{
		<anonymous> * x1_21 = globals->ptr12FD8;
		if (x1_21 != null)
		{
			word64 sp_27;
			word64 x0_28;
			word64 x1_29;
			word64 x29_30;
			word64 x30_31;
			word64 x2_32;
			x1_21();
			register_tm_clones();
			return;
		}
	}
	register_tm_clones();
}

// 0000000000000FA0: void E(Register word32 w0)
void E(word32 w0)
{
	word32 * x2_4 = globals->ptr12F30;
	word32 w1_5 = *x2_4;
	*x2_4 = w1_5 + 0x01;
	*(int64) (int32) w1_5 = (byte) w0;
}

// 0000000000000FC8: Register Eq_255 o(Register Eq_255 w0, Stack (ptr64 Eq_104) qwArg00, Register out Eq_257 w3Out, Register out ptr64 x29Out, Register out ptr64 x30Out, Register out (ptr64 Eq_260) spOut)
Eq_255 o(Eq_255 w0, Eq_104 * qwArg00, Eq_257 & w3Out, ptr64 & x29Out, ptr64 & x30Out, Eq_260 * & spOut)
{
	*x29Out = x29;
	*x30Out = x30;
	*w3Out = w3;
	word32 * x0_4 = globals->ptr12F68;
	word64 sp_1;
	*spOut = fp;
	Eq_255 w0_5 = (word32) x0_4;
	word32 w1_6 = *x0_4;
	if (w1_6 == 0x00)
	{
		Eq_255 w0_55 = (word32) (word64) *globals->ptr12FC0;
		fn0000000000000CA0();
		*globals->ptr12F58 = (union Eq_255 *) w0_55;
		word64 x29_60;
		*x29Out = x30;
		word64 x30_63;
		*x30Out = qwArg00;
		word64 sp_64;
		*spOut = fp + 0x08;
		return w0_55;
	}
	else
	{
		*x0_4 = w1_6 + 0x01;
		union Eq_255 * x2_30 = globals->ptr12F58;
		Eq_255 w1_32 = (word32) *(int64) (int32) w1_6;
		*x2_30 = (union Eq_255 *) w1_32;
		word32 w3_27;
		*w3Out = w1_6 + 0x01;
		if (w1_32 != 0x02)
			return w0_5;
		*x0_4 = 0x00;
		Eq_255 w0_43 = *globals->ptr12FB8;
		*x2_30 = (union Eq_255 *) w0_43;
		return w0_43;
	}
}

// 0000000000001048: Register Eq_255 Y.part.1(Register Eq_255 w0, Register (ptr64 Eq_104) x30)
Eq_255 Y.part.1(Eq_255 w0, Eq_104 * x30)
{
	word32 w3_10;
	word64 x29_11;
	word64 x30_12;
	word64 sp_13;
	o(w0, x30, out w3_10, out x29_11, out x30_12, out sp_13);
	word32 * x0_17 = globals->ptr12F58;
	Eq_255 w0_18 = (word32) x0_17;
	if (*x0_17 == 110)
		*x0_17 = 0x0A;
	return w0_18;
}

// 0000000000001078: void X()
void X()
{
	fn0000000000000D00();
}

// 00000000000010B0: void Y(Register (ptr64 Eq_104) x30)
void Y(Eq_104 * x30)
{
	Eq_255 w0_5 = *globals->ptr12F58;
	if (w0_5 != 0x5C)
		return;
	Y.part.1(w0_5, x30);
}

// 00000000000010D0: Register Eq_255 ad(Register ui32 w18, Register Eq_255 w20, Stack (ptr64 Eq_104) qwArg00, Register out (ptr64 Eq_255) x19Out, Register out (ptr64 Eq_287) x20Out, Register out (ptr64 Eq_288) x21Out, Register out (ptr64 Eq_289) x22Out, Register out (ptr64 Eq_290) x23Out, Register out (ptr64 Eq_291) x24Out, Register out (ptr64 Eq_292) x25Out, Register out ptr64 x26Out, Register out ptr64 x27Out, Register out ptr64 x29Out, Register out ptr64 x30Out, Register out (ptr64 Eq_297) spOut)
Eq_255 ad(ui32 w18, Eq_255 w20, Eq_104 * qwArg00, Eq_255 * & x19Out, Eq_287 * & x20Out, Eq_288 * & x21Out, Eq_289 * & x22Out, Eq_290 * & x23Out, Eq_291 * & x24Out, Eq_292 * & x25Out, ptr64 & x26Out, ptr64 & x27Out, ptr64 & x29Out, ptr64 & x30Out, Eq_297 * & spOut)
{
	struct Eq_669 * sp_104 = fp + -88;
	struct Eq_673 * x21_15 = (struct Eq_673 *) 0x00012000;
	struct Eq_675 * x23_22 = (struct Eq_675 *) 0x00012000;
	struct Eq_677 * x22_29 = (struct Eq_677 *) 0x00012000;
	struct Eq_679 * x25_32 = (struct Eq_679 *) 0x00012000;
	while (true)
	{
l0000000000001104:
		union Eq_255 * x20_632 = x22_29->ptr0F58;
		Eq_255 w19_667 = *x20_632;
		fn0000000000000C70();
		Eq_255 w20_74 = (word32) x20_632;
		bool Z_629 = (bool) cond(w19_667 - 0x23);
		Eq_255 w0_647 = (word32) (w19_667 == 0x23) | w19_667;
		while (w0_647 != 0x00)
		{
			if (!Z_629)
			{
				word32 w3_677;
				word64 x29_678;
				word64 x30_679;
				o(w0_647, x28, out w3_677, out x29_678, out x30_679, out sp_104);
			}
			else
			{
				word32 w3_682;
				word64 x29_683;
				word64 x30_684;
				word64 sp_685;
				o(w0_647, x28, out w3_682, out x29_683, out x30_684, out sp_685);
				word64 x19_687;
				word32 * x24_692;
				word64 x26_694;
				word64 x29_696;
				word64 x30_697;
				word64 sp_698;
				union Eq_255 * x27_695;
				ad(w18, w20_74, x28, out x19_687, out x20_632, out x21_15, out x22_29, out x23_22, out x24_692, out x25_32, out x26_694, out x27_695, out x29_696, out x30_697, out sp_698);
				if (*x24_692 == 0x0218)
				{
					word64 x19_765;
					int32 * x24_770;
					word32 * x26_772;
					word64 x29_774;
					word64 x30_775;
					word64 sp_776;
					ad(w18, w20_74, x28, out x19_765, out x20_632, out x21_15, out x22_29, out x23_22, out x24_770, out x25_32, out x26_772, out x27_695, out x29_774, out x30_775, out sp_776);
					word32 w0_778 = *x26_772;
					*x26_772 = w0_778 + 0x01;
					*(int64) (int32) w0_778 = 0x20;
					*(word64) *x24_770 = 0x01;
					*(int64) (int32) (*x24_770 + 0x04) = *x26_772;
				}
				Eq_255 w1_718 = *x27_695;
				int32 * x28_720 = x21_15->ptr0F30;
				union Eq_255 * x19_724 = x22_29->ptr0F58;
				while (w1_718 != 0x0A)
				{
					int32 w0_750 = *x28_720;
					*x28_720 = w0_750 + 0x01;
					byte * x0_752 = (int64) (int32) w0_750;
					*x0_752 = (byte) w1_718;
					word32 w3_756;
					word64 x29_757;
					word64 x30_758;
					word64 sp_759;
					o((word32) x0_752, x28, out w3_756, out x29_757, out x30_758, out sp_759);
					w1_718 = *x19_724;
				}
				int32 * x1_729 = x21_15->ptr0F30;
				int32 w0_732 = *x1_729;
				*x1_729 = w0_732 + 0x01;
				*(int64) (int32) w0_732 = 0x0A;
				int32 w0_737 = *x1_729;
				*x1_729 = w0_737 + 0x01;
				byte * x0_739 = (int64) (int32) w0_737;
				*x0_739 = 0x02;
				word32 w3_743;
				word64 x29_744;
				word64 x30_745;
				o((word32) x0_739, x28, out w3_743, out x29_744, out x30_745, out sp_104);
			}
			w19_667 = *x20_632;
			fn0000000000000C70();
			Z_629 = (bool) cond(w19_667 - 0x23);
			w0_647 = (word32) (w19_667 == 0x23) | w19_667;
		}
		Eq_255 w0_183;
		word32 * x28_105 = x25_32->ptr0F98;
		union Eq_255 * x27_108 = x23_22->ptr0F50;
		*x28_105 = 0x00;
		*x27_108 = (union Eq_255 *) w19_667;
		fn0000000000000D00();
		Eq_255 w0_114 = (word32) (w19_667 == 0x5F) | w19_667;
		if (w0_114 != 0x00)
			break;
		word32 w3_352;
		word64 x29_353;
		struct Eq_104 * x30_354;
		o(w0_114, x28, out w3_352, out x29_353, out x30_354, out sp_104);
		Eq_255 w4_357 = *x27_108;
		if (w4_357 == 0x27)
		{
			Eq_255 w1_566 = *x20_632;
			*x27_108 = (union Eq_255 *) 0x02;
			if (w1_566 == 0x5C)
			{
				Y.part.1(0x02, x30_354);
				w1_566 = *x20_632;
			}
			union Eq_255 * x0_576 = globals->ptr12F70;
			*x0_576 = (union Eq_255 *) w1_566;
			word32 w3_579;
			word64 x29_580;
			word64 x30_581;
			struct Eq_1207 * sp_582;
			Eq_255 w0_583 = o((word32) x0_576, x28, out w3_579, out x29_580, out x30_581, out sp_582);
			word64 x19_586;
			*x19Out = sp_582->qw0010;
			word64 x20_589;
			*x20Out = sp_582->qw0018;
			word64 x21_592;
			*x21Out = sp_582->qw0020;
			word64 x22_594;
			*x22Out = sp_582->qw0028;
			word64 x23_596;
			*x23Out = sp_582->qw0030;
			word64 x24_598;
			*x24Out = sp_582->qw0038;
			word64 x25_600;
			*x25Out = sp_582->qw0040;
			word64 x26_602;
			*x26Out = sp_582->qw0048;
			word64 x27_604;
			*x27Out = sp_582->qw0050;
			word32 w3_612;
			word64 x29_613;
			word64 x30_614;
			word64 sp_615;
			return o(w0_583, x28, out w3_612, out x29_613, out x30_614, out sp_615);
		}
		Eq_255 w5_360 = *x20_632;
		bool Z_367 = false;
		if (w4_357 == 0x2F)
			Z_367 = (bool) cond(w5_360 - 0x2A);
		if (Z_367)
		{
			word32 w3_430 = (word32) 0x2980;
			int32 * x8_432 = globals->ptr12F70;
			do
			{
				byte * x0_444 = (int64) (int32) w3_430;
				w0_183 = (word32) x0_444;
				word32 w1_446 = w3_430 + 0x01;
				if ((word32) *x0_444 == 0x00)
					goto l0000000000001408;
				Eq_255 w9_456 = (word32) *(int64) (int32) w1_446;
				*x8_432 = 0x00;
				ui32 w0_459 = (word32) *(int64) (int32) (w3_430 + 0x02);
				*x28_105 = w0_459 - 0x62;
				word32 w2_452 = w3_430 + 0x03;
				w0_183 = w0_459 - 0x62;
				if ((w0_459 - 0x62 & 0x00) == 0x00)
				{
					w3_430 = w2_452;
					bool Z_541 = true;
					if (w9_456 != 0x40)
						Z_541 = (bool) cond(w5_360 - w18);
					bool Z_547 = false;
					if (!Z_541)
						Z_547 = (bool) cond(w4_357 - w20_74);
					if (!Z_547)
						break;
					continue;
				}
				struct Eq_1310 * x2_487 = (int64) (int32) (w3_430 + 0x04);
				int32 w1_485 = 0x00;
				word32 w2_488 = (word32) x2_487;
				do
				{
					int32 w1_496 = (word32) w0_183 + (w1_485 << 0x06);
					*x8_432 = w1_496 + 0x40;
					x2_487 = &x2_487->bFFFFFFFE + 0x03;
					ui32 w0_505 = (word32) x2_487->bFFFFFFFE;
					*x28_105 = w0_505 - 0x62;
					w3_430 = w2_488;
					w1_485 = w1_496 + 0x40;
					w2_488 = (word32) x2_487;
					w0_183 = w0_505 - 0x62;
				} while ((w0_505 - 0x62 & 0x00) == 0x00);
				bool Z_513 = true;
				if (w9_456 != 0x40)
					Z_513 = (bool) cond(w5_360 - w18);
				bool Z_519 = false;
				if (!Z_513)
					Z_519 = (bool) cond(w4_357 - w20_74);
			} while (Z_519);
			if (w5_360 == w9_456)
			{
				word32 w3_475;
				word64 x29_476;
				word64 x30_477;
				o(w0_183, x28, out w3_475, out x29_476, out x30_477, out sp_104);
				*x23_22->ptr0F50 = (union Eq_255 *) 0x01;
				w0_183.u0 = 0x01;
			}
			goto l0000000000001408;
		}
		word32 w3_374;
		word64 x29_375;
		word64 x30_376;
		word64 sp_377;
		o(0x2A, x28, out w3_374, out x29_375, out x30_376, out sp_377);
		union Eq_255 * x19_379 = x22_29->ptr0F58;
		Eq_255 w0_381 = *x20_632;
		do
		{
			if (w0_381 == 0x00)
				goto l0000000000001394;
			while (w0_381 != 0x2A)
			{
				word32 w3_420;
				word64 x29_421;
				word64 x30_422;
				word64 sp_423;
				o(w0_381, x28, out w3_420, out x29_421, out x30_422, out sp_423);
				w0_381 = *x19_379;
			}
			word32 w3_410;
			word64 x29_411;
			word64 x30_412;
			word64 sp_413;
			o(w0_381, x28, out w3_410, out x29_411, out x30_412, out sp_413);
			w0_381 = *x19_379;
		} while (w0_381 != 0x2F);
		*x19_379 = (union Eq_255 *) 0x00;
l0000000000001394:
		word32 w3_397;
		word64 x29_398;
		word64 x30_399;
		o(w0_381, x28, out w3_397, out x29_398, out x30_399, out sp_104);
	}
	int32 * x0_211 = x21_15->ptr0F30;
	int32 w1_219 = *x0_211;
	union Eq_255 * x20_214 = x22_29->ptr0F58;
	int32 * x2_218 = globals->ptr12FA8;
	*x0_211 = w1_219 + 0x01;
	*(int64) (int32) w1_219 = 0x20;
	*x2_218 = *x0_211;
	while (true)
	{
		Eq_255 w28_232 = *x20_214;
		fn0000000000000D00();
		if (((word32) (w28_232 == 0x5F) | w28_232) == 0x00)
			break;
		int32 w0_341 = *x0_211;
		*x0_211 = w0_341 + 0x01;
		byte * x0_343 = (int64) (int32) w0_341;
		*x0_343 = (byte) w28_232;
		word32 w3_347;
		word64 x29_348;
		word64 x30_349;
		o((word32) x0_343, x28, out w3_347, out x29_348, out x30_349, out sp_104);
	}
	union Eq_255 * x19_239 = x23_22->ptr0F50;
	if (*x19_239 <= 0x39)
	{
		Eq_255 w0_307 = *globals->ptr12FA8;
		fn0000000000000CE0();
		struct Eq_864 * v67_311 = &sp_104->qw0008 + 0x03;
		word64 x21_312;
		*x21Out = v67_311->qw0000;
		word64 x22_314;
		*x22Out = v67_311->qw0008;
		*x19_239 = (union Eq_255 *) 0x02;
		struct Eq_881 * v68_317 = &sp_104->qw0008 + 0x01;
		struct Eq_884 * v69_323 = &sp_104->qw0008 + 0x05;
		word64 x19_318;
		*x19Out = v68_317->qw0000;
		word64 x20_321;
		*x20Out = v68_317->qw0008;
		word64 x23_324;
		*x23Out = v69_323->qw0000;
		word64 x24_326;
		*x24Out = v69_323->qw0008;
		*globals->ptr12F70 = (union Eq_255 *) w0_307;
		struct Eq_914 * v70_328 = &sp_104->qw0008 + 0x07;
		word64 x25_329;
		*x25Out = v70_328->qw0000;
		word64 x26_331;
		*x26Out = v70_328->qw0008;
		word64 x27_333;
		*x27Out = sp_104->qw0050;
		word64 x29_337;
		*x29Out = sp_104->qw0000;
		word64 x30_339;
		*x30Out = sp_104->qw0008;
		word64 sp_340;
		*spOut = &sp_104->qw0050 + 0x02;
		return w0_307;
	}
	int32 * x28_246 = x21_15->ptr0F30;
	*(word64) *x28_246 = 0x20;
	fn0000000000000CF0();
	byte * x1_263 = (word64) *x28_246;
	*x19_239 = (union Eq_255 *) 0x00;
	*x1_263 = 0x00;
	w0_183 = (char *) *x19_239 + 0x0020 << 0x03;
	*x19_239 = (union Eq_255 *) w0_183;
	if (w0_183 > 0x0218)
	{
		w0_183 = (word32) w0_183.u0 + *globals->ptr12F38;
		*x19_239 = (union Eq_255 *) w0_183;
		if (*(int64) (int32) w0_183 == 0x01)
		{
			Eq_255 w3_292 = *x20_214;
			union Eq_255 * x1_295 = globals->ptr12FB8;
			Eq_255 w0_296 = *(int64) (int32) ((word32) w0_183 + 0x04);
			*globals->ptr12F68 = (union Eq_255 *) w0_296;
			*x1_295 = (union Eq_255 *) w3_292;
			word32 w3_299;
			word64 x29_300;
			word64 x30_301;
			o(w0_296, x28, out w3_299, out x29_300, out x30_301, out sp_104);
			goto l0000000000001104;
		}
	}
l0000000000001408:
	struct Eq_986 * v39_184 = &sp_104->qw0008 + 0x01;
	struct Eq_989 * v40_190 = &sp_104->qw0008 + 0x03;
	struct Eq_992 * v41_194 = &sp_104->qw0008 + 0x05;
	struct Eq_995 * v42_198 = &sp_104->qw0008 + 0x07;
	word64 x19_185;
	*x19Out = v39_184->qw0000;
	word64 x20_188;
	*x20Out = v39_184->qw0008;
	word64 x21_191;
	*x21Out = v40_190->qw0000;
	word64 x22_193;
	*x22Out = v40_190->qw0008;
	word64 x23_195;
	*x23Out = v41_194->qw0000;
	word64 x24_197;
	*x24Out = v41_194->qw0008;
	word64 x25_199;
	*x25Out = v42_198->qw0000;
	word64 x26_201;
	*x26Out = v42_198->qw0008;
	word64 x27_203;
	*x27Out = sp_104->qw0050;
	word64 x29_207;
	*x29Out = sp_104->qw0000;
	word64 x30_209;
	*x30Out = sp_104->qw0008;
	word64 sp_210;
	*spOut = &sp_104->qw0050 + 0x02;
	return w0_183;
}

// 0000000000001550: void ae(Register Eq_1593 w0)
void ae(Eq_1593 w0)
{
	word32 * x2_8 = globals->ptr12FC8;
	for (; w0 > 0x00; w0 >>= 0x08)
	{
		word32 w1_18 = *x2_8;
		*x2_8 = w1_18 + 0x01;
		*(int64) (int32) w1_18 = (byte) w0;
	}
}

// 0000000000001590: void A(Register word32 w0)
void A(word32 w0)
{
	word32 * x3_4 = globals->ptr12FC8;
	while (w0 != 0x00)
	{
		word32 * x2_12 = (int64) (int32) w0;
		w0 = *x2_12;
		*x2_12 = *x3_4 - w0 - 0x04;
	}
}

// 00000000000015C0: void s(Register Eq_1645 w0, Register word32 w1)
void s(Eq_1645 w0, word32 w1)
{
	word32 * x3_8 = globals->ptr12FC8;
	for (; w0 > 0x00; w0 >>= 0x08)
	{
		word32 w2_25 = *x3_8;
		*x3_8 = w2_25 + 0x01;
		*(int64) (int32) w2_25 = (byte) w0;
	}
	int32 * x2_15 = globals->ptr12FC8;
	*(word64) *x2_15 = w1;
	*x2_15 += 0x04;
}

// 0000000000001618: void H(Register word32 w0)
void H(word32 w0)
{
	word32 * x1_5 = globals->ptr12FC8;
	word32 w2_6 = *x1_5;
	*x1_5 = w2_6 + 0x01;
	*(int64) (int32) w2_6 = 0xB8;
	*(word64) *x1_5 = w0;
	*x1_5 += 0x04;
}

// 0000000000001658: void B(Register word32 w0)
void B(word32 w0)
{
	word32 * x1_5 = globals->ptr12FC8;
	word32 w2_6 = *x1_5;
	*x1_5 = w2_6 + 0x01;
	*(int64) (int32) w2_6 = 233;
	*(word64) *x1_5 = w0;
	*x1_5 += 0x04;
}

// 0000000000001690: Register Eq_255 S(Register Eq_255 w0, Register word32 w1)
Eq_255 S(Eq_255 w0, word32 w1)
{
	word32 w4_12;
	int32 w3_11 = 0x000FC085;
	word32 * x6_9 = globals->ptr12FC8;
	for (w4_12 = 0x03; w4_12 != 0x00; --w4_12)
	{
		word32 w2_13 = *x6_9;
		*x6_9 = w2_13 + 0x01;
		*(int64) (int32) w2_13 = (byte) w3_11;
		w3_11 >>= 0x08;
	}
	word32 * x3_25 = globals->ptr12FC8;
	Eq_1802 w0_29 = (word32) w0.u2 + 0x0084;
	if (w0 > 0x84)
	{
		do
		{
			word32 w2_48 = *x3_25;
			*x3_25 = w2_48 + 0x01;
			*(int64) (int32) w2_48 = (byte) w0_29;
			w0_29 >>= 0x08;
		} while (w0_29 > 0x00);
	}
	union Eq_255 * x5_37 = globals->ptr12FC8;
	*(word64) *x5_37 = w1;
	Eq_255 w0_42 = *x5_37;
	*x5_37 = (union Eq_255 *) ((word32) w0_42.u0 + 0x04);
	return w0_42;
}

// 0000000000001718: void Z(Register Eq_255 w0)
void Z(Eq_255 w0)
{
	word32 * x1_10 = globals->ptr12FC8;
	word32 w3_18 = *x1_10;
	*x1_10 = w3_18 + 0x01;
	*(int64) (int32) w3_18 = 0x39;
	word32 w3_23 = *x1_10;
	*x1_10 = w3_23 + 0x01;
	*(int64) (int32) w3_23 = 0xC1;
	word32 w3_28 = *x1_10;
	*x1_10 = w3_28 + 0x01;
	*(int64) (int32) w3_28 = 0xB8;
	*(word64) *x1_10 = 0x00;
	word32 w3_36 = *x1_10;
	*x1_10 = w3_36 + 0x05;
	*(int64) (int32) (w3_36 + 0x04) = 0x0F;
	Eq_1923 w0_13 = (word32) w0.u2 + 144;
	if (w0 > 0x90)
	{
		do
		{
			word32 w1_56 = *x1_10;
			*x1_10 = w1_56 + 0x01;
			*(int64) (int32) w1_56 = (byte) w0_13;
			w0_13 >>= 0x08;
		} while (w0_13 > 0x00);
	}
	word32 * x4_46 = globals->ptr12FC8;
	word32 w0_48 = *x4_46;
	*x4_46 = w0_48 + 0x01;
	*(int64) (int32) w0_48 = 0xC0;
}

// 00000000000017E8: void N(Register Eq_255 w0, Register Eq_255 w1)
void N(Eq_255 w0, Eq_255 w1)
{
	Eq_1969 w0_32 = (word32) w0.u2 + 131;
	word32 * x3_10 = globals->ptr12FC8;
	if (w0 > 131)
	{
		do
		{
			word32 w2_33 = *x3_10;
			*x3_10 = w2_33 + 0x01;
			*(int64) (int32) w2_33 = (byte) w0_32;
			w0_32 >>= 0x08;
		} while (w0_32 > 0x00);
	}
	word32 * x2_14 = globals->ptr12FC8;
	word32 w3_21 = *x2_14;
	*x2_14 = w3_21 + 0x01;
	*(int64) (int32) w3_21 = (byte) (w1 > 0x01FF ? 0x05 : 133);
	*(word64) *x2_14 = (union Eq_255 *) w1;
	*x2_14 += 0x04;
}

// 0000000000001868: Register Eq_255 O(Register Eq_255 w0, Register ui32 w18, Register Eq_255 w20, Register (ptr64 Eq_104) x30, Stack (ptr64 Eq_104) qwArg00, Register out Eq_2044 w20Out, Register out Eq_2045 w21Out, Register out Eq_2046 w22Out, Register out Eq_2047 w23Out, Register out Eq_2048 w25Out, Register out Eq_2049 w26Out, Register out ptr64 x29Out, Register out ptr64 x30Out)
Eq_255 O(Eq_255 w0, ui32 w18, Eq_255 w20, Eq_104 * x30, Eq_104 * qwArg00, Eq_2044 & w20Out, Eq_2045 & w21Out, Eq_2046 & w22Out, Eq_2047 & w23Out, Eq_2048 & w25Out, Eq_2049 & w26Out, ptr64 & x29Out, ptr64 & x30Out)
{
	if (w0 == 0x01)
	{
		word32 w20_474;
		word32 w21_475;
		word32 w22_476;
		word32 w23_477;
		word32 w25_478;
		word32 w26_479;
		word64 x29_480;
		word64 x30_481;
		word64 sp_482;
		return T(w0, w18, w20, x30, qwArg00, out w20_474, out w21_475, out w22_476, out w23_477, out w25_478, out w26_479, out x29_480, out x30_481, out sp_482);
	}
	else
	{
		word32 w21_116;
		word32 w22_117;
		word32 w23_118;
		word32 w25_119;
		word64 x29_121;
		word64 x30_122;
		Eq_255 w20_115;
		word32 w26_120;
		Eq_255 w19_123 = O(w0 - 0x01, w18, w20, x30, x30, out w20_115, out w21_116, out w22_117, out w23_118, out w25_119, out w26_120, out x29_121, out x30_122);
		struct Eq_2076 * sp_164 = fp + -88;
		union Eq_255 * x23_127 = globals->ptr12F70;
		struct Eq_2085 * x25_129 = (struct Eq_2085 *) 0x00012000;
l00000000000018B8:
		while (w19_123 == *x25_129->ptr0F98)
		{
			Eq_255 w20_372 = *x23_127;
			word64 x19_376;
			word64 x20_377;
			word64 x21_378;
			word64 x22_379;
			word64 x24_381;
			word64 x26_383;
			word64 x27_384;
			word64 x29_385;
			struct Eq_104 * x30_386;
			ad(w18, w20_372, x28, out x19_376, out x20_377, out x21_378, out x22_379, out x23_127, out x24_381, out x25_129, out x26_383, out x27_384, out x29_385, out x30_386, out sp_164);
			if (w19_123 > 0x08)
			{
				S(w20_372, w26_120);
				word32 w21_464;
				word32 w22_465;
				word32 w23_466;
				word32 w25_467;
				word64 x29_469;
				word64 x30_470;
				w19_123 = O(w19_123, w18, w20_372, x30_386, x28, out w20_115, out w21_464, out w22_465, out w23_466, out w25_467, out w26_120, out x29_469, out x30_470);
				goto l00000000000018B8;
			}
			word32 * x27_394 = globals->ptr12FC8;
			word32 w1_395 = *x27_394;
			*x27_394 = w1_395 + 0x01;
			*(int64) (int32) w1_395 = 0x50;
			word32 w21_401;
			up32 w22_402;
			word32 w23_403;
			word32 w25_404;
			word64 x29_406;
			word64 x30_407;
			w19_123 = O(w19_123, w18, w20_372, x30_386, x28, out w20_115, out w21_401, out w22_402, out w23_403, out w25_404, out w26_120, out x29_406, out x30_407);
			word32 w0_410 = *x27_394;
			*x27_394 = w0_410 + 0x01;
			*(int64) (int32) w0_410 = 0x59;
			if (w22_402 <= 0x01)
			{
				Z(w20_115);
				goto l00000000000018B8;
			}
			Eq_255 w1_419 = w20_115;
			if (w20_115 > 0x00)
			{
				do
				{
					word32 w0_446 = *x27_394;
					*x27_394 = w0_446 + 0x01;
					*(int64) (int32) w0_446 = (byte) w1_419;
					w1_419 >>= 0x08;
				} while (w1_419 > 0x00);
			}
			if (w21_401 != 0x25)
				goto l00000000000018B8;
			word32 * x28_433 = globals->ptr12FC8;
			word32 w0_435 = *x28_433;
			*x28_433 = w0_435 + 0x01;
			*(int64) (int32) w0_435 = 0x92;
		}
		Eq_2087 NZV_201 = 0x04;
		if (w26_120 != 0x00)
			NZV_201 = cond(w19_123 - 0x08);
		if (NZV_201)
		{
			word32 w0_255 = S(w20_115, w26_120);
			word32 * x4_257 = globals->ptr12FC8;
			word32 w1_263 = *x4_257;
			*x4_257 = w1_263 + 0x01;
			*(int64) (int32) w1_263 = 0xB8;
			*(word64) *x4_257 = w20_115 ^ 0x01;
			word32 w1_271 = *x4_257;
			*x4_257 = w1_271 + 0x05;
			*(int64) (int32) (w1_271 + 0x04) = 233;
			*(word64) *x4_257 = 0x05;
			word32 w2_280 = *x4_257;
			*x4_257 = w2_280 + 0x04;
			word32 w1_281 = w2_280 + 0x04;
			if (w0_255 != 0x00)
			{
				while (true)
				{
					word32 * x3_335 = (int64) (int32) w0_255;
					word32 w2_338 = *x3_335;
					*x3_335 = w1_281 - w0_255 - 0x04;
					w0_255 = w2_338;
					if (w2_338 == 0x00)
						break;
					w1_281 = *x4_257;
				}
				w1_281 = *globals->ptr12FC8;
			}
			word32 * x28_287 = globals->ptr12FC8;
			*x28_287 = w1_281 + 0x01;
			*(int64) (int32) w1_281 = 0xB8;
			struct Eq_2452 * v79_295 = &sp_164->qw0008 + 0x03;
			word32 w21_297;
			*w21Out = (word32) v79_295->qw0000;
			word32 w22_300;
			*w22Out = (word32) v79_295->qw0008;
			word32 w23_303;
			*w23Out = (word32) sp_164->qw0030;
			*(word64) *x28_287 = (union Eq_255 *) w20_115;
			struct Eq_2480 * v81_307 = &sp_164->qw0030 + 0x02;
			struct Eq_2483 * v82_314 = &sp_164->qw0008 + 0x01;
			word32 w25_309;
			*w25Out = (word32) v81_307->qw0000;
			word32 w26_312;
			*w26Out = (word32) v81_307->qw0008;
			Eq_255 w19_316 = (word32) v82_314->qw0000;
			word32 w20_319;
			*w20Out = (word32) v82_314->qw0008;
			*x28_287 += 0x04;
			word64 x29_327;
			*x29Out = sp_164->qw0000;
			word64 x30_329;
			*x30Out = sp_164->qw0008;
			return w19_316;
		}
		else
		{
			struct Eq_2327 * v37_213 = &sp_164->qw0008 + 0x01;
			struct Eq_2330 * v38_219 = &sp_164->qw0008 + 0x03;
			struct Eq_2333 * v40_230 = &sp_164->qw0030 + 0x02;
			word32 w20_218;
			*w20Out = (word32) v37_213->qw0008;
			word32 w21_221;
			*w21Out = (word32) v38_219->qw0000;
			word32 w22_224;
			*w22Out = (word32) v38_219->qw0008;
			word32 w23_227;
			*w23Out = (word32) sp_164->qw0030;
			word32 w25_232;
			*w25Out = (word32) v40_230->qw0000;
			word32 w26_235;
			*w26Out = (word32) v40_230->qw0008;
			word64 x29_241;
			*x29Out = sp_164->qw0000;
			word64 x30_243;
			*x30Out = sp_164->qw0008;
			return (word32) v37_213->qw0000;
		}
	}
}

// 0000000000001AD0: Register Eq_255 T(Register Eq_255 w0, Register ui32 w18, Register Eq_255 w20, Register (ptr64 Eq_104) x30, Stack (ptr64 Eq_104) qwArg00, Register out Eq_2402 w20Out, Register out Eq_2403 w21Out, Register out Eq_2404 w22Out, Register out Eq_2405 w23Out, Register out Eq_2406 w25Out, Register out Eq_2407 w26Out, Register out ptr64 x29Out, Register out ptr64 x30Out, Register out ptr64 spOut)
Eq_255 T(Eq_255 w0, ui32 w18, Eq_255 w20, Eq_104 * x30, Eq_104 * qwArg00, Eq_2402 & w20Out, Eq_2403 & w21Out, Eq_2404 & w22Out, Eq_2405 & w23Out, Eq_2406 & w25Out, Eq_2407 & w26Out, ptr64 & x29Out, ptr64 & x30Out, ptr64 & spOut)
{
	sp = fp;
	sp = (struct Eq_104 **) ((char *) fp - 0x0050);
	qwLoc50 = x29;
	sp = (struct Eq_104 **) ((char *) fp - 0x0048);
	qwLoc48 = x30;
	x29 = (struct Eq_104 *) ((char *) fp - 0x0048);
	v5 = (char *) fp - 0x0018;
	qwLoc18 = x23;
	v5 = (char *) fp - 0x0010;
	qwLoc10 = x24;
	x24 = (struct Eq_104 *) 0x00012000;
	v8 = (char *) fp - 0x0028;
	qwLoc28 = x21;
	v8 = (char *) fp - 0x0020;
	qwLoc20 = x22;
	v11 = (char *) fp - 0x0038;
	qwLoc38 = x19;
	v11 = (char *) fp - 0x0030;
	qwLoc30 = x20;
	x22 = x24->ptr0F50;
	w22 = (word32) x22;
	v14 = (struct Eq_104 **) ((char *) fp - 0x08);
	qwLoc08 = x25;
	v14 = fp;
	qwArg00 = x26;
	w21 = x22->t0000;
	x21 = DPB(x21, w21, 0);
	NZCV = cond(w21 - 0x22);
	Z = (bool) NZCV;
	if (Test(EQ,Z))
	{
		x1 = (struct Eq_104 *) 0x00012000;
		x22 = (struct Eq_104 *) 0x00012000;
		w4.u0 = ~0x47;
		x0 = (struct Eq_104 *) 0x00012000;
		x1 = x1->ptr0FC8;
		x19 = x22->ptr0F60;
		x0 = x0->ptr0F58;
		w2 = x1->t0000;
		x20 = x0;
		w3 = x19->t0000;
		w5 = (word32) w2 + 0x01;
		x2 = (int64) (int32) w2;
		x1->t0000 = w5;
		x2->t0000.u1 = 0xB8;
		v58 = x1->t0000;
		x2 = (word64) v58;
		x2->t0000 = w3;
		w2 = x1->t0000;
		w0 = x0->t0000;
		w2 = (word32) w2 + 0x04;
		NZCV = cond(w0 - 0x22);
		x1->t0000 = w2;
		while (Test(NE,Z))
		{
			NZCV = cond(w0 - 0x5C);
			if (Test(EQ,Z))
				w0 = Y.part.1(w0, x30);
			w0 = x19->t0000;
			w1 = x20->t0000;
			w2 = (word32) w0 + 0x01;
			x0 = (int64) (int32) w0;
			x19->t0000 = w2;
			x0->t0000 = (byte) w1;
			w0 = o(w0, qwArg00, out w3, out x29, out x30, out sp);
			w0 = x20->t0000;
			NZCV = cond(w0 - 0x22);
		}
		x22 = x22->ptr0F60;
		v59 = x22->t0000;
		x0 = (word64) v59;
		x0->t0000.u1 = 0x00;
		w0 = x22->t0000;
		w0 = (word32) w0 + 0x04;
		w0 &= ~0x03;
		x22->t0000 = w0;
		w0 = o(w0, qwArg00, out w3, out x29, out x30, out sp);
		w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
		x0 = x24->ptr0F50;
		w0 = x0->t0000;
		goto l0000000000001DEC;
	}
	else
	{
		x20 = (struct Eq_104 *) 0x00012000;
		w20 = (word32) x20;
		x25 = (struct Eq_104 *) 0x00012000;
		w25 = (word32) x25;
		w23 = w0;
		x23 = DPB(x23, w23, 0);
		x1 = x20->ptr0F98;
		x0 = x25->ptr0F70;
		w26 = x1->t0000;
		x26 = DPB(x26, w26, 0);
		w19 = x0->t0000;
		x19 = DPB(x19, w19, 0);
		w0 = ad(w18, w20, qwLoc48, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
		NZCV = cond(w21 - 0x02);
		Z = (bool) NZCV;
		if (Test(EQ,Z))
		{
			x1 = (struct Eq_104 *) 0x00012000;
			w2.u0 = ~0x47;
			x1 = x1->ptr0FC8;
			w0 = x1->t0000;
			w3 = (word32) w0 + 0x01;
			x0 = (int64) (int32) w0;
			x1->t0000 = w3;
			x0->t0000.u1 = 0xB8;
			v57 = x1->t0000;
			x0 = (word64) v57;
			x0->t0000 = w19;
			w2 = x1->t0000;
			w0 = x22->t0000;
			w2 = (word32) w2.u0 + 0x04;
			NZCV = cond(w0 - 0x28);
			x1->t0000 = w2;
			if (Test(NE,Z))
				goto l0000000000001DF4;
l0000000000001E50:
			x20 = (struct Eq_104 *) 0x00012000;
			w20 = (word32) x20;
			w22.u0 = 0x01;
			x22 = DPB(x22, w22, 0);
			w2.u0 = 0x50;
			x1 = x20->ptr0FC8;
			w0 = x1->t0000;
			w3 = (word32) w0 + 0x01;
			x0 = (int64) (int32) w0;
			x1->t0000 = w3;
			x0->t0000.u1 = 0x50;
l0000000000001BA8:
			x19 = x20->ptr0FC8;
			w2.u0 = ~0x7E;
			w1.u0 = ~0x13;
			w25.u0 = 0x00;
			x25 = DPB(x25, w25, 0);
			w0 = x19->t0000;
			w3 = (word32) w0.u0 + 0x01;
			x0 = (int64) (int32) w0;
			x19->t0000 = w3;
			x0->t0000.u1 = 0x81;
			w0 = x19->t0000;
			w2 = (word32) w0.u0 + 0x01;
			x0 = (int64) (int32) w0;
			x19->t0000 = w2;
			x0->t0000.u1 = ~0x13;
			v34 = x19->t0000;
			x0 = (word64) v34;
			x0->t0000.u0 = 0x00;
			w23 = x19->t0000;
			x23 = DPB(x23, w23, 0);
			w0 = (word32) w23 + 0x04;
			x19->t0000 = w0;
			w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
			x24 = x24->ptr0F50;
			w0 = x24->t0000;
			NZCV = cond(w0 - 0x29);
			Z = (bool) NZCV;
			while (Test(NE,Z))
			{
				w0.u0 = 11;
				w19 = O(w0, w18, w20, x30, qwArg00, out w20, out w21, out w22, out w23, out w25, out w26, out x29, out x30);
				x19 = DPB(x19, w19, 0);
				w1.u0 = 33929;
				w2.u0 = 0x03;
				x2 = DPB(x2, w2, 0);
				w1.u0 = 2393225;
				x1 = DPB(x1, w1, 0);
				do
				{
					w0 = x19->t0000;
					--w2;
					x2 = DPB(x2, w2, 0);
					NZCV = cond(w2);
					Z = (bool) NZCV;
					w3 = (word32) w0.u0 + 0x01;
					x0 = (int64) (int32) w0;
					x19->t0000 = w3;
					x0->t0000 = (byte) w1;
					w1 >>= 0x08;
					x1 = DPB(x1, w1, 0);
				} while (Test(NE,Z));
				v35 = x19->t0000;
				x0 = (word64) v35;
				x0->t0000 = w25;
				w0 = x19->t0000;
				w1 = x24->t0000;
				x1 = DPB(x1, w1, 0);
				w0 = (word32) w0.u0 + 0x04;
				NZCV = cond(w1 - 44);
				Z = (bool) NZCV;
				x19->t0000 = w0;
				if (Test(EQ,Z))
				{
					w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
					w1 = x24->t0000;
					x1 = DPB(x1, w1, 0);
				}
				NZCV = cond(w1 - 0x29);
				Z = (bool) NZCV;
				w25 = (word32) w25.u0 + 0x04;
				x25 = DPB(x25, w25, 0);
			}
			x23 = (int64) (int32) w23;
			w23 = (word32) x23;
			x23->t0000 = w25;
			w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
			if (w22 == 0x00)
			{
				x0 = x20->ptr0FC8;
				w1 = (word32) w21 + 0x04;
				w4.u0 = ~0x17;
				x1 = (int64) (int32) w1;
				w2 = x0->t0000;
				w3 = x1->t0000;
				w5 = (word32) w2.u0 + 0x01;
				x2 = (int64) (int32) w2;
				x0->t0000 = w5;
				x2->t0000.u1 = 232;
				v39 = x0->t0000;
				x2 = (word64) v39;
				x2->t0000 = w3;
				w2 = x0->t0000;
				w3 = (word32) w2.u0 + 0x04;
				x0->t0000 = w3;
				x1->t0000 = w2;
			}
			else
			{
				NZCV = cond(w22 - 0x01);
				Z = (bool) NZCV;
				if (Test(EQ,Z))
				{
					x3 = x20->ptr0FC8;
					w3 = (word32) x3;
					w1.u0 = 0x94FF;
					w2.u0 = 0x03;
					x2 = DPB(x2, w2, 0);
					w1.u0 = 0x002494FF;
					x1 = DPB(x1, w1, 0);
					do
					{
						w0 = x3->t0000;
						--w2;
						x2 = DPB(x2, w2, 0);
						NZCV = cond(w2);
						Z = (bool) NZCV;
						w4 = (word32) w0 + 0x01;
						x0 = (int64) (int32) w0;
						x3->t0000 = w4;
						x0->t0000 = (byte) w1;
						w1 >>= 0x08;
						x1 = DPB(x1, w1, 0);
					} while (Test(NE,Z));
					v53 = x3->t0000;
					x0 = (word64) v53;
					x0->t0000 = w25;
					w25 = (word32) w25 + 0x04;
					x25 = DPB(x25, w25, 0);
					w0 = x3->t0000;
					w0 = (word32) w0 + 0x04;
					x0 = DPB(x0, w0, 0);
l0000000000001CC4:
					x20 = x20->ptr0FC8;
					x2 = (int64) (int32) w0;
					w3.u0 = ~0x7E;
					w0 = (word32) w0 + 0x01;
					w1.u0 = ~0x3B;
					x20->t0000 = w0;
					x2->t0000.u1 = 0x81;
					w0 = x20->t0000;
					w2 = (word32) w0 + 0x01;
					x0 = (int64) (int32) w0;
					x20->t0000 = w2;
					x0->t0000.u1 = 0xC4;
					v40 = x20->t0000;
					x0 = (word64) v40;
					v41 = (struct Eq_104 **) ((char *) sp + 0x0020);
					x21 = (struct Eq_104 *) *v41;
					w21 = (word32) x21;
					v41 = (struct Eq_104 **) ((char *) v41 + 0x08);
					x22 = (struct Eq_104 *) *v41;
					w22 = (word32) x22;
					v42 = (struct Eq_104 **) ((char *) sp + 0x0030);
					x23 = (struct Eq_104 *) *v42;
					w23 = (word32) x23;
					v42 = (struct Eq_104 **) ((char *) v42 + 0x08);
					x24 = (struct Eq_104 *) *v42;
					x0->t0000 = w25;
					v43 = (struct Eq_104 **) ((char *) sp + 0x0040);
					x25 = (struct Eq_104 *) *v43;
					w25 = (word32) x25;
					v43 = (struct Eq_104 **) ((char *) v43 + 0x08);
					x26 = (struct Eq_104 *) *v43;
					w26 = (word32) x26;
					w0 = x20->t0000;
					w0 = (word32) w0 + 0x04;
					x20->t0000 = w0;
					w0.u0 = 0x00;
					v44 = (struct Eq_104 **) ((char *) sp + 0x0010);
					x19 = (struct Eq_104 *) *v44;
					w19 = (word32) x19;
					v44 = (struct Eq_104 **) ((char *) v44 + 0x08);
					x20 = (struct Eq_104 *) *v44;
					w20 = (word32) x20;
					v45 = sp;
					x29 = (struct Eq_104 *) *v45;
					v45 = (struct Eq_104 **) ((char *) v45 + 0x08);
					x30 = (struct Eq_104 *) *v45;
					sp = (struct Eq_104 **) ((char *) sp + 0x0050);
					return w19;
				}
				x1 = x20->ptr0FC8;
				w3.u0 = ~0x17;
				w2 = x1->t0000;
				w4 = (word32) w2 + 0x01;
				w0 = w22 - w2;
				x2 = (int64) (int32) w2;
				x1->t0000 = w4;
				w0 -= 0x05;
				x2->t0000.u1 = 232;
				v51 = x1->t0000;
				x2 = (word64) v51;
				x2->t0000 = w0;
				w0 = x1->t0000;
				w0 = (word32) w0.u0 + 0x04;
				x1->t0000 = w0;
			}
			if (w25 != 0x00)
			{
				x0 = x20->ptr0FC8;
				w0 = x0->t0000;
				x0 = DPB(x0, w0, 0);
				goto l0000000000001CC4;
			}
l0000000000001DF4:
			w0.u0 = 0x00;
			v46 = (struct Eq_104 **) ((char *) sp + 0x0010);
			x19 = (struct Eq_104 *) *v46;
			w19 = (word32) x19;
			v46 = (struct Eq_104 **) ((char *) v46 + 0x08);
			x20 = (struct Eq_104 *) *v46;
			w20 = (word32) x20;
			v47 = (struct Eq_104 **) ((char *) sp + 0x0020);
			x21 = (struct Eq_104 *) *v47;
			w21 = (word32) x21;
			v47 = (struct Eq_104 **) ((char *) v47 + 0x08);
			x22 = (struct Eq_104 *) *v47;
			w22 = (word32) x22;
			v48 = (struct Eq_104 **) ((char *) sp + 0x0030);
			x23 = (struct Eq_104 *) *v48;
			w23 = (word32) x23;
			v48 = (struct Eq_104 **) ((char *) v48 + 0x08);
			x24 = (struct Eq_104 *) *v48;
			v49 = (struct Eq_104 **) ((char *) sp + 0x0040);
			x25 = (struct Eq_104 *) *v49;
			w25 = (word32) x25;
			v49 = (struct Eq_104 **) ((char *) v49 + 0x08);
			x26 = (struct Eq_104 *) *v49;
			w26 = (word32) x26;
			v50 = sp;
			x29 = (struct Eq_104 *) *v50;
			v50 = (struct Eq_104 **) ((char *) v50 + 0x08);
			x30 = (struct Eq_104 *) *v50;
			sp = (struct Eq_104 **) ((char *) sp + 0x0050);
			return w19;
		}
		NZCV = cond(w26 - 0x02);
		Z = (bool) NZCV;
		if (Test(NE,Z))
		{
			NZCV = cond(w21 - 0x28);
			Z = (bool) NZCV;
			if (Test(EQ,Z))
			{
				w0.u0 = 11;
				w19 = O(w0, w18, w20, x30, qwArg00, out w20, out w21, out w22, out w23, out w25, out w26, out x29, out x30);
				w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
				w0 = x22->t0000;
				goto l0000000000001DEC;
			}
			NZCV = cond(w21 - 0x2A);
			Z = (bool) NZCV;
			if (Test(NE,Z))
			{
				NZCV = cond(w21 - 0x26);
				Z = (bool) NZCV;
				if (Test(NE,Z))
				{
					x0 = (int64) (int32) w21;
					w22 = x0->t0000;
					x22 = DPB(x22, w22, 0);
					if (w22 == 0x00)
					{
						x1 = (struct Eq_104 *) 0x00012000;
						w0.u0 = 0x00;
						x1 = x1->ptr0FA8;
						w1 = x1->t0000;
						fn0000000000000C80();
						w22.u0 = 0x00;
						x22 = DPB(x22, w22, 0);
					}
					x0 = x24->ptr0F50;
					w0 = x0->t0000;
					x0 = DPB(x0, w0, 0);
					NZCV = cond(w0 - 0x3D);
					Z = (bool) NZCV;
					w1 = (word32) Test(EQ,Z);
					NZ = cond(w1 & w23);
					Z = (bool) NZ;
					C = false;
					V = false;
					if (Test(EQ,Z))
					{
						NZCV = cond(w0 - 0x28);
						Z = (bool) NZCV;
						if (Test(EQ,Z))
							goto l0000000000001B9C;
						w1 = w22;
						w0.u0 = 0x08;
						N(w0, w1);
						x20 = x20->ptr0F98;
						w20 = (word32) x20;
						w0 = x20->t0000;
						NZCV = cond(w0 - 11);
						Z = (bool) NZCV;
						if (Test(EQ,Z))
						{
							w1 = w22;
							w0.u0 = 0x00;
							x20 = (struct Eq_104 *) 0x00012000;
							N(w0, w1);
							x25 = x25->ptr0F70;
							w25 = (word32) x25;
							x20 = x20->ptr0FC8;
							w20 = (word32) x20;
							w1 = x25->t0000;
							x1 = DPB(x1, w1, 0);
							w0 = (word32) w1.u0 + 0x01;
							NZCV = cond(w0 - 0x01);
							ZC = NZCV;
							while (Test(UGT,ZC))
							{
								w0 = x20->t0000;
								w2 = (word32) w0 + 0x01;
								x0 = (int64) (int32) w0;
								x20->t0000 = w2;
								x0->t0000 = (byte) w1;
								w1 >>= 0x08;
								x1 = DPB(x1, w1, 0);
								w0 = (word32) w1.u0 + 0x01;
								NZCV = cond(w0 - 0x01);
								ZC = NZCV;
							}
							w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
						}
					}
					else
					{
						w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
						w0.u0 = 11;
						w19 = O(w0, w18, w20, x30, qwArg00, out w20, out w21, out w22, out w23, out w25, out w26, out x29, out x30);
						x19 = DPB(x19, w19, 0);
						w1 = w22;
						w0.u0 = 0x06;
						N(w0, w1);
					}
					x0 = x24->ptr0F50;
					w0 = x0->t0000;
					NZCV = cond(w0 - 0x28);
					Z = (bool) NZCV;
					if (Test(NE,Z))
						goto l0000000000001DF4;
l0000000000001B9C:
					NZCV = cond(w22 - 0x01);
					Z = (bool) NZCV;
					if (Test(NE,Z))
					{
						x20 = (struct Eq_104 *) 0x00012000;
						w20 = (word32) x20;
						goto l0000000000001BA8;
					}
					goto l0000000000001E50;
				}
				v55 = x22->t0000;
				x1 = (word64) v55;
				w0.u0 = 0x0A;
				w1 = x1->t0000;
				N(w0, w1);
				w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
				w0 = x22->t0000;
				x0 = DPB(x0, w0, 0);
l0000000000001DEC:
				NZCV = cond(w0 - 0x28);
				Z = (bool) NZCV;
				if (Test(NE,Z))
					goto l0000000000001DF4;
				goto l0000000000001E50;
			}
			w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
			w21 = x22->t0000;
			x21 = DPB(x21, w21, 0);
			w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
			w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
			w0 = x22->t0000;
			NZCV = cond(w0 - 0x2A);
			Z = (bool) NZCV;
			if (Test(NE,Z))
			{
				w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
				w0.u0 = 0x00;
				w19 = T(w0, w18, w20, x30, qwArg00, out w20, out w21, out w22, out w23, out w25, out w26, out x29, out x30, out sp);
				w0 = *x22;
				NZCV = cond(w0 - 0x3D);
				if (Test(NE,Z))
				{
					if (w21 != 0x00)
					{
						NZCV = cond(w21 - 0x0100);
						x20 = (struct Eq_3831 *) 0x00012000;
						if (Test(NE,Z))
						{
							x1 = x20->ptr0FC8;
							w3.u0 = 0x0F;
							w2 = ~0x41;
							w0 = x1->t0000;
							w4 = (word32) w0 + 0x01;
							x0 = (int64) (int32) w0;
							x1->t0000 = w4;
							*x0 = (union Eq_255 *) 0x0F;
						}
						else
						{
							w2.u0 = ~0x74;
							x1 = x20->ptr0FC8;
						}
						w0 = x1->t0000;
						x20 = x20->ptr0FC8;
						w3 = (word32) w0 + 0x01;
						x0 = (int64) (int32) w0;
						x1->t0000 = w3;
						*x0 = (union Eq_255 *) (byte) w2;
						x0 = x24->ptr0F50;
						w1 = x20->t0000;
						w1 = (word32) w1 + 0x01;
						w0 = *x0;
						x20->t0000 = w1;
					}
					goto l0000000000001DEC;
				}
			}
			else
			{
				w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
				w21.u0 = 0x00;
				w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
				w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
				w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
				w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
				w0.u0 = 0x00;
				w19 = T(w0, w18, w20, x30, qwArg00, out w20, out w21, out w22, out w23, out w25, out w26, out x29, out x30, out sp);
				w0 = x22->t0000;
				NZCV = cond(w0 - 0x3D);
				if (Test(NE,Z))
					goto l0000000000001DEC;
			}
			x20 = (struct Eq_104 *) 0x00012000;
			w0 = ad(w18, w20, qwArg00, out x19, out x20, out x21, out x22, out x23, out x24, out x25, out x26, out x27, out x29, out x30, out sp);
			w2.u0 = 0x50;
			w0.u0 = 11;
			x20 = x20->ptr0FC8;
			w1 = x20->t0000;
			w3 = (word32) w1.u0 + 0x01;
			x1 = (int64) (int32) w1;
			x20->t0000 = w3;
			x1->t0000.u1 = 0x50;
			w19 = O(w0, w18, w20, x30, qwArg00, out w20, out w21, out w22, out w23, out w25, out w26, out x29, out x30);
			w1 = x20->t0000;
			NZCV = cond(w21 - 0x0100);
			w3.u0 = 0x59;
			w0 = (word32) Test(EQ,Z);
			w2 = (word32) w1.u0 + 0x01;
			w0 = (word32) w0.u0 + 0x0188;
			x1 = (int64) (int32) w1;
			x20->t0000 = w2;
			x2 = x20;
			x1->t0000.u1 = 0x59;
			do
			{
				w1 = x2->t0000;
				w3 = (word32) w1.u0 + 0x01;
				x1 = (int64) (int32) w1;
				x2->t0000 = w3;
				x1->t0000 = (byte) w0;
				w0 >>= 0x08;
				NZCV = cond(w0 - 0x01);
			} while (Test(EQ,Z));
		}
		else
		{
			x20 = (struct Eq_104 *) 0x00012000;
			w0.u0 = 0x00;
			w19 = T(w0, w18, w20, x30, qwArg00, out w20, out w21, out w22, out w23, out w25, out w26, out x29, out x30, out sp);
			x1 = x20->ptr0FC8;
			w2.u0 = ~0x46;
			NZCV = cond(w21 - 33);
			w0 = x1->t0000;
			w3 = (word32) w0.u0 + 0x01;
			x0 = (int64) (int32) w0;
			x1->t0000 = w3;
			x0->t0000.u1 = ~0x46;
			v56 = x1->t0000;
			x0 = (word64) v56;
			x0->t0000.u0 = 0x00;
			w0 = x1->t0000;
			w0 = (word32) w0.u0 + 0x04;
			x1->t0000 = w0;
			if (Test(EQ,Z))
			{
				w0 = w19;
				Z(w0);
				w0 = x22->t0000;
				goto l0000000000001DEC;
			}
			w2 = (word32) w19.u0 + 0x01;
			NZCV = cond(w2 - 0x01);
			if (Test(ULE,ZC))
			{
				w0 = x22->t0000;
				goto l0000000000001DEC;
			}
			while (true)
			{
				x2 = (int64) (int32) w0;
				w0 = (word32) w0 + 0x01;
				x1->t0000 = w0;
				x2->t0000 = (byte) w19;
				w19 >>= 0x08;
				w0 = (word32) w19.u0 + 0x01;
				NZCV = cond(w0 - 0x01);
				if (Test(ULE,ZC))
					break;
				w0 = x1->t0000;
			}
		}
		x0 = x24->ptr0F50;
		w0 = x0->t0000;
		goto l0000000000001DEC;
	}
}

// 00000000000021B0: void w(Register ui32 w18, Register Eq_255 w20, Register (ptr64 Eq_104) x30)
void w(ui32 w18, Eq_255 w20, Eq_104 * x30)
{
	word32 w20_7;
	word32 w21_8;
	word32 w22_9;
	word32 w23_10;
	word32 w25_11;
	word32 w26_12;
	word64 x29_13;
	word64 x30_14;
	O(11, w18, w20, x30, qwArg00, out w20_7, out w21_8, out w22_9, out w23_10, out w25_11, out w26_12, out x29_13, out x30_14);
}

// 00000000000021B8: void U(Register ui32 w18, Register Eq_255 w20, Register (ptr64 Eq_104) x30)
void U(ui32 w18, Eq_255 w20, Eq_104 * x30)
{
	word32 w20_12;
	word32 w21_13;
	word32 w22_14;
	word32 w23_15;
	word32 w25_16;
	word32 w26_17;
	word64 x29_18;
	word64 x30_19;
	O(11, w18, w20, x30, x30, out w20_12, out w21_13, out w22_14, out w23_15, out w25_16, out w26_17, out x29_18, out x30_19);
	S(0x00, 0x00);
}

// 00000000000021D8: Register word64 ab(Register word32 w0, Register ui32 w18, Register Eq_255 w20, Register out ptr64 x21Out, Register out Eq_323 w22Out, Register out Eq_324 w24Out, Register out Eq_325 w27Out)
word64 ab(word32 w0, ui32 w18, Eq_255 w20, ptr64 & x21Out, Eq_323 & w22Out, Eq_324 & w24Out, Eq_325 & w27Out)
{
	ptr64 sp_5 = fp + -88;
	struct Eq_4095 * x20_161 = (struct Eq_4095 *) 0x00012000;
	Eq_255 w20_162 = (word32) 0x00012000;
	word32 w22_166 = w0;
	ui32 w24_169 = (word32) (w0 == 0x00);
	union Eq_255 * x23_41 = globals->ptr12F50;
l0000000000002210:
	Eq_255 w1_153 = *x23_41;
	struct Eq_4111 * sp_113 = DPB(sp_5, (word32) w1_153 + 0x01, 0);
	bool Z_157 = (bool) cond(w1_153 - 0x0100);
	while (((word32) (w1_153 == 0x0100) | w24_169 & (word32) (w1_153 != 0x01)) != 0x00)
	{
		if (Z_157)
		{
			struct Eq_4141 * x19_421;
			word64 x22_424;
			word64 x23_425;
			word64 x24_426;
			word64 x25_427;
			word64 x26_428;
			word64 x27_429;
			word64 x29_430;
			word64 x30_431;
			word64 sp_432;
			struct Eq_4151 * x20_422;
			word32 * x21_423;
			ad(w18, w20_162, qwArg00, out x19_421, out x20_422, out x21_423, out x22_424, out x23_425, out x24_426, out x25_427, out x26_428, out x27_429, out x29_430, out x30_431, out sp_432);
			union Eq_255 * x19_434 = x19_421->ptr0FA0;
			while (true)
			{
				word32 w0_454 = *x20_422->ptr0F50;
				do
				{
					word32 * x1_472 = (int64) (int32) w0_454;
					if (w0_454 == 0x3B)
					{
						word64 x19_540;
						word64 x21_542;
						word64 x22_543;
						word64 x24_545;
						word64 x25_546;
						word64 x26_547;
						word64 x27_548;
						word64 x29_549;
						word64 x30_550;
						ad(w18, w20_162, qwArg00, out x19_540, out x20_161, out x21_542, out x22_543, out x23_41, out x24_545, out x25_546, out x26_547, out x27_548, out x29_549, out x30_550, out sp_5);
						goto l0000000000002210;
					}
					if (w22_166 == 0x00)
					{
						*x1_472 = *x21_423;
						*x21_423 += 0x04;
						struct Eq_4695 * x20_500;
						word64 x22_502;
						word64 x23_503;
						word64 x24_504;
						word64 x25_505;
						word64 x26_506;
						word64 x27_507;
						word64 x29_508;
						word64 x30_509;
						word64 sp_510;
						ad(w18, w20_162, qwArg00, out x19_434, out x20_500, out x21_423, out x22_502, out x23_503, out x24_504, out x25_505, out x26_506, out x27_507, out x29_508, out x30_509, out sp_510);
						w0_454 = *x20_500->ptr0F50;
						if (w0_454 == 44)
							break;
						continue;
					}
					Eq_255 w1_517 = *x19_434;
					*x19_434 = (union Eq_255 *) ((word32) w1_517 + 0x04);
					*x1_472 = ~0x03 - w1_517;
					struct Eq_4649 * x20_523;
					word64 x22_525;
					word64 x23_526;
					word64 x24_527;
					word64 x25_528;
					word64 x26_529;
					word64 x27_530;
					word64 x29_531;
					word64 x30_532;
					word64 sp_533;
					ad(w18, w20_162, qwArg00, out x19_434, out x20_523, out x21_423, out x22_525, out x23_526, out x24_527, out x25_528, out x26_529, out x27_530, out x29_531, out x30_532, out sp_533);
					w0_454 = *x20_523->ptr0F50;
				} while (w0_454 != 44);
				word64 x22_484;
				word64 x23_485;
				word64 x24_486;
				word64 x25_487;
				word64 x26_488;
				word64 x27_489;
				word64 x29_490;
				word64 x30_491;
				word64 sp_492;
				ad(w18, w20_162, qwArg00, out x19_434, out x20_422, out x21_423, out x22_484, out x23_485, out x24_486, out x25_487, out x26_488, out x27_489, out x29_490, out x30_491, out sp_492);
			}
		}
		word32 w0_180 = *(int64) (int32) ((word32) w1_153 + 0x04);
		if (w0_180 != 0x00)
		{
			word32 * x3_406 = globals->ptr12FC8;
			do
			{
				word32 * x2_410 = (int64) (int32) w0_180;
				w0_180 = *x2_410;
				*x2_410 = *x3_406 - w0_180 - 0x04;
			} while (w0_180 != 0x00);
			w1_153 = x20_161->ptr0F50->t0000;
		}
		*(int64) (int32) w1_153 = *globals->ptr12FC8;
		word64 x19_194;
		word64 x20_195;
		word64 x21_196;
		word64 x22_197;
		word64 x23_198;
		word64 x24_199;
		word64 x25_200;
		word64 x26_201;
		word64 x27_202;
		word64 x29_203;
		word64 x30_204;
		word64 sp_205;
		ad(w18, w20_162, qwArg00, out x19_194, out x20_195, out x21_196, out x22_197, out x23_198, out x24_199, out x25_200, out x26_201, out x27_202, out x29_203, out x30_204, out sp_205);
		word64 x19_207;
		struct Eq_4222 * x20_208;
		word64 x21_209;
		word64 x22_210;
		word64 x23_211;
		word64 x24_212;
		word64 x25_213;
		word64 x26_214;
		word64 x27_215;
		word64 x29_216;
		word64 x30_217;
		word64 sp_218;
		ad(w18, w20_162, qwArg00, out x19_207, out x20_208, out x21_209, out x22_210, out x23_211, out x24_212, out x25_213, out x26_214, out x27_215, out x29_216, out x30_217, out sp_218);
		word32 w25_188 = 0x08;
		word32 w0_222 = *x20_208->ptr0F50;
l0000000000002298:
		word32 * x1_241 = (int64) (int32) w0_222;
		if (w0_222 != 0x29)
		{
			do
			{
				*x1_241 = w25_188;
				word64 x19_371;
				word64 x20_372;
				word64 x21_373;
				word64 x22_374;
				word64 x23_375;
				word64 x24_376;
				word64 x25_377;
				word32 * x26_378;
				word64 x27_379;
				word64 x29_380;
				word64 x30_381;
				word64 sp_382;
				ad(w18, w20_162, qwArg00, out x19_371, out x20_372, out x21_373, out x22_374, out x23_375, out x24_376, out x25_377, out x26_378, out x27_379, out x29_380, out x30_381, out sp_382);
				w25_188 += 0x04;
				w0_222 = *x26_378;
				if (w0_222 != 44)
					goto l0000000000002298;
				word64 x19_388;
				word64 x20_389;
				word64 x21_390;
				word64 x22_391;
				word64 x23_392;
				word64 x24_393;
				word64 x25_394;
				word32 * x26_395;
				word64 x27_396;
				word64 x29_397;
				word64 x30_398;
				word64 sp_399;
				ad(w18, w20_162, qwArg00, out x19_388, out x20_389, out x21_390, out x22_391, out x23_392, out x24_393, out x25_394, out x26_395, out x27_396, out x29_397, out x30_398, out sp_399);
				word32 w0_401 = *x26_395;
				x1_241 = (int64) (int32) w0_401;
			} while (w0_401 != 0x29);
		}
		struct Eq_4284 * x19_248;
		word64 x20_249;
		word64 x21_250;
		word64 x22_251;
		union Eq_255 * x23_252;
		word64 x24_253;
		struct Eq_4290 * x25_254;
		struct Eq_4291 * x26_255;
		word64 x27_256;
		word64 x29_257;
		struct Eq_104 * x30_258;
		word64 sp_259;
		ad(w18, w20_162, qwArg00, out x19_248, out x20_249, out x21_250, out x22_251, out x23_252, out x24_253, out x25_254, out x26_255, out x27_256, out x29_257, out x30_258, out sp_259);
		word32 * x1_261 = x19_248->ptr0FC8;
		word32 * x0_267 = x26_255->ptr0FB0;
		*x25_254->ptr0FA0 = 0x00;
		*x0_267 = 0x00;
		word32 w3_265;
		int32 w2_268 = 0x00E58955;
		for (w3_265 = 0x03; w3_265 != 0x00; --w3_265)
		{
			word32 w0_276 = *x1_261;
			*x1_261 = w0_276 + 0x01;
			*(int64) (int32) w0_276 = (byte) w2_268;
			w2_268 >>= 0x08;
		}
		word32 w2_287 = *x1_261;
		*x1_261 = w2_287 + 0x01;
		*(int64) (int32) w2_287 = 0x81;
		word32 w2_295 = *x1_261;
		*x1_261 = w2_295 + 0x01;
		*(int64) (int32) w2_295 = ~0x13;
		*(word64) *x1_261 = 0x00;
		*x1_261 += 0x04;
		word32 w21_307;
		struct Eq_4476 * x25_310;
		struct Eq_4477 * x26_311;
		word32 w27_312;
		word64 x29_313;
		word64 x30_314;
		word64 sp_315;
		w20_162 = I(0x00, w18, w20_162, x30_258, out w21_307, out w22_166, out w24_169, out x25_310, out x26_311, out w27_312, out x29_313, out x30_314, out sp_315);
		x20_161 = DPB(x20_249, w20_162, 0);
		word32 * x3_319 = x19_248->ptr0FC8;
		word32 w0_321 = *x26_311->ptr0FB0;
		while (w0_321 != 0x00)
		{
			word32 * x2_356 = (int64) (int32) w0_321;
			w0_321 = *x2_356;
			*x2_356 = *x3_319 - w0_321 - 0x04;
		}
		word32 * x19_324 = x19_248->ptr0FC8;
		word32 w0_330 = *x19_324;
		word32 * x25_327 = x25_310->ptr0FA0;
		*x19_324 = w0_330 + 0x01;
		*(int64) (int32) w0_330 = 0xC9;
		word32 w0_335 = *x19_324;
		*x19_324 = w0_335 + 0x01;
		*(int64) (int32) w0_335 = 0xC3;
		*(int64) (int32) w27_312 = *x25_327;
		w1_153 = *x23_252;
		sp_113 = DPB(sp_315, (word32) w1_153 + 0x01, 0);
		Z_157 = (bool) cond(w1_153 - 0x0100);
	}
	struct Eq_4110 * v30_119 = &sp_113->qw0018 + 0x01;
	word64 x21_120;
	*x21Out = v30_119->qw0000;
	word32 w22_124;
	*w22Out = (word32) v30_119->qw0008;
	word32 w24_129;
	*w24Out = (word32) sp_113->qw0038;
	word32 w27_135;
	*w27Out = (word32) sp_113->qw0050;
	return sp_113->qw0018;
}

// 00000000000024B0: Register Eq_255 I(Register word32 w0, Register ui32 w18, Register Eq_255 w20, Register (ptr64 Eq_104) x30, Register out Eq_4488 w21Out, Register out Eq_4489 w22Out, Register out Eq_4490 w24Out, Register out ptr64 x25Out, Register out ptr64 x26Out, Register out Eq_4493 w27Out, Register out ptr64 x29Out, Register out ptr64 x30Out, Register out (ptr64 Eq_4496) spOut)
Eq_255 I(word32 w0, ui32 w18, Eq_255 w20, Eq_104 * x30, Eq_4488 & w21Out, Eq_4489 & w22Out, Eq_4490 & w24Out, ptr64 & x25Out, ptr64 & x26Out, Eq_4493 & w27Out, ptr64 & x29Out, ptr64 & x30Out, Eq_4496 * & spOut)
{
	*w27Out = w27;
	struct Eq_4777 * sp_103;
	Eq_255 w20_150 = (word32) 0x00012000;
	word32 w19_35 = *globals->ptr12F50;
	if (w19_35 != 288)
	{
		bool Z_130 = true;
		if (w19_35 != 0x0160)
			Z_130 = (bool) cond(w19_35 - 0x01F8);
		if (!Z_130)
		{
			if (w19_35 != 0x7B)
			{
				if (w19_35 != 448)
				{
					if (w19_35 != 400)
					{
						if (w19_35 != 0x3B)
						{
							word32 w21_192;
							word32 w22_193;
							word32 w23_194;
							word32 w25_195;
							word32 w26_196;
							word64 x29_197;
							word64 x30_198;
							O(11, w18, w20_150, x30, x30, out w20_150, out w21_192, out w22_193, out w23_194, out w25_195, out w26_196, out x29_197, out x30_198);
						}
					}
					else
					{
						word64 x19_200;
						word64 x20_201;
						word64 x21_202;
						word32 * x22_203;
						word64 x23_204;
						word64 x24_205;
						word64 x25_206;
						word64 x26_207;
						word64 x27_208;
						word64 x29_209;
						word64 x30_210;
						word64 sp_211;
						ad(w18, w20_150, x30, out x19_200, out x20_201, out x21_202, out x22_203, out x23_204, out x24_205, out x25_206, out x26_207, out x27_208, out x29_209, out x30_210, out sp_211);
						word32 * x0_216 = globals->ptr12FC8;
						word32 w1_217 = *x0_216;
						word32 w2_215 = *x22_203;
						*x0_216 = w1_217 + 0x01;
						*(int64) (int32) w1_217 = 233;
						*(word64) *x0_216 = w2_215;
						word32 w1_225 = *x0_216;
						*x0_216 = w1_225 + 0x04;
						*x22_203 = w1_225;
					}
				}
				else
				{
					word64 x19_229;
					word64 x20_230;
					word32 * x21_231;
					word64 x22_232;
					word64 x23_233;
					word64 x24_234;
					word64 x25_235;
					word64 x26_236;
					word64 x27_237;
					word64 x29_238;
					struct Eq_104 * x30_239;
					word64 sp_240;
					ad(w18, w20_150, x30, out x19_229, out x20_230, out x21_231, out x22_232, out x23_233, out x24_234, out x25_235, out x26_236, out x27_237, out x29_238, out x30_239, out sp_240);
					if (*x21_231 != 0x3B)
					{
						word32 w21_275;
						word32 w22_276;
						word32 w23_277;
						word32 w25_278;
						word32 w26_279;
						word64 x29_280;
						word64 x30_281;
						O(11, w18, w20_150, x30_239, qwArg00, out w20_150, out w21_275, out w22_276, out w23_277, out w25_278, out w26_279, out x29_280, out x30_281);
					}
					word32 * x0_258 = globals->ptr12FC8;
					word32 * x1_259 = globals->ptr12FB0;
					word32 w2_260 = *x0_258;
					word32 w3_261 = *x1_259;
					*x0_258 = w2_260 + 0x01;
					*(int64) (int32) w2_260 = 233;
					*(word64) *x0_258 = w3_261;
					word32 w2_269 = *x0_258;
					*x1_259 = w2_269;
					*x0_258 = w2_269 + 0x04;
				}
			}
			else
			{
				word64 x19_283;
				word64 x20_284;
				word32 * x21_285;
				word64 x22_286;
				word64 x23_287;
				word64 x24_288;
				word64 x25_289;
				word64 x26_290;
				word64 x27_291;
				word64 x29_292;
				word64 sp_294;
				struct Eq_104 * x30_293;
				ad(w18, w20_150, x30, out x19_283, out x20_284, out x21_285, out x22_286, out x23_287, out x24_288, out x25_289, out x26_290, out x27_291, out x29_292, out x30_293, out sp_294);
				word32 * x21_298;
				word32 w24_300;
				word32 w27_301;
				word32 w22_299;
				w20_150 = (word32) ab(0x01, w18, w20_150, out x21_298, out w22_299, out w24_300, out w27_301);
				if (*x21_298 != 0x7D)
				{
					do
					{
						word32 w21_312;
						word32 w24_314;
						word64 x25_315;
						word64 x26_316;
						word32 w27_317;
						word64 x29_318;
						word64 sp_320;
						w20_150 = I(w22_299, w18, w20_150, x30_293, out w21_312, out w22_299, out w24_314, out x25_315, out x26_316, out w27_317, out x29_318, out x30_293, out sp_320);
					} while (*x21_285 != 0x7D);
				}
			}
			word64 x19_156;
			word64 x20_157;
			word64 x21_158;
			word64 x22_159;
			word64 x23_160;
			word64 x24_161;
			word64 x25_162;
			word64 x26_163;
			word64 x27_164;
			word64 x29_165;
			word64 x30_166;
			ad(w18, w20_150, qwArg00, out x19_156, out x20_157, out x21_158, out x22_159, out x23_160, out x24_161, out x25_162, out x26_163, out x27_164, out x29_165, out x30_166, out sp_103);
		}
		else
		{
			Eq_255 w20_362;
			word64 x19_326;
			word64 x20_327;
			word64 x21_328;
			word64 x22_329;
			word64 x23_330;
			word64 x24_331;
			word64 x25_332;
			word64 x26_333;
			word64 x27_334;
			word64 x29_335;
			word64 x30_336;
			word64 sp_337;
			ad(w18, w20_150, x30, out x19_326, out x20_327, out x21_328, out x22_329, out x23_330, out x24_331, out x25_332, out x26_333, out x27_334, out x29_335, out x30_336, out sp_337);
			word64 x19_339;
			word64 x20_340;
			word32 * x21_341;
			word64 x22_342;
			word64 x23_343;
			word64 x24_344;
			word64 x25_345;
			word64 x26_346;
			word64 x27_347;
			word64 x29_348;
			struct Eq_104 * x30_349;
			word64 sp_350;
			ad(w18, w20_150, qwArg00, out x19_339, out x20_340, out x21_341, out x22_342, out x23_343, out x24_344, out x25_345, out x26_346, out x27_347, out x29_348, out x30_349, out sp_350);
			if (w19_35 != 0x0160)
			{
				if (*x21_341 != 0x3B)
				{
					word32 w21_569;
					word32 w22_570;
					word32 w23_571;
					word32 w25_572;
					word32 w26_573;
					word64 x29_574;
					word64 x30_575;
					O(11, w18, w20_150, x30_349, qwArg00, out w20_150, out w21_569, out w22_570, out w23_571, out w25_572, out w26_573, out x29_574, out x30_575);
				}
				word64 x19_452;
				struct Eq_5471 * x20_453;
				word64 x21_454;
				word64 x22_455;
				word64 x23_456;
				word64 x24_457;
				word64 x25_458;
				word64 x26_459;
				word64 x27_460;
				struct Eq_5479 * x29_461;
				struct Eq_104 * x30_462;
				word64 sp_463;
				ad(w18, w20_150, qwArg00, out x19_452, out x20_453, out x21_454, out x22_455, out x23_456, out x24_457, out x25_458, out x26_459, out x27_460, out x29_461, out x30_462, out sp_463);
				word32 * x0_466 = x20_453->ptr0F50;
				x29_461->dw004C = 0x00;
				if (*x0_466 != 0x3B)
				{
					word32 w21_555;
					word32 w22_556;
					word32 w23_557;
					word32 w25_558;
					word32 w26_559;
					struct Eq_5662 * x29_560;
					word64 x30_561;
					O(11, w18, w20_150, x30_462, qwArg00, out w20_150, out w21_555, out w22_556, out w23_557, out w25_558, out w26_559, out x29_560, out x30_561);
					x29_560->dw004C = S(0x00, 0x00);
				}
				struct Eq_5621 * x19_481;
				struct Eq_5622 * x20_482;
				word64 x21_483;
				word64 x22_484;
				word64 x23_485;
				word64 x24_486;
				word64 x25_487;
				word64 x26_488;
				word64 x27_489;
				word64 x29_490;
				struct Eq_104 * x30_491;
				word64 sp_492;
				ad(w18, w20_150, qwArg00, out x19_481, out x20_482, out x21_483, out x22_484, out x23_485, out x24_486, out x25_487, out x26_488, out x27_489, out x29_490, out x30_491, out sp_492);
				word32 * x20_494 = x20_482->ptr0F50;
				w20_362 = (word32) x20_494;
				if (*x20_494 != 0x29)
				{
					union Eq_255 * x22_499 = x19_481->ptr0FC8;
					Eq_255 w1_503 = *x22_499;
					*x22_499 = (union Eq_255 *) ((word32) w1_503 + 0x01);
					*(int64) (int32) w1_503 = 233;
					*(word64) *x22_499 = 0x00;
					Eq_255 w20_511 = *x22_499;
					*x22_499 = (union Eq_255 *) ((word32) w20_511 + 0x04);
					word32 w21_516;
					word32 w22_517;
					word32 w23_518;
					word32 w25_519;
					word32 w26_520;
					word64 x29_521;
					word64 x30_522;
					O(11, w18, w20_511, x30_491, qwArg00, out w20_362, out w21_516, out w22_517, out w23_518, out w25_519, out w26_520, out x29_521, out x30_522);
					Eq_255 w0_524 = *x22_499;
					*x22_499 = (union Eq_255 *) ((word32) w0_524 + 0x01);
					*(int64) (int32) w0_524 = 233;
					*(word64) *x22_499 = w23_518 - w0_524 - 0x05;
					Eq_255 w0_534 = *x22_499;
					*x22_499 = (union Eq_255 *) ((word32) w0_534 + 0x04);
					Eq_255 w0_535 = (word32) w0_534 + 0x04;
					if (w20_362 != 0x00)
					{
						while (true)
						{
							union Eq_255 * x2_543 = (int64) (int32) w20_362;
							Eq_255 w1_546 = *x2_543;
							*x2_543 = (union Eq_255 *) (w0_535 - w20_362 - 0x04);
							w20_362 = w1_546;
							if (w1_546 == 0x00)
								break;
							w0_535 = *x22_499;
						}
					}
				}
			}
			else
			{
				word32 w21_582;
				word32 w22_583;
				word32 w23_584;
				word32 w25_585;
				word32 w26_586;
				struct Eq_5445 * x29_587;
				word64 x30_588;
				O(11, w18, w20_150, x30_349, qwArg00, out w20_362, out w21_582, out w22_583, out w23_584, out w25_585, out w26_586, out x29_587, out x30_588);
				x29_587->dw004C = S(0x00, 0x00);
			}
			struct Eq_5527 * x19_363;
			word64 x20_364;
			word64 x21_365;
			word64 x22_366;
			word64 x23_367;
			word64 x24_368;
			word64 x25_369;
			word64 x26_370;
			word64 x27_371;
			word64 x29_372;
			struct Eq_104 * x30_373;
			word64 sp_374;
			ad(w18, w20_362, qwArg00, out x19_363, out x20_364, out x21_365, out x22_366, out x23_367, out x24_368, out x25_369, out x26_370, out x27_371, out x29_372, out x30_373, out sp_374);
			word32 w21_378;
			word32 w22_379;
			word32 w24_380;
			word64 x25_381;
			word64 x26_382;
			word32 w27_383;
			struct Eq_5559 * x29_384;
			word64 x30_385;
			I((word32) (x29_372 + 0x4C), w18, w20_362, x30_373, out w21_378, out w22_379, out w24_380, out x25_381, out x26_382, out w27_383, out x29_384, out x30_385, out sp_103);
			word32 * x4_389 = x19_363->ptr0FC8;
			word32 w0_392 = *x4_389;
			*x4_389 = w0_392 + 0x01;
			*(int64) (int32) w0_392 = 233;
			*(word64) *x4_389 = w21_378 - w0_392 - 0x05;
			word32 w1_403 = *x4_389;
			word32 w2_404 = x29_384->dw004C;
			*x4_389 = w1_403 + 0x04;
			word32 w0_406 = w1_403 + 0x04;
			if (w2_404 != 0x00)
			{
				while (true)
				{
					word32 * x3_413 = (int64) (int32) w2_404;
					word32 w1_416 = *x3_413;
					*x3_413 = w0_406 - w2_404 - 0x04;
					w2_404 = w1_416;
					if (w1_416 == 0x00)
						break;
					w0_406 = *x4_389;
				}
				word32 w21_427;
				*w21Out = (word32) sp_103->qw0020;
				word32 w22_430;
				*w22Out = (word32) sp_103->qw0028;
				word32 w24_435;
				*w24Out = (word32) sp_103->qw0038;
				word64 x29_437;
				*x29Out = sp_103->qw0000;
				word64 x30_439;
				*x30Out = sp_103->qw0008;
				word64 sp_440;
				*spOut = &sp_103->qw0038 + 0x03;
				return (word32) sp_103->qw0018;
			}
		}
	}
	else
	{
		word64 x19_596;
		word64 x20_597;
		word64 x21_598;
		word64 x22_599;
		word64 x23_600;
		word64 x24_601;
		word64 x25_602;
		word64 x26_603;
		word64 x27_604;
		word64 x29_605;
		word64 x30_606;
		word64 sp_607;
		ad(w18, w20_150, x30, out x19_596, out x20_597, out x21_598, out x22_599, out x23_600, out x24_601, out x25_602, out x26_603, out x27_604, out x29_605, out x30_606, out sp_607);
		word64 x19_609;
		word64 x20_610;
		word64 x21_611;
		word64 x22_612;
		word64 x23_613;
		word64 x24_614;
		word64 x25_615;
		word64 x26_616;
		word64 x27_617;
		word64 x29_618;
		struct Eq_104 * x30_619;
		word64 sp_620;
		ad(w18, w20_150, qwArg00, out x19_609, out x20_610, out x21_611, out x22_612, out x23_613, out x24_614, out x25_615, out x26_616, out x27_617, out x29_618, out x30_619, out sp_620);
		Eq_255 w20_623;
		word32 w21_624;
		word32 w22_625;
		word32 w23_626;
		word32 w25_627;
		word32 w26_628;
		struct Eq_4850 * x29_629;
		word64 x30_630;
		O(11, w18, w20_150, x30_619, qwArg00, out w20_623, out w21_624, out w22_625, out w23_626, out w25_627, out w26_628, out x29_629, out x30_630);
		x29_629->dw004C = S(0x00, 0x00);
		word64 x19_637;
		word64 x20_638;
		word32 * x21_639;
		word64 x22_640;
		word64 x23_641;
		word64 x24_642;
		word64 x25_643;
		word64 x26_644;
		word64 x27_645;
		word64 x29_646;
		struct Eq_104 * x30_647;
		word64 sp_648;
		ad(w18, w20_623, qwArg00, out x19_637, out x20_638, out x21_639, out x22_640, out x23_641, out x24_642, out x25_643, out x26_644, out x27_645, out x29_646, out x30_647, out sp_648);
		word32 w21_651;
		word32 w22_652;
		word32 w24_653;
		word64 x25_654;
		word64 x26_655;
		word32 w27_656;
		struct Eq_4902 * x29_657;
		word64 x30_658;
		Eq_255 w20_660 = I(w22_625, w18, w20_623, x30_647, out w21_651, out w22_652, out w24_653, out x25_654, out x26_655, out w27_656, out x29_657, out x30_658, out sp_103);
		if (*x21_639 != 0x0138)
		{
			word32 w0_665 = x29_657->dw004C;
			if (w0_665 != 0x00)
			{
				word32 * x4_668 = globals->ptr12FC8;
				do
				{
					word32 * x2_672 = (int64) (int32) w0_665;
					w0_665 = *x2_672;
					*x2_672 = *x4_668 - w0_665 - 0x04;
				} while (w0_665 != 0x00);
				word32 w21_686;
				*w21Out = (word32) sp_103->qw0020;
				word32 w22_689;
				*w22Out = (word32) sp_103->qw0028;
				word32 w24_694;
				*w24Out = (word32) sp_103->qw0038;
				word64 x29_696;
				*x29Out = sp_103->qw0000;
				word64 x30_698;
				*x30Out = sp_103->qw0008;
				word64 sp_699;
				*spOut = &sp_103->qw0038 + 0x03;
				return (word32) sp_103->qw0018;
			}
		}
		else
		{
			struct Eq_4929 * x19_701;
			word64 x20_702;
			word64 x21_703;
			word64 x22_704;
			word64 x23_705;
			word64 x24_706;
			word64 x25_707;
			word64 x26_708;
			word64 x27_709;
			struct Eq_4938 * x29_710;
			struct Eq_104 * x30_711;
			word64 sp_712;
			ad(w18, w20_660, qwArg00, out x19_701, out x20_702, out x21_703, out x22_704, out x23_705, out x24_706, out x25_707, out x26_708, out x27_709, out x29_710, out x30_711, out sp_712);
			union Eq_255 * x4_715 = x19_701->ptr0FC8;
			Eq_255 w0_717 = *x4_715;
			*x4_715 = (union Eq_255 *) ((word32) w0_717 + 0x01);
			*(int64) (int32) w0_717 = 233;
			*(word64) *x4_715 = 0x00;
			Eq_255 w20_725 = *x4_715;
			word32 w1_727 = x29_710->dw004C;
			*x4_715 = (union Eq_255 *) ((word32) w20_725 + 0x04);
			Eq_255 w0_729 = (word32) w20_725 + 0x04;
			if (w1_727 != 0x00)
			{
				while (true)
				{
					word32 * x3_764 = (int64) (int32) w1_727;
					word32 w2_767 = *x3_764;
					*x3_764 = w0_729 - w1_727 - 0x04;
					w1_727 = w2_767;
					if (w2_767 == 0x00)
						break;
					w0_729 = *x4_715;
				}
			}
			word32 w21_738;
			word32 w22_739;
			word32 w24_740;
			word64 x25_741;
			word64 x26_742;
			word32 w27_743;
			word64 x29_744;
			word64 x30_745;
			Eq_255 w20_747 = I(w22_652, w18, w20_725, x30_711, out w21_738, out w22_739, out w24_740, out x25_741, out x26_742, out w27_743, out x29_744, out x30_745, out sp_103);
			union Eq_255 * x4_749 = x19_701->ptr0FC8;
			while (w20_747 != 0x00)
			{
				union Eq_255 * x1_753 = (int64) (int32) w20_747;
				w20_747 = *x1_753;
				*x1_753 = (union Eq_255 *) (*x4_749 - w20_747 - 0x04);
			}
		}
	}
	struct Eq_5005 * v48_109 = &sp_103->qw0020;
	word32 w21_111;
	*w21Out = (word32) v48_109->qw0000;
	word32 w22_114;
	*w22Out = (word32) v48_109->qw0008;
	word32 w24_119;
	*w24Out = (word32) sp_103->qw0038;
	word64 x29_121;
	*x29Out = sp_103->qw0000;
	word64 x30_123;
	*x30Out = sp_103->qw0008;
	word64 sp_124;
	*spOut = &sp_103->qw0038 + 0x03;
	return (word32) sp_103->qw0018;
}

// 00000000000028E8: void __libc_csu_init(Register word64 x30, Stack word64 qwArg00)
void __libc_csu_init(word64 x30, word64 qwArg00)
{
	<anonymous> * x21_23[] = globals->a12D10;
	word64 sp_38 = _init(x30);
	if (77080 - 77072 >> 0x03 != 0x00)
	{
		ui64 x19_71 = 0x00;
		do
		{
			<anonymous> * x3_77 = x21_23[x19_71];
			word64 sp_82;
			word64 x29_83;
			word64 x30_84;
			word64 x22_86;
			word64 x20_88;
			word64 x23_89;
			word64 x24_90;
			word64 x2_91;
			word32 w0_92;
			word32 w24_93;
			word64 x1_94;
			word64 x3_95;
			word64 x31_96;
			byte NZCV_97;
			bool Z_98;
			x3_77();
		} while (x20_88 - x19_71 != 0x00);
	}
}

// 0000000000002960: void __libc_csu_fini()
void __libc_csu_fini()
{
}

// 0000000000002964: void _fini(Stack word64 qwArg00)
void _fini(word64 qwArg00)
{
}

