// subject_bss.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

byte g_b15088 = 0x00; // 0000000000015088
Eq_110 g_t1508C = // 000000000001508C
	{
		0
	};
int32 g_dw15090 = 0; // 0000000000015090
word32 g_dw15094 = 0x00; // 0000000000015094
Eq_110 g_t15098 = // 0000000000015098
	{
		0
	};
word32 g_dw1509C = 0x00; // 000000000001509C
Eq_110 g_t150A0 = // 00000000000150A0
	{
		0
	};
Eq_110 g_t150A4 = // 00000000000150A4
	{
		0
	};
Eq_110 g_t150A8 = // 00000000000150A8
	{
		0
	};
word32 g_dw150AC = 0x00; // 00000000000150AC
Eq_110 g_t150B0 = // 00000000000150B0
	{
		0
	};
Eq_110 g_t150B4 = // 00000000000150B4
	{
		0
	};
Eq_110 g_t150B8 = // 00000000000150B8
	{
		0
	};
Eq_110 g_t150BC = // 00000000000150BC
	{
		0
	};
ui32 g_dw150C0 = 0x00; // 00000000000150C0
Eq_110 g_t150C4 = // 00000000000150C4
	{
		0
	};
Eq_110 g_t150C8 = // 00000000000150C8
	{
		0
	};
Eq_110 g_t150CC = // 00000000000150CC
	{
		0
	};
uipr32 g_dw150D0 = 0x00; // 00000000000150D0
Eq_110 g_t150D4 = // 00000000000150D4
	{
		0
	};
// subject_fini.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0000000000004204: void _fini()
void _fini()
{
}

// subject_got.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

<anonymous> * __libc_csu_fini_GOT = __libc_csu_fini; // 0000000000014F10
<anonymous> * g_ptr14F18 = null; // 0000000000014F18
union Eq_110 * g_ptr14F20 = &g_t1508C; // 0000000000014F20
int32 * g_ptr14F28 = &g_dw15090; // 0000000000014F28
word32 * g_ptr14F30 = &g_dw15094; // 0000000000014F30
union Eq_110 * g_ptr14F38 = &g_t15098; // 0000000000014F38
word32 * g_ptr14F40 = &g_dw1509C; // 0000000000014F40
union Eq_110 * g_ptr14F48 = &g_t150A0; // 0000000000014F48
word64 g_qw14F50 = 0x00; // 0000000000014F50
union Eq_110 * g_ptr14F58 = &g_t150A4; // 0000000000014F58
union Eq_110 * g_ptr14F60 = &g_t150A8; // 0000000000014F60
word64 g_qw14F68 = 0x00; // 0000000000014F68
word32 * g_ptr14F70 = &g_dw150AC; // 0000000000014F70
<anonymous> * __libc_csu_init_GOT = __libc_csu_init; // 0000000000014F78
union Eq_110 * g_ptr14F80 = &g_t150B0; // 0000000000014F80
union Eq_110 * g_ptr14F88 = &g_t150B4; // 0000000000014F88
union Eq_110 * g_ptr14F90 = &g_t150B8; // 0000000000014F90
union Eq_110 * g_ptr14F98 = &g_t150BC; // 0000000000014F98
ui32 * g_ptr14FA0 = &g_dw150C0; // 0000000000014FA0
union Eq_110 * g_ptr14FA8 = &g_t150C4; // 0000000000014FA8
union Eq_110 * g_ptr14FB0 = &g_t150C8; // 0000000000014FB0
union Eq_110 * g_ptr14FB8 = &g_t150CC; // 0000000000014FB8
uipr32 * g_ptr14FC0 = &g_dw150D0; // 0000000000014FC0
<anonymous> * main_GOT = main; // 0000000000014FC8
<anonymous> * g_ptr14FD0 = null; // 0000000000014FD0
<anonymous> * g_ptr14FD8 = null; // 0000000000014FD8
union Eq_110 * g_ptr14FE0 = &g_t150D4; // 0000000000014FE0
// subject_got_plt.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

struct Eq_72 g_t15000 = // 0000000000015000
	{
		0x00,
	};
// subject_init.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0000000000000D08: Register word64 _init(Register out ptr64 x30Out)
// Called from:
//      __libc_csu_init
word64 _init(ptr64 & x30Out)
{
	call_weak_fn();
	x30Out = qwArg00;
	return x30;
}

// subject_init_array.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

<anonymous> * g_a14D00[] = // 0000000000014D00
	{
	};
// subject_jcr.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

word64 g_qw14D10 = 0x00; // 0000000000014D10
// subject_rodata.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

word64 g_qw42A0 = 0x2E6F732E6362696C; // 00000000000042A0
word16 g_w42A8 = 0x36; // 00000000000042A8
word64 g_qw42B0 = 8030813603607243116; // 00000000000042B0
word32 g_dw42B7 = 3288687; // 00000000000042B7
word64 g_qw42C0 = 0x2D646C2F62696C2F; // 00000000000042C0
word64 g_qw42C8 = 8030813655432849772; // 00000000000042C8
word32 g_dw42CF = 3288687; // 00000000000042CF
word64 g_qw4300 = 0x20666920746E6920; // 0000000000004300
word64 g_qw4308 = 7595451752585063525; // 0000000000004308
word64 g_qw4310 = 0x6B6165726220656C; // 0000000000004310
word64 g_qw4318 = 0x206E727574657220; // 0000000000004318
word64 g_qw4320 = 0x6966656420726F66; // 0000000000004320
word64 g_qw4328 = 0x206E69616D20656E; // 0000000000004328
byte g_b4330 = 0x00; // 0000000000004330
// subject_text.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0000000000000E30: void _start(Register (ptr64 Eq_9) x0, Stack Eq_10 qwArg00)
void _start(void (* x0)(), Eq_10 qwArg00)
{
	x0_17 = (uint64) __libc_start_main(main_GOT, qwArg00, (char *) fp + 8, __libc_csu_init_GOT, __libc_csu_fini_GOT, x0, fp);
	abort();
}

// 0000000000000E68: void call_weak_fn()
// Called from:
//      _init
void call_weak_fn()
{
	if (g_qw14F68 == 0x00)
		return;
	__gmon_start__();
}

// 0000000000000E80: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
	if (0x0001508F - 0x00015088 <= 0x0E)
		return;
	<anonymous> * x1_13 = g_ptr14F18;
	if (x1_13 == null)
		return;
	x1_13();
}

// 0000000000000EB8: void register_tm_clones()
// Called from:
//      frame_dummy
void register_tm_clones()
{
	int64 x1_7 = 0x00015088 - 0x00015088;
	if ((x1_7 >> 3) + ((x1_7 >> 3) >>u 63) >> 1 == 0x00)
		return;
	<anonymous> * x2_13 = g_ptr14FD8;
	if (x2_13 == null)
		return;
	word64 x2_17;
	x2_13();
}

// 0000000000000EF8: void __do_global_dtors_aux(Register word64 x30)
void __do_global_dtors_aux(word64 x30)
{
	struct Eq_72 * x19_12 = &g_t15000;
	if ((word32) g_b15088 == 0x00)
	{
		if (g_qw14F50 != 0x00)
		{
			word64 x1_45;
			__cxa_finalize();
		}
		deregister_tm_clones();
		x19_12->b0088 = 0x01;
	}
}

// 0000000000000F40: void frame_dummy(Register word64 x29, Register word64 x30)
void frame_dummy(word64 x29, word64 x30)
{
	if (g_qw14D10 != 0x00)
	{
		<anonymous> * x1_8 = g_ptr14FD0;
		if (x1_8 != null)
		{
			x1_8();
			register_tm_clones();
			return;
		}
	}
	register_tm_clones();
}

// 0000000000000F78: Register word64 L(Register Eq_110 w0)
// Called from:
//      av
word64 L(Eq_110 w0)
{
	union Eq_110 * x1_11 = g_ptr14F20;
	Eq_110 w0_8 = *g_ptr14F20;
	*x1_11 = (word64) w0_8 + 1;
	uint32 w1_15 = (uint32) (uint8) w0;
	null[(int64) w0_8] = (byte) w1_15;
	return SEQ(SLICE(x1_11, word32, 32), w1_15);
}

// 0000000000000FB8: Register word64 w(Register out ptr64 x29Out, Register out ptr64 x30Out)
// Called from:
//      an
//      av
//      ab
//      main
word64 w(ptr64 & x29Out, ptr64 & x30Out)
{
	if (*g_ptr14F40 == 0x00)
	{
		Eq_110 w0_21 = (word32) (uint64) fgetc((int64) *g_ptr14F70);
		*g_ptr14FB8 = (union Eq_110 *) w0_21;
		word64 x1_70 = SEQ(x1_32_32, w0_21);
		x29Out = x29;
		x30Out = x30;
		return x1_70;
	}
	else
	{
		word32 * x1_36 = g_ptr14F40;
		word32 w0_33 = *g_ptr14F40;
		*x1_36 = w0_33 + 0x01;
		*g_ptr14FB8 = (union Eq_110 *) (word32) null[(int64) w0_33];
		word32 x1_32_32_67 = SLICE(x1_36, word32, 32);
		ptr64 x30_48;
		x29Out = fn0000000000001008(out x30_48);
		x30Out = x30_48;
		return SEQ(x1_32_32_67, w1_49);
	}
}

// 0000000000001008: Register word64 fn0000000000001008(Register out ptr64 x30Out)
// Called from:
//      w
//      e843419@0008_00000059_8c
word64 fn0000000000001008(ptr64 & x30Out)
{
	if (*g_ptr14FB8 == 0x02)
	{
		*g_ptr14F40 = 0x00;
		*g_ptr14FB8 = *g_ptr14FE0;
	}
	x30Out = qwArg08;
	return qwArg00;
}

// 0000000000001074: Register ui32 am(Register word64 x29, Register word64 x30)
// Called from:
//      av
ui32 am(word64 x29, word64 x30)
{
	union Eq_110 * x0_11 = g_ptr14FB8;
	word64 x0_18;
	isalnum();
	union Eq_110 * x0_24 = g_ptr14FB8;
	return (word32) x0_18 | (uint32) ((uint8) ((word32) (*x0_24 == 0x5F)));
}

// 00000000000010B4: void an()
// Called from:
//      av
//      ab
void an()
{
	if (*g_ptr14FB8 == 0x5C)
	{
		word64 x29_66;
		word64 x30_67;
		w(out x29_66, out x30_67);
		if (*g_ptr14FB8 == 110)
			*g_ptr14FB8 = (union Eq_110 *) 0x0A;
	}
}

// 0000000000001104: Register word64 av(Register word64 x30, Register out (ptr64 Eq_279) x30Out)
// Called from:
//      av
//      ab
//      X
//      S
//      ar
//      main
word64 av(word64 x30, struct Eq_279 & x30Out)
{
	ptr64 x29_126 = fp + -24;
	while (true)
	{
		union Eq_110 * x0_12 = g_ptr14FB8;
		word64 x0_22;
		word64 x29_20;
		word64 x30_21;
		isspace();
		if (((word32) x0_22 | (uint32) ((uint8) ((word32) (*g_ptr14FB8 == 0x23)))) == 0x00)
			break;
		if (*g_ptr14FB8 == 0x23)
		{
			word64 x30_47;
			word64 x29_659;
			w(out x29_659, out x30_47);
			word64 x30_54;
			av(x30_47, out x30_54);
			if (*g_ptr14FA8 == 0x0218)
			{
				word64 x30_660;
				av(x30_54, out x30_660);
				L(0x20);
				null[(int64) *g_ptr14FA8 /64 4] = 0x01;
				null[(int64) ((char *) *g_ptr14FA8 + 4) /64 4].t0000 = *g_ptr14F20;
			}
			while (*g_ptr14FB8 != 0x0A)
			{
				L(*g_ptr14FB8);
				word64 x29_661;
				word64 x30_662;
				w(out x29_661, out x30_662);
			}
			L(*g_ptr14FB8);
			L(0x02);
		}
		w(out x29_126, out x30);
	}
	word64 x1_345;
	*g_ptr14F28 = 0x00;
	*g_ptr14FA8 = *g_ptr14FB8;
	if (am(x29_20, x30_21) != 0x00)
	{
		word32 x1_32_32_600 = SLICE(L(0x20), word32, 32);
		*g_ptr14F58 = *g_ptr14F20;
		while (am(x29_20, x30_21) != 0x00)
		{
			L(*g_ptr14FB8);
			x1_32_32_600 = SLICE(w(out x29_20, out x30_21), word32, 32);
		}
		if (*g_ptr14FA8 <= 0x39)
		{
			union Eq_110 * x0_530 = g_ptr14F58;
			*g_ptr14F80 = (union Eq_110 *) (word32) (uint64) strtol(SEQ(SLICE(x0_530, word32, 32), *x0_530));
			*g_ptr14FA8 = (union Eq_110 *) 0x02;
			x1_345 = SEQ(x1_32_32_600, 0x02);
		}
		else
		{
			null[(int64) *g_ptr14F20] = 0x20;
			char * x0_448 = strstr((int64) *g_ptr14FA0, (int64) (*g_ptr14F58 - 0x01));
			*g_ptr14FA8 = (union Eq_110 *) ((word32) x0_448 + (0x00 - *g_ptr14FA0));
			null[(int64) *g_ptr14F20] = 0x00;
			Eq_110 w1_472 = (char *) *g_ptr14FA8 + 32 << 3;
			*g_ptr14FA8 = (union Eq_110 *) w1_472;
			word32 x1_32_32_604 = SLICE(x0_448, word32, 32);
			x1_345 = SEQ(x1_32_32_604, w1_472);
			if (*g_ptr14FA8 > 0x0218)
			{
				Eq_110 w1_487 = (char *) *g_ptr14FA8 + *g_ptr14F30;
				*g_ptr14FA8 = (union Eq_110 *) w1_487;
				x1_345 = SEQ(x1_32_32_604, w1_487);
				if (null[(int64) *g_ptr14FA8 /64 4] == 0x01)
				{
					*g_ptr14F40 = null[(int64) ((char *) *g_ptr14FA8 + 4) /64 4];
					*g_ptr14FE0 = *g_ptr14FB8;
					word64 x30_517;
					word64 x29_663;
					w(out x29_663, out x30_517);
					word64 x30_664;
					x1_345 = av(x30_517, out x30_664);
				}
			}
		}
	}
	else
	{
		struct Eq_335 * x29_153;
		word64 x30_658;
		word32 x1_32_32_608 = SLICE(w(out x29_153, out x30_658), word32, 32);
		if (*g_ptr14FA8 == 0x27)
		{
			*g_ptr14FA8 = (union Eq_110 *) 0x02;
			an();
			*g_ptr14F80 = *g_ptr14FB8;
			word64 x29_665;
			word64 x30_666;
			w(out x29_665, out x30_666);
			word64 x29_667;
			word64 x30_668;
			x1_345 = w(out x29_667, out x30_668);
		}
		else if ((uint32) (uint8) ((uint32) (uint8) (word32) (*g_ptr14FA8 == 0x2F) & (uint32) ((uint8) ((word32) (*g_ptr14FB8 == 0x2A)))) != 0x00)
		{
			word64 x29_669;
			word64 x30_670;
			w(out x29_669, out x30_670);
			while (*g_ptr14FB8 != 0x00)
			{
				while (*g_ptr14FB8 != 0x2A)
				{
					word64 x29_673;
					word64 x30_674;
					w(out x29_673, out x30_674);
				}
				word64 x29_675;
				word64 x30_676;
				w(out x29_675, out x30_676);
				if (*g_ptr14FB8 == 0x2F)
					*g_ptr14FB8 = (union Eq_110 *) 0x00;
			}
			word64 x30_334;
			word64 x29_671;
			w(out x29_671, out x30_334);
			word64 x30_672;
			x1_345 = av(x30_334, out x30_672);
		}
		else
		{
			x29_153->dw001C = (word32) 0x4220;
			do
			{
				word32 w0_188 = x29_153->dw001C;
				x29_153->dw001C = w0_188 + 0x01;
				x29_153->t0018 = (word32) null[(int64) w0_188];
				x1_345 = SEQ(x1_32_32_608, w0_188 + 0x01);
				if (x29_153->t0018 == 0x00)
					goto l0000000000001678;
				word32 w0_198 = x29_153->dw001C;
				x29_153->dw001C = w0_198 + 0x01;
				x29_153->t0014 = (word32) null[(int64) w0_198];
				*g_ptr14F80 = (union Eq_110 *) 0x00;
				while (true)
				{
					word32 w0_210 = x29_153->dw001C;
					x29_153->dw001C = w0_210 + 0x01;
					*g_ptr14F28 = (word32) null[(int64) w0_210] - 0x62;
					if (*g_ptr14F28 >= 0x00)
						break;
					*g_ptr14F80 = (union Eq_110 *) ((*g_ptr14F80 << 6) + *g_ptr14F28 + 0x40);
				}
			} while (((uint32) (uint8) (word32) (x29_153->t0018 == *g_ptr14FA8) & (uint32) ((uint8) ((uint32) ((uint8) ((word32) (x29_153->t0014 == *g_ptr14FB8))) | (uint32) ((uint8) ((word32) (x29_153->t0014 == 0x40)))))) == 0x00);
			Eq_110 w1_267 = x29_153->t0014;
			x1_345 = SEQ(x1_32_32_608, w1_267);
			if (w1_267 == *g_ptr14FB8)
			{
				word64 x29_677;
				word64 x30_678;
				word32 x1_32_32_613 = SLICE(w(out x29_677, out x30_678), word32, 32);
				*g_ptr14FA8 = (union Eq_110 *) 0x01;
				x1_345 = SEQ(x1_32_32_613, 0x01);
			}
		}
	}
l0000000000001678:
	x30Out = (struct Eq_279 *) <invalid>;
	return x1_345;
}

// 0000000000001684: void aw()
// Called from:
//      x
//      aa
//      aq
//      W
//      ab
//      X
//      ar
//      au
void aw()
{
	struct Eq_922 * sp_24 = fp - 0x10;
	while (true)
	{
		word32 sp_32_32_23 = SLICE(sp_24, word32, 32);
		if (sp_24->t000C == 0x00)
			break;
		Eq_930 w0_11 = sp_24->t000C;
		sp_24 = SEQ(sp_32_32_23, (word32) w0_11 + 1);
		if (w0_11 == 0x01)
			return;
		Eq_110 w0_17 = *g_ptr14F60;
		*g_ptr14F60 = (word64) w0_17 + 1;
		null[(int64) w0_17] = (byte) (uint32) sp_24->t000C;
		sp_24->t000C >>= 8;
	}
}

// 00000000000016EC: Register (ptr64 byte) E(Register Eq_110 w0, Register Eq_110 w1)
// Called from:
//      ap
//      x
//      ab
//      ar
//      ax
//      ae
byte * E(Eq_110 w0, Eq_110 w1)
{
	null[(int64) w0] = (byte) (uint32) (uint8) w1;
	null[(int64) ((word64) w0 + 1)] = (byte) (uint32) (uint8) (w1 >> 8);
	null[(int64) ((word64) w0 + 2)] = (byte) (uint32) (uint8) (w1 >> 16);
	byte * x0_36 = (int64) ((word64) w0 + 3);
	*x0_36 = (byte) (uint32) (uint8) (w1 >> 24);
	return x0_36;
}

// 000000000000178C: Register Eq_110 ao(Register Eq_110 w0)
// Called from:
//      ap
//      ae
Eq_110 ao(Eq_110 w0)
{
	byte * x0_27 = (int64) ((word64) w0 + 3);
	return (word32) null[(int64) dwLoc0A] | (word32) null[(int64) ((word64) w0 + 1)] << 8 | (word32) null[(int64) ((word64) w0 + 2)] << 16 | (word32) (*x0_27) << 24;
}

// 00000000000017F0: Register word64 ap(Register Eq_110 w0, Register Eq_110 w1, Register out (ptr64 Eq_1057) x29Out)
// Called from:
//      H
//      ae
word64 ap(Eq_110 w0, Eq_110 w1, struct Eq_1057 & x29Out)
{
	Eq_110 w1 = (word32) x1;
	Eq_110 dwLoc0C_102 = w0;
	word64 x1_121 = x1;
	while (dwLoc0C_102 != 0x00)
	{
		Eq_110 w0_22 = ao(dwLoc0C_102);
		if ((word32) null[(int64) (dwLoc0C_102 - 0x01)] == 0x05)
		{
			if (w1 >= *g_ptr14F88 && w1 < *g_ptr14FB0)
				x1_121 = E(dwLoc0C_102, (word32) w1.u0 + *g_ptr14FC0);
			else
				x1_121 = E(dwLoc0C_102, (char *) *g_ptr14F48 + (w1 - *g_ptr14F90) + *g_ptr14FC0);
		}
		else
			x1_121 = E(dwLoc0C_102, w1 - dwLoc0C_102 - 0x04);
		dwLoc0C_102 = w0_22;
	}
	x29Out = x30;
	return x1_121;
}

// 00000000000018FC: Register word64 H(Register Eq_110 w0, Register word32 x1_32_32)
// Called from:
//      X
//      S
//      ar
word64 H(Eq_110 w0, word32 x1_32_32)
{
	word64 x29_36;
	return ap(w0, SEQ(x1_32_32, *g_ptr14F60), out x29_36);
}

// 000000000000192C: Register Eq_110 x(Register Eq_110 w1, Register out ptr64 x1Out, Register out (ptr64 Eq_1140) x29Out, Register out ptr64 x30Out)
// Called from:
//      M
//      I
//      aa
//      W
//      ab
//      ar
//      au
Eq_110 x(Eq_110 w1, ptr64 & x1Out, struct Eq_1140 & x29Out, ptr64 & x30Out)
{
	aw();
	word32 x1_32_32_53 = SLICE(E(*g_ptr14F60, w1), word32, 32);
	union Eq_110 * x0_37 = g_ptr14F60;
	Eq_110 w0_30 = *g_ptr14F60;
	Eq_110 w0_34 = *g_ptr14F60;
	*x0_37 = (word64) w0_34 + 4;
	x1Out = SEQ(x1_32_32_53, (word64) w0_34 + 4);
	x29Out = x30;
	x30Out = qwLoc10;
	return w0_30;
}

// 0000000000001990: void M(Register Eq_110 w0)
// Called from:
//      aq
//      ab
//      X
//      au
void M(Eq_110 w0)
{
	word64 x1_32;
	word64 x29_33;
	word64 x30_34;
	x(w0, out x1_32, out x29_33, out x30_34);
}

// 00000000000019B4: Register Eq_110 I(Register Eq_110 w0, Register out ptr64 x1Out)
// Called from:
//      X
//      S
Eq_110 I(Eq_110 w0, ptr64 & x1Out)
{
	ptr64 x1_17;
	word64 x29_33;
	word64 x30_34;
	uint64 x0_16 = (uint64) x(w0, out x1_17, out x29_33, out x30_34);
	x1Out = x1_17;
	return (word32) x0_16;
}

// 00000000000019D4: Register Eq_110 aa(Register Eq_110 w1)
// Called from:
//      X
//      ac
Eq_110 aa(Eq_110 w1)
{
	aw();
	word64 x1_45;
	word64 x29_46;
	word64 x30_47;
	return x(w1, out x1_45, out x29_46, out x30_47);
}

// 0000000000001A08: Register word64 aq(Register out ptr64 x30Out)
// Called from:
//      ab
//      X
word64 aq(ptr64 & x30Out)
{
	aw();
	M(0x00);
	aw();
	aw();
	aw();
	x30Out = qwLoc10;
	return x30;
}

// 0000000000001A4C: Register word64 W(Register word64 x19)
// Called from:
//      ab
word64 W(word64 x19)
{
	aw();
	int32 dwLoc24_85 = SLICE(x19, int32, 32);
	Eq_110 w0_27 = null[(int64) dwLoc24_85 /64 4].t0000;
	if (w0_27 != 0x00 && w0_27 <= 0x01FF)
	{
		word64 x29_108;
		word64 x30_109;
		word64 x1_107;
		x(w0_27, out x1_107, out x29_108, out x30_109);
	}
	else
	{
		word64 x30_106;
		word64 x1_104;
		word64 x29_105;
		null[(int64) dwLoc24_85 /64 4].t0000 = x(null[(int64) dwLoc24_85 /64 4].t0000, out x1_104, out x29_105, out x30_106);
	}
	return qwLoc30;
}

// 0000000000001ADC: Register word64 ab(Register ui32 w0, Register word64 x19, Register word64 x30, Register out (ptr64 Eq_279) x30Out)
// Called from:
//      ab
//      X
word64 ab(ui32 w0, word64 x19, word64 x30, struct Eq_279 & x30Out)
{
	struct Eq_1273 * x29_124 = fp + -56;
	if (*g_ptr14FA8 == 0x22)
	{
		M((char *) *g_ptr14FB0 + *g_ptr14FC0);
		while (*g_ptr14FB8 != 0x22)
		{
			an();
			Eq_110 w0_418 = *g_ptr14FB0;
			*g_ptr14FB0 = (word64) w0_418 + 1;
			null[(int64) w0_418] = (byte) (uint32) *g_ptr14FB8;
			word64 x29_749;
			word64 x30_750;
			w(out x29_749, out x30_750);
		}
		null[(int64) *g_ptr14FB0] = 0x00;
		*g_ptr14FB0 = (union Eq_110 *) ((char *) *g_ptr14FB0 + 4 & ~0x03);
		word64 x30_456;
		w(out x29_124, out x30_456);
		word64 x30_751;
		av(x30_456, out x30_751);
	}
	else
	{
		int32 w0_23 = *g_ptr14F28;
		Eq_110 w0_27 = *g_ptr14F80;
		Eq_110 w0_31 = *g_ptr14FA8;
		word64 x30_748;
		av(x30, out x30_748);
		if (w0_31 == 0x02)
			M(w0_27);
		else if (w0_23 == 0x02)
		{
			word64 x30_754;
			ab(0x00, x19, x30, out x30_754);
			word64 x30_756;
			word64 x1_755;
			x(0x00, out x1_755, out x29_124, out x30_756);
			if (x29_124->dw0038 == 33)
			{
				word64 x30_757;
				x29_124 = aq(out x30_757);
			}
			else
				aw();
		}
		else if (w0_31 == 0x28)
		{
			word64 x30_322;
			B(out x29_124, out x30_322);
			word64 x30_765;
			av(x30_322, out x30_765);
		}
		else if (w0_31 == 0x2A)
		{
			word64 x30_769;
			av(x30, out x30_769);
			word64 x30_770;
			av(x30, out x30_770);
			word64 x30_771;
			av(x30, out x30_771);
			if (*g_ptr14FA8 == 0x2A)
			{
				word64 x30_773;
				av(x30, out x30_773);
				word64 x30_774;
				av(x30, out x30_774);
				word64 x30_775;
				av(x30, out x30_775);
				word64 x30_776;
				av(x30, out x30_776);
			}
			word64 x30_772;
			av(x30, out x30_772);
			word64 x30_234;
			x29_124 = ab(0x00, x19, x30, out x30_234);
			if (*g_ptr14FA8 == 0x3D)
			{
				word64 x30_777;
				av(x30_234, out x30_777);
				aw();
				word64 x30_778;
				B(out x29_124, out x30_778);
				aw();
				x29_124->dw0038 != 0x0100;
				aw();
			}
			else if (x29_124->dw0038 != 0x00)
			{
				if (x29_124->dw0038 == 0x0100)
					aw();
				else
					aw();
				*g_ptr14F60 = (union Eq_110 *) ((char *) *g_ptr14F60 + 1);
			}
		}
		else if (w0_31 == 0x26)
		{
			W(x19);
			word64 x30_779;
			av(x30, out x30_779);
		}
		else if (((uint32) (uint8) (word32) (*g_ptr14FA8 == 0x3D) & w0) != 0x00)
		{
			word64 x30_780;
			av(x30, out x30_780);
			word64 x30_781;
			W(B(out x29_124, out x30_781));
		}
		else if (*g_ptr14FA8 != 0x28)
		{
			word64 x19_78 = W(x19);
			if (*g_ptr14F28 == 11)
			{
				W(x19_78);
				aw();
				word64 x30_782;
				av(x30, out x30_782);
			}
		}
	}
	if (*g_ptr14FA8 == 0x28)
	{
		if (x29_124->dw003C != 0x00)
			aw();
		word64 x1_752;
		struct Eq_1411 * x29_495;
		word64 x30_496;
		x29_495->t0030 = x(0x00, out x1_752, out x29_495, out x30_496);
		word64 x30_753;
		av(x30_496, out x30_753);
		x29_495->t002C.u0 = 0x00;
		while (*g_ptr14FA8 != 0x29)
		{
			struct Eq_1467 * x29_522;
			word64 x30_758;
			B(out x29_522, out x30_758);
			word64 x1_759;
			x(x29_522->t002C, out x1_759, out x29_495, out x30_496);
			if (*g_ptr14FA8 == 44)
			{
				word64 x30_783;
				av(x30_496, out x30_783);
			}
			x29_495->t002C.u3 = (word64) x29_495->t002C + 4;
		}
		struct Eq_1492 * x29_588;
		E(x29_495->t0030, x29_495->t002C);
		word64 x30_760;
		av(x30_496, out x30_760);
		if (x29_495->dw003C != 0x00)
		{
			word64 x30_764;
			word64 x1_763;
			x(x29_495->t002C, out x1_763, out x29_588, out x30_764);
			x29_588->t002C.u3 = (word64) x29_588->t002C + 4;
		}
		else
		{
			x29_495->dw0038 += 0x04;
			word64 x30_762;
			word64 x1_761;
			null[(int64) x29_495->dw001C /64 4].t0000 = x(null[(int64) x29_495->dw001C /64 4].t0000, out x1_761, out x29_588, out x30_762);
		}
		if (x29_588->t002C != 0x00)
		{
			word64 x29_767;
			word64 x30_768;
			word64 x1_766;
			x(x29_588->t002C, out x1_766, out x29_767, out x30_768);
		}
	}
	x30Out = (struct Eq_279 *) <invalid>;
	return <invalid>;
}

// 0000000000001F44: Register word64 X(Register int32 w0, Register out (ptr64 Eq_279) x30Out)
// Called from:
//      X
//      B
word64 X(int32 w0, struct Eq_279 & x30Out)
{
	if (w0 == 0x01)
	{
		word64 x30_256;
		ab(0x01, x19, x30, out x30_256);
	}
	else
	{
		word64 x30_116;
		struct Eq_1273 * x29_115 = X(w0 - 0x01, out x30_116);
		x29_115->t0028.u0 = 0x00;
		while (x29_115->dw001C == *g_ptr14F28)
		{
			x29_115->t0024 = *g_ptr14FA8;
			x29_115->t002C = *g_ptr14F80;
			word64 x30_257;
			av(x30_116, out x30_257);
			if (x29_115->dw001C > 0x08)
			{
				x29_115->t0028 = aa(x29_115->t0028);
				x29_115 = X(x29_115->dw001C, out x30_116);
			}
			else
			{
				aw();
				x29_115 = X(x29_115->dw001C, out x30_116);
				aw();
				if ((uint32) (uint8) ((uint32) (uint8) (word32) (x29_115->dw001C == 0x04) | (uint32) ((uint8) ((word32) (x29_115->dw001C == 0x05)))) != 0x00)
					x29_115 = aq(out x30_116);
				else
				{
					aw();
					if (x29_115->t0024 == 0x25)
						aw();
				}
			}
		}
		if (x29_115->t0028 != 0x00 && x29_115->dw001C > 0x08)
		{
			x29_115->t0028 = aa(x29_115->t0028);
			M(x29_115->t002C ^ 0x01);
			word64 x1_169;
			I(0x05, out x1_169);
			H(x29_115->t0028, SLICE(x1_169, word32, 32));
			M(x29_115->t002C);
		}
	}
	x30Out = (struct Eq_279 *) <invalid>;
	return <invalid>;
}

// 00000000000020AC: Register word64 B(Register out (ptr64 Eq_279) x29Out, Register out (ptr64 Eq_279) x30Out)
// Called from:
//      ab
//      ac
//      S
word64 B(struct Eq_279 & x29Out, struct Eq_279 & x30Out)
{
	word64 x30_25;
	X(11, out x30_25);
	x29Out = (struct Eq_279 *) <invalid>;
	x30Out = (struct Eq_279 *) <invalid>;
	return <invalid>;
}

// 00000000000020C8: Register word32 ac(Register out ptr64 x29Out, Register out ptr64 x30Out)
// Called from:
//      S
word32 ac(ptr64 & x29Out, ptr64 & x30Out)
{
	word64 x29_30;
	word64 x30_31;
	B(out x29_30, out x30_31);
	uint64 x0_14 = (uint64) aa(0x00);
	x29Out = x30;
	x30Out = qwArg00;
	return (word32) x0_14;
}

// 00000000000020E8: Register word64 S(Register word64 x19, Register word64 x30, Register out ptr64 x19Out, Register out (ptr64 Eq_279) x29Out, Register out (ptr64 Eq_279) x30Out)
// Called from:
//      S
//      ar
word64 S(word64 x19, word64 x30, ptr64 & x19Out, struct Eq_279 & x29Out, struct Eq_279 & x30Out)
{
	word64 x1_112;
	struct Eq_1940 * x29_211 = fp + -56;
	int32 dwLoc22_445 = SEQ(wLoc20, SLICE(x19, word16, 48));
	if (*g_ptr14FA8 == 288)
	{
		word64 x30_494;
		av(x30, out x30_494);
		word64 x30_495;
		av(x30, out x30_495);
		struct Eq_1988 * x29_349;
		word64 x30_350;
		x29_349->dw0034 = ac(out x29_349, out x30_350);
		word64 x30_496;
		av(x30_350, out x30_496);
		struct Eq_2002 * x29_366;
		word64 x30_367;
		word64 x19_368;
		word32 x1_32_32_379 = SLICE(S(x19, x30_350, out x19_368, out x29_366, out x30_367), word32, 32);
		if (*g_ptr14FA8 == 0x0138)
		{
			word64 x30_497;
			av(x30_367, out x30_497);
			word64 x1_396;
			x29_366->t003C = I(0x00, out x1_396);
			H(x29_366->t0034, SLICE(x1_396, word32, 32));
			struct Eq_2043 * x29_413;
			word64 x19_498;
			word64 x30_499;
			x1_112 = H(x29_413->t003C, SLICE(S(x19_368, x30_367, out x19_498, out x29_413, out x30_499), word32, 32));
		}
		else
			x1_112 = H(x29_366->t0034, x1_32_32_379);
	}
	else if ((uint32) (uint8) ((uint32) (uint8) (word32) (*g_ptr14FA8 == 0x0160) | (uint32) ((uint8) ((word32) (*g_ptr14FA8 == 0x01F8)))) != 0x00)
	{
		Eq_110 w0_162 = *g_ptr14FA8;
		word64 x30_500;
		av(x30, out x30_500);
		word64 x30_501;
		av(x30, out x30_501);
		if (w0_162 == 0x0160)
		{
			struct Eq_2088 * x29_277;
			x29_277->dw0034 = ac(out x29_277, out x30);
		}
		else
		{
			if (*g_ptr14FA8 != 0x3B)
			{
				word64 x29_506;
				word64 x30_507;
				B(out x29_506, out x30_507);
			}
			word64 x30_505;
			av(x30, out x30_505);
			if (*g_ptr14FA8 != 0x3B)
				x29_211->dw0034 = ac(out x29_211, out x30);
			word64 x30_510;
			av(x30, out x30_510);
			if (*g_ptr14FA8 != 0x29)
			{
				word64 x1_517;
				x29_211->t0038 = I(0x00, out x1_517);
				word64 x29_518;
				word64 x30_519;
				B(out x29_518, out x30_519);
				word64 x1_253;
				I(x29_211->dw003C - *g_ptr14F60 - 0x05, out x1_253);
				H(x29_211->t0038, SLICE(x1_253, word32, 32));
				x29_211->dw003C = (word32) ((word64) x29_211->t0038 + 4);
			}
		}
		word64 x30_502;
		av(x30, out x30_502);
		struct Eq_2100 * x29_302;
		word64 x19_503;
		word64 x30_504;
		S(x19, x30, out x19_503, out x29_302, out x30_504);
		word64 x1_318;
		I(x29_302->dw003C - *g_ptr14F60 - 0x05, out x1_318);
		x1_112 = H(x29_302->t0034, SLICE(x1_318, word32, 32));
	}
	else if (*g_ptr14FA8 == 0x7B)
	{
		word64 x30_508;
		av(x30, out x30_508);
		word64 x29_509;
		word64 x30_128;
		word64 x19_129 = ar(x30, out x29_509, out x30_128);
		while (*g_ptr14FA8 != 0x7D)
		{
			word64 x29_515;
			S(x19_129, x30_128, out x19_129, out x29_515, out x30_128);
		}
		word64 x30_516;
		x1_112 = av(x30_128, out x30_516);
	}
	else
	{
		if (*g_ptr14FA8 == 448)
		{
			word64 x30_511;
			av(x30, out x30_511);
			if (*g_ptr14FA8 != 0x3B)
			{
				word64 x29_513;
				word64 x30_514;
				B(out x29_513, out x30_514);
			}
			word64 x1_512;
			*g_ptr14F98 = (union Eq_110 *) I(*g_ptr14F98, out x1_512);
		}
		else if (*g_ptr14FA8 == 400)
		{
			word64 x30_521;
			av(x30, out x30_521);
			word64 x1_522;
			null[(int64) dwLoc22_445 /64 4].t0000 = I(null[(int64) dwLoc22_445 /64 4].t0000, out x1_522);
		}
		else if (*g_ptr14FA8 != 0x3B)
		{
			word64 x29_523;
			word64 x30_524;
			B(out x29_523, out x30_524);
		}
		word64 x30_520;
		x1_112 = av(x30, out x30_520);
	}
	x19Out = qwLoc30;
	x29Out = (struct Eq_279 *) <invalid>;
	x30Out = (struct Eq_279 *) <invalid>;
	return x1_112;
}

// 00000000000023C8: Register word64 ar(Register word64 x30, Register out ptr64 x29Out, Register out ptr64 x30Out)
// Called from:
//      S
//      main
word64 ar(word64 x30, ptr64 & x29Out, ptr64 & x30Out)
{
	word32 sp_32_32_259 = SLICE(fp + -40, word32, 32);
	struct Eq_2323 * x29_149 = fp + -40;
	while (true)
	{
		Eq_110 w0_23 = *g_ptr14FA8;
		struct Eq_2331 * sp_264 = SEQ(sp_32_32_259, (word64) w0_23 + 1);
		if (((uint32) (uint8) (word32) (*g_ptr14FA8 == 0x0100) | (uint32) ((uint8) ((uint32) ((uint8) ((word32) (w0_23 != 0x01))) & (uint32) ((uint8) ((word32) (x29_149->dw001C == 0x00)))))) == 0x00)
			break;
		if (*g_ptr14FA8 == 0x0100)
		{
			word64 x30_294;
			av(x30, out x30_294);
			while (*g_ptr14FA8 != 0x3B)
			{
				if (x29_149->dw001C != 0x00)
				{
					*g_ptr14F38 = (union Eq_110 *) ((char *) *g_ptr14F38 + 4);
					null[(int64) *g_ptr14FA8 /64 4] = 0x00 - *g_ptr14F38;
				}
				else
				{
					null[(int64) *g_ptr14FA8 /64 4].t0000 = *g_ptr14FB0;
					*g_ptr14FB0 = (union Eq_110 *) ((char *) *g_ptr14FB0 + 4);
				}
				word64 x30_301;
				av(x30, out x30_301);
				if (*g_ptr14FA8 == 44)
				{
					word64 x30_303;
					av(x30, out x30_303);
				}
			}
			word64 x30_295;
			av(x30, out x30_295);
		}
		else
		{
			null[(int64) *g_ptr14FA8 /64 4].t0000 = *g_ptr14F60;
			word64 x30_292;
			av(x30, out x30_292);
			word64 x30_293;
			av(x30, out x30_293);
			x29_149->t002C.u0 = 0x08;
			while (*g_ptr14FA8 != 0x29)
			{
				null[(int64) *g_ptr14FA8 /64 4].t0000 = x29_149->t002C;
				x29_149->t002C.u3 = (word64) x29_149->t002C + 4;
				word64 x30_296;
				av(x30, out x30_296);
				if (*g_ptr14FA8 == 44)
				{
					word64 x30_302;
					av(x30, out x30_302);
				}
			}
			word64 x30_297;
			av(x30, out x30_297);
			*g_ptr14F38 = (union Eq_110 *) 0x00;
			*g_ptr14F98 = *g_ptr14F38;
			aw();
			struct Eq_2484 * x29_139;
			word64 x30_140;
			word64 x1_298;
			x29_139->t002C = x(0x00, out x1_298, out x29_139, out x30_140);
			word64 x19_300;
			H(*g_ptr14F98, SLICE(S(x19, x30_140, out x19_300, out x29_149, out x30), word32, 32));
			aw();
			E(x29_149->t002C, *g_ptr14F38);
			word64 sp_135 = <invalid>;
			sp_32_32_259 = SLICE(sp_135, word32, 32);
		}
	}
	ptr64 x30_268 = sp_264->ptr0008;
	x29Out = sp_264->ptr0000;
	x30Out = x30_268;
	return <invalid>;
}

// 0000000000002630: Register word64 ax(Register Eq_110 w0, Register out (ptr64 Eq_2599) x29Out)
// Called from:
//      ad
//      ae
//      au
word64 ax(Eq_110 w0, struct Eq_2599 & x29Out)
{
	word32 x1_32_32_34 = SLICE(E(*g_ptr14FB0, w0), word32, 32);
	Eq_110 w0_20 = *g_ptr14FB0;
	*g_ptr14FB0 = (word64) w0_20 + 4;
	x29Out = x30;
	return SEQ(x1_32_32_34, (word64) w0_20 + 4);
}

// 0000000000002678: void ad(Register Eq_110 w0)
// Called from:
//      au
void ad(Eq_110 w0)
{
	struct Eq_2626 * x29_18;
	ax(w0, out x29_18);
	x29_18->t001C.u3 = (word64) x29_18->t001C + 0x08048000;
	struct Eq_2639 * x29_29;
	ax(x29_18->t001C, out x29_29);
	struct Eq_2646 * x29_35;
	ax(x29_29->t001C, out x29_35);
	struct Eq_2653 * x29_41;
	ax(x29_35->t0018, out x29_41);
	word64 x29_58;
	ax(x29_41->t0018, out x29_58);
}

// 00000000000026D0: void ae(Register word32 x1_32_32)
// Called from:
//      au
void ae(word32 x1_32_32)
{
	struct Eq_2668 * x29_105 = fp + -56;
	while (true)
	{
		x29_105->t003C.u3 = (word64) x29_105->t003C + 1;
		x29_105->t0030 = x29_105->t003C;
		while ((word32) null[(int64) x29_105->dw001E] != 0x20 && x29_105->t003C < *g_ptr14F20)
			x29_105->t003C.u3 = (word64) x29_105->t003C + 1;
		if (x29_105->t003C == *g_ptr14F20)
			break;
		*g_ptr14FA8 = (union Eq_110 *) ((x29_105->t0030 - *g_ptr14FA0 << 3) + *g_ptr14F30 + 0xF8);
		x29_105->dw002C = null[(int64) *g_ptr14FA8 /64 4];
		x29_105->t0038 = null[(int64) ((char *) *g_ptr14FA8 + 4) /64 4].t0000;
		if (x29_105->t0038 != 0x00 && x29_105->dw002C != 0x01)
		{
			if (x29_105->dw002C == 0x00)
			{
				if (x29_105->dw001C == 0x00)
				{
					void * x0_216 = (int64) x29_105->dw0018;
					memcpy((int64) *g_ptr14FB0, x0_216, (int64) (x29_105->t003C - x29_105->t0030));
					Mem237[Mem83[0x0000000000014FB0<p64>:word64] + 0x00:word32] = Mem83[Mem83[0x0000000000014FB0<p64>:word64] + 0x00:word32] + Mem83[x29_105 + 60:word32] - Mem83[x29_105 + 48:word32] + 0x01;
					x1_32_32 = SLICE(x0_216, word32, 32);
				}
				else if (x29_105->dw001C == 0x01)
				{
					word64 x29_279;
					ax((word64) x29_105->t0034 + 22, out x29_279);
					word64 x29_280;
					ax(0x00, out x29_280);
					word64 x29_281;
					ax(0x00, out x29_281);
					x1_32_32 = SLICE(ax(0x10, out x29_105), word32, 32);
					Mem209[x29_105 + 52:word32] = Mem83[x29_105 + 52:word32] + Mem83[x29_105 + 60:word32] - Mem83[x29_105 + 48:word32] + 0x01;
				}
				else
				{
					x29_105->t0034.u3 = (word64) x29_105->t0034 + 1;
					while (x29_105->t0038 != 0x00)
					{
						x29_105->t0030 = ao(x29_105->t0038);
						x29_105->dw0028 = (uint32) (uint8) (word32) ((word32) null[(int64) (x29_105->t0038 - 0x01)] != 0x05);
						E(x29_105->t0038, 0x00 - x29_105->dw0028 << 2);
						struct Eq_2950 * x29_164;
						ax((char *) *g_ptr14F48 + (x29_105->t0038 - *g_ptr14F90) + *g_ptr14FC0, out x29_164);
						x1_32_32 = SLICE(ax((x29_164->dw0034 << 8) + x29_164->dw0028 + 0x01, out x29_105), word32, 32);
						x29_105->t0038 = x29_105->t0030;
					}
				}
			}
			else if (x29_105->dw001C == 0x00)
				x1_32_32 = SLICE(ap(x29_105->t0038, SEQ(x1_32_32, x29_105->dw002C), out x29_105), word32, 32);
		}
	}
}

// 0000000000002998: void au()
// Called from:
//      main
void au()
{
	*g_ptr14F48 = *g_ptr14FB0;
	*g_ptr14F60 = *g_ptr14F90;
	aw();
	struct Eq_3018 * x29_60;
	word64 x30_683;
	word64 x1_682;
	x(null[(int64) (*g_ptr14F30 + 0x0250) /64 4] - *g_ptr14F60 - 0x05, out x1_682, out x29_60, out x30_683);
	aw();
	M(0x01);
	aw();
	*g_ptr14FB0 = (union Eq_110 *) ((char *) *g_ptr14FB0 + x29_60->dw0048);
	x29_60->t0044 = *g_ptr14FB0;
	*g_ptr14FB0 = (union Eq_110 *) ((char *) *g_ptr14FB0 + 1);
	struct Eq_3086 * x0_112 = (int64) *g_ptr14FB0;
	x0_112->qw0000 = g_qw42A0;
	x0_112->w0008 = g_w42A8;
	*g_ptr14FB0 = (union Eq_110 *) ((word32) x0_112 + 0x0A);
	struct Eq_3111 * x0_132 = (int64) *g_ptr14FB0;
	x0_132->qw0000 = g_qw42B0;
	x0_132->dw0007 = g_dw42B7;
	*g_ptr14FB0 = (union Eq_110 *) ((word32) x0_132 + 11);
	ae(SLICE(0x42B0, word32, 32));
	x29_60->dw0040 = *g_ptr14FB0 - x29_60->t0044;
	*g_ptr14FB0 = (union Eq_110 *) ((char *) *g_ptr14FB0 + 3 & ~0x03);
	x29_60->t003C = *g_ptr14FB0;
	word64 x29_684;
	ax(0x00, out x29_684);
	word64 x29_685;
	ax(0x00, out x29_685);
	word64 x29_686;
	ax(0x00, out x29_686);
	struct Eq_3190 * x29_196;
	ae(SLICE(ax(0x00, out x29_196), word32, 32));
	x29_196->t0038 = *g_ptr14FB0;
	int32 w0_214 = *g_ptr14FB0 - x29_196->dw003C;
	x29_196->dw0034 = (w0_214 < 0x00 ? w0_214 + 0x0F : w0_214) >> 4;
	struct Eq_3226 * x29_225;
	ax(0x01, out x29_225);
	word64 x29_687;
	ax(x29_225->t0034, out x29_687);
	word64 x29_688;
	ax(0x01, out x29_688);
	struct Eq_3243 * x29_243;
	ax(0x00, out x29_243);
	x29_243->t004C.u0 = 0x02;
	while (x29_243->t004C < x29_243->t0034)
	{
		Eq_110 w0_253 = x29_243->t004C;
		x29_243->t004C.u3 = (word64) w0_253 + 1;
		ax(w0_253, out x29_243);
	}
	struct Eq_3271 * x29_265;
	word32 x1_32_32_272 = SLICE(ax(0x00, out x29_265), word32, 32);
	x29_265->t0030 = *g_ptr14FB0;
	ae(x1_32_32_272);
	memcpy((int64) *g_ptr14F48, (int64) *g_ptr14F90, (int64) x29_265->dw0024);
	x29_265->t002C = *g_ptr14FB0;
	*g_ptr14FB0 = *g_ptr14F88;
	word64 x29_689;
	ax(0x464C457F, out x29_689);
	word64 x29_690;
	ax(0x00010101, out x29_690);
	word64 x29_691;
	ax(0x00, out x29_691);
	word64 x29_692;
	ax(0x00, out x29_692);
	word64 x29_693;
	ax(0x00030002, out x29_693);
	word64 x29_694;
	ax(0x01, out x29_694);
	word64 x29_695;
	ax((char *) *g_ptr14F48 + *g_ptr14FC0, out x29_695);
	word64 x29_696;
	ax(0x30, out x29_696);
	word64 x29_697;
	ax(0x00, out x29_697);
	word64 x29_698;
	ax(0x00, out x29_698);
	word64 x29_699;
	ax(0x00200034, out x29_699);
	word64 x29_700;
	ax(0x03, out x29_700);
	word64 x29_701;
	ax(0x03, out x29_701);
	ad(0x90);
	word64 x29_702;
	ax(0x04, out x29_702);
	word64 x29_703;
	ax(0x01, out x29_703);
	word64 x29_704;
	ax(0x01, out x29_704);
	ad(0x00);
	word64 x29_705;
	ax(0x07, out x29_705);
	word64 x29_706;
	ax(0x1000, out x29_706);
	word64 x29_707;
	ax(0x02, out x29_707);
	ad(0xA4);
	word64 x29_708;
	ax(0x06, out x29_708);
	word64 x29_709;
	ax(0x04, out x29_709);
	struct Eq_3449 * x0_461 = (int64) *g_ptr14FB0;
	word64 x1_470 = g_qw42C8;
	x0_461->qw0000 = g_qw42C0;
	x0_461->qw0008 = x1_470;
	x0_461->dw000F = g_dw42CF;
	*g_ptr14FB0 = (union Eq_110 *) ((word32) x0_461 + 0x14);
	word64 x29_710;
	ax(0x01, out x29_710);
	word64 x29_711;
	ax(0x01, out x29_711);
	word64 x29_712;
	ax(0x01, out x29_712);
	word64 x29_713;
	ax(11, out x29_713);
	struct Eq_3500 * x29_514;
	ax(0x04, out x29_514);
	word64 x29_714;
	ax(*g_ptr14FC0 + x29_514->dw0038, out x29_714);
	struct Eq_3518 * x29_530;
	ax(0x06, out x29_530);
	word64 x29_715;
	ax(*g_ptr14FC0 + x29_530->dw003C, out x29_715);
	struct Eq_3536 * x29_546;
	ax(0x05, out x29_546);
	word64 x29_716;
	ax(*g_ptr14FC0 + x29_546->dw0044, out x29_716);
	struct Eq_3554 * x29_562;
	ax(0x0A, out x29_562);
	word64 x29_717;
	ax(x29_562->t0040, out x29_717);
	word64 x29_718;
	ax(11, out x29_718);
	word64 x29_719;
	ax(0x10, out x29_719);
	struct Eq_3576 * x29_586;
	ax(0x11, out x29_586);
	word64 x29_720;
	ax(*g_ptr14FC0 + x29_586->dw0030, out x29_720);
	struct Eq_3594 * x29_602;
	ax(0x12, out x29_602);
	word64 x29_721;
	ax(x29_602->dw002C - x29_602->dw0030, out x29_721);
	word64 x29_722;
	ax(0x13, out x29_722);
	word64 x29_723;
	ax(0x08, out x29_723);
	word64 x29_724;
	ax(0x00, out x29_724);
	struct Eq_3625 * x29_634;
	ax(0x00, out x29_634);
	x29_634->dw004C = (word32) fopen((int64) x29_634->dw000E, "w");
	x0_664 = (uint64) fwrite((int64) *g_ptr14F88, 0x01, (int64) (x29_634->dw002C - *g_ptr14F88), (int64) x29_634->dw0026);
	x0_668 = (uint64) fclose((int64) x29_634->dw0026);
}

// 0000000000002F7C: void main(Register int32 w0)
void main(int32 w0)
{
	if (w0 <= 0x02)
		x0_197 = (uint64) puts("usage: otccelf file.c outfile");
	else
	{
		*g_ptr14FA0 = (word32) calloc(0x01, 99999);
		struct Eq_3700 * x0_30 = (int64) *g_ptr14FA0;
		word64 x3_38 = g_qw4308;
		x0_30->qw0000 = g_qw4300;
		x0_30->qw0008 = x3_38;
		word64 x3_46 = g_qw4318;
		x0_30->qw0010 = g_qw4310;
		x0_30->qw0018 = x3_46;
		word64 x3_54 = g_qw4328;
		x0_30->qw0020 = g_qw4320;
		x0_30->qw0028 = x3_54;
		x0_30->b0030 = g_b4330;
		*g_ptr14F20 = (union Eq_110 *) ((word32) x0_30 + 0x30);
		*g_ptr14F88 = (union Eq_110 *) (word32) calloc(0x01, 99999);
		*g_ptr14FB0 = *g_ptr14F88;
		*g_ptr14F90 = (union Eq_110 *) (word32) calloc(0x01, 99999);
		*g_ptr14F60 = *g_ptr14F90;
		*g_ptr14F30 = (word32) calloc(0x01, 99999);
		*g_ptr14F70 = (word32) fopen((int64) null[(int64) dwLoc0C /64 4], "r");
		*g_ptr14FC0 = 0x08048000 - *g_ptr14F88;
		*g_ptr14FB0 = (union Eq_110 *) ((char *) *g_ptr14FB0 + 252);
		*g_ptr14F60 = (union Eq_110 *) ((char *) *g_ptr14F60 + 0x0011);
		word64 x30_157;
		word64 x29_238;
		w(out x29_238, out x30_157);
		word64 x30_239;
		av(x30_157, out x30_239);
		struct Eq_3864 * x29_173;
		word64 x30_240;
		ar(x30_157, out x29_173, out x30_240);
		x29_173->dw0018 += 0x04;
		au();
	}
}

// 0000000000003188: void e843419@0008_00000059_8c(Register (ptr64 word32) x0, Register word32 w1)
void e843419@0008_00000059_8c(word32 * x0, word32 w1)
{
	*x0 = w1;
	word64 x30_15;
	fn0000000000001008(out x30_15);
}

// 0000000000004188: void __libc_csu_init(Register word32 w0, Register word64 x1, Register word64 x2, Register word64 x24)
void __libc_csu_init(word32 w0, word64 x1, word64 x2, word64 x24)
{
	word32 x24_32_32_100 = SLICE(x24, word32, 32);
	int64 x20_26 = 85256 - 0x00014D00;
	<anonymous> * x21_24[] = g_a14D00;
	word64 x22_34 = x2;
	word64 x23_38 = x1;
	word64 x30_42;
	word64 x29_41 = _init(out x30_42);
	int64 x20_43 = x20_26 >> 3;
	if (x20_26 >> 3 != 0x00)
	{
		int64 x19_44 = 0x00;
		word64 x24_145 = SEQ(x24_32_32_100, w0);
		do
		{
			word64 x3_74;
			x21_24[x19_44]();
			int64 x31_77 = x20_43 - x19_44;
		} while (x31_77 != 0x00);
	}
}

// 0000000000004200: void __libc_csu_fini()
void __libc_csu_fini()
{
}

