// subject.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0000000000000660: Register ptr64 _init(Stack word64 qwArg00)
ptr64 _init(word64 qwArg00)
{
	call_weak_fn();
	return fp + 0x08;
}

// 00000000000006A0: void fn00000000000006A0()
void fn00000000000006A0()
{
	<anonymous> * x17_4 = globals->ptr11000;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 00000000000006B0: void fn00000000000006B0()
void fn00000000000006B0()
{
	<anonymous> * x17_4 = globals->ptr11008;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 00000000000006D0: void fn00000000000006D0()
void fn00000000000006D0()
{
	<anonymous> * x17_4 = globals->ptr11018;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 00000000000006E0: void fn00000000000006E0()
void fn00000000000006E0()
{
	<anonymous> * x17_4 = globals->ptr11020;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 00000000000006F0: void main()
void main()
{
	ui32 w6_40;
	word32 w7_10 = 0x09;
	for (w6_40 = 0x07; w6_40 != 0x03; w6_40 -= 0x02)
	{
		if (w7_10 != 0x01)
		{
			int32 w3_88;
			int32 w5_89 = w6_40 - 0x01 - (w6_40 & ~0x01);
			do
			{
				word32 w20_96;
				word32 w21_97;
				word32 w22_98;
				word32 w23_99;
				word32 w24_100;
				word32 w25_101;
				word32 w26_102;
				word32 w27_103;
				word32 w28_104;
				word64 x29_105;
				word64 sp_106;
				fib(w3_88, dwArg00, out w20_96, out w21_97, out w22_98, out w23_99, out w24_100, out w25_101, out w26_102, out w27_103, out w28_104, out x29_105, out sp_106);
				w3_88 -= 0x02;
			} while (w3_88 != w5_89);
		}
		w7_10 -= 0x02;
	}
	fn00000000000006E0();
}

// 000000000000077C: void _start(Stack word64 qwArg00)
void _start(word64 qwArg00)
{
	fn00000000000006B0();
	fn00000000000006D0();
	call_weak_fn();
}

// 00000000000007B4: void call_weak_fn()
void call_weak_fn()
{
	word64 x0_4 = globals->qw10FC0;
	if (x0_4 == 0x00)
		return;
	<anonymous> * x17_10 = globals->ptr11010;
	word64 sp_12;
	word64 x0_13;
	word64 x16_14;
	word64 x17_15;
	x17_10();
}

// 00000000000007C8: void deregister_tm_clones()
void deregister_tm_clones()
{
	if (69695 - 69688 <= 0x0E)
		return;
	<anonymous> * x1_18 = globals->ptr10FB0;
	if (x1_18 == null)
		return;
	word64 sp_19;
	word64 x1_20;
	word64 x0_21;
	byte NZCV_22;
	byte ZC_23;
	x1_18();
}

// 0000000000000800: void register_tm_clones()
void register_tm_clones()
{
	int64 x1_6 = 69688 - 69688;
	if ((x1_6 >> 0x03) + ((x1_6 >> 0x03) >>u 0x003F) >> 0x01 == 0x00)
		return;
	<anonymous> * x2_18 = globals->ptr10FE0;
	if (x2_18 == null)
		return;
	word64 sp_19;
	word64 x1_20;
	word64 x0_21;
	word64 x2_22;
	x2_18();
}

// 0000000000000840: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	if ((word32) globals->b11038 == 0x00)
	{
		if (globals->qw10FB8 != 0x00)
			fn00000000000006A0();
		deregister_tm_clones();
		globals->b11038 = 0x01;
	}
}

// 0000000000000888: void frame_dummy(Stack word64 qwArg00)
void frame_dummy(word64 qwArg00)
{
	if (globals->qw10DB8 != 0x00)
	{
		<anonymous> * x1_21 = globals->ptr10FD8;
		if (x1_21 != null)
		{
			word64 sp_27;
			word64 x0_28;
			word64 x1_29;
			word64 x29_30;
			word64 x30_31;
			word64 x2_32;
			x1_21();
			register_tm_clones();
			return;
		}
	}
	register_tm_clones();
}

// 00000000000008C0: Register word32 fib(Register int32 w0, Stack word32 dwArg00, Register out Eq_70 w20Out, Register out Eq_71 w21Out, Register out Eq_72 w22Out, Register out Eq_73 w23Out, Register out Eq_74 w24Out, Register out Eq_75 w25Out, Register out Eq_76 w26Out, Register out Eq_77 w27Out, Register out Eq_78 w28Out, Register out (ptr64 Eq_79) x29Out, Register out ptr64 spOut)
word32 fib(int32 w0, word32 dwArg00, Eq_70 & w20Out, Eq_71 & w21Out, Eq_72 & w22Out, Eq_73 & w23Out, Eq_74 & w24Out, Eq_75 & w25Out, Eq_76 & w26Out, Eq_77 & w27Out, Eq_78 & w28Out, Eq_79 * & x29Out, ptr64 & spOut)
{
	struct Eq_225 * sp_148 = fp + -200;
	struct Eq_229 * x29_11 = fp + -200;
	if (w0 > 0x01)
	{
		do
		{
			int32 w1_149 = x29_11[0x004A];
			int32 w0_152 = w1_149;
			if (w1_149 != 0x01)
			{
				struct Eq_237 * v27_194 = x29_11 + 0x0056;
				v27_194->dw0000 = w1_149 - 0x01;
				v27_194->dw0004 = w1_149 - 0x03;
				x29_11[0x0062] = (struct Eq_229) 0x00;
				do
				{
					ui32 w0_231;
					if (x29_11[0x0056] != 0x01)
					{
						word32 w1_265 = w0_152 - 0x02;
						ui32 w0_268 = x29_11[88];
						x29_11[0x0040] = (struct Eq_229) w1_265;
						struct Eq_279 * v28_271 = x29_11 + 0x0046;
						v28_271->dw0000 = w1_265;
						word32 w0_266 = w0_152 - 0x04;
						v28_271->dw0004 = w0_266;
						x29_11[0x005C] = (struct Eq_229) 0x00;
						x29_11[0x0038] = (struct Eq_229) (w0_266 - (w0_268 & ~0x01));
						do
						{
							int32 w1_301 = x29_11[0x0046];
							int32 w0_304 = w1_301;
							if (w1_301 != 0x01)
							{
								struct Eq_305 * v29_347 = x29_11 + 0x0052;
								v29_347->dw0000 = w1_301 - 0x01;
								v29_347->dw0004 = w1_301 - 0x03;
								x29_11[0x0060] = (struct Eq_229) 0x00;
								do
								{
									ui32 w0_385;
									if (x29_11[0x0052] != 0x01)
									{
										word32 w1_419 = w0_304 - 0x02;
										ui32 w0_422 = x29_11[0x0054];
										x29_11[0x003E] = (struct Eq_229) w1_419;
										struct Eq_347 * v30_425 = x29_11 + 66;
										v30_425->dw0000 = w1_419;
										word32 w0_420 = w0_304 - 0x04;
										v30_425->dw0004 = w0_420;
										x29_11[0x005A] = (struct Eq_229) 0x00;
										x29_11[0x0036] = (struct Eq_229) (w0_420 - (w0_422 & ~0x01));
										do
										{
											int32 w0_454 = x29_11[66];
											int32 w25_457 = w0_454;
											if (w0_454 != 0x01)
											{
												struct Eq_373 * v32_500 = x29_11 + 0x004E;
												v32_500->dw0000 = w0_454 - 0x01;
												v32_500->dw0004 = w0_454 - 0x03;
												x29_11[0x005E] = (struct Eq_229) 0x00;
												do
												{
													word32 w26_546;
													ui32 w0_536;
													if (x29_11[0x004E] != 0x01)
													{
														int32 w0_571 = w25_457 - 0x02;
														ui32 w1_570 = x29_11[0x0050];
														x29_11[0x003C] = (struct Eq_229) w0_571;
														ui32 w25_572 = w25_457 - 0x04;
														x29_11[0x0066] = (struct Eq_229) (w25_572 - (w1_570 & ~0x01));
														int32 w24_574;
														w26_546 = 0x00;
														do
														{
															word32 w27_622;
															int32 w20_606 = w24_574;
															if (w24_574 != 0x01)
															{
																ui32 w22_640 = w24_574 - 0x01;
																w27_622 = 0x00;
																do
																{
																	ui32 w0_674;
																	word32 w20_673;
																	int32 w28_667 = w20_606 - 0x02;
																	if (w22_640 != 0x01)
																	{
																		int32 w19_700 = w28_667;
																		do
																		{
																			word32 w20_709;
																			ui32 w21_710;
																			int32 w23_712;
																			w19_700 = fib(w19_700, 0x00, out w20_709, out w21_710, out w22_640, out w23_712, out w24_574, out w25_572, out w26_546, out w27_622, out w28_667, out x29_11, out sp_148);
																			w20_673 = w20_709 + w19_700;
																		} while (w23_712 != w19_700);
																		w0_674 = w21_710 & 0x01;
																	}
																	else
																	{
																		w0_674 = w22_640;
																		w20_673 = 0x00;
																	}
																	w27_622 += w0_674 + w20_673;
																	w22_640 -= 0x02;
																	w20_606 = w28_667;
																} while (w28_667 > 0x01);
																w20_606 = w25_572 & 0x01;
															}
															else
																w27_622 = 0x00;
															w24_574 -= 0x02;
															w25_572 -= 0x02;
															w26_546 += w20_606 + w27_622;
														} while (x29_11[0x0066] != w24_574);
														w0_536 = x29_11[0x0050] & 0x01;
													}
													else
													{
														w0_536 = (ui32) x29_11[0x004E];
														x29_11[0x003C] = (struct Eq_229) (w25_457 - 0x02);
														w26_546 = 0x00;
													}
													w25_457 = (int32) x29_11[0x003C];
													x29_11[0x005E] = (struct Eq_229) ((word16) x29_11[0x005E] + (w0_536 + w26_546));
													x29_11[0x004E] = (struct Eq_229) (x29_11[0x004E] - 0x02);
													x29_11[0x0050] = (struct Eq_229) (x29_11[0x0050] - 0x02);
												} while (w25_457 > 0x01);
												w25_457 = x29_11[0x0044] & 0x01;
											}
											else
												x29_11[0x005E] = (struct Eq_229) 0x00;
											word32 w0_482 = x29_11[66];
											word32 w25_483 = (word16) x29_11[0x005E] + w25_457;
											word32 w1_485 = x29_11[0x0036];
											x29_11[66] = (struct Eq_229) (w0_482 - 0x02);
											x29_11[0x005A] = (struct Eq_229) ((word16) x29_11[0x005A] + w25_483);
											x29_11[0x0044] = (struct Eq_229) (x29_11[0x0044] - 0x02);
										} while (w1_485 != w0_482 - 0x02);
										w0_385 = x29_11[0x0054] & 0x01;
									}
									else
									{
										x29_11[0x005A] = (struct Eq_229) 0x00;
										x29_11[0x003E] = (struct Eq_229) (w0_304 - 0x02);
										w0_385 = (ui32) x29_11[0x0052];
									}
									word32 w1_407 = x29_11[0x0052];
									x29_11[0x0060] = (struct Eq_229) ((word16) x29_11[0x0060] + ((word16) x29_11[0x005A] + w0_385));
									w0_304 = (int32) x29_11[0x003E];
									x29_11[0x0052] = (struct Eq_229) (w1_407 - 0x02);
									x29_11[0x0054] = (struct Eq_229) (x29_11[0x0054] - 0x02);
								} while (w0_304 > 0x01);
								w0_304 = x29_11[0x0048] & 0x01;
							}
							else
								x29_11[0x0060] = (struct Eq_229) 0x00;
							word32 w1_333 = x29_11[0x0038];
							x29_11[0x005C] = (struct Eq_229) ((word16) x29_11[0x005C] + ((word16) x29_11[0x0060] + w0_304));
							word32 w0_335 = x29_11[0x0046];
							x29_11[0x0046] = (struct Eq_229) (w0_335 - 0x02);
							x29_11[0x0048] = (struct Eq_229) (x29_11[0x0048] - 0x02);
						} while (w1_333 != w0_335 - 0x02);
						w0_231 = x29_11[88] & 0x01;
					}
					else
					{
						x29_11[0x005C] = (struct Eq_229) 0x00;
						x29_11[0x0040] = (struct Eq_229) (w0_152 - 0x02);
						w0_231 = (ui32) x29_11[0x0056];
					}
					w0_152 = (int32) x29_11[0x0040];
					x29_11[0x0062] = (struct Eq_229) ((word16) x29_11[0x0062] + ((word16) x29_11[0x005C] + w0_231));
					x29_11[0x0056] = (struct Eq_229) (x29_11[0x0056] - 0x02);
					x29_11[88] = (struct Eq_229) (x29_11[88] - 0x02);
				} while (w0_152 > 0x01);
				w0_152 = x29_11[0x004C] & 0x01;
			}
			else
				x29_11[0x0062] = (struct Eq_229) 0x00;
			word32 w1_177 = x29_11[0x004A];
			word32 w0_178 = (word16) x29_11[0x0062] + w0_152;
			word32 w2_179 = x29_11[0x003A];
			x29_11[0x004A] = (struct Eq_229) (w1_177 - 0x02);
			x29_11[100] = (struct Eq_229) ((word16) x29_11[100] + w0_178);
			x29_11[0x004C] = (struct Eq_229) (x29_11[0x004C] - 0x02);
		} while (w2_179 != w1_177 - 0x02);
	}
	struct Eq_592 * v43_56 = sp_148 + 0x08;
	struct Eq_595 * v44_63 = sp_148 + 0x0010;
	struct Eq_598 * v45_69 = sp_148 + 0x0018;
	struct Eq_601 * v46_75 = sp_148 + 0x0020;
	struct Eq_604 * v47_81 = sp_148 + 0x0028;
	word32 w20_61;
	*w20Out = (word32) v43_56->qw0008;
	word32 w21_65;
	*w21Out = (word32) v44_63->qw0000;
	word32 w22_68;
	*w22Out = (word32) v44_63->qw0008;
	word32 w23_71;
	*w23Out = (word32) v45_69->qw0000;
	word32 w24_74;
	*w24Out = (word32) v45_69->qw0008;
	word32 w25_77;
	*w25Out = (word32) v46_75->qw0000;
	word32 w26_80;
	*w26Out = (word32) v46_75->qw0008;
	word32 w27_83;
	*w27Out = (word32) v47_81->qw0000;
	word32 w28_86;
	*w28Out = (word32) v47_81->qw0008;
	word64 x29_88;
	*x29Out = sp_148->qw0000;
	word64 sp_91;
	*spOut = sp_148 + 0x0068;
	return (word32) v43_56->qw0000;
}

// 0000000000000CA8: void __libc_csu_init(Register word64 x30, Stack word64 qwArg00)
void __libc_csu_init(word64 x30, word64 qwArg00)
{
	<anonymous> * x21_23[] = globals->a10DA8;
	word64 sp_38 = _init(x30);
	if (0x00010DB0 - 0x00010DA8 >> 0x03 != 0x00)
	{
		ui64 x19_71 = 0x00;
		do
		{
			<anonymous> * x3_77 = x21_23[x19_71];
			word64 sp_82;
			word64 x29_83;
			word64 x30_84;
			word64 x22_86;
			word64 x20_88;
			word64 x23_89;
			word64 x24_90;
			word64 x2_91;
			word32 w0_92;
			word32 w24_93;
			word64 x1_94;
			word64 x3_95;
			word64 x31_96;
			byte NZCV_97;
			bool Z_98;
			x3_77();
		} while (x20_88 - x19_71 != 0x00);
	}
}

// 0000000000000D20: void __libc_csu_fini()
void __libc_csu_fini()
{
}

// 0000000000000D24: void _fini(Stack word64 qwArg00)
void _fini(word64 qwArg00)
{
}

