// subject_code.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0C00:0100: void fn0C00_0100(Sequence (ptr32 Eq_13) ds_bx, Register (memptr (ptr16 Eq_19) byte) di)
void fn0C00_0100(union Eq_13 * ds_bx, byte Eq_19::* di)
{
	bool C;
	word16 bx = (word16) ds_bx;
	__syscall<byte>(0x10);
	Eq_13 es_cx_8 = ds_bx->u1;
	word16 cx_10 = (word16) es_cx_8;
	struct Eq_19 * es_51 = SLICE(es_cx_8, selector, 16);
	do
	{
		ui8 al_13 = (byte) cx_10;
		__out<byte>(969, al_13);
		__out<byte>(969, al_13);
		__out<byte>(969, al_13);
		--cx_10;
	} while (cx_10 != 0x00);
	while (true)
	{
		word16 bx_16 = bx + 0x01;
		byte bh_48 = SLICE(bx_16, byte, 8);
		word16 cx_60 = cx_10;
		do
		{
			al_13 = al_13 + SLICE(cx_65, byte, 8) + (byte) C & 0x7F ^ bh_48;
			es_51->*di = al_13;
			byte cl_34 = (byte) cx_65;
			byte ch_47 = SLICE(cx_65 - 0x01, byte, 8);
			C = false;
			++di;
			bx = bx_16;
			cx_60 = SEQ(ch_47, cl_34 - 0x01);
			cx_65 = cx_60;
		} while (cx_65 != 0x01);
		cx_10 = SEQ(ch_47, cl_34 - 0x01);
	}
}

