// subject_bss.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

byte g_b14060 = 0x00; // 0000000000014060
byte g_b14067 = 0x00; // 0000000000014067
// subject_data.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

word64 g_qw14058 = 82008; // 0000000000014058
// subject_fini.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 00000000000016AC: void _fini()
void _fini()
{
}

// subject_got.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

<anonymous> * __libc_csu_fini_GOT = __libc_csu_fini; // 0000000000013FA8
<anonymous> * g_ptr13FB0 = null; // 0000000000013FB0
word64 g_qw13FB8 = 0x00; // 0000000000013FB8
word64 g_qw13FC0 = 0x00; // 0000000000013FC0
<anonymous> * __libc_csu_init_GOT = __libc_csu_init; // 0000000000013FC8
<anonymous> * main_GOT = main; // 0000000000013FD0
<anonymous> * g_ptr13FD8 = null; // 0000000000013FD8
<anonymous> * g_ptr13FE0 = null; // 0000000000013FE0
// subject_got_plt.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

struct Eq_1402 g_t14000 = // 0000000000014000
	{
		0x00,
	};
// subject_init.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0000000000000778: void _init()
// Called from:
//      __libc_csu_init
void _init()
{
	call_weak_fn();
}

// subject_init_array.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

<anonymous> * g_a13DA8[] = // 0000000000013DA8
	{
	};
// subject_jcr.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

word64 g_qw13DB8 = 0x00; // 0000000000013DB8
// subject_rodata.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

void g_v16C0 = ??void??; // 00000000000016C0
// subject_text.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0000000000000850: void main(Register (ptr64 (ptr64 char)) x1)
void main(char ** x1)
{
	printf("with single ' quote %p\n", strchr(*x1, '''));
	printf("with double \" quote %p\n", strchr(*x1, '\"'));
	FILE * x0_39 = fopen("with-null-byte", "w");
	fwrite(&g_v16C0, 0x11, 0x01, x0_39);
	fwrite(&g_v16C0, 0x01, 0x11, x0_39);
	fclose(x0_39);
	puts("hex=0x01 dec=1 char=\x01FINI");
	puts("hex=0x02 dec=2 char=\x02FINI");
	puts("hex=0x03 dec=3 char=\x03FINI");
	puts("hex=0x04 dec=4 char=\x04FINI");
	puts("hex=0x05 dec=5 char=\x05FINI");
	puts("hex=0x06 dec=6 char=\x06FINI");
	puts("hex=0x07 dec=7 char=\aFINI");
	puts("hex=0x08 dec=8 char=\bFINI");
	puts("hex=0x09 dec=9 char=\tFINI");
	puts("hex=0x0a dec=10 char=\nFINI");
	puts("hex=0x0b dec=11 char=\vFINI");
	puts("hex=0x0c dec=12 char=\fFINI");
	puts("hex=0x0d dec=13 char=\rFINI");
	puts("hex=0x0e dec=14 char=\x0EFINI");
	puts("hex=0x0f dec=15 char=\x0FFINI");
	puts("hex=0x10 dec=16 char=\x10FINI");
	puts("hex=0x11 dec=17 char=\x11FINI");
	puts("hex=0x12 dec=18 char=\x12FINI");
	puts("hex=0x13 dec=19 char=\x13FINI");
	puts("hex=0x14 dec=20 char=\x14FINI");
	puts("hex=0x15 dec=21 char=\x15FINI");
	puts("hex=0x16 dec=22 char=\x16FINI");
	puts("hex=0x17 dec=23 char=\x17FINI");
	puts("hex=0x18 dec=24 char=\x18FINI");
	puts("hex=0x19 dec=25 char=\x19FINI");
	puts("hex=0x1a dec=26 char=\x1AFINI");
	puts("hex=0x1b dec=27 char=\x1BFINI");
	puts("hex=0x1c dec=28 char=\x1CFINI");
	puts("hex=0x1d dec=29 char=\x1DFINI");
	puts("hex=0x1e dec=30 char=\x1EFINI");
	puts("hex=0x1f dec=31 char=\x1FFINI");
	puts("hex=0x20 dec=32 char= FINI");
	puts("hex=0x21 dec=33 char=!FINI");
	puts("hex=0x22 dec=34 char=\"FINI");
	puts("hex=0x23 dec=35 char=#FINI");
	puts("hex=0x24 dec=36 char=$FINI");
	puts("hex=0x25 dec=37 char=%FINI");
	puts("hex=0x26 dec=38 char=&FINI");
	puts("hex=0x27 dec=39 char='FINI");
	puts("hex=0x28 dec=40 char=(FINI");
	puts("hex=0x29 dec=41 char=)FINI");
	puts("hex=0x2a dec=42 char=*FINI");
	puts("hex=0x2b dec=43 char=+FINI");
	puts("hex=0x2c dec=44 char=,FINI");
	puts("hex=0x2d dec=45 char=-FINI");
	puts("hex=0x2e dec=46 char=.FINI");
	puts("hex=0x2f dec=47 char=/FINI");
	puts("hex=0x30 dec=48 char=0FINI");
	puts("hex=0x31 dec=49 char=1FINI");
	puts("hex=0x32 dec=50 char=2FINI");
	puts("hex=0x33 dec=51 char=3FINI");
	puts("hex=0x34 dec=52 char=4FINI");
	puts("hex=0x35 dec=53 char=5FINI");
	puts("hex=0x36 dec=54 char=6FINI");
	puts("hex=0x37 dec=55 char=7FINI");
	puts("hex=0x38 dec=56 char=8FINI");
	puts("hex=0x39 dec=57 char=9FINI");
	puts("hex=0x3a dec=58 char=:FINI");
	puts("hex=0x3b dec=59 char=;FINI");
	puts("hex=0x3c dec=60 char=<FINI");
	puts("hex=0x3d dec=61 char==FINI");
	puts("hex=0x3e dec=62 char=>FINI");
	puts("hex=0x3f dec=63 char=?FINI");
	puts("hex=0x40 dec=64 char=@FINI");
	puts("hex=0x41 dec=65 char=AFINI");
	puts("hex=0x42 dec=66 char=BFINI");
	puts("hex=0x43 dec=67 char=CFINI");
	puts("hex=0x44 dec=68 char=DFINI");
	puts("hex=0x45 dec=69 char=EFINI");
	puts("hex=0x46 dec=70 char=FFINI");
	puts("hex=0x47 dec=71 char=GFINI");
	puts("hex=0x48 dec=72 char=HFINI");
	puts("hex=0x49 dec=73 char=IFINI");
	puts("hex=0x4a dec=74 char=JFINI");
	puts("hex=0x4b dec=75 char=KFINI");
	puts("hex=0x4c dec=76 char=LFINI");
	puts("hex=0x4d dec=77 char=MFINI");
	puts("hex=0x4e dec=78 char=NFINI");
	puts("hex=0x4f dec=79 char=OFINI");
	puts("hex=0x50 dec=80 char=PFINI");
	puts("hex=0x51 dec=81 char=QFINI");
	puts("hex=0x52 dec=82 char=RFINI");
	puts("hex=0x53 dec=83 char=SFINI");
	puts("hex=0x54 dec=84 char=TFINI");
	puts("hex=0x55 dec=85 char=UFINI");
	puts("hex=0x56 dec=86 char=VFINI");
	puts("hex=0x57 dec=87 char=WFINI");
	puts("hex=0x58 dec=88 char=XFINI");
	puts("hex=0x59 dec=89 char=YFINI");
	puts("hex=0x5a dec=90 char=ZFINI");
	puts("hex=0x5b dec=91 char=[FINI");
	puts("hex=0x5c dec=92 char=\\FINI");
	puts("hex=0x5d dec=93 char=]FINI");
	puts("hex=0x5e dec=94 char=^FINI");
	puts("hex=0x5f dec=95 char=_FINI");
	puts("hex=0x60 dec=96 char=`FINI");
	puts("hex=0x61 dec=97 char=aFINI");
	puts("hex=0x62 dec=98 char=bFINI");
	puts("hex=0x63 dec=99 char=cFINI");
	puts("hex=0x64 dec=100 char=dFINI");
	puts("hex=0x65 dec=101 char=eFINI");
	puts("hex=0x66 dec=102 char=fFINI");
	puts("hex=0x67 dec=103 char=gFINI");
	puts("hex=0x68 dec=104 char=hFINI");
	puts("hex=0x69 dec=105 char=iFINI");
	puts("hex=0x6a dec=106 char=jFINI");
	puts("hex=0x6b dec=107 char=kFINI");
	puts("hex=0x6c dec=108 char=lFINI");
	puts("hex=0x6d dec=109 char=mFINI");
	puts("hex=0x6e dec=110 char=nFINI");
	puts("hex=0x6f dec=111 char=oFINI");
	puts("hex=0x70 dec=112 char=pFINI");
	puts("hex=0x71 dec=113 char=qFINI");
	puts("hex=0x72 dec=114 char=rFINI");
	puts("hex=0x73 dec=115 char=sFINI");
	puts("hex=0x74 dec=116 char=tFINI");
	puts("hex=0x75 dec=117 char=uFINI");
	puts("hex=0x76 dec=118 char=vFINI");
	puts("hex=0x77 dec=119 char=wFINI");
	puts("hex=0x78 dec=120 char=xFINI");
	puts("hex=0x79 dec=121 char=yFINI");
	puts("hex=0x7a dec=122 char=zFINI");
	puts("hex=0x7b dec=123 char={FINI");
	puts("hex=0x7c dec=124 char=|FINI");
	puts("hex=0x7d dec=125 char=}FINI");
	puts("hex=0x7e dec=126 char=~FINI");
	puts("hex=0x7f dec=127 char=\x7FFINI");
	puts("hex=0x80 dec=128 char=\x80FINI");
	puts("hex=0x81 dec=129 char=\x81FINI");
	puts("hex=0x82 dec=130 char=\x82FINI");
	puts("hex=0x83 dec=131 char=\x83FINI");
	puts("hex=0x84 dec=132 char=\x84FINI");
	puts("hex=0x85 dec=133 char=\x85FINI");
	puts("hex=0x86 dec=134 char=\x86FINI");
	puts("hex=0x87 dec=135 char=\x87FINI");
	puts("hex=0x88 dec=136 char=\x88FINI");
	puts("hex=0x89 dec=137 char=\x89FINI");
	puts("hex=0x8a dec=138 char=\x8AFINI");
	puts("hex=0x8b dec=139 char=\x8BFINI");
	puts("hex=0x8c dec=140 char=\x8CFINI");
	puts("hex=0x8d dec=141 char=\x8DFINI");
	puts("hex=0x8e dec=142 char=\x8EFINI");
	puts("hex=0x8f dec=143 char=\x8FFINI");
	puts("hex=0x90 dec=144 char=\x90FINI");
	puts("hex=0x91 dec=145 char=\x91FINI");
	puts("hex=0x92 dec=146 char=\x92FINI");
	puts("hex=0x93 dec=147 char=\x93FINI");
	puts("hex=0x94 dec=148 char=\x94FINI");
	puts("hex=0x95 dec=149 char=\x95FINI");
	puts("hex=0x96 dec=150 char=\x96FINI");
	puts("hex=0x97 dec=151 char=\x97FINI");
	puts("hex=0x98 dec=152 char=\x98FINI");
	puts("hex=0x99 dec=153 char=\x99FINI");
	puts("hex=0x9a dec=154 char=\x9AFINI");
	puts("hex=0x9b dec=155 char=\x9BFINI");
	puts("hex=0x9c dec=156 char=\x9CFINI");
	puts("hex=0x9d dec=157 char=\x9DFINI");
	puts("hex=0x9e dec=158 char=\x9EFINI");
	puts("hex=0x9f dec=159 char=\x9FFINI");
	puts("hex=0xa0 dec=160 char=\xA0FINI");
	puts("hex=0xa1 dec=161 char=\xA1FINI");
	puts("hex=0xa2 dec=162 char=\xA2FINI");
	puts("hex=0xa3 dec=163 char=\xA3FINI");
	puts("hex=0xa4 dec=164 char=\xA4FINI");
	puts("hex=0xa5 dec=165 char=\xA5FINI");
	puts("hex=0xa6 dec=166 char=\xA6FINI");
	puts("hex=0xa7 dec=167 char=\xA7FINI");
	puts("hex=0xa8 dec=168 char=\xA8FINI");
	puts("hex=0xa9 dec=169 char=\xA9FINI");
	puts("hex=0xaa dec=170 char=\xAAFINI");
	puts("hex=0xab dec=171 char=\xABFINI");
	puts("hex=0xac dec=172 char=\xACFINI");
	puts("hex=0xad dec=173 char=\xADFINI");
	puts("hex=0xae dec=174 char=\xAEFINI");
	puts("hex=0xaf dec=175 char=\xAFFINI");
	puts("hex=0xb0 dec=176 char=\xB0FINI");
	puts("hex=0xb1 dec=177 char=\xB1FINI");
	puts("hex=0xb2 dec=178 char=\xB2FINI");
	puts("hex=0xb3 dec=179 char=\xB3FINI");
	puts("hex=0xb4 dec=180 char=\xB4FINI");
	puts("hex=0xb5 dec=181 char=\xB5FINI");
	puts("hex=0xb6 dec=182 char=\xB6FINI");
	puts("hex=0xb7 dec=183 char=\xB7FINI");
	puts("hex=0xb8 dec=184 char=\xB8FINI");
	puts("hex=0xb9 dec=185 char=\xB9FINI");
	puts("hex=0xba dec=186 char=\xBAFINI");
	puts("hex=0xbb dec=187 char=\xBBFINI");
	puts("hex=0xbc dec=188 char=\xBCFINI");
	puts("hex=0xbd dec=189 char=\xBDFINI");
	puts("hex=0xbe dec=190 char=\xBEFINI");
	puts("hex=0xbf dec=191 char=\xBFFINI");
	puts("hex=0xc0 dec=192 char=\xC0FINI");
	puts("hex=0xc1 dec=193 char=\xC1FINI");
	puts("hex=0xc2 dec=194 char=\xC2FINI");
	puts("hex=0xc3 dec=195 char=\xC3FINI");
	puts("hex=0xc4 dec=196 char=\xC4FINI");
	puts("hex=0xc5 dec=197 char=\xC5FINI");
	puts("hex=0xc6 dec=198 char=\xC6FINI");
	puts("hex=0xc7 dec=199 char=\xC7FINI");
	puts("hex=0xc8 dec=200 char=\xC8FINI");
	puts("hex=0xc9 dec=201 char=\xC9FINI");
	puts("hex=0xca dec=202 char=\xCAFINI");
	puts("hex=0xcb dec=203 char=\xCBFINI");
	puts("hex=0xcc dec=204 char=\xCCFINI");
	puts("hex=0xcd dec=205 char=\xCDFINI");
	puts("hex=0xce dec=206 char=\xCEFINI");
	puts("hex=0xcf dec=207 char=\xCFFINI");
	puts("hex=0xd0 dec=208 char=\xD0FINI");
	puts("hex=0xd1 dec=209 char=\xD1FINI");
	puts("hex=0xd2 dec=210 char=\xD2FINI");
	puts("hex=0xd3 dec=211 char=\xD3FINI");
	puts("hex=0xd4 dec=212 char=\xD4FINI");
	puts("hex=0xd5 dec=213 char=\xD5FINI");
	puts("hex=0xd6 dec=214 char=\xD6FINI");
	puts("hex=0xd7 dec=215 char=\xD7FINI");
	puts("hex=0xd8 dec=216 char=\xD8FINI");
	puts("hex=0xd9 dec=217 char=\xD9FINI");
	puts("hex=0xda dec=218 char=\xDAFINI");
	puts("hex=0xdb dec=219 char=\xDBFINI");
	puts("hex=0xdc dec=220 char=\xDCFINI");
	puts("hex=0xdd dec=221 char=\xDDFINI");
	puts("hex=0xde dec=222 char=\xDEFINI");
	puts("hex=0xdf dec=223 char=\xDFFINI");
	puts("hex=0xe0 dec=224 char=\xE0FINI");
	puts("hex=0xe1 dec=225 char=\xE1FINI");
	puts("hex=0xe2 dec=226 char=\xE2FINI");
	puts("hex=0xe3 dec=227 char=\xE3FINI");
	puts("hex=0xe4 dec=228 char=\xE4FINI");
	puts("hex=0xe5 dec=229 char=\xE5FINI");
	puts("hex=0xe6 dec=230 char=\xE6FINI");
	puts("hex=0xe7 dec=231 char=\xE7FINI");
	puts("hex=0xe8 dec=232 char=\xE8FINI");
	puts("hex=0xe9 dec=233 char=\xE9FINI");
	puts("hex=0xea dec=234 char=\xEAFINI");
	puts("hex=0xeb dec=235 char=\xEBFINI");
	puts("hex=0xec dec=236 char=\xECFINI");
	puts("hex=0xed dec=237 char=\xEDFINI");
	puts("hex=0xee dec=238 char=\xEEFINI");
	puts("hex=0xef dec=239 char=\xEFFINI");
	puts("hex=0xf0 dec=240 char=\xF0FINI");
	puts("hex=0xf1 dec=241 char=\xF1FINI");
	puts("hex=0xf2 dec=242 char=\xF2FINI");
	puts("hex=0xf3 dec=243 char=\xF3FINI");
	puts("hex=0xf4 dec=244 char=\xF4FINI");
	puts("hex=0xf5 dec=245 char=\xF5FINI");
	puts("hex=0xf6 dec=246 char=\xF6FINI");
	puts("hex=0xf7 dec=247 char=\xF7FINI");
	puts("hex=0xf8 dec=248 char=\xF8FINI");
	puts("hex=0xf9 dec=249 char=\xF9FINI");
	puts("hex=0xfa dec=250 char=\xFAFINI");
	puts("hex=0xfb dec=251 char=\xFBFINI");
	puts("hex=0xfc dec=252 char=\xFCFINI");
	puts("hex=0xfd dec=253 char=\xFDFINI");
	puts("hex=0xfe dec=254 char=\xFEFINI");
	puts("hex=0xff dec=255 char=\xFFFINI");
}

// 00000000000014EC: void _start(Register (ptr64 Eq_1341) x0, Stack word32 dwArg00, Stack (ptr64 char) ptrArg08)
void _start(void (* x0)(), word32 dwArg00, char * ptrArg08)
{
	void * fp;
	word64 qwArg00;
	__libc_start_main(main_GOT, (int32) qwArg00, &ptrArg08, __libc_csu_init_GOT, __libc_csu_fini_GOT, x0, fp);
	abort();
}

// 0000000000001524: void call_weak_fn()
// Called from:
//      _init
void call_weak_fn()
{
	if (g_qw13FC0 == 0x00)
		return;
	__gmon_start__();
}

// 0000000000001538: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
	if (&g_b14067 - &g_b14060 <= 0x0E)
		return;
	<anonymous> * x1_13 = g_ptr13FB0;
	if (x1_13 == null)
		return;
	x1_13();
}

// 0000000000001570: void register_tm_clones()
// Called from:
//      frame_dummy
void register_tm_clones()
{
	byte * x1_7 = &g_b14060 - &g_b14060;
	if ((x1_7 >> 3) + ((x1_7 >> 3) >>u 63) >> 1 == 0x00)
		return;
	<anonymous> * x2_13 = g_ptr13FE0;
	if (x2_13 == null)
		return;
	word64 x2_17;
	x2_13();
}

// 00000000000015B0: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	struct Eq_1402 * x19_11 = &g_t14000;
	if ((word32) g_b14060 == 0x00)
	{
		if (g_qw13FB8 != 0x00)
			__cxa_finalize(&g_t14000, g_qw14058);
		deregister_tm_clones();
		x19_11->b0060 = 0x01;
	}
}

// 00000000000015F8: void frame_dummy(Register word64 x29, Register word64 x30)
void frame_dummy(word64 x29, word64 x30)
{
	ptr64 fp;
	if (g_qw13DB8 != 0x00)
	{
		<anonymous> * x1_8 = g_ptr13FD8;
		if (x1_8 != null)
		{
			x1_8();
			register_tm_clones();
			return;
		}
	}
	register_tm_clones();
}

// 0000000000001630: void __libc_csu_init(Register word32 w0, Register word64 x1, Register word64 x2, Register word64 x24, Register word64 x30)
void __libc_csu_init(word32 w0, word64 x1, word64 x2, word64 x24, word64 x30)
{
	ptr64 fp;
	word32 x24_32_32_89 = SLICE(x24, word32, 32);
	_init();
	int64 x20_23 = 81328 - g_a13DA8;
	ptr64 x29_49 = fp + -64;
	<anonymous> * x21_21[] = g_a13DA8;
	word64 x22_30 = x2;
	word64 x23_34 = x1;
	int64 x20_36 = x20_23 >> 3;
	if (x20_23 >> 3 != 0x00)
	{
		int64 x19_37 = 0x00;
		word64 x24_133 = SEQ(x24_32_32_89, w0);
		do
		{
			word64 x3_67;
			x21_21[x19_37]();
			int64 x31_70 = x20_36 - x19_37;
		} while (x31_70 != 0x00);
	}
}

// 00000000000016A8: void __libc_csu_fini()
void __libc_csu_fini()
{
}

