/* r2dec pseudo code output */
/* SUBJECTS/from_internet/asmutils/truss/ia32_elf/subject.exe @ 0x8048b82 */
#include <stdint.h>
 
int32_t entry0 (int32_t arg_4h) {
    ebp = esp + ecx*4 + 4;
    ecx--;
    if (ecx == 0) {
        goto label_2;
    }
    eax = 2;
    eax = syscall_80h (ebx, ecx, edx, esi, edi, edp);
    *(0x8048d47) = eax;
    eax |= eax;
    if (eax < 0) {
        goto label_2;
    }
    if (eax == 0) {
        goto label_3;
    }
    esi = 0;
    edx = 0;
    ecx = 0;
    eax = 0x72;
    eax = sys_wait4 (0xffffffff, ecx, edx, esi);
    eax |= eax;
    if (eax < 0) {
        goto label_2;
    }
    esi = 0;
    edx = 1;
    ebx = 0x18;
    eax = 0x1a;
    eax = sys_ptrace (0x18, 0x8048d47, 0x1, esi);
    do {
        esi = 0;
        edx = 0;
        ecx = 0;
        eax = 0x72;
        eax = sys_wait4 (0xffffffff, ecx, edx, esi);
        eax |= eax;
        if (eax < 0) {
            goto label_2;
        }
        edx = 0;
        ebx = 0xc;
        eax = 0x1a;
        eax = sys_ptrace (0xc, 0x8048d47, edx, 0x804906b);
        ecx = *(0x8049097);
        edi = *((ecx*4 + 0x80487cb));
        eax = 0;
        ecx = 0;
        ecx--;
        __asm ("repne scasb al, byte es:[edi]");
        edi = edi + ecx + 1;
        ecx = ~ecx;
        ecx--;
        ebx = 1;
        eax = 4;
        eax = sys_write (0x1, 0xed, 0xec);
        edx = 4;
        ebx = 1;
        eax = 4;
        eax = sys_write (0x1, 0x8048d43, 0x4);
        esi = 0;
        edx = 1;
        ebx = 0x18;
        eax = 0x1a;
        eax = sys_ptrace (0x18, 0x8048d47, 0x1, esi);
        esi = 0;
        edx = 0;
        ecx = 0;
        eax = 0x72;
        eax = sys_wait4 (0xffffffff, ecx, edx, esi);
        edx = 0;
        ebx = 0xc;
        eax = 0x1a;
        eax = sys_ptrace (0xc, 0x8048d47, edx, 0x804906b);
        edi = 0x8048d9b;
        ecx = *(0x8049083);
        eax = fcn_08048b47 ();
        ebx = 1;
        eax = 4;
        eax = sys_write (0x1, 0x8048d9b, 0xea);
        edx = 1;
        ebx = 1;
        eax = 4;
        eax = sys_write (0x1, 0x8048d42, 0x1);
        esi = 0;
        edx = 1;
        ebx = 0x18;
        eax = 0x1a;
        eax = sys_ptrace (0x18, 0x8048d47, 0x1, esi);
    } while (1);
label_3:
    esi = 0;
    edx = 0;
    ecx = 0;
    ebx = 0;
    eax = 0x1a;
    eax = sys_ptrace (ebx, ecx, edx, esi);
    ecx = 0;
    esi = *(esp);
    if (*(esi) == 0x2f) {
        goto label_4;
    }
    if (*(esi) == 0x2e) {
        goto label_4;
    }
    do {
label_0:
        esi = *((ebp + ecx*4));
        esi |= esi;
        if (esi == 0) {
            goto label_2;
        }
        eax = *(esi);
        esi += 4;
        ecx++;
    } while (eax != 0x48544150);
    al = *(esi);
    esi++;
    if (al != 0x3d) {
        goto label_0;
    }
    eax = 0;
    ecx = 0;
    ecx--;
    edi = esi;
    __asm ("repne scasb al, byte es:[edi]");
    edx = ecx;
    ecx = 0;
    ecx--;
    edi = *(esp);
    __asm ("repne scasb al, byte es:[edi]");
    ecx += edx;
label_1:
    edi = esp + ecx;
    do {
        al = *(esi);
        esi++;
        if (al == 0x3a) {
            goto label_5;
        }
        *(es:edi) = al;
        es:edi++;
        al |= al;
    } while (al != 0);
label_5:
    esi = *((esp + 4));
    al = 0x2f;
    *(es:edi) = al;
    es:edi++;
    do {
        al = *(esi);
        esi++;
        *(es:edi) = al;
        es:edi++;
        al |= al;
    } while (al != 0);
    ebx = esp + ecx + 4;
    edi = ecx;
    eax = 0xb;
    eax = sys_execve (ebx, 0xe, 0xeb, esi);
    ecx = edi;
    goto label_1;
label_4:
    eax = 0xb;
    eax = sys_execve (0xe, 0xe, 0xeb, esi);
label_2:
    ebx = 1;
    eax = 1;
    eax = sys_exit (0x1);
    ah |= *(eax);
    eax -= 0x203e;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
    *(eax) += al;
}
/* r2dec pseudo code output */
/* SUBJECTS/from_internet/asmutils/truss/ia32_elf/subject.exe @ 0x8048b47 */
#include <stdint.h>
 
uint32_t fcn_08048b47 (void) {
    __asm ("std");
    edi += 7;
    edx = 8;
    do {
        al = cl;
        al &= 0xf;
        al += 0x30;
        if (al > 0x39) {
            al += 0x27;
        }
        *(es:edi) = al;
        es:edi++;
        ecx >>= 4;
        if (ecx == 0) {
            goto label_0;
        }
        edx--;
    } while (edx != 0);
label_0:
    esi = edi;
    edi--;
    ecx = edx;
    eax = edx - 9;
    eax = -eax;
    ecx = eax + 1;
    *(es:edi) = *(esi);
    ecx--;
    esi++;
    es:edi++;
    *((edi + eax)) = 0;
    return eax;
}
