//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x804804c - 0x80480d9
int32_t entry_point(int32_t a1, int32_t a2, int32_t a3) {
    int32_t v1 = a2;
    int32_t v2 = a1 - 1; // 0x8048052
    int32_t v3 = &v1; // 0x8048053
    int32_t v4 = v2; // 0x8048053
    int32_t v5; // 0x804804c
    int32_t v6; // 0x804804c
    int32_t v7; // 0x804804c
    int32_t v8; // 0x804804c
    int32_t v9; // 0x804805b
    if (v2 == 0 || v2 > 2) {
        goto lab_0x804809c;
    } else {
        // 0x804805a
        int32_t v10; // bp+12, 0x804804c
        v9 = &v10;
        v7 = 0;
        v8 = v9;
        v4 = v2;
        if (*(char *)a3 != 0) {
            int32_t v11 = a3 + 1; // 0x8048065
            int32_t v12 = v11; // 0x8048069
            while (*(char *)v11 != 0) {
                // 0x8048065
                v11 = v12 + 1;
                v12 = v11;
            }
            v5 = v11;
            int32_t v13 = v5 - 1; // 0x804806d
            v7 = 0;
            v8 = v9;
            v4 = v2;
            while (v13 >= a3) {
                // 0x8048076
                v6 = v5;
                if (*(char *)v13 != 47) {
                    goto lab_0x804807e;
                }
                v5 = v13;
                v13 = v5 - 1;
                v7 = 0;
                v8 = v9;
                v4 = v2;
            }
        }
        goto lab_0x804808d;
    }
  lab_0x804807e:;
    int32_t v14 = v6 - 1; // 0x804807e
    int32_t v15 = v6; // 0x8048082
    int32_t v16 = v5; // 0x8048082
    int32_t v17 = v9; // 0x8048082
    int32_t v18 = v2; // 0x8048082
    if (*(char *)v14 == 47) {
        goto lab_0x80480a2;
    } else {
        // 0x8048084
        v6 = v14;
        v15 = a3;
        v16 = v5;
        v17 = v9;
        v18 = v2;
        if (v14 == a3) {
            goto lab_0x80480a2;
        } else {
            goto lab_0x804807e;
        }
    }
  lab_0x804809c:
    // 0x804809c
    *(int32_t *)(v3 - 4) = 1;
    __asm_int(128);
    v15 = 2;
    int32_t v19; // 0x804804c
    v16 = v19;
    v17 = v3;
    v18 = v4;
    goto lab_0x80480a2;
  lab_0x80480a2:;
    int32_t v20 = v17;
    int32_t v21 = v16;
    int32_t v22 = v15;
    int32_t v23 = v21 - v22; // 0x80480a4
    int32_t v24 = v18 - 1; // 0x80480a6
    int32_t v25 = v22; // 0x80480a7
    v7 = v23;
    v8 = v20;
    v4 = 0;
    if (v24 != 0) {
        int32_t * v26 = (int32_t *)v20;
        int32_t v27 = *v26; // 0x80480a9
        *v26 = v22;
        int32_t * v28 = (int32_t *)(v20 - 4);
        *v28 = v23;
        int32_t v29 = v23; // 0x80480b3
        int32_t v30 = v27; // 0x80480b3
        if (*(char *)v27 != 0) {
            int32_t v31 = v30;
            int32_t v32 = v31 + 1; // 0x80480b5
            while (*(char *)v32 != 0) {
                // 0x80480b5
                v31 = v32;
                v32 = v31 + 1;
            }
            // 0x80480bb
            v29 = v23;
            if (v32 - v27 < v23) {
                // 0x80480c1
                *(int32_t *)(v20 - 8) = v32;
                int32_t v33 = v32; // 0x80480c3
                int32_t v34 = v21; // 0x80480c3
                v33--;
                while (*(char *)(v34 - 1) == *(char *)v33) {
                    // 0x80480c4
                    v34--;
                    // 0x80480cc
                    if (v33 == v27) {
                        // 0x80480d0
                        v25 = *v26;
                        v7 = v27 + -1 - v31 + *v28;
                        v8 = v20 + 4;
                        v4 = v24;
                        goto lab_0x804808d;
                    }
                    v33--;
                }
                // 0x804808b
                v29 = *v28;
            }
        }
        // 0x804808b
        v25 = *v26;
        v7 = v29;
        v8 = v20 + 4;
        v4 = v24;
    }
    goto lab_0x804808d;
  lab_0x804808d:
    // 0x804808d
    v3 = v8;
    *(char *)(v7 + v25) = 10;
    *(int32_t *)(v3 - 4) = 4;
    __asm_int(128);
    v19 = v7 + 1;
    goto lab_0x804809c;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (3.2.x)
// Detected functions: 1

