#define __MOD(a,b) a % b
/*****************************************************************************************/
/******                                                                             ******/
/******                            Structure Definitions                            ******/
/******                                                                             ******/
/*****************************************************************************************/
typedef char BOOLEAN;
typedef unsigned int size_t;
typedef enum  { NORECALL = 0, RECALL_URL = 1, RECALL_CMD = 2, RECALL_MAIL = 3, } RecallType;
typedef struct _win_st WINDOW;
typedef unsigned long chtype;
typedef chtype attr_t;
struct pdat {
     short _pad_y;
     short _pad_x;
     short _pad_top;
     short _pad_left;
     short _pad_bottom;
     short _pad_right;
  } ;
typedef int wchar_t;
typedef struct {
     attr_t attr;
     wchar_t chars[5];
  } cchar_t;
struct _win_st {
     short _cury;
     short _curx;
     short _maxy;
     short _maxx;
     short _begy;
     short _begx;
     short _flags;
     attr_t _attrs;
     chtype _bkgd;
     _Bool _notimeout;
     _Bool _clear;
     _Bool _leaveok;
     _Bool _scroll;
     _Bool _idlok;
     _Bool _idcok;
     _Bool _immed;
     _Bool _sync;
     _Bool _use_keypad;
     int _delay;
     struct ldat *_line;
     short _regtop;
     short _regbottom;
     int _parx;
     int _pary;
     WINDOW *_parent;
     struct pdat  _pad;
     short _yoffset;
     cchar_t _bkgrnd;
  } ;
typedef struct _IO_FILE FILE;
struct _IO_marker {
     struct _IO_marker *_next;
     struct _IO_FILE *_sbuf;
     int _pos;
  } ;
typedef long __off_t;
typedef void _IO_lock_t;
typedef long long __quad_t;
typedef __quad_t __off64_t;
struct _IO_FILE {
     int _flags;
     char *_IO_read_ptr;
     char *_IO_read_end;
     char *_IO_read_base;
     char *_IO_write_base;
     char *_IO_write_ptr;
     char *_IO_write_end;
     char *_IO_buf_base;
     char *_IO_buf_end;
     char *_IO_save_base;
     char *_IO_backup_base;
     char *_IO_save_end;
     struct _IO_marker *_markers;
     struct _IO_FILE *_chain;
     int _fileno;
     int _flags2;
     __off_t _old_offset;
     unsigned short _cur_column;
     char _vtable_offset;
     char _shortbuf[1];
     _IO_lock_t *_lock;
     __off64_t _offset;
     void *__pad1;
     void *__pad2;
     void *__pad3;
     void *__pad4;
     size_t __pad5;
     int _mode;
     char _unused2[40];
  } ;
typedef enum  { UIP_UNKNOWN = -1, UIP_HISTORY = 0, UIP_DOWNLOAD_OPTIONS = 1, UIP_PRINT_OPTIONS = 2, UIP_SHOWINFO = 3, UIP_LIST_PAGE = 4, UIP_VLINKS = 5, UIP_LYNXCFG = 6, UIP_OPTIONS_MENU = 7, UIP_DIRED_MENU = 8, UIP_PERMIT_OPTIONS = 9, UIP_UPLOAD_OPTIONS = 10, UIP_ADDRLIST_PAGE = 11, UIP_CONFIG_DEF = 12, UIP_TRACELOG = 13, UIP_INSTALL = 14, } UIP_t;
typedef struct {
     int value;
     char *LongName;
     char *HtmlName;
  } OptValues;
typedef struct {
     char *str;
     int len;
  } bstring;
typedef struct {
     char *title;
     char *address;
     bstring *post_data;
     char *post_content_type;
     char *bookmark;
     BOOLEAN isHEAD;
     BOOLEAN safe;
     int link;
     int line;
     BOOLEAN internal_link;
     char *style;
  } DocInfo;
typedef struct _DocAddress DocAddress;
struct _DocAddress {
     char *address;
     bstring *post_data;
     char *post_content_type;
     char *bookmark;
     BOOLEAN isHEAD;
     BOOLEAN safe;
     char __pad[2];
  } ;
typedef void (*__sighandler_t)( int  );
typedef unsigned short LYKeymap_t;
typedef struct _LYUCcharset LYUCcharset;
struct _LYUCcharset {
     int UChndl;
     char *MIMEname;
     int enc;
     int codepage;
     int repertoire;
     int codepoints;
     int cpranges;
     int like8859;
  } ;
typedef enum  { NOCJK = 0, JAPANESE = 1, CHINESE = 2, KOREAN = 3, TAIPEI = 4, } HTCJKlang;
/*****************************************************************************************/
/******                                                                             ******/
/******                          Function Prototypes                                ******/
/******                                                                             ******/
/*****************************************************************************************/
void cleanup_sig( int  );
char *LYstrncpy( char *, char *, int  );
int LYgetch_single( void );
int LYhandlePopupList( int , int , int , char **, int , int , int , BOOLEAN  );
int LYgetstr( char *, int , size_t , RecallType  );
char *LYstrsep( char **, char * );
void HTAlert( char * );
void HTAlwaysAlert( char *, char * );
void HTInfoMsg( char * );
void HTUserMsg( char * );
void HTUserMsg2( char *, char * );
char *HTProgressUnits( int  );
BOOLEAN confirm_post_resub( char *, char *, int , int  );
void LYSleepAlert( void );
void HTuncache_current_document( void );
BOOLEAN HTreparse_document( void );
BOOLEAN HTcan_reparse_document( void );
int HTisDocumentSource( void );
char *HTLoadedDocumentURL( void );
BOOLEAN HTLoadedDocumentIsHEAD( void );
void srcmode_for_next_retrieval( int  );
FILE *TraceFP( void );
void LYwaddnstr( WINDOW *, char *, size_t  );
int LYstrExtent( char *, int , int  );
void LYclear( void );
void LYclrtoeol( void );
void LYerase( void );
void LYmove( int , int  );
void LYrefresh( void );
void lynx_force_repaint( void );
void lynx_start_h1_color( void );
void lynx_stop_h1_color( void );
void lynx_start_prompt_color( void );
void lynx_stop_prompt_color( void );
void lynx_start_bold( void );
void lynx_start_reverse( void );
void lynx_stop_bold( void );
void lynx_stop_reverse( void );
void LYSetDisplayLines( void );
int LYindex2MBM( int  );
int LYMBM2index( int  );
void LYMBM_statusline( char * );
char *LYGetEnv( char * );
void statusline( char * );
BOOLEAN LYPathOffHomeOK( char *, size_t  );
void LYCloseTempFP( FILE * );
BOOLEAN LYIsUIPage3( char *, UIP_t , int  );
void LYRegisterUIPage( char *, UIP_t  );
void LYLocalFileToURL( char **, char * );
FILE *InternalPageFP( char *, int  );
void BeginInternalPage( FILE *, char *, char * );
void EndInternalPage( FILE * );
char *LYgetXDisplay( void );
void LYsetXDisplay( char * );
BOOLEAN LYCheckUserAgent( void );
void validate_x_display( void );
void summarize_x_display( char * );
void SetupChosenShowColor( void );
int add_it( char *, int  );
void addlbl( char * );
void LYoptions( void );
int widest_choice( char ** );
void show_choice( char *, int  );
int boolean_choice( int , int , int , char ** );
void terminate_options( int  );
void edit_bookmarks( void );
int popup_choice( int , int , int , char **, int , int , BOOLEAN  );
void PutOptValues( FILE *, int , OptValues * );
BOOLEAN GetOptValues( OptValues *, char *, int * );
PostPair *break_data( bstring * );
BOOLEAN isLynxOptionsPage( char *, char * );
int postoptions( DocInfo * );
char *NewSecureValue( void );
void PutLabel( FILE *, char *, char * );
char *check_if_write_lynxrc( char ** );
char *will_save_cookies( void );
char *will_save_images( void );
void LYMenuVisitedLinks( FILE *, int  );
int gen_options( char ** );
int LYpush( DocInfo *, BOOLEAN  );
void LYpop( DocInfo * );
int save_rc( FILE * );
BOOLEAN will_save_rc( char * );
void set_vi_keys( void );
void reset_vi_keys( void );
void set_emacs_keys( void );
void reset_emacs_keys( void );
void set_numbers_as_arrows( void );
void reset_numbers_as_arrows( void );
char *key_for_func_ext( int , int  );
BOOLEAN LYisNonAlnumKeyname( int , int  );
void outofmem( char *, char * );
void HTMLSetCharacterHandling( int  );
void HTMLSetUseDefaultRawMode( int , BOOLEAN  );
void HTMLUseCharacterSet( int  );
int UCGetLYhndl_byMIME( char * );
int safeUCGetLYhndl_byMIME( char * );
void LYFindLocaleCharset( void );
char *HTUnEscape( char * );
BOOLEAN HTLoadAbsolute( DocAddress * );
void HTSwitchDTD( int  );
int strncasecomp( char *, char *, int  );
char *HTSACopy( char **, char * );
char *HTSprintf0( char **, char *, ... );
void HTSABFree( bstring ** );
void HTFilterPresentations( void );
int sprintf( char *, char *, ... );
void *random( void );
int waddch( WINDOW *, unsigned long  );
__sighandler_t signal( int , __sighandler_t  );
void *realloc( void *, unsigned int  );
void *calloc( unsigned int , unsigned int  );
char *gettext( char * );
void free( void * );
short **__ctype_b_loc( void );
unsigned int strlen( char * );
int atoi( char * );
unsigned int fwrite( void *, unsigned int , unsigned int , FILE * );
int fprintf( FILE *, char *, ... );
char *strstr( char *, char * );
void *malloc( unsigned int  );
int has_colors( void );
void __stack_chk_fail( void );
int strncmp( char *, char *, unsigned int  );
int strcmp( char *, char * );
/*****************************************************************************************/
/******                                                                             ******/
/******                        Forward Var Declarations                             ******/
/******                                                                             ******/
/*****************************************************************************************/
extern BOOLEAN LYShowScrollbar;
extern int LYlines;
extern int LYcols;
extern BOOLEAN lynx_edit_mode;
extern BOOLEAN LYforce_no_cache;
extern BOOLEAN case_sensitive;
extern BOOLEAN dump_output_immediately;
extern BOOLEAN verbose_img;
extern char *helpfilepath;
extern int LYTransferRate;
extern int keypad_mode;
extern int user_mode;
extern BOOLEAN no_dotfiles;
extern BOOLEAN no_editor;
extern BOOLEAN no_lynxcfg_info;
extern BOOLEAN show_dotfiles;
extern char *personal_mail_address;
extern char *editor;
extern BOOLEAN enable_scrollback;
extern BOOLEAN clickable_images;
extern BOOLEAN pseudo_inline_alts;
extern BOOLEAN LYRawMode;
extern BOOLEAN LYUseDefaultRawMode;
extern char *UCAssume_MIMEcharset;
extern BOOLEAN LYSelectPopups;
extern int LYStatusLine;
extern BOOLEAN LYSetCookies;
extern BOOLEAN LYAcceptAllCookies;
extern int Old_DTD;
extern int dir_list_style;
extern BOOLEAN LYUseFormsOptions;
extern BOOLEAN LYShowCursor;
extern BOOLEAN LYoverride_no_cache;
extern BOOLEAN emacs_keys;
extern BOOLEAN vi_keys;
extern char *language;
extern char *pref_charset;
extern char *bookmark_page;
extern BOOLEAN HEAD_request;
extern char *LYUserAgent;
extern int LYMultiBookmarks;
extern WINDOW *LYwin;
extern int LYShowColor;
extern BOOLEAN LYCursesON;
extern BOOLEAN LYUnderlineLinks;
extern char *x_display;
extern char *MBM_A_subbookmark[26];
extern char *MBM_A_subdescript[26];
extern BOOLEAN no_bookmark;
extern BOOLEAN no_option_save;
extern BOOLEAN no_useragent;
extern BOOLEAN mustshow;
extern int dir_list_order;
extern int LYrcShowColor;
extern BOOLEAN system_editor;
extern int LYAcceptEncoding;
extern int LYAcceptMedia;
extern char *anonftp_password;
extern BOOLEAN no_margins;
extern char *LYUserAgentDefault;
extern BOOLEAN LYisConfiguredForX;
extern BOOLEAN LYMBMBlocked;
extern BOOLEAN ftp_passive;
extern int cookie_noprompt;
extern BOOLEAN LYLocaleCharset;
extern BOOLEAN term_options;
extern int Visited_Links_As;
extern LYKeymap_t keymap[661];
extern int current_lineedit;
extern char *LYLineeditNames[4];
extern BOOLEAN LYHaveCJKCharacterSet;
extern int current_char_set;
extern char *LYchar_set_names[61];
extern int LYNumCharsets;
extern LYUCcharset LYCharSet_UC[60];
extern int UCLYhndl_for_unspec;
extern BOOLEAN reloading;
extern int HTfileSortMethod;
extern HTCJKlang HTCJK;
extern BOOLEAN WWW_TraceFlag;
/*****************************************************************************************/
/******                                                                             ******/
/******                      Inline Function Definitions                            ******/
/******                                                                             ******/
/*****************************************************************************************/
