#define __MOD(a,b) a % b
/*****************************************************************************************/
/******                                                                             ******/
/******                            Structure Definitions                            ******/
/******                                                                             ******/
/*****************************************************************************************/
typedef struct _IO_FILE FILE;
struct _IO_marker {
     struct _IO_marker *_next;
     struct _IO_FILE *_sbuf;
     int _pos;
  } ;
typedef long __off_t;
typedef void _IO_lock_t;
typedef long long __quad_t;
typedef __quad_t __off64_t;
typedef unsigned int size_t;
struct _IO_FILE {
     int _flags;
     char *_IO_read_ptr;
     char *_IO_read_end;
     char *_IO_read_base;
     char *_IO_write_base;
     char *_IO_write_ptr;
     char *_IO_write_end;
     char *_IO_buf_base;
     char *_IO_buf_end;
     char *_IO_save_base;
     char *_IO_backup_base;
     char *_IO_save_end;
     struct _IO_marker *_markers;
     struct _IO_FILE *_chain;
     int _fileno;
     int _flags2;
     __off_t _old_offset;
     unsigned short _cur_column;
     char _vtable_offset;
     char _shortbuf[1];
     _IO_lock_t *_lock;
     __off64_t _offset;
     void *__pad1;
     void *__pad2;
     void *__pad3;
     void *__pad4;
     size_t __pad5;
     int _mode;
     char _unused2[40];
  } ;
typedef char BOOLEAN;
typedef enum  { UIP_UNKNOWN = -1, UIP_HISTORY = 0, UIP_DOWNLOAD_OPTIONS = 1, UIP_PRINT_OPTIONS = 2, UIP_SHOWINFO = 3, UIP_LIST_PAGE = 4, UIP_VLINKS = 5, UIP_LYNXCFG = 6, UIP_OPTIONS_MENU = 7, UIP_DIRED_MENU = 8, UIP_PERMIT_OPTIONS = 9, UIP_UPLOAD_OPTIONS = 10, UIP_ADDRLIST_PAGE = 11, UIP_CONFIG_DEF = 12, UIP_TRACELOG = 13, UIP_INSTALL = 14, } UIP_t;
typedef struct _lynx_list_item_type lynx_list_item_type;
struct _lynx_list_item_type {
     struct _lynx_list_item_type *next;
     char *name;
     char *command;
     int always_enabled;
     BOOLEAN override_primary_action;
     int pagelen;
  } ;
typedef enum  { HTL_comm = 0, HTL_tag = 1, HTL_attrib = 2, HTL_attrval = 3, HTL_abracket = 4, HTL_entity = 5, HTL_href = 6, HTL_entire = 7, HTL_badseq = 8, HTL_badtag = 9, HTL_badattr = 10, HTL_sgmlspecial = 11, HTL_num_lexemes = 12, } HTlexeme;
typedef BOOLEAN optidx_set_t[207];
typedef struct {
     char *str;
     int len;
  } bstring;
typedef struct {
     char *title;
     char *address;
     bstring *post_data;
     char *post_content_type;
     char *bookmark;
     BOOLEAN isHEAD;
     BOOLEAN safe;
     int link;
     int line;
     BOOLEAN internal_link;
     char *style;
  } DocInfo;
typedef struct {
     char *name;
     int value;
  } Config_Enum;
typedef struct _DocAddress DocAddress;
struct _DocAddress {
     char *address;
     bstring *post_data;
     char *post_content_type;
     char *bookmark;
     BOOLEAN isHEAD;
     BOOLEAN safe;
     char __pad[2];
  } ;
typedef enum  { ppUnknown = 0, ppBZIP2 = 1, ppCHMOD = 2, ppCOMPRESS = 3, ppCOPY = 4, ppCSWING = 5, ppGZIP = 6, ppINFLATE = 7, ppINSTALL = 8, ppMKDIR = 9, ppMV = 10, ppRLOGIN = 11, ppRM = 12, ppRMDIR = 13, ppSETFONT = 14, ppTAR = 15, ppTELNET = 16, ppTN3270 = 17, ppTOUCH = 18, ppUNCOMPRESS = 19, ppUNZIP = 20, ppUUDECODE = 21, ppZCAT = 22, ppZIP = 23, pp_Last = 24, } ProgramPaths;
typedef struct _HTList HTList;
struct _HTList {
     void *object;
     HTList *next;
  } ;
typedef enum  { mediaINT = 1, mediaEXT = 2, mediaCFG = 4, mediaUSR = 8, mediaSYS = 16, mediaOpt1 = 1, mediaOpt2 = 5, mediaOpt3 = 13, mediaOpt4 = 29, mediaALL = 31, } AcceptMedia;
typedef struct _HText HText;
typedef struct _HTParentAnchor HTParentAnchor;
typedef struct _HTParentAnchor0 HTParentAnchor0;
typedef struct _HTBTree_top HTBTree;
typedef int (*HTComparer)( void *, void * );
struct _HTBTree_element {
     void *object;
     struct _HTBTree_element *up;
     struct _HTBTree_element *left;
     int left_depth;
     struct _HTBTree_element *right;
     int right_depth;
  } ;
struct _HTBTree_top {
     HTComparer compare;
     struct _HTBTree_element *top;
  } ;
struct _HTParentAnchor0 {
     HTParentAnchor0 *parent;
     char *address;
     HTParentAnchor *info;
     HTBTree *children;
     HTList sources;
     HTList _add_adult;
     short adult_hash;
     BOOLEAN underway;
     char __pad[1];
  } ;
typedef struct _HyperDoc HyperDoc;
struct _HyperDoc  ;
typedef struct _HTAtom HTAtom;
struct _HTAtom {
     HTAtom *next;
     char *name;
  } ;
typedef HTAtom *HTFormat;
typedef struct _HTChunk HTChunk;
struct _HTChunk {
     int size;
     int growby;
     int allocated;
     char *data;
     int failok;
     HTChunk *next;
  } ;
typedef struct _UCAnchorInfo UCAnchorInfo;
typedef struct _LYUCcharset LYUCcharset;
struct _LYUCcharset {
     int UChndl;
     char *MIMEname;
     int enc;
     int codepage;
     int repertoire;
     int codepoints;
     int cpranges;
     int like8859;
  } ;
struct _UCStageInfo {
     int lock;
     int LYhndl;
     LYUCcharset C;
  } ;
struct _UCAnchorInfo {
     struct _UCStageInfo  s[4];
  } ;
struct _HTParentAnchor {
     HTParentAnchor0 *parent;
     HTList children_notag;
     HyperDoc *document;
     char *address;
     bstring *post_data;
     char *post_content_type;
     char *bookmark;
     HTFormat format;
     char *charset;
     BOOLEAN isIndex;
     char *isIndexAction;
     char *isIndexPrompt;
     char *title;
     char *owner;
     char *RevTitle;
     char *citehost;
     char *style;
     HTList *methods;
     void *protocol;
     char *physical;
     BOOLEAN isISMAPScript;
     BOOLEAN isHEAD;
     BOOLEAN safe;
     char *source_cache_file;
     HTChunk *source_cache_chunk;
     char *FileCache;
     char *SugFname;
     char *cache_control;
     BOOLEAN no_cache;
     BOOLEAN inBASE;
     char *content_type_params;
     char *content_type;
     char *content_language;
     char *content_encoding;
     char *content_base;
     char *content_disposition;
     char *content_location;
     char *content_md5;
     char *message_id;
     char *subject;
     int content_length;
     char *date;
     char *expires;
     char *last_modified;
     char *ETag;
     char *server;
     UCAnchorInfo *UCStages;
     HTList *imaps;
  } ;
typedef struct _line HTLine;
typedef struct {
     unsigned int bits_at_0;
  } HTStyleChange;
struct _line {
     struct _line *next;
     struct _line *prev;
     unsigned short offset;
     unsigned short size;
     HTStyleChange *styles;
     unsigned short numstyles;
     char data[1];
     char __pad[1];
  } ;
typedef struct {
     HTLine base;
     char data[1026];
     char __pad[2];
  } HTLineTemp;
typedef struct _TextAnchor TextAnchor;
typedef struct _FormInfo FormInfo;
typedef struct _OptionType OptionType;
struct _OptionType {
     char *name;
     char *cp_submit_value;
     int value_cs;
     struct _OptionType *next;
  } ;
struct _FormInfo {
     char *name;
     int number;
     int type;
     char *value;
     char *orig_value;
     int size;
     unsigned int maxlength;
     int group;
     int num_value;
     int hrange;
     int lrange;
     OptionType *select_list;
     char *submit_action;
     int submit_method;
     char *submit_enctype;
     char *submit_title;
     BOOLEAN no_cache;
     char *cp_submit_value;
     char *orig_submit_value;
     int size_l;
     int disabled;
     int name_cs;
     int value_cs;
     char *accept_cs;
  } ;
typedef struct {
     char *hl_text;
     short hl_x;
     char __pad[2];
  } HiliteInfo;
typedef struct {
     HiliteInfo *hl_info;
     HiliteInfo hl_base;
     short hl_len;
     char __pad[2];
  } HiliteList;
typedef struct _HTAnchor HTAnchor;
struct _HTAnchor {
     HTParentAnchor0 *parent;
  } ;
typedef HTAtom HTLinkType;
typedef struct {
     HTParentAnchor0 *parent;
     char *tag;
     HTAnchor *dest;
     HTLinkType *type;
     HTList _add_children_notag;
     HTList _add_sources;
  } HTChildAnchor;
struct _TextAnchor {
     struct _TextAnchor *next;
     struct _TextAnchor *prev;
     int sgml_offset;
     int number;
     int line_num;
     short line_pos;
     short extent;
     BOOLEAN show_anchor;
     BOOLEAN inUnderline;
     BOOLEAN expansion_anch;
     char link_type;
     FormInfo *input_field;
     HiliteList lites;
     HTChildAnchor *anchor;
  } ;
typedef struct _HTStyle HTStyle;
typedef long HTFont;
typedef int HTCoord;
typedef int HTColor;
typedef struct {
     short kind;
     HTCoord position;
  } HTTabStop;
struct _HTStyle {
     struct _HTStyle *next;
     char *name;
     int id;
     char *SGMLTag;
     HTFont font;
     HTCoord fontSize;
     HTColor color;
     int superscript;
     HTAnchor *anchor;
     HTCoord indent1st;
     HTCoord leftIndent;
     HTCoord rightIndent;
     short alignment;
     HTCoord lineHt;
     HTCoord descentLine;
     HTTabStop *tabs;
     BOOLEAN wordWrap;
     BOOLEAN freeFormat;
     HTCoord spaceBefore;
     HTCoord spaceAfter;
     int paraFlags;
  } ;
typedef struct _STable_info STable_info;
struct _STable_info  ;
typedef enum  { NOKANJI = 0, EUC = 1, SJIS = 2, JIS = 3, } HTkcode;
typedef enum  { DET_SJIS = 0, DET_EUC = 1, DET_NOTYET = 2, DET_MIXED = 3, } eDetectedKCode;
typedef enum  { SJIS_state_neutral = 0, SJIS_state_in_kanji = 1, SJIS_state_has_bad_code = 2, } eSJIS_status;
typedef enum  { EUC_state_neutral = 0, EUC_state_in_kanji = 1, EUC_state_in_kana = 2, EUC_state_has_bad_code = 3, } eEUC_status;
typedef enum  { S_text = 0, S_esc = 1, S_dollar = 2, S_paren = 3, S_nonascii_text = 4, S_dollar_paren = 5, S_jisx0201_text = 6, } eGridState;
typedef struct _UCTransParams UCTransParams;
struct _UCTransParams {
     BOOLEAN transp;
     BOOLEAN do_cjk;
     BOOLEAN decode_utf8;
     BOOLEAN output_utf8;
     BOOLEAN use_raw_char_in;
     BOOLEAN strip_raw_char_in;
     BOOLEAN pass_160_173_raw;
     BOOLEAN do_8bitraw;
     BOOLEAN trans_to_uni;
     BOOLEAN trans_C0_to_uni;
     BOOLEAN repl_translated_C0;
     BOOLEAN trans_from_uni;
  } ;
typedef struct _HTStream HTStream;
typedef struct _HTStreamClass HTStreamClass;
typedef void *HTError;
struct _HTStreamClass {
     char *name;
     void (*_free)( HTStream * );
     void (*_abort)( HTStream *, HTError  );
     void (*put_character)( HTStream *, char  );
     void (*put_string)( HTStream *, char * );
     void (*put_block)( HTStream *, char *, int  );
  } ;
struct _HTStream {
     HTStreamClass *isa;
  } ;
typedef struct _HTPool HTPool;
typedef HTStyleChange pool_data;
struct _HTPool {
     pool_data data[2042];
     struct _HTPool *prev;
     int used;
  } ;
struct _HText {
     HTParentAnchor *node_anchor;
     HTLine *last_line;
     HTLineTemp temp_line[2];
     int Lines;
     TextAnchor *first_anchor;
     TextAnchor *last_anchor;
     TextAnchor *last_anchor_before_stbl;
     TextAnchor *last_anchor_before_split;
     HTList *forms;
     int last_anchor_number;
     BOOLEAN source;
     BOOLEAN toolbar;
     HTList *tabs;
     HTList *hidden_links;
     int hiddenlinkflag;
     BOOLEAN no_cache;
     char LastChar;
     BOOLEAN IgnoreExcess;
     HTStyle *style;
     int display_on_the_fly;
     int top_of_screen;
     HTLine *top_of_screen_line;
     HTLine *next_line;
     unsigned int permissible_split;
     BOOLEAN in_line_1;
     BOOLEAN stale;
     BOOLEAN page_has_target;
     BOOLEAN has_utf8;
     BOOLEAN had_utf8;
     int first_lineno_last_disp_partial;
     int last_lineno_last_disp_partial;
     STable_info *stbl;
     HTList *enclosed_stbl;
     HTkcode kcode;
     HTkcode specified_kcode;
     eDetectedKCode detected_kcode;
     eSJIS_status SJIS_status;
     eEUC_status EUC_status;
     eGridState state;
     int kanji_buf;
     int in_sjis;
     int halted;
     BOOLEAN have_8bit_chars;
     LYUCcharset *UCI;
     int UCLYhndl;
     UCTransParams T;
     HTStream *target;
     HTStreamClass targetClass;
     HTPool *pool;
     BOOLEAN clickable_images;
     BOOLEAN pseudo_inline_alts;
     BOOLEAN verbose_img;
     BOOLEAN raw_mode;
     BOOLEAN historical_comments;
     BOOLEAN minimal_comments;
     BOOLEAN soft_dquotes;
     short old_dtd;
     short keypad_mode;
     short disp_lines;
     short disp_cols;
  } ;
typedef struct {
     DocInfo hdoc;
     int intern_seq_start;
  } HistInfo;
struct {
     char *name;
     char *value;
  } ;
struct {
     char *name;
     char *value;
  } ;
typedef enum  { CONF_NIL = 0, CONF_BOOL = 1, CONF_FUN = 2, CONF_TIME = 3, CONF_ENUM = 4, CONF_INT = 5, CONF_STR = 6, CONF_PRG = 7, CONF_ENV = 8, CONF_ENV2 = 9, CONF_INCLUDE = 10, CONF_ADD_ITEM = 11, CONF_ADD_STRING = 12, CONF_ADD_TRUSTED = 13, } Conf_Types;
typedef struct {
     char *name;
     Conf_Types type;
     long value;
     Config_Enum *table;
  } Config_Type;
/*****************************************************************************************/
/******                                                                             ******/
/******                          Function Prototypes                                ******/
/******                                                                             ******/
/*****************************************************************************************/
char *LYstrncpy( char *, char *, int  );
void LYLowerCase( char * );
void LYUpperCase( char * );
char *LYRemoveBlanks( char * );
char *LYSkipBlanks( char * );
char *LYSkipNonBlanks( char * );
void LYTrimLeading( char * );
void LYTrimTrailing( char * );
char *LYSafeGets( char **, FILE * );
void HTuncache_current_document( void );
char *HTLoadedDocumentURL( void );
char *HTLoadedDocumentTitle( void );
void add_trusted( char *, int  );
void exit_immediately( int  );
void reload_read_cfg( void );
FILE *TraceFP( void );
int lynx_chg_color( int , int , int  );
void lynx_setup_colors( void );
void set_default_bookmark_page( char * );
char *LYGetEnv( char * );
BOOLEAN LYisAbsPath( char * );
void LYAddLocalhostAlias( char * );
BOOLEAN LYCloseInput( FILE * );
BOOLEAN LYCanReadFile( char * );
void remove_backslashes( char * );
char *Home_Dir( void );
char *LYPathLeaf( char * );
BOOLEAN LYPathOffHomeOK( char *, size_t  );
char *LYTildeExpand( char **, BOOLEAN  );
void LYAddPathToHome( char *, size_t , char * );
void LYCloseTempFP( FILE * );
BOOLEAN LYIsUIPage3( char *, UIP_t , int  );
void LYRegisterUIPage( char *, UIP_t  );
void LYLocalFileToURL( char **, char * );
FILE *InternalPageFP( char *, int  );
void BeginInternalPage( FILE *, char *, char * );
void EndInternalPage( FILE * );
char *LYgetXDisplay( void );
BOOLEAN is_true( char * );
char *find_colon( char * );
void free_item_list( lynx_list_item_type ** );
void free_all_item_lists( void );
void add_item_to_list( char *, lynx_list_item_type **, int  );
lynx_list_item_type *find_item_by_number( lynx_list_item_type *, char * );
int match_item_by_name( lynx_list_item_type *, char *, BOOLEAN  );
int check_color( char *, int  );
void exit_with_color_syntax( char * );
void parse_color( char * );
int assume_charset_fun( char * );
int assume_local_charset_fun( char * );
int assume_unrec_charset_fun( char * );
int character_set_fun( char * );
int outgoing_mail_charset_fun( char * );
int assumed_color_fun( char * );
int color_fun( char * );
int default_colors_fun( char * );
int default_bookmark_file_fun( char * );
int default_cache_size_fun( char * );
int default_editor_fun( char * );
int numbers_as_arrows_fun( char * );
int dired_menu_fun( char * );
int jumpfile_fun( char * );
int keymap_fun( char * );
int localhost_alias_fun( char * );
int lynxcgi_environment_fun( char * );
int lynx_sig_file_fun( char * );
int news_chunk_size_fun( char * );
int news_max_chunk_fun( char * );
int news_posting_fun( char * );
int cern_rulesfile_fun( char * );
int referer_with_query_fun( char * );
int suffix_fun( char * );
int suffix_order_fun( char * );
int system_editor_fun( char * );
int viewer_fun( char * );
int nonrest_sigwinch_fun( char * );
void html_src_bad_syntax( char *, char * );
int parse_html_src_spec( HTlexeme , char *, char * );
int psrcspec_fun( char * );
int read_htmlsrc_attrname_xform( char * );
int read_htmlsrc_tagname_xform( char * );
void free_lynx_cfg( void );
Config_Type *lookup_config( char * );
char *actual_filename( char *, char *, char * );
FILE *LYOpenCFG( char *, char *, char * );
void LYSetConfigValue( char *, char * );
void do_read_cfg( char *, char *, int , FILE *, optidx_set_t * );
void read_cfg( char *, char *, int , FILE * );
void extra_cfg_link( FILE *, char *, char * );
int lynx_cfg_infopage( DocInfo * );
int lynx_compile_opts( DocInfo * );
void LYpop( DocInfo * );
BOOLEAN LYgetEnum( Config_Enum *, char *, int * );
int lacname_to_lac( char * );
int lecname_to_lec( char * );
int lkcstring_to_lkc( char * );
int remap( char *, char *, BOOLEAN  );
void HTFileInit( void );
void outofmem( char *, char * );
BOOLEAN LYJumpInit( char * );
void add_lynxcgi_environment( char * );
BOOLEAN LYRemapEditBinding( int , int , int  );
int UCGetLYhndl_byAnyName( char * );
void LYEntify( char **, BOOLEAN  );
void LYTrimTail( char * );
void LYConfigCookies( void );
int html_src_parse_tagspec( char *, HTlexeme , BOOLEAN , BOOLEAN  );
void html_src_clean_item( HTlexeme  );
int UCGetLYhndl_byMIME( char * );
int safeUCGetLYhndl_byMIME( char * );
void add_menu_item( char * );
void reset_dired_menu( void );
BOOLEAN HTLoadAbsolute( DocAddress * );
void HTSetSuffix5( char *, char *, char *, char *, double  );
void HTSetProgramPath( ProgramPaths , char * );
void HTInitProgramPaths( void );
HTList *HTList_new( void );
void HTList_appendObject( HTList *, void * );
int strcasecomp( char *, char * );
int strncasecomp( char *, char *, int  );
char *HTSACopy( char **, char * );
char *HTSACat( char **, char * );
char *HTNextTok( char **, char *, char *, char * );
char *HTSprintf0( char **, char *, ... );
int HTLoadRules( char * );
void HTSetPresentation( char *, char *, char *, double , double , double , long , AcceptMedia  );
int unsetenv( char * );
double strtod( char *, char ** );
char *strchr( char *, char  );
void *calloc( unsigned int , unsigned int  );
int toupper( int  );
FILE *fopen64( char *, char * );
char *strrchr( char *, char  );
char *gettext( char * );
void *strtol( char *, char **, int  );
void free( void * );
short **__ctype_b_loc( void );
unsigned int strlen( char * );
int atoi( char * );
int putenv( char * );
unsigned int fwrite( void *, unsigned int , unsigned int , FILE * );
int fprintf( FILE *, char *, ... );
char *strstr( char *, char * );
void __stack_chk_fail( void );
char *strtok( char *, char * );
int sscanf( char *, char *, ... );
int strcmp( char *, char * );
/*****************************************************************************************/
/******                                                                             ******/
/******                        Forward Var Declarations                             ******/
/******                                                                             ******/
/*****************************************************************************************/
extern struct _IO_FILE  *stderr;
extern HText *HTMainText;
extern int nhist;
extern BOOLEAN lynx_edit_mode;
extern int HTCacheSize;
extern BOOLEAN LYforce_no_cache;
extern char *LynxSigFile;
extern int keypad_mode;
extern int user_mode;
extern BOOLEAN no_compileopts_info;
extern BOOLEAN no_newspost;
extern char LYRefererWithQuery;
extern char *editor;
extern char *UCAssume_MIMEcharset;
extern HistInfo *history;
extern BOOLEAN LYoverride_no_cache;
extern char *lynx_lss_file;
extern BOOLEAN LYuse_default_colors;
extern BOOLEAN no_lynxcfg_xinfo;
extern BOOLEAN LYNonRestartingSIGWINCH;
extern BOOLEAN system_editor;
extern lynx_list_item_type *printers;
extern lynx_list_item_type *downloaders;
extern lynx_list_item_type *uploaders;
extern lynx_list_item_type *externals;
extern BOOLEAN LYUseNoviceLineTwo;
extern BOOLEAN LYNewsPosting;
extern char *lynx_cfg_file;
extern int outgoing_mail_charset;
extern BOOLEAN LYUseBuiltinSuffixes;
extern BOOLEAN FileInitAlreadyDone;
extern int default_fg;
extern int default_bg;
extern BOOLEAN have_read_cfg;
extern int current_char_set;
extern LYUCcharset LYCharSet_UC[60];
extern BOOLEAN default_color_reset;
extern char *HTL_tagspecs[12];
extern int tagname_transform;
extern int attrname_transform;
extern int UCLYhndl_for_unspec;
extern int UCLYhndl_for_unrec;
extern int UCLYhndl_HTFile_for_unspec;
extern BOOLEAN reloading;
extern BOOLEAN WWW_TraceFlag;
extern int WWW_TraceMask;
extern int HTNewsChunkSize;
extern int HTNewsMaxChunk;
/*****************************************************************************************/
/******                                                                             ******/
/******                      Inline Function Definitions                            ******/
/******                                                                             ******/
/*****************************************************************************************/
