// subject_bss.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

FILE * stdout = null; // 0000000000411058
byte g_b411060 = 0x00; // 0000000000411060
Eq_407 g_t411068 = // 0000000000411068
	{
		
		{
			null
		},
	};
ptr64 * g_ptr411070 = null; // 0000000000411070
ptr64 * g_ptr411078 = null; // 0000000000411078
word32 g_dw411080 = 0x00; // 0000000000411080
// subject_fini.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0000000000400C34: void _fini()
void _fini()
{
}

// subject_got.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

word64 g_qw410FE0 = 0x00; // 0000000000410FE0
// subject_init.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 00000000004005A0: Register word64 _init(Register out ptr64 x30Out)
// Called from:
//      __libc_csu_init
word64 _init(ptr64 & x30Out)
{
	call_weak_fn();
	x30Out = qwArg00;
	return x30;
}

// subject_init_array.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

<anonymous> * g_a410DE0[] = // 0000000000410DE0
	{
	};
// subject_jcr.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

word64 g_qw410DF0 = 0x00; // 0000000000410DF0
// subject_text.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0000000000400670: void _start(Register (ptr64 Eq_9) x0, Stack Eq_10 qwArg00)
void _start(void (* x0)(), Eq_10 qwArg00)
{
	x0_14 = (uint64) __libc_start_main(g_ptr4006A0, qwArg00, (char *) fp + 8, g_ptr4006A8, g_ptr4006B0, x0, fp);
	abort();
}

int32 (* g_ptr4006A0)(int32 x0, char ** x1, char ** x2) = main; // 00000000004006A0
void (* g_ptr4006A8)() = __libc_csu_init; // 00000000004006A8
void (* g_ptr4006B0)() = __libc_csu_fini; // 00000000004006B0
// 00000000004006B8: void call_weak_fn()
// Called from:
//      _init
void call_weak_fn()
{
	if (g_qw410FE0 == 0x00)
		return;
	__gmon_start__();
}

// 00000000004006D0: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
	if (0x0041105F - 4264024 <= 0x0E)
		return;
	<anonymous> * x1_12 = g_ptr400708;
	if (x1_12 == null)
		return;
	x1_12();
}

<anonymous> * g_ptr400708 = null; // 0000000000400708
// 0000000000400710: void register_tm_clones()
// Called from:
//      frame_dummy
void register_tm_clones()
{
	int64 x1_7 = 4264024 - 4264024;
	if ((x1_7 >> 3) + ((x1_7 >> 3) >>u 63) >> 1 == 0x00)
		return;
	<anonymous> * x2_12 = g_ptr400748;
	if (x2_12 == null)
		return;
	word64 x2_16;
	x2_12();
}

<anonymous> * g_ptr400748 = null; // 0000000000400748
// 0000000000400750: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	if ((word32) g_b411060 == 0x00)
	{
		deregister_tm_clones();
		g_b411060 = 0x01;
	}
}

// 0000000000400780: void frame_dummy(Register word64 x29, Register word64 x30)
void frame_dummy(word64 x29, word64 x30)
{
	if (g_qw410DF0 != 0x00)
	{
		<anonymous> * x1_7 = g_ptr4007B8;
		if (x1_7 != null)
		{
			x1_7();
			register_tm_clones();
			return;
		}
	}
	register_tm_clones();
}

<anonymous> * g_ptr4007B8 = null; // 00000000004007B8
// 00000000004007C0: void new_tower(Register uint64 x0)
void new_tower(uint64 x0)
{
	word32 x0_32_32_13 = SLICE(x0, word32, 32);
	ptr64 * x0_15 = calloc(SEQ(x0_32_32_13, 0x01), __sbfiz(x0, 2) + 0x10);
	*x0_15 = x0_15 + 2;
}

// 00000000004007E8: void text(Register word32 w2)
void text(word32 w2)
{
	word32 w20_26 = w2;
	x0_39 = (uint64) printf("\x1B[%d;%dH", 0x00);
	if (w2 != 0x00)
	{
		do
		{
			--w20_26;
			x0_49 = (uint64) printf("%s", 0x00);
		} while (w20_26 != 0x00);
	}
}

// 0000000000400860: Register uint64 add_disk(Register word32 w0, Register word32 w1, Register uint64 x19, Register ptr64 x20, Register ptr64 x21, Register (ptr64 char) x22, Register word64 x30, Register out ptr64 x19Out, Register out ptr64 x20Out, Register out ptr64 x30Out)
// Called from:
//      move
//      main
uint64 add_disk(word32 w0, word32 w1, uint64 x19, ptr64 x20, ptr64 x21, char * x22, word64 x30, ptr64 & x19Out, ptr64 & x20Out, ptr64 & x30Out)
{
	word32 x19_32_32_68 = SLICE(x19, word32, 32);
	ptr64 x20_51;
	struct Eq_158 * x8_25 = (&g_t411068)[(int64) w0 /64 8];
	int64 x9_29 = (int64) x8_25->dw0004;
	word32 x10_30[] = x8_25->ptr0000;
	x8_25->dw0008 = (word32) x9_29 + 0x01;
	x10_30[x9_29] = w1;
	word32 w1_42 = 0x01 - x8_25->dw0008 + g_dw411080;
	word32 w19_27 = w1;
	x0_47 = (uint64) printf("\x1B[%d;%dH", 0x00);
	word64 x19_67 = SEQ(x19_32_32_68, w1);
	x20_51 = x20;
	if (w1 != 0x00)
	{
		x20_51 = 0x00400C51;
		x21 = 0x00400C54;
		do
		{
			--w19_27;
			w1_42 = (word32) 0x00400C54;
			x0_59 = (uint64) printf("%s", 0x00);
			x19_67 = SEQ(x19_32_32_68, w19_27);
		} while (w19_27 != 0x00);
	}
	usleep();
	uint64 x0_110 = (uint64) fflush(stdout);
	x19Out = x20;
	x20Out = qwLoc20;
	x30Out = x29;
	return x0_110;
}

// 0000000000400914: void remove_disk(Register word32 w0)
void remove_disk(word32 w0)
{
	struct Eq_229 * x8_25 = (&g_t411068)[(int64) w0 /64 8];
	int64 x9_28 = (int64) x8_25->dw0004;
	word32 x11_29[] = x8_25->ptr0000;
	x8_25->dw0008 = (word32) x9_28 - 0x01;
	word32 w19_34 = x11_29[x9_28 - 0x01];
	x0_42 = (uint64) printf("\x1B[%d;%dH", 0x00);
	if (w19_34 != 0x00)
	{
		word32 w22_48 = w19_34;
		do
		{
			--w22_48;
			x0_55 = (uint64) printf("%s", 0x00);
		} while (w22_48 != 0x00);
	}
}

// 00000000004009B0: Register word64 move(Register Eq_275 w0, Register out ptr64 x20Out, Register out ptr64 x21Out, Register out ptr64 x22Out, Register out (ptr64 char) x23Out, Register out ptr64 x28Out, Register out ptr64 x30Out)
// Called from:
//      move
//      main
word64 move(Eq_275 w0, ptr64 & x20Out, ptr64 & x21Out, ptr64 & x22Out, char & x23Out, ptr64 & x28Out, ptr64 & x30Out)
{
	Eq_275 w0 = (word32) x0;
	if (w0 != 0x00)
	{
		do
		{
			char * x23_86;
			char * x22_87;
			ptr64 x21_88;
			ptr64 x20_89;
			word64 x30_92;
			word64 x28_337;
			uint64 x19_90 = move(w0, out x20_89, out x21_88, out x22_87, out x23_86, out x28_337, out x30_92);
			struct Eq_333 * x8_105 = (&g_t411068)[(int64) (word32) x20_89 /64 8];
			int64 x9_109 = (int64) x8_105->dw0004;
			word32 x10_110[] = x8_105->ptr0000;
			x8_105->dw0008 = (word32) x9_109 - 0x01;
			word32 w27_115 = x10_110[x9_109 - 0x01];
			word32 w19_134 = (word32) x19_90;
			word32 w21_168 = (word32) x21_88;
			x0_120 = (uint64) printf(x22_87, 0x00);
			word32 w26_122 = w27_115;
			if (w27_115 != 0x00)
			{
				do
				{
					--w26_122;
					x0_129 = (uint64) printf(x23_86, 0x00);
				} while (w26_122 != 0x00);
			}
			word64 x19_334;
			word64 x20_335;
			word64 x30_336;
			add_disk(w19_134, w27_115, x19_90, x20_89, x21_88, x22_87, x30_92, out x19_334, out x20_335, out x30_336);
		} while (w21_168 != 0x00);
	}
	x20Out = x21;
	x21Out = x22;
	x22Out = x23;
	x23Out = x24;
	x28Out = <invalid>;
	x30Out = x29;
	return x20;
}

// 0000000000400AA8: void main(Register int32 w0, Register (ptr64 Eq_369) x1, Register word64 x30)
void main(int32 w0, struct Eq_369 * x1, word64 x30)
{
	uint64 x19_211;
	word32 x19_32_32_43 = SLICE(x1, word32, 32);
	word32 x0_32_32_54 = SLICE((uint64) puts("\x1B[H\x1B[J"), word32, 32);
	if (w0 >= 0x02)
	{
		uint64 x0_35 = (uint64) strtol(x1->ptr0008);
		x0_32_32_54 = SLICE(x0_35, word32, 32);
		x19_211 = x0_35;
		x19_32_32_43 = SLICE(x0_35, word32, 32);
		if ((word32) x0_35 > 0x00)
		{
l0000000000400AF4:
			word64 x8_47 = __sbfiz(x19_211, 2);
			g_dw411080 = (word32) x19_211;
			Eq_407 x0_59 = calloc(SEQ(x0_32_32_54, 0x01), x8_47 + 0x10);
			*x0_59.t0000 = (Eq_407) ((word64) x0_59.t0000 + 16);
			g_t411068.t0000 = x0_59;
			ptr64 * x0_72 = calloc(SEQ(SLICE(x0_59, word32, 32), 0x01), x8_47 + 0x10);
			*x0_72 = x0_72 + 2;
			g_ptr411070 = x0_72;
			ptr64 * x0_81 = calloc(SEQ(SLICE(x0_72, word32, 32), 0x01), x8_47 + 0x10);
			*x0_81 = x0_81 + 2;
			g_ptr411078 = x0_81;
			ptr64 x20_101 = x8_47 + 0x10;
			do
			{
				word32 w19_106 = (word32) x19_100;
				word64 x19_100;
				word32 x0_32_32_113 = SLICE(add_disk(0x00, (word32) x19_211, x19_211, x20_101, 0x00411000, &g_t411068, x30, out x19_100, out x20_101, out x30), word32, 32);
				x19_211 = SEQ(SLICE(x19_100, word32, 32), w19_106 - 0x01);
			} while (w19_106 != 0x01);
			word64 x28_217;
			word64 x30_218;
			word64 x21_214;
			word64 x22_215;
			word64 x23_216;
			word64 x20_213;
			move(SEQ(x0_32_32_113, g_dw411080), out x20_213, out x21_214, out x22_215, out x23_216, out x28_217, out x30_218);
			x0_137 = (uint64) printf("\x1B[%d;%dH", 0x00);
			x0_144 = (uint64) printf("%s", 0x00);
			return;
		}
	}
	x19_211 = SEQ(x19_32_32_43, 0x08);
	goto l0000000000400AF4;
}

// 0000000000400BB8: void __libc_csu_init(Register word32 w0, Register word64 x1, Register word64 x2, Register word64 x24)
void __libc_csu_init(word32 w0, word64 x1, word64 x2, word64 x24)
{
	word32 x24_32_32_100 = SLICE(x24, word32, 32);
	int64 x20_26 = 4263400 - 0x00410DE0;
	<anonymous> * x21_24[] = g_a410DE0;
	word64 x22_34 = x2;
	word64 x23_38 = x1;
	word64 x30_42;
	word64 x29_41 = _init(out x30_42);
	int64 x20_43 = x20_26 >> 3;
	if (x20_26 >> 3 != 0x00)
	{
		int64 x19_44 = 0x00;
		word64 x24_145 = SEQ(x24_32_32_100, w0);
		do
		{
			word64 x3_74;
			x21_24[x19_44]();
			int64 x31_77 = x20_43 - x19_44;
		} while (x31_77 != 0x00);
	}
}

// 0000000000400C30: void __libc_csu_fini()
void __libc_csu_fini()
{
}

