// subject.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 00000000004005A0: Register ptr64 _init(Stack word64 qwArg00)
ptr64 _init(word64 qwArg00)
{
	call_weak_fn();
	return fp + 0x08;
}

// 00000000004005E0: void fn00000000004005E0()
void fn00000000004005E0()
{
	<anonymous> * x17_4 = globals->ptr411000;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 00000000004005F0: void fn00000000004005F0()
void fn00000000004005F0()
{
	<anonymous> * x17_4 = globals->ptr411008;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000400610: void fn0000000000400610()
void fn0000000000400610()
{
	<anonymous> * x17_4 = globals->ptr411018;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000400620: void fn0000000000400620()
void fn0000000000400620()
{
	<anonymous> * x17_4 = globals->ptr411020;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000400630: void fn0000000000400630()
void fn0000000000400630()
{
	<anonymous> * x17_4 = globals->ptr411028;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000400650: void fn0000000000400650()
void fn0000000000400650()
{
	<anonymous> * x17_4 = globals->ptr411038;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000400660: void fn0000000000400660()
void fn0000000000400660()
{
	<anonymous> * x17_4 = globals->ptr411040;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 0000000000400670: void _start(Stack word64 qwArg00)
void _start(word64 qwArg00)
{
	fn00000000004005E0();
	fn0000000000400610();
}

// 00000000004006B8: void call_weak_fn()
void call_weak_fn()
{
	word64 x0_4 = globals->qw410FE0;
	if (x0_4 == 0x00)
		return;
	<anonymous> * x17_10 = globals->ptr411010;
	word64 sp_12;
	word64 x0_13;
	word64 x16_14;
	word64 x17_15;
	x17_10();
}

// 00000000004006D0: void deregister_tm_clones()
void deregister_tm_clones()
{
	if (0x0041105F - 4264024 <= 0x0E)
		return;
	<anonymous> * x1_17 = globals->ptr400708;
	if (x1_17 == null)
		return;
	word64 sp_18;
	word64 x1_19;
	word64 x0_20;
	byte NZCV_21;
	byte ZC_22;
	x1_17();
}

// 0000000000400710: void register_tm_clones()
void register_tm_clones()
{
	int64 x1_6 = 4264024 - 4264024;
	if ((x1_6 >> 0x03) + ((x1_6 >> 0x03) >>u 0x003F) >> 0x01 == 0x00)
		return;
	<anonymous> * x2_17 = globals->ptr400748;
	if (x2_17 == null)
		return;
	word64 sp_18;
	word64 x1_19;
	word64 x0_20;
	word64 x2_21;
	x2_17();
}

// 0000000000400750: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	if ((word32) globals->b411060 == 0x00)
	{
		deregister_tm_clones();
		globals->b411060 = 0x01;
	}
}

// 0000000000400780: void frame_dummy(Stack word64 qwArg00)
void frame_dummy(word64 qwArg00)
{
	if (globals->qw410DF0 != 0x00)
	{
		<anonymous> * x1_20 = globals->ptr4007B8;
		if (x1_20 != null)
		{
			word64 sp_26;
			word64 x0_27;
			word64 x1_28;
			word64 x29_29;
			word64 x30_30;
			word64 x2_31;
			x1_20();
			register_tm_clones();
			return;
		}
	}
	register_tm_clones();
}

// 00000000004007C0: void new_tower(Register (ptr64 Eq_171) x0, Stack word64 qwArg00)
void new_tower(Eq_171 * x0, word64 qwArg00)
{
	__sbfiz(x0, 0x02);
	fn00000000004005F0();
	word64 * x0_13 = DPB(x0, 0x01, 0);
	*x0_13 = x0_13 + 0x02;
}

// 00000000004007E8: void text(Register word32 w0, Register word32 w1, Register word32 w2, Stack word64 qwArg00)
void text(word32 w0, word32 w1, word32 w2, word64 qwArg00)
{
	__bfm(w1, 0x001F, 0x001E);
	fn0000000000400660();
	word32 w20_26 = w2;
	if (w2 != 0x00)
	{
		do
		{
			fn0000000000400660();
			w20_26 = w20_26 - 0x01;
		} while (w20_26 != 0x00);
	}
}

// 0000000000400860: Register word32 add_disk(Register word32 w0, Register int32 w1, Register word32 w9, Stack word64 qwArg00, Register out Eq_218 w19Out, Register out ptr64 x21Out, Register out (ptr64 Eq_220) spOut)
word32 add_disk(word32 w0, int32 w1, word32 w9, word64 qwArg00, Eq_218 & w19Out, ptr64 & x21Out, Eq_220 * & spOut)
{
	Eq_221 x8_25 = globals->a411068[(int64) (int32) w0];
	ui64 x9_30 = (word64) (&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&x8_25.a0000[0x04].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00];
	int32 x10_32[] = (&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&x8_25.a0000[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00];
	(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&x8_25.a0000[0x08].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00] = (Eq_221) ((word32) x9_30 + 0x01);
	x10_32[x9_30] = w1;
	word32 w10_42 = __bfm(w0, 0x001F, 0x001E);
	fn0000000000400660();
	int32 w19_102 = w1;
	if (w1 != 0x00)
	{
		do
		{
			fn0000000000400660();
			w19_102 = w19_102 - 0x01;
		} while (w19_102 != 0x00);
	}
	fn0000000000400650();
	<anonymous> * x17_71 = globals->ptr411030;
	word64 sp_73;
	word64 x22_74;
	word64 x21_75;
	word64 x20_76;
	word64 x19_77;
	word64 x29_78;
	word64 x30_79;
	word64 x8_80;
	word32 w0_81;
	word32 w1_82;
	word32 w19_83;
	word64 x9_84;
	word64 x10_85;
	word32 w11_86;
	word32 w9_87;
	word32 w8_88;
	word32 w10_89;
	word64 x0_90;
	word32 w2_91;
	word64 x1_92;
	word64 x16_93;
	word64 x17_94;
	x17_71();
	return w9_87;
}

// 0000000000400914: void remove_disk(Register word32 w0, Register word32 w9, Stack word64 qwArg00)
void remove_disk(word32 w0, word32 w9, word64 qwArg00)
{
	Eq_294 x8_25 = globals->a411068[(int64) (int32) w0];
	ui64 x9_28 = (word64) (&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&x8_25.a0000[0x04].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00];
	word32 x11_29[] = (&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&x8_25.a0000[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00];
	(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&x8_25.a0000[0x08].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00] = (Eq_294) (word32) (x9_28 - 0x01);
	word32 w19_34 = x11_29[x9_28 - 0x01];
	__bfm(w0, 0x001F, 0x001E);
	fn0000000000400660();
	if (w19_34 != 0x00)
	{
		word32 w22_67 = w19_34;
		do
		{
			fn0000000000400660();
			w22_67 = w22_67 - 0x01;
		} while (w22_67 != 0x00);
	}
}

// 00000000004009B0: Register word32 move(Register word32 w0, Stack word64 qwArg00, Register out Eq_338 w19Out, Register out Eq_339 w20Out, Register out Eq_340 w21Out, Register out Eq_341 w25Out, Register out ptr64 x28Out, Register out ptr64 spOut)
word32 move(word32 w0, word64 qwArg00, Eq_338 & w19Out, Eq_339 & w20Out, Eq_340 & w21Out, Eq_341 & w25Out, ptr64 & x28Out, ptr64 & spOut)
{
	struct Eq_344 * sp_171 = fp + -88;
	word32 w21_123 = w0;
	if (w0 != 0x00)
	{
		do
		{
			word32 w19_135;
			word32 w20_136;
			word32 w25_138;
			word64 x28_139;
			word64 sp_140;
			move(w21_123 - 0x01, x30, out w19_135, out w20_136, out w21_123, out w25_138, out x28_139, out sp_140);
			Eq_423 x8_144 = globals->a411068[(int64) (int32) w20_136];
			__bfm(w20_136, 0x001F, 0x001E);
			ui64 x9_148 = (word64) (&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&x8_144.a0000[0x04].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00];
			int32 x10_149[] = (&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&x8_144.a0000[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00];
			(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&x8_144.a0000[0x08].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00] = (Eq_423) (word32) (x9_148 - 0x01);
			int32 w27_154 = x10_149[x9_148 - 0x01];
			fn0000000000400660();
			word32 w9_158 = 0x00 - w27_154;
			int32 w26_161 = w27_154;
			if (w27_154 != 0x00)
			{
				do
				{
					fn0000000000400660();
					w26_161 = w26_161 - 0x01;
				} while (w26_161 != 0x00);
			}
			word32 w19_169;
			word64 x21_170;
			w9 = add_disk(w19_135, w27_154, w9_158, x30, out w19_169, out x21_170, out sp_171);
		} while (w21_123 != 0x00);
	}
	struct Eq_351 * v40_79 = &sp_171->qw0038 + 0x01;
	word32 w20_81;
	*w20Out = (word32) v40_79->qw0000;
	word32 w19_84;
	*w19Out = (word32) v40_79->qw0008;
	word32 w21_89;
	*w21Out = (word32) sp_171->qw0038;
	word32 w25_98;
	*w25Out = (word32) sp_171->qw0018;
	word64 x28_100;
	*x28Out = sp_171->qw0000;
	word64 sp_103;
	*spOut = &sp_171->qw0038 + 0x05;
	return w9;
}

// 0000000000400AA8: void main(Register int32 w0, Register (ptr64 Eq_171) x1, Register word32 w9, Register word32 w19, Stack word64 qwArg00)
void main(int32 w0, Eq_171 * x1, word32 w9, word32 w19, word64 qwArg00)
{
	int32 w19_115;
	fn0000000000400620();
	struct Eq_171 * x0_111 = &globals->t400C5A;
	struct Eq_171 * x19_113 = x1;
	if (w0 >= 0x02)
	{
		x0_111 = x1->ptr0008;
		fn0000000000400630();
		x19_113 = x0_111;
		w19_115 = (word32) x0_111;
		if (w19_115 > 0x00)
		{
l0000000000400AF4:
			__sbfiz(x19_113, 0x02);
			globals->dw411080 = 0x08;
			fn00000000004005F0();
			ptr64 * x0_43 = DPB(x0_111, 0x01, 0);
			*x0_43 = x0_43 + 0x02;
			(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&(&globals->a411068->a0000[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00].a0000)[0x00] = (Eq_221) x0_43;
			fn00000000004005F0();
			ptr64 * x0_52 = DPB(x0_111, 0x01, 0);
			*x0_52 = x0_52 + 0x02;
			globals->ptr411070 = x0_52;
			fn00000000004005F0();
			ptr64 * x0_58 = DPB(x0_111, 0x01, 0);
			*x0_58 = x0_58 + 0x02;
			globals->ptr411078 = x0_58;
			do
			{
				word32 w19_69;
				struct Eq_535 * x21_70;
				word64 sp_71;
				w9 = add_disk(0x00, w19_115, w9, x30, out w19_69, out x21_70, out sp_71);
				w19_115 = w19_69 - 0x01;
			} while (w19_69 != 0x01);
			word32 w19_79;
			word32 w20_80;
			word32 w21_81;
			word32 w25_82;
			word64 x28_83;
			word64 sp_84;
			move(x21_70->dw0080, x30, out w19_79, out w20_80, out w21_81, out w25_82, out x28_83, out sp_84);
			fn0000000000400660();
			fn0000000000400660();
			return;
		}
	}
	w19_115 = 0x08;
	x19_113 = DPB(x19_113, 0x08, 0);
	goto l0000000000400AF4;
}

// 0000000000400BB8: void __libc_csu_init(Register word64 x30, Stack word64 qwArg00)
void __libc_csu_init(word64 x30, word64 qwArg00)
{
	<anonymous> * x21_23[] = globals->a410DE0;
	word64 sp_38 = _init(x30);
	if (4263400 - 0x00410DE0 >> 0x03 != 0x00)
	{
		ui64 x19_71 = 0x00;
		do
		{
			<anonymous> * x3_77 = x21_23[x19_71];
			word64 sp_82;
			word64 x29_83;
			word64 x30_84;
			word64 x22_86;
			word64 x20_88;
			word64 x23_89;
			word64 x24_90;
			word64 x2_91;
			word32 w0_92;
			word32 w24_93;
			word64 x1_94;
			word64 x3_95;
			word64 x31_96;
			byte NZCV_97;
			bool Z_98;
			x3_77();
		} while (x20_88 - x19_71 != 0x00);
	}
}

// 0000000000400C30: void __libc_csu_fini()
void __libc_csu_fini()
{
}

// 0000000000400C34: void _fini(Stack word64 qwArg00)
void _fini(word64 qwArg00)
{
}

