// subject.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0000827C: void _init()
void _init()
{
}

// 000082CC: void _start()
void _start()
{
}

// 00008308: void call_weak_fn()
void call_weak_fn()
{
}

// 0000832C: void deregister_tm_clones()
void deregister_tm_clones()
{
}

// 0000835C: void register_tm_clones()
void register_tm_clones()
{
}

// 00008394: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
}

// 000083BC: void frame_dummy()
void frame_dummy()
{
}

// 000083F4: void main()
void main()
{
}

// 00008440: void __libc_csu_init()
void __libc_csu_init()
{
}

// 000084A0: void __libc_csu_fini()
void __libc_csu_fini()
{
}

// 000084A4: void _fini()
void _fini()
{
}

