//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t proc1(int32_t a1, char * str);

// ------------------------ Functions -------------------------

// Address range: 0x10000440 - 0x100004f3
int32_t proc1(int32_t a1, char * str) {
    // 0x10000440
    int32_t v1; // bp-48
    v1 = &v1;
    int32_t len = strlen(str); // 0x1000046c
    int32_t len2; // 0x1000047c
    if (a1 > 2) {
        // 0x10000468
        len2 = strlen(str);
        printf("%d", len2 + len);
        // branch -> 0x100004bc
    }
    // 0x100004bc
    printf("%d, %d", len, len2);
    return len;
}

// Address range: 0x100004f4 - 0x1000055f
int main(int argc, char ** argv) {
    // 0x100004f4
    int32_t v1; // bp-32
    v1 = &v1;
    printf("%d\n", proc1(argc, (char *)*(int32_t *)((int32_t)argv + 4)));
    return 0;
}

// --------------- Statically Linked Functions ----------------

// int printf(const char * restrict format, ...);
// size_t strlen(const char * s);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (gcc-powerpc-elf) (4.5.1 - 4.5.2)
// Detected functions: 2
// Decompiler release: VERSION
// Decompilation date: DATE
