// subject.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

// 0000000000000660: Register ptr64 _init(Stack word64 qwArg00)
ptr64 _init(word64 qwArg00)
{
	call_weak_fn();
	return fp + 0x08;
}

// 00000000000006A0: void fn00000000000006A0()
void fn00000000000006A0()
{
	<anonymous> * x17_4 = globals->ptr11000;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 00000000000006B0: void fn00000000000006B0()
void fn00000000000006B0()
{
	<anonymous> * x17_4 = globals->ptr11008;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 00000000000006D0: void fn00000000000006D0()
void fn00000000000006D0()
{
	<anonymous> * x17_4 = globals->ptr11018;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 00000000000006E0: void fn00000000000006E0()
void fn00000000000006E0()
{
	<anonymous> * x17_4 = globals->ptr11020;
	word64 sp_6;
	word64 x16_7;
	word64 x17_8;
	x17_4();
}

// 00000000000006F0: void main(Register word64 x30)
void main(word64 x30)
{
	word64 sp_9;
	b(x30, x30, out sp_9);
	fn00000000000006E0();
	fn00000000000006E0();
}

// 0000000000000730: void _start(Stack word64 qwArg00)
void _start(word64 qwArg00)
{
	fn00000000000006B0();
	fn00000000000006D0();
	call_weak_fn();
}

// 0000000000000768: void call_weak_fn()
void call_weak_fn()
{
	word64 x0_4 = globals->qw10FC0;
	if (x0_4 == 0x00)
		return;
	<anonymous> * x17_10 = globals->ptr11010;
	word64 sp_12;
	word64 x0_13;
	word64 x16_14;
	word64 x17_15;
	x17_10();
}

// 0000000000000780: void deregister_tm_clones()
void deregister_tm_clones()
{
	if (0x00011077 - 0x00011070 <= 0x0E)
		return;
	<anonymous> * x1_18 = globals->ptr10FB0;
	if (x1_18 == null)
		return;
	word64 sp_19;
	word64 x1_20;
	word64 x0_21;
	byte NZCV_22;
	byte ZC_23;
	x1_18();
}

// 00000000000007B8: void register_tm_clones()
void register_tm_clones()
{
	int64 x1_6 = 0x00011070 - 0x00011070;
	if ((x1_6 >> 0x03) + ((x1_6 >> 0x03) >>u 0x003F) >> 0x01 == 0x00)
		return;
	<anonymous> * x2_18 = globals->ptr10FE0;
	if (x2_18 == null)
		return;
	word64 sp_19;
	word64 x1_20;
	word64 x0_21;
	word64 x2_22;
	x2_18();
}

// 00000000000007F8: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	if ((word32) globals->b11070 == 0x00)
	{
		if (globals->qw10FB8 != 0x00)
			fn00000000000006A0();
		deregister_tm_clones();
		globals->b11070 = 0x01;
	}
}

// 0000000000000840: void frame_dummy(Stack word64 qwArg00)
void frame_dummy(word64 qwArg00)
{
	if (globals->qw10DB8 != 0x00)
	{
		<anonymous> * x1_21 = globals->ptr10FD8;
		if (x1_21 != null)
		{
			word64 sp_27;
			word64 x0_28;
			word64 x1_29;
			word64 x29_30;
			word64 x30_31;
			word64 x2_32;
			x1_21();
			register_tm_clones();
			return;
		}
	}
	register_tm_clones();
}

// 0000000000000878: Register ptr64 g()
ptr64 g()
{
	ui32 w0_4 = globals->dw11038;
	globals->dw11038 = w0_4 - 0x01;
	if ((w0_4 - 0x01 & 0x00) == 0x00)
	{
		globals->dw11074 = globals->dw11074 + 0x0D;
		return fp;
	}
	else
	{
		word64 sp_21;
		f(out sp_21);
		globals->dw11074 = globals->dw11074 + 0x0D;
		return sp_21 + 0x0010;
	}
}

// 00000000000008C8: Register word64 f(Register out ptr64 spOut)
word64 f(ptr64 & spOut)
{
	ui32 w0_5 = globals->dw1103C;
	globals->dw1103C = w0_5 - 0x01;
	word64 sp_1;
	*spOut = fp;
	if ((w0_5 - 0x01 & 0x00) == 0x00)
	{
		globals->dw11074 = globals->dw11074 + 11;
		return x30;
	}
	else
	{
		struct Eq_248 * sp_23 = g();
		word64 x30_28 = sp_23->qw0008;
		globals->dw11074 = globals->dw11074 + 11;
		word64 sp_29;
		*spOut = &sp_23->qw0008 + 0x01;
		return x30_28;
	}
}

// 0000000000000920: void h()
void h()
{
	ui32 w0_5 = globals->dw11040;
	globals->dw11040 = w0_5 - 0x01;
	if ((w0_5 - 0x01 & 0x00) == 0x00)
		globals->dw11074 = globals->dw11074 + 0x11;
	else
		globals->dw11074 = globals->dw11074 + 0x24;
}

// 0000000000000960: void i()
void i()
{
	globals->dw11074 = globals->dw11074 + 0x13;
}

// 0000000000000978: Register word64 l(Register word64 x30, Register out ptr64 spOut)
word64 l(word64 x30, ptr64 & spOut)
{
	ui32 w0_5 = globals->dw11044;
	globals->dw11044 = w0_5 - 0x01;
	word64 sp_1;
	*spOut = fp;
	if ((w0_5 - 0x01 & 0x00) == 0x00)
	{
		globals->dw11074 = globals->dw11074 + 0x1D;
		return x20;
	}
	else
	{
		word64 sp_24;
		word64 x20_25 = b(x30, x30, out sp_24);
		globals->dw11074 = globals->dw11074 + 0x1D;
		word64 sp_31;
		*spOut = sp_24 + 0x0010;
		return x20_25;
	}
}

// 00000000000009D0: Register word64 c(Register word64 x30, Stack word64 qwArg00, Register out ptr64 x20Out)
word64 c(word64 x30, word64 qwArg00, ptr64 & x20Out)
{
	ui32 w0_18 = globals->dw11048;
	globals->dw11048 = w0_18 - 0x01;
	ptr64 sp_23 = fp + -0x0018;
	ptr64 x19_15 = 0x00011000;
	if ((w0_18 - 0x01 & 0x00) != 0x00)
		x19_15 = d(x30, out x30, out sp_23);
	struct Eq_393 * x1_24 = x19_15 + 0x38;
	ui32 w0_25 = x1_24->dw0014;
	x1_24->dw0014 = w0_25 - 0x01;
	if ((w0_25 - 0x01 & 0x00) != 0x00)
		x30 = f(out sp_23);
	struct Eq_418 * x1_30 = x19_15 + 0x38;
	ui32 w0_32 = x1_30->dw0018;
	x1_30->dw0018 = w0_32 - 0x01;
	if ((w0_32 - 0x01 & 0x00) != 0x00)
	{
		word32 w0_73;
		ui32 w0_69 = x1_30->dw0008;
		x1_30->dw0008 = w0_69 - 0x01;
		if ((w0_69 - 0x01 & 0x00) != 0x00)
			w0_73 = globals->dw11074 + 0x13;
		else
			w0_73 = globals->dw11074;
		globals->dw11074 = w0_73 + 0x11;
	}
	struct Eq_438 * x1_36 = x19_15 + 0x38;
	ui32 w0_37 = x1_36->dw001C;
	x1_36->dw001C = w0_37 - 0x01;
	struct Eq_450 * x20_35 = &globals->ptr11000;
	if ((w0_37 - 0x01 & 0x00) != 0x00)
		x19_15 = j(x30, out x20_35, out x30, out sp_23);
	struct Eq_482 * x19_44 = x19_15 + 0x38;
	ui32 w0_45 = x19_44->dw0020;
	x19_44->dw0020 = w0_45 - 0x01;
	if ((w0_45 - 0x01 & 0x00) != 0x00)
		x20_35 = l(x30, out sp_23);
	x20_35->dw0074 = x20_35->dw0074 + 0x03;
	struct Eq_523 * v10_53 = sp_23 + 0x0010;
	word64 x20_56;
	*x20Out = v10_53->qw0008;
	return v10_53->qw0000;
}

// 0000000000000AA0: Register word64 b(Register word64 x30, Stack word64 qwArg00, Register out ptr64 spOut)
word64 b(word64 x30, word64 qwArg00, ptr64 & spOut)
{
	ui32 w0_5 = globals->dw1105C;
	globals->dw1105C = w0_5 - 0x01;
	word64 sp_1;
	*spOut = fp;
	if ((w0_5 - 0x01 & 0x00) == 0x00)
	{
		globals->dw11074 = globals->dw11074 + 0x02;
		return x20;
	}
	else
	{
		word64 x20_25;
		c(x30, x30, out x20_25);
		globals->dw11074 = globals->dw11074 + 0x02;
		word64 sp_33;
		*spOut = fp + 0x08;
		return x20_25;
	}
}

// 0000000000000AF8: Register word64 e(Register word64 x30, Stack word64 qwArg00, Register out ptr64 x20Out, Register out ptr64 spOut)
word64 e(word64 x30, word64 qwArg00, ptr64 & x20Out, ptr64 & spOut)
{
	*x20Out = x20;
	ui32 w0_5 = globals->dw11060;
	globals->dw11060 = w0_5 - 0x01;
	word64 sp_1;
	*spOut = fp;
	if ((w0_5 - 0x01 & 0x00) == 0x00)
	{
		globals->dw11074 = globals->dw11074 + 0x07;
		return x19;
	}
	else
	{
		word64 x20_26;
		word64 x19_27 = c(x30, x30, out x20_26);
		globals->dw11074 = globals->dw11074 + 0x07;
		word64 sp_34;
		*spOut = fp + 0x08;
		return x19_27;
	}
}

// 0000000000000B50: Register word64 d(Register word64 x30, Register out ptr64 x30Out, Register out ptr64 spOut)
word64 d(word64 x30, ptr64 & x30Out, ptr64 & spOut)
{
	*x30Out = x30;
	ui32 w0_5 = globals->dw11064;
	globals->dw11064 = w0_5 - 0x01;
	word64 sp_1;
	*spOut = fp;
	if ((w0_5 - 0x01 & 0x00) == 0x00)
	{
		globals->dw11074 = globals->dw11074 + 0x05;
		return x19;
	}
	else
	{
		word64 x20_26;
		struct Eq_674 * sp_27;
		word64 x19_28 = e(x30, x30, out x20_26, out sp_27);
		word64 x30_33;
		*x30Out = sp_27->qw0008;
		globals->dw11074 = globals->dw11074 + 0x05;
		word64 sp_34;
		*spOut = &sp_27->qw0008 + 0x01;
		return x19_28;
	}
}

// 0000000000000BA8: Register word64 k(Register word64 x30, Register out ptr64 x20Out, Register out ptr64 spOut)
word64 k(word64 x30, ptr64 & x20Out, ptr64 & spOut)
{
	*x20Out = x20;
	ui32 w0_5 = globals->dw11068;
	globals->dw11068 = w0_5 - 0x01;
	word64 sp_1;
	*spOut = fp;
	if ((w0_5 - 0x01 & 0x00) == 0x00)
	{
		globals->dw11074 = globals->dw11074 + 0x1B;
		return x19;
	}
	else
	{
		word64 x20_26;
		word64 sp_27;
		word64 x19_28 = e(x30, x30, out x20_26, out sp_27);
		globals->dw11074 = globals->dw11074 + 0x1B;
		word64 sp_34;
		*spOut = sp_27 + 0x0010;
		return x19_28;
	}
}

// 0000000000000C00: Register word64 j(Register word64 x30, Register out ptr64 x20Out, Register out ptr64 x30Out, Register out ptr64 spOut)
word64 j(word64 x30, ptr64 & x20Out, ptr64 & x30Out, ptr64 & spOut)
{
	*x30Out = x30;
	*x20Out = x20;
	ui32 w0_5 = globals->dw1106C;
	globals->dw1106C = w0_5 - 0x01;
	word64 sp_1;
	*spOut = fp;
	if ((w0_5 - 0x01 & 0x00) == 0x00)
	{
		globals->dw11074 = globals->dw11074 + 0x17;
		return x19;
	}
	else
	{
		word64 x20_27;
		struct Eq_790 * sp_28;
		word64 x19_29 = k(x30, out x20_27, out sp_28);
		word64 x30_34;
		*x30Out = sp_28->qw0008;
		globals->dw11074 = globals->dw11074 + 0x17;
		word64 sp_35;
		*spOut = &sp_28->qw0008 + 0x01;
		return x19_29;
	}
}

// 0000000000000C58: void __libc_csu_init(Register word64 x30, Stack word64 qwArg00)
void __libc_csu_init(word64 x30, word64 qwArg00)
{
	<anonymous> * x21_23[] = globals->a10DA8;
	word64 sp_38 = _init(x30);
	if (0x00010DB0 - 0x00010DA8 >> 0x03 != 0x00)
	{
		ui64 x19_71 = 0x00;
		do
		{
			<anonymous> * x3_77 = x21_23[x19_71];
			word64 sp_82;
			word64 x29_83;
			word64 x30_84;
			word64 x22_86;
			word64 x20_88;
			word64 x23_89;
			word64 x24_90;
			word64 x2_91;
			word32 w0_92;
			word32 w24_93;
			word64 x1_94;
			word64 x3_95;
			word64 x31_96;
			byte NZCV_97;
			bool Z_98;
			x3_77();
		} while (x20_88 - x19_71 != 0x00);
	}
}

// 0000000000000CD0: void __libc_csu_fini()
void __libc_csu_fini()
{
}

// 0000000000000CD4: void _fini(Stack word64 qwArg00)
void _fini(word64 qwArg00)
{
}

