//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int80_t;
typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef double float64_t;
typedef long double float80_t;
typedef long double float128_t;

// ------------------- Function Prototypes --------------------

int64_t __addtf3(uint64_t a1);
int64_t __do_global_dtors_aux(void);
int64_t __sfp_handle_exceptions(int128_t a1);
int64_t _fini(void);
int64_t _init(void);
int64_t _start(void);
void _start_c(int64_t * p);
int64_t add_double(void);
int64_t add_float(void);
int64_t add_long_double(int64_t a1);
int64_t deregister_tm_clones(int64_t a1);
int64_t frame_dummy(int64_t a1);
int64_t function_127c(int64_t a1, int64_t a2);
int64_t function_59c(int64_t a1, int64_t a2);
int32_t function_5d0(char * format, ...);
void function_5e0(int64_t * d);
int64_t function_5f0(int64_t * a1);
int32_t function_600(int64_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int64_t function_610(int64_t * a1, int64_t * a2);
int64_t register_tm_clones(int64_t a1);

// --------------------- Global Variables ---------------------

int64_t g1 = 0; // 0x11fc0
void (*g2)() = (void (*)())1432; // 0x11fc8
int64_t g3 = 0; // 0x11fd0
int32_t g4 = 1932; // 0x11fe8
void (*g5)() = (void (*)())0x1278; // 0x11ff0
int64_t g6 = 0; // 0x11ff8
int64_t g7; // 0x12000
int64_t g8 = 0; // 0x12008
int64_t g9 = 0; // 0x12010
int64_t g10 = 16; // 0x1330
int32_t g11;

// ------------------------ Functions -------------------------

// Address range: 0x598 - 0x59c
int64_t _init(void) {
    // 0x598
    int64_t result; // 0x598
    return result;
}

// Address range: 0x59c - 0x5a8
int64_t function_59c(int64_t a1, int64_t a2) {
    // 0x59c
    int64_t result; // 0x59c
    return result;
}

// Address range: 0x5d0 - 0x5e0
int32_t function_5d0(char * format, ...) {
    // 0x5d0
    return printf(format);
}

// Address range: 0x5e0 - 0x5f0
void function_5e0(int64_t * d) {
    // 0x5e0
    __cxa_finalize(d);
}

// Address range: 0x5f0 - 0x600
int64_t function_5f0(int64_t * a1) {
    // 0x5f0
    return __deregister_frame_info();
}

// Address range: 0x600 - 0x610
int32_t function_600(int64_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x600
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x610 - 0x620
int64_t function_610(int64_t * a1, int64_t * a2) {
    // 0x610
    return __register_frame_info();
}

// Address range: 0x620 - 0x63c
int64_t _start(void) {
    // 0x620
    int64_t v1; // 0x620
    _start_c(&v1);
    return &g11;
}

// From module:   /home/buildozer/aports/main/musl/src/musl-1.1.24/crt/crt1.c
// Address range: 0x63c - 0x664
// Line range:    14 - 18
void _start_c(int64_t * p) {
    int32_t v1 = g4; // 0x658
    __libc_start_main((int64_t)v1, v1, (char **)((int64_t)p + 8), g2, g5, NULL);
}

// Address range: 0x664 - 0x694
int64_t deregister_tm_clones(int64_t a1) {
    // 0x664
    return &g8;
}

// Address range: 0x694 - 0x6d0
int64_t register_tm_clones(int64_t a1) {
    // 0x694
    return &g8;
}

// Address range: 0x6d0 - 0x738
int64_t __do_global_dtors_aux(void) {
    // 0x6d0
    if (*(char *)&g8 != 0) {
        // 0x734
        return &g7;
    }
    int64_t v1 = 0; // 0x6f4
    if (g1 != 0) {
        // 0x6f8
        __cxa_finalize((int64_t *)g7);
        v1 = &g11;
    }
    // 0x704
    deregister_tm_clones(v1);
    if (g3 != 0) {
        // 0x714
        function_5f0(&g10);
    }
    // 0x720
    *(char *)&g8 = 1;
    return 1;
}

// Address range: 0x738 - 0x768
int64_t frame_dummy(int64_t a1) {
    int64_t v1 = 0; // 0x740
    if (g6 != 0) {
        // 0x744
        v1 = function_610(&g10, &g9);
    }
    // 0x764
    return register_tm_clones(v1);
}

// Address range: 0x768 - 0x770
int64_t add_float(void) {
    // 0x768
    int64_t result; // 0x768
    return result;
}

// Address range: 0x770 - 0x778
int64_t add_double(void) {
    // 0x770
    int64_t result; // 0x770
    return result;
}

// Address range: 0x778 - 0x78c
int64_t add_long_double(int64_t a1) {
    // 0x778
    int64_t v1; // 0x778
    return __addtf3(v1);
}

// Address range: 0x78c - 0x7e8
int main(int argc, char ** argv) {
    // 0x78c
    int128_t v1; // 0x78c
    printf("float:       %2ld %f\n", 4, (float64_t)(int64_t)v1);
    printf("double:      %2ld %f\n", 8, (float64_t)(int64_t)v1);
    printf("long double: %2ld %Lf\n", 16, (float80_t)(int80_t)v1);
    return 0;
}

// Address range: 0x7e8 - 0x1208
int64_t __addtf3(uint64_t a1) {
    // 0x7e8
    int64_t v1; // 0x7e8
    int64_t v2 = __asm_mrs(v1, v1); // 0x800
    int64_t v3 = __asm_ubfx(v1, a1, 48, 15); // 0x804
    int64_t v4 = __asm_ubfx(v1, a1, 48, 15); // 0x808
    uint64_t v5 = __asm_ubfiz(v1, a1, 3, 48); // 0x80c
    int64_t v6 = a1 / 0x8000000000000000; // 0x810
    uint64_t v7 = __asm_ubfiz(a1, a1, 3, 48); // 0x818
    int64_t v8 = v3 - v4; // 0x81c
    int64_t v9 = v8 & 0xffffffff; // 0x81c
    float128_t v10; // 0x7e8
    int64_t v11 = v7 | (int64_t)(float64_t)v10 / 0x2000000000000000; // 0x828
    int64_t v12 = v5 | (int64_t)(float64_t)v10 / 0x2000000000000000; // 0x830
    int64_t v13 = 8 * (int64_t)(float64_t)v10; // 0x834
    int64_t v14 = 8 * (int64_t)(float64_t)v10; // 0x83c
    int32_t v15 = v8;
    int64_t v16; // 0x7e8
    int64_t v17; // 0x7e8
    int64_t v18; // 0x7e8
    int64_t v19; // 0xaa0
    int64_t v20; // 0x7e8
    int64_t v21; // 0x7e8
    int64_t v22; // 0x7e8
    int64_t v23; // 0x7e8
    int64_t v24; // 0x7e8
    int64_t v25; // 0x7e8
    int64_t v26; // 0x7e8
    int64_t v27; // 0x7e8
    int64_t v28; // 0x7e8
    int64_t v29; // 0x7e8
    int64_t v30; // 0x7e8
    int64_t v31; // 0x7e8
    int64_t v32; // 0x7e8
    int64_t v33; // 0x7e8
    int64_t v34; // 0x7e8
    int64_t v35; // 0x7e8
    int64_t v36; // 0x7e8
    int64_t v37; // 0x7e8
    int64_t v38; // 0x7e8
    int64_t v39; // 0x7e8
    int64_t v40; // 0x7e8
    int64_t v41; // 0x7e8
    int64_t v42; // 0x7e8
    int64_t v43; // 0x7e8
    int64_t v44; // 0x7e8
    int64_t v45; // 0x7e8
    int64_t v46; // 0x7e8
    int64_t v47; // 0x7e8
    int64_t v48; // 0x7e8
    int64_t v49; // 0x7e8
    int64_t v50; // 0x7e8
    int64_t v51; // 0x7e8
    int64_t v52; // 0x7e8
    int64_t v53; // 0x7e8
    int64_t v54; // 0x7e8
    int64_t v55; // 0x7e8
    if (v15 < 1) {
        if (v15 == 0) {
            int64_t v56 = v3 + 1; // 0xa90
            if ((v56 & 0x7ffe) == 0) {
                // 0xaa0
                v19 = v12 | v13;
                switch (v3) {
                    case 0: {
                        // 0xaa8
                        v40 = v11;
                        v54 = v14;
                        if (v19 == 0) {
                            goto lab_0xe58;
                        } else {
                            // 0xaac
                            v40 = v12;
                            v54 = v13;
                            if ((v11 || v14) == 0) {
                                goto lab_0xe58;
                            } else {
                                int64_t v57 = v13 + v14; // 0xab4
                                int64_t v58 = v11 + v12 + (int64_t)(v57 < v13); // 0xabc
                                v40 = v58;
                                v54 = v57;
                                if (v58 % 0x8000000000001 == 0) {
                                    goto lab_0xe58;
                                } else {
                                    // 0xac4
                                    v30 = v57;
                                    v36 = v58 & -0x8000000000001;
                                    v46 = 1;
                                    v52 = v9;
                                    v24 = 0;
                                    goto lab_0xad0;
                                }
                            }
                        }
                    }
                    case 0x7fff: {
                        if (v19 == 0) {
                            // 0x11dc
                            v30 = v14;
                            v36 = v11;
                            v46 = 0x7fff;
                            v52 = v9;
                            v24 = 0;
                            v25 = 0;
                            if (v4 == 0x7fff) {
                                goto lab_0xb30;
                            } else {
                                goto lab_0xad0;
                            }
                        } else {
                            int64_t v59 = v5 / 0x4000000000000 % 2 ^ 1; // 0xb28
                            v25 = v59;
                            v26 = v59;
                            if (v4 == 0x7fff) {
                                goto lab_0xb30;
                            } else {
                                goto lab_0xb98;
                            }
                        }
                    }
                    default: {
                        // 0xb78
                        v25 = 0;
                        if (v4 == 0x7fff) {
                            goto lab_0xb30;
                        } else {
                            // 0xb88
                            v30 = v14;
                            v36 = v11;
                            v46 = 0x7fff;
                            v52 = v9;
                            v24 = 0;
                            v26 = 0;
                            if (v19 == 0) {
                                goto lab_0xad0;
                            } else {
                                goto lab_0xb98;
                            }
                        }
                    }
                }
            } else {
                if (v56 == 0x7fff) {
                    int64_t v60 = v2 & 0xc00000;
                    v22 = 20;
                    v49 = v9;
                    v43 = 0x7fff;
                    v34 = 0;
                    v28 = 0;
                    switch (v60) {
                        case 0: {
                            goto lab_0x10ec;
                        }
                        case 0x400000: {
                            // 0xbe0
                            v17 = 20;
                            v44 = 0x7ffe;
                            v50 = v9;
                            v31 = -1;
                            v37 = -1;
                            v22 = 20;
                            v49 = v9;
                            v43 = 0x7fff;
                            v34 = 0;
                            v28 = 0;
                            if (v6 == 0) {
                                goto lab_0x10ec;
                            } else {
                                goto lab_0xb08;
                            }
                        }
                        default: {
                            // 0xbf4
                            v16 = v60;
                            v23 = 20;
                            v51 = v9;
                            v45 = 0x7ffe;
                            v35 = -1;
                            v29 = -1;
                            v22 = 20;
                            v49 = v9;
                            v43 = 0x7fff;
                            v34 = 0;
                            v28 = 0;
                            if (v6 == 0 || v60 != 0x800000) {
                                goto lab_0xad8;
                            } else {
                                goto lab_0x10ec;
                            }
                        }
                    }
                } else {
                    uint64_t v61 = v13 + v14; // 0xbb4
                    uint64_t v62 = v11 + v12 + (int64_t)(v61 < v13); // 0xbbc
                    v30 = 0x8000000000000000 * v62 | v61 / 2;
                    v36 = v62 / 2;
                    v46 = v56;
                    v52 = v9;
                    v24 = 0;
                    goto lab_0xad0;
                }
            }
        } else {
            if (v3 == 0) {
                if ((v12 || v13) == 0) {
                    // 0x9a0
                    v41 = v11;
                    v47 = v4;
                    v55 = v14;
                    if (v4 == 0x7fff) {
                        goto lab_0x9a8;
                    } else {
                        goto lab_0x1038;
                    }
                } else {
                    if (v15 == -1) {
                        int64_t v63 = v13 + v14; // 0x9d0
                        v38 = v11 + v12 + (int64_t)(v63 < v13);
                        v42 = v4;
                        v53 = v63;
                        goto lab_0x89c;
                    } else {
                        if (v4 == 0x7fff) {
                            goto lab_0x9a8;
                        } else {
                            // 0x9ec
                            v39 = v12;
                            v21 = v9 ^ 0xffffffff;
                            goto lab_0x9f0;
                        }
                    }
                }
            } else {
                if (v4 == 0x7fff) {
                    goto lab_0x9a8;
                } else {
                    // 0xa40
                    v39 = v12 | 0x8000000000000;
                    v21 = -v8 & 0xffffffff;
                    goto lab_0x9f0;
                }
            }
        }
    } else {
        if (v4 == 0) {
            if ((v11 || v14) == 0) {
                // 0x860
                v41 = v12;
                v47 = v3;
                v55 = v13;
                if (v3 == 0x7fff) {
                    // 0x868
                    v18 = 0;
                    v20 = 0;
                    v32 = 0;
                    v27 = 0;
                    if ((v12 || v13) == 0) {
                        goto lab_0x1128;
                    } else {
                        // 0x870
                        v30 = v13;
                        v36 = v12;
                        v46 = 0x7fff;
                        v52 = 0;
                        v24 = v5 / 0x4000000000000 % 2 ^ 1;
                        goto lab_0xad0;
                    }
                } else {
                    goto lab_0x1038;
                }
            } else {
                if (v15 == 1) {
                    int64_t v64 = v13 + v14; // 0x890
                    v38 = v11 + v12 + (int64_t)(v64 < v13);
                    v42 = v3;
                    v53 = v64;
                    goto lab_0x89c;
                } else {
                    // 0x8cc
                    v33 = v11;
                    v48 = v8 + 0xffffffff & 0xffffffff;
                    if (v3 == 0x7fff) {
                        goto lab_0x8d4;
                    } else {
                        goto lab_0x900;
                    }
                }
            }
        } else {
            if (v3 == 0x7fff) {
                goto lab_0x8d4;
            } else {
                // 0x8fc
                v33 = v11 | 0x8000000000000;
                v48 = v9;
                goto lab_0x900;
            }
        }
    }
  lab_0x8d4:
    // 0x8d4
    v18 = 0;
    v20 = 0;
    v32 = 0;
    v27 = 0;
    if ((v12 || v13) == 0) {
        goto lab_0x1128;
    } else {
        // 0x8dc
        v30 = v13;
        v36 = v12;
        v46 = 0x7fff;
        v52 = 0;
        v24 = v5 / 0x4000000000000 % 2 ^ 1;
        goto lab_0xad0;
    }
  lab_0x9a8:
    // 0x9a8
    v18 = 0;
    v20 = 0;
    v32 = 0;
    v27 = 0;
    if ((v11 || v14) == 0) {
        goto lab_0x1128;
    } else {
        // 0x9b0
        v30 = v14;
        v36 = v11;
        v46 = 0x7fff;
        v52 = 0;
        v24 = v7 / 0x4000000000000 % 2 ^ 1;
        goto lab_0xad0;
    }
  lab_0x1038:
    // 0x1038
    v30 = v55;
    v36 = v41;
    v46 = v47;
    v52 = 0;
    v24 = 0;
    v40 = v41;
    v54 = v55;
    if (v47 == 0) {
        goto lab_0xe58;
    } else {
        goto lab_0xad0;
    }
  lab_0x1128:;
    int64_t v65 = v18;
    int64_t v66 = (0x2000000000000000 * v32 | v65 | v27 / 8) == 0 ? 0 : v65 | 0x800000000000; // 0x1134
    int64_t v67 = v20; // 0x1134
    int64_t v68 = 0x7fff; // 0x1134
    int64_t v69 = v66; // 0x1134
    goto lab_0x1138;
  lab_0x900:;
    int32_t v103 = v48; // 0x904
    int64_t v104; // 0x7e8
    int64_t v105; // 0x7e8
    if (v103 > 116) {
        // 0x97c
        v105 = 0;
        v104 = (v33 | v14) != 0;
    } else {
        if (v103 > 63) {
            int64_t v106 = v103 == 64 ? 0 : v33 << (128 - v48 & 0xffffffff); // 0x960
            v105 = 0;
            v104 = v33 >> (v48 + 0xffffffc0 & 0xffffffff) | (int64_t)((v106 | v14) != 0);
        } else {
            uint64_t v107 = 64 - v48 & 0xffffffff; // 0x914
            v105 = v33 >> v48;
            v104 = v33 << v107 | v14 >> v48 | (int64_t)(v14 << v107 != 0);
        }
    }
    int64_t v108 = v104 + v13; // 0x938
    v38 = v105 + v12 + (int64_t)(v108 < v104);
    v42 = v3;
    v53 = v108;
    goto lab_0x89c;
  lab_0xb30:;
    // 0xb30
    int64_t v72; // 0x7e8
    int64_t v73; // 0x7e8
    int64_t v71; // 0x7e8
    if ((v11 || v14) == 0) {
        // 0x11d4
        v30 = v14;
        v36 = v11;
        v46 = 0x7fff;
        v52 = v9;
        v24 = v25;
        v71 = v25;
        if (v19 == 0) {
            goto lab_0xad0;
        } else {
            goto lab_0xba0;
        }
    } else {
        int64_t v109 = v7 % 0x4000000000001;
        int64_t v110 = v109 == 0 ? 1 : v25 & 0xffffffff;
        v30 = v14;
        v36 = v11;
        v46 = 0x7fff;
        v52 = v9;
        v24 = v110;
        v72 = v109;
        v73 = v110;
        if (v19 == 0) {
            goto lab_0xad0;
        } else {
            goto lab_0xb44;
        }
    }
  lab_0xe58:
    // 0xe58
    v30 = v54;
    v36 = v40;
    v46 = 0;
    v52 = (v54 | v40) != 0;
    v24 = 0;
    goto lab_0xad0;
  lab_0x10ec:;
    int64_t v82 = v43; // 0x10ec
    int64_t v78 = v28; // 0x10ec
    int64_t v80 = v34; // 0x10ec
    int64_t v84 = v22; // 0x10ec
    int64_t v92; // 0x7e8
    int64_t v90; // 0x7e8
    int64_t v91; // 0x7e8
    int64_t v89; // 0x7e8
    if ((int32_t)v49 == 0) {
        goto lab_0x10fc;
    } else {
        // 0x10f0
        v89 = v43;
        v90 = v28;
        v91 = v34;
        v92 = v22;
        v82 = v43;
        v78 = v28;
        v80 = v34;
        v84 = v22;
        if ((v22 & 16 || v2 & 2048) == 0) {
            goto lab_0x10fc;
        } else {
            goto lab_0x10f8;
        }
    }
  lab_0xad0:
    // 0xad0
    v22 = v24;
    v49 = v52;
    v43 = v46;
    v34 = v36;
    v28 = v30;
    if (v30 % 8 == 0) {
        goto lab_0x10ec;
    } else {
        // 0xad0
        v16 = v2 & 0xc00000;
        v23 = v24;
        v51 = v52;
        v45 = v46;
        v35 = v36;
        v29 = v30;
        goto lab_0xad8;
    }
  lab_0x9f0:;
    int32_t v93 = v21; // 0x9f4
    int64_t v94; // 0x7e8
    int64_t v95; // 0x7e8
    if (v93 > 116) {
        // 0xa80
        v95 = (v39 | v13) != 0;
        v94 = 0;
    } else {
        if (v93 > 63) {
            int64_t v96 = v93 == 64 ? 0 : v39 << (128 - v21 & 0xffffffff); // 0xa64
            v95 = v39 >> (v21 + 0xffffffc0 & 0xffffffff) | (int64_t)((v96 | v13) != 0);
            v94 = 0;
        } else {
            uint64_t v97 = 64 - v21 & 0xffffffff; // 0xa04
            v95 = v39 << v97 | v13 >> v21 | (int64_t)(v13 << v97 != 0);
            v94 = v39 >> v21;
        }
    }
    int64_t v98 = v95 + v14; // 0xa28
    v38 = v94 + v11 + (int64_t)(v98 < v95);
    v42 = v4;
    v53 = v98;
    goto lab_0x89c;
  lab_0x89c:;
    uint64_t v99 = v53;
    v41 = v38;
    v47 = v42;
    v55 = v99;
    int64_t v88; // 0x7e8
    if (v38 % 0x8000000000001 == 0) {
        goto lab_0x1038;
    } else {
        if (v42 == 0x7ffe) {
            int64_t v100 = v2 & 0xc00000;
            v18 = 0;
            v20 = 20;
            v32 = 0;
            v27 = 0;
            switch (v100) {
                case 0: {
                    goto lab_0x1128;
                }
                case 0x400000: {
                    // 0xc20
                    v18 = 0;
                    v20 = 20;
                    v32 = 0;
                    v27 = 0;
                    v88 = 20;
                    if (v6 == 0) {
                        goto lab_0x1128;
                    } else {
                        goto lab_0x117c;
                    }
                }
                default: {
                    // 0xc30
                    v16 = v100;
                    v23 = 20;
                    v51 = 0;
                    v45 = 0x7ffe;
                    v35 = -1;
                    v29 = -1;
                    v18 = 0;
                    v20 = 20;
                    v32 = 0;
                    v27 = 0;
                    if (v6 == 0 || v100 != 0x800000) {
                        goto lab_0xad8;
                    } else {
                        goto lab_0x1128;
                    }
                }
            }
        } else {
            // 0x8b0
            v30 = v99 / 2 | 0x8000000000000000 * v38 | v99 % 2;
            v36 = v38 / 2 & 0x7ffbffffffffffff;
            v46 = v42 + 1;
            v52 = 0;
            v24 = 0;
            goto lab_0xad0;
        }
    }
  lab_0x1138:;
    int128_t v70 = __asm_fmov(__asm_bfi(__asm_bfxil(0, v69, 0, 48), v68 % 0x8000 | 0x8000 * v6, 48, 16)); // 0x1150
    int64_t result = v67; // 0x1154
    if ((int32_t)v67 != 0) {
        // 0x1158
        result = __sfp_handle_exceptions(v70);
    }
    // 0x1164
    return result;
  lab_0xb98:
    // 0xb98
    v71 = v26;
    if ((v11 || v14) == 0) {
        goto lab_0xba0;
    } else {
        // 0xb98
        v72 = v7 % 0x4000000000001;
        v73 = v26;
        goto lab_0xb44;
    }
  lab_0xad8:;
    int64_t v74 = v23 & 0xffffffef | 16; // 0xadc
    v17 = v74;
    v44 = v45;
    v50 = v51;
    v31 = v29;
    v37 = v35;
    bool v75; // 0x7e8
    int64_t v76; // 0x7e8
    switch (v16) {
        case 0x400000: {
            // 0x10d8
            v17 = v74;
            v44 = v45;
            v50 = v51;
            v31 = v29;
            v37 = v35;
            if (v6 == 0) {
                // 0x10dc
                v76 = v29 + 8;
                v75 = v29 > 0xfffffffffffffff7;
                goto lab_0xb04;
            } else {
                goto lab_0xb08;
            }
        }
        case 0x800000: {
            // 0x10e4
            v17 = v74;
            v44 = v45;
            v50 = v51;
            v31 = v29;
            v37 = v35;
            if (v6 == 0) {
                goto lab_0xb08;
            } else {
                // 0x10dc
                v76 = v29 + 8;
                v75 = v29 > 0xfffffffffffffff7;
                goto lab_0xb04;
            }
        }
        case 0: {
            // 0xaf4
            v17 = v74;
            v44 = v45;
            v50 = v51;
            v31 = v29;
            v37 = v35;
            if (v29 % 16 == 4) {
                goto lab_0xb08;
            } else {
                // 0xb00
                v76 = v29 + 4;
                v75 = v29 > 0xfffffffffffffffb;
                goto lab_0xb04;
            }
        }
        default: {
            goto lab_0xb08;
        }
    }
  lab_0x10fc:;
    int64_t v77 = v78; // 0x10fc
    int64_t v79 = v80; // 0x10fc
    int64_t v81 = v82; // 0x10fc
    int64_t v83 = v84; // 0x10fc
    int64_t v85; // 0x7e8
    int64_t v86; // 0x7e8
    int64_t v87; // 0x7e8
    if (v80 % 0x8000000000001 == 0) {
        goto lab_0x1114;
    } else {
        if (v82 == 0x7ffe) {
            // 0x116c
            v88 = v84;
            v85 = v84;
            v86 = 0;
            v87 = 0x7fff;
            switch (v2 & 0xc00000) {
                case 0: {
                    goto lab_0x118c;
                }
                case 0x400000: {
                    goto lab_0x117c;
                }
                case 0x800000: {
                    // 0x11a4
                    v85 = v84;
                    v86 = v6 == 0;
                    v87 = v6 == 0 ? 0x7ffe : 0x7fff;
                    goto lab_0x118c;
                }
                default: {
                    // 0x11b8
                    v85 = v84;
                    v86 = -1;
                    v87 = 0x7ffe;
                    goto lab_0x118c;
                }
            }
        } else {
            // 0x1114
            v67 = v84;
            v68 = v82 + 1;
            v69 = v80 / 8 & 0x1ffeffffffffffff;
            goto lab_0x1138;
        }
    }
  lab_0xb08:
    // 0xb08
    v89 = v44;
    v90 = v31;
    v91 = v37;
    v92 = v17;
    v82 = v44;
    v78 = v31;
    v80 = v37;
    v84 = v17;
    if ((int32_t)v50 == 0) {
        goto lab_0x10fc;
    } else {
        goto lab_0x10f8;
    }
  lab_0xba0:
    // 0xba0
    v30 = v13;
    v36 = v12;
    v46 = 0x7fff;
    v52 = v9;
    v24 = v71;
    goto lab_0xad0;
  lab_0xb44:
    // 0xb44
    if (v5 % 0x4000000000001 != 0 == v72 == 0) {
        // branch -> 0xb6c
    }
    uint64_t v101 = 0x2000000000000000 * v12 | (int64_t)(float64_t)v10 & 0x1fffffffffffffff;
    v30 = 8 * v101;
    v36 = v101 / 0x2000000000000000 | v5 & -8;
    v46 = 0x7fff;
    v52 = v9;
    v24 = v73;
    goto lab_0xad0;
  lab_0x1114:;
    int64_t v102 = v79 / 8; // 0x1120
    v18 = v102;
    v20 = v83;
    v32 = v79;
    v27 = v77;
    v67 = v83;
    v68 = v81;
    v69 = v102;
    if (v81 == 0x7fff) {
        goto lab_0x1128;
    } else {
        goto lab_0x1138;
    }
  lab_0x10f8:
    // 0x10f8
    v82 = v89;
    v78 = v90;
    v80 = v91;
    v84 = v92 & 0xfffffff7 | 8;
    goto lab_0x10fc;
  lab_0xb04:
    // 0xb04
    v17 = v74;
    v44 = v45;
    v50 = v51;
    v31 = v76;
    v37 = v35 + (int64_t)v75;
    goto lab_0xb08;
  lab_0x118c:
    // 0x118c
    v77 = v86;
    v79 = v86;
    v81 = v87;
    v83 = v85 & 0xffffffeb | 20;
    goto lab_0x1114;
  lab_0x117c:
    // 0x117c
    v85 = v88;
    v86 = v6 != 0;
    v87 = v6 == 0 ? 0x7fff : 0x7ffe;
    goto lab_0x118c;
}

// Address range: 0x1208 - 0x1278
int64_t __sfp_handle_exceptions(int128_t a1) {
    // 0x1208
    int64_t v1; // 0x1208
    int128_t v2; // 0x1208
    int64_t v3; // 0x1208
    int128_t v4; // 0x1208
    int64_t v5; // 0x1208
    if (v3 % 2 != 0) {
        int128_t v6 = __asm_movi(v4, 0); // 0x120c
        int64_t v7 = __asm_mrs(v3, v3); // 0x1214
        v2 = v6;
        v5 = v7;
        v1 = v7;
    }
    int64_t v8 = v1; // 0x1218
    if ((v3 & 2) != 0) {
        // 0x121c
        __asm_movi(v4, 0);
        v8 = __asm_mrs(v5, v1);
    }
    int64_t v9 = v8; // 0x122c
    if ((v3 & 4) != 0) {
        // 0x1230
        v9 = __asm_mrs(0x749dc5ae, v8);
    }
    int64_t v10 = v9; // 0x124c
    if ((v3 & 8) != 0) {
        // 0x1250
        __asm_movi(v2, 0x800000);
        v10 = __asm_mrs(v9, v9);
    }
    int64_t result; // 0x1208
    if ((v3 & 16) != 0) {
        // 0x1260
        result = __asm_mrs(0x7f7fffff, v10);
    }
    // 0x1274
    return result;
}

// Address range: 0x1278 - 0x127c
int64_t _fini(void) {
    // 0x1278
    int64_t result; // 0x1278
    return result;
}

// Address range: 0x127c - 0x1288
int64_t function_127c(int64_t a1, int64_t a2) {
    // 0x127c
    int64_t result; // 0x127c
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __cxa_finalize(void * d);
// int64_t __deregister_frame_info(void);
// int __libc_start_main(int *(main)(int, char **, char **), int argc, char ** ubp_av, void(* init)(void), void(* fini)(void), void(* rtld_fini)(void), void(* stack_end));
// int64_t __register_frame_info(void);
// int printf(const char * restrict format, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (9.3.0)
// Detected functions: 21

