// subject.globals.c
// Generated by decompiling subject.exe
// using Reko decompiler version VERSION

#include "subject.h"

struct Eq_21 * g_ptrFFF80000;
struct Eq_21 * g_ptrFFF90000;
struct Eq_21 * g_ptrFFFB8000;

